### ISSUE TITLE
wx:model 双向绑定是不支持自定义组件吗？

### ISSUE THREAD

**Issue by godfox2012** [didi/mpx#100]
我使用的是vant-weapp组件
```
<van-field
  id="phone"
  wx:model="{{ form.phone }}"
  label="手机号"
  placeholder="请输入手机号"
  error-message="手机号格式错误"
  border="{{ false }}"
/>
```
测试了一下，双向绑定不起作用，是我那里用得不对吗？

**Comment by cougarwww** [comment]
我猜应该用：wx:model-prop和wx:model-event 绑定一下
https://didi.github.io/mpx/single/template-enhance.html#%E5%8F%8C%E5%90%91%E7%BB%91%E5%AE%9A

**Comment by cougarwww** [comment]
看了一下，是因为vant 的 field 组件，input事件回调中的值直接在 e.detail 上, 没有跟默认组件对齐，mpx双向绑定是按照默认组件读的是 e.detail.value， 自己在bind:input方法里this.phone = v.detail手动同步吧

**Comment by godfox2012** [comment]
@cougarwww 嗯，是的暂时也只能这么解决了

**Comment by sky-admin** [comment]
稍等，今天内给解决。

**Comment by sky-admin** [comment]
我们会加一个新属性叫model-value-path，让用户自定义取值路径，对于vant的这个，传个"[]"即可。发版后我再关这个issue

**Comment by sky-admin** [comment]
已支持。文档随后更新。对于这个case： 
```html
<vanfield wx:model="{{testModel2}}" wx:model-value-path="[]"></vanfield>
```
即可解决。
别的比如原生swiper组件，取的是e.detail.current，传wx:model-value-path="current"
