### ISSUE TITLE
[Bug report]转百度小程序编译失败

### ISSUE THREAD

**Issue by wusiquan** [didi/mpx#1004]
**问题描述**
模板使用\<import\>语法，在主包和分包引用同一个模板template时，编译失败
(转百度似乎用到了swanHelper.wxs)
尝试在@mpxjs/webpack-plugin的wxs/loader.js中，将`issuerPackageName`获取改为如下方式，编译成功
`const issuerPackageName = issuerQueryObj.packageRoot || 'main'`
不知道是不是这个原因

**环境信息描述**  
@mpxjs/core  2.7.30
@mpxjs/webpack-plugin  2.7.25

**最简复现demo**  
执行yarn build:cross
pages/index/index页和packHello/pages/hello1/index均引入了lib/mytemplate/abc.wxml
[mpx-project.zip](https://github.com/didi/mpx/files/8547448/mpx-project.zip)

**Comment by hiyuki** [comment]
已修复，感谢反馈，https://github.com/didi/mpx/releases/tag/v2.7.31
