### ISSUE TITLE
[Bug report]当i18n配置`useComputed:true`时 `wx:for`中的翻译报错`item`为`undefined`

### ISSUE THREAD

**Issue by TianchengTerrence** [didi/mpx#1005]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
当i18n配置`useComputed:true`时
`wx:for`中的翻译报错`item`为`undefined`
2. 期望的表现
与`useComputed:false`时一致
3. 实际的表现
报错

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
"@mpxjs/core": "^2.7.18"
 "@mpxjs/webpack-plugin": "^2.7.18",
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）
[mpx-project.zip](https://github.com/didi/mpx/files/8548943/mpx-project.zip)

**Comment by hiyuki** [comment]
这是useComputed本身实现方案带来的使用限制，文档里面也有描述：https://mpxjs.cn/guide/tool/i18n.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

建议是在computed中调用$t函数进行翻译或者是关闭useComputed。
