### ISSUE TITLE
npm run watch:web 无法启动项目

### ISSUE THREAD

**Issue by zhangliangxue** [didi/mpx#1015]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 执行npm run watch:web 无法启动

**环境信息描述**  
至少包含以下部分：
1. 系统类型：  Windows
2. Mpx依赖版本 "@mpxjs/core": "^2.7.18" ,"@mpxjs/webpack-plugin": "^2.7.18","@mpxjs/api-proxy": "^2.7.1",
4. web端
**最简复现demo**  
通过mpx init mpx-project 下载的新代码
![image](https://user-images.githubusercontent.com/28263954/168025056-48b3272f-12e5-4dc6-b5e2-11a6c13d1fd8.png)

**Comment by Blackgan3** [comment]
应该是windows电脑路径适配问题，我们看下

**Comment by hiyuki** [comment]
最新的脚手架模板已修复，重新初始化项目使用，或者将当前项目中的，config/devServer.js中的static配置改为static:false即可
