### ISSUE TITLE
mpx init mpx-project无法安装项目

### ISSUE THREAD

**Issue by zhangliangxue** [didi/mpx#1016]
**问题描述**  
通过`npm i -g @mpxjs/cli `全局安装脚手架后
mpx init mpx-project无法安装项目，网络超时 报错
![image](https://user-images.githubusercontent.com/28263954/168093393-1b13e20e-2faa-4931-815b-c46a13dd3ea4.png)

**环境信息描述**  
至少包含以下部分：
1. 系统类型Windows10   node14.16.1  npm6.14.12
2. Mpx依赖版本 最新版本 @mpxjs/core 2.7.1

**Comment by Blackgan3** [comment]
下载模版项目时网络问题，可以重试下，另外先看下github是否能正常访问，如果不能访问代理下网络翻墙试试

**Comment by zhangliangxue** [comment]
> 下载模版项目时网络问题，可以重试下，另外先看下github是否能正常访问，如果不能访问代理下网络翻墙试试
用了免费翻墙软件，依然不行呀  ，能不能弄个国内地址

**Comment by zhangliangxue** [comment]
> 下载模版项目时网络问题，可以重试下，另外先看下github是否能正常访问，如果不能访问代理下网络翻墙试试

用免费翻墙软件也不行 ，有没有国内地址

**Comment by hiyuki** [comment]
可以安装我们的下一代脚手架工具 @mpxjs/cli@next来初始化项目使用，这个不依赖github模板
