### ISSUE TITLE
mpx 转 web

### ISSUE THREAD

**Issue by SuXW** [didi/mpx#1017]
通过mpx转web出现报错：
版本是：
  "dependencies": {
    "@mpxjs/api-proxy": "^2.7.1",
    "@mpxjs/core": "^2.7.33",
    "@mpxjs/fetch": "^2.7.28",
    "vue": "^2.6.10",
    "vue-i18n": "^8.15.3"
  },
报错信息：
<img width="1583" alt="WeChat85126ad7bb9ee2825905f9ebb6106402" src="https://user-images.githubusercontent.com/12590725/168540791-53f51775-b4cd-47ac-a049-8e93a0c84e11.png">

**Comment by hiyuki** [comment]
类似的resolve错误都先检查报错的对应位置是否真的存在对应文件
