### ISSUE TITLE
web 端引入vant-weapp 无样式

### ISSUE THREAD

**Issue by zhangliangxue** [didi/mpx#1018]
**问题描述**  
使用vant-weapp 在浏览器端 无样式

**环境信息描述**  
至少包含以下部分：
1. 系统类型Windows
2. Mpx依赖版本  最新版
![image](https://user-images.githubusercontent.com/28263954/168546877-45ccf0f0-65c2-4570-8f2c-cce81c3505c5.png)
![image](https://user-images.githubusercontent.com/28263954/168546992-aabc52dd-4b6e-4d27-8684-b4a3f764aa53.png)

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现

demo：
[demo.zip](https://github.com/didi/mpx/files/8698227/demo.zip)

**Comment by hiyuki** [comment]
输出web时目前还不支持直接使用vant/weapp这样的原生小程序组件库，未来我们会支持，目前可以采用条件编译的方式在输出web时替换为vant vue版本的组件库

**Comment by Blackgan3** [comment]
另外关于使用vant组件库输出H5和原生小程序的使用可以参考demo项目：
https://github.com/didi/mpx/tree/master/examples/mpx-useuilib

**Comment by zhangliangxue** [comment]
> 另外关于使用vant组件库输出H5和原生小程序的使用可以参考demo项目： https://github.com/didi/mpx/tree/master/examples/mpx-useuilib

谢谢大佬的指点 ~~
