### ISSUE TITLE
小程序插件开发

### ISSUE THREAD

**Issue by fu188-dev** [didi/mpx#1021]
在开发小程序插件的时候，不能添加多个pages页面，添加多个的时候就会编译失败；如图：
https://user-images.githubusercontent.com/68093183/169248174-96cceb83-f445-4e9d-a52a-3ee5c0bed20b.png，
https://user-images.githubusercontent.com/68093183/169248368-e21195c4-9204-49f4-b8f0-cb114972c202.png，
不知道是什么原因，麻烦请处理一下呢

**Comment by hiyuki** [comment]
留一个issue吧，这个先关闭了

**Comment by fu188-dev** [comment]
ok
