### ISSUE TITLE
[Bug report]小程序插件开发多页面编译报错

### ISSUE THREAD

**Issue by fu188-dev** [didi/mpx#1022]
在开发小程序插件的时候，不能添加多个pages页面，添加多个的时候就会编译失败；如图：
![image](https://user-images.githubusercontent.com/68093183/169248842-778bdb39-9eb6-490d-87e8-cbbaf023467f.png)
![image](https://user-images.githubusercontent.com/68093183/169248868-f388cc90-ee3f-423a-9131-cfea4fd9aace.png)
不知道什么原因，麻烦处理一下呢

**Comment by hiyuki** [comment]
已修复 https://github.com/didi/mpx/releases/tag/v2.7.35

**Comment by fu188-dev** [comment]
感谢，辛苦啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/mpx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [didi/mpx] [Bug report]小程序插件开发多页面编译报错 (Issue #1022)





 
已修复 https://github.com/didi/mpx/releases/tag/v2.7.35
