### ISSUE TITLE
[Bug report] init了一个空项目，watch模式下，修改mpx文件，会触发2次编译

### ISSUE THREAD

**Issue by paraself** [didi/mpx#1024]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
init一个空项目，执行`npm run watch`或者 `npm run watch:prod`, 修改任意mpx文件
2. 期望的表现
应该只编译一次
3. 实际的表现
编译一次之后，又重复编译了一次
如视频里表现。

https://user-images.githubusercontent.com/2179686/170232897-94dec4e6-d9ae-4d33-a4f6-1a4fec40e9f6.mov

**环境信息描述**  
至少包含以下部分：

1. 系统类型(Mac或者Windows)
macOS Montery 2.3.1 

2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
```
"@mpxjs/api-proxy": "^2.7.1",
"@mpxjs/core": "^2.7.18",
"@mpxjs/miniprogram-simulate": "^1.4.8",
"@mpxjs/mpx-jest": "0.0.9",
"@mpxjs/webpack-plugin": "^2.7.18",
```

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
小程序基础库：2.13.2
开发工具：1.05.220425
Node: 16.14.0
npm: 8.3.1

**最简复现demo**  
[mpx-text.zip](https://github.com/didi/mpx/files/8769827/mpx-text.zip)

**Comment by paraself** [comment]
```
➜  ~ mpx -V
2.7.1
➜  ~ 
```

**Comment by hiyuki** [comment]
建议检查编辑器是否会触发重复保存文件，或者调大webpack watch的延迟时间，https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout

**Comment by paraself** [comment]
今天修改了aggregatetimeout 之后，发现问题依旧，没有任何改变。同时，不使用任何的ide，仅用记事本打开源码进行保存，一样会触发2次编译。

https://user-images.githubusercontent.com/2179686/170329236-3c370fd3-6352-4b1b-8e99-26e4baae26a5.mov

**Comment by paraself** [comment]
对了，补充一下，上面的操作我是换了台电脑进行的。macOS Big Sur + Node 16

**Comment by paraself** [comment]
在Docker里跑了一下，发现没有这样的问题，应该还是和本地的环境有关。

**Comment by hiyuki** [comment]
mpx当中编译的watch完全依赖于webpack本身的watch，框架对此无任何改动，webpack5确实对watch系统进行了升级，不再依赖于fsevents而是直接使用node原生的fs.watch，你可以考虑在出现该问题的环境下用一个单纯webpack5项目测试一下如果存在同样问题且无法用watch配置处理，建议向webpack项目提对应的issue

**Comment by paraself** [comment]
后来又搜了一下，发现确实是webpack高版本，在macOS上，如果开启了output clean会出现这个bug
https://github.com/webpack/webpack/issues/15206#issuecomment-1030170006
