### ISSUE TITLE
[Bug report] init了一个空项目，watch模式下wxs生效；但是watch:prod下wxs不生效

### ISSUE THREAD

**Issue by paraself** [didi/mpx#1025]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
mpx cli 2.7.1, init一个空项目，在默认的模板里，list.mpx里写一个简单的wxs。然后分别跑watch模式和watch prod模式。并用微信小程序开发工具打开编译后的dist/wx目录
```
<template>
  <wxs module="base">
    function includes() { return true };
    module.exports.includes = includes
  </wxs>
  <view>
    {{ base.includes() ? '外层 - wxs可以用' : '外层 - wxs不能用' }}
  </view>
</template>
```

2. 期望的表现
2个模式下应该均能正常执行wxs，并显示 'wxs可以用'

3. 实际的表现
在watch模式下显示 ` wxs可以用`; 在watch prod下显示`wxs不能用`

**环境信息描述**

系统类型(Mac或者Windows)
macOS Montery 2.3.1

Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)

"@mpxjs/api-proxy": "^2.7.1",
"@mpxjs/core": "^2.7.18",
"@mpxjs/miniprogram-simulate": "^1.4.8",
"@mpxjs/mpx-jest": "0.0.9",
"@mpxjs/webpack-plugin": "^2.7.18",
小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
小程序基础库：2.13.2
开发工具：1.05.220425
Node: 16.14.0
npm: 8.3.1

[mpx-text.zip](https://github.com/didi/mpx/files/8777017/mpx-text.zip)

**Comment by Blackgan3** [comment]
OK，看起来是webpack prod模式对wxs中的module.exports.xx 这种写法进行了unusedExport处理，includes方法被标记为了unusedExport没有导出来，我们修复处理下哈

**Comment by Blackgan3** [comment]
这个地方你可以先通过 这种写法来规避掉
```js
module.exports = {
  includes
}
```

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.7.36 已修复
