### ISSUE TITLE
[Bug report]我在为 MPX 开发适配 UnoCSS 的插件，但发现 UnoCSS 在 Webpack 构建过程中无法与 MPX 兼容。

### ISSUE THREAD

**Issue by ItsRyanWu** [didi/mpx#1028]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件：在 MPX 中使用 @unocss/webpack 插件。
2. 期望的表现：UnoCSS 的样式产物可以被正常当作 asset 生成在 wxss 文件中（就如同 Windi CSS 可以在 MPX 项目中自然使用那样）。
3. 实际的表现：UnoCSS 的样式产物被当作普通字符串生成在了 `app.js` 中，并没有生成在 wxss 文件中。可是若将同样的步骤应用在如 uni-app 这类基于 webpack 的框架中时 UnoCSS 的样式产物是可以被正常生成为 wxss 文件的。

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)：Mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看):
```json
{
  "@mpxjs/api-proxy": "^2.7.1",
  "@mpxjs/core": "^2.7.18",
  "@mpxjs/miniprogram-simulate": "^1.4.12",
  "@mpxjs/mpx-jest": "0.0.18",
  "@mpxjs/webpack-plugin": "^2.7.18",
}
```
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
无关

**最简复现demo**  
https://github.com/ItsRyanWu/issue-reprod-mpx-with-unocss

**复现步骤**
1. 安装 unocss 与 @unocss/webpack
``` sh
npm i unocss @unocss/webpack -D
```

2. 使用 @unocss/webpack 插件
``` javascript
//getPlugins.js line 94
plugins.push(UnoCSS())
```

3. 配置 unocss

在项目根目录中新建 `unocss.config.ts`

4. 引入 unocss 产物
```html
// app.mpx
<style src="uno.css"></style>
```

5. 在项目中使用 unocss 样式
```html
// index.mpx
<template>
  <list class="bg-red h-[50vh]"></list>
</template>
```

6. 运行项目
```sh
npm run watch
```

7. 观察 unocss 样式是否注入 wxss
   
结果发现生成的样式并未注入 wxss, 而是将样式作为字符串生成在了 `dist/wx/app.js` line 122，结果不正常，没有达到预期效果。

**Comment by hiyuki** [comment]
我向@unocss/webpack中处理相关逻辑的依赖库提了一个[pr](https://github.com/unjs/unplugin/pull/129)，如被合入就可以解决该问题，不过@unocss/webpack目前的处理逻辑没有考虑webpack5持久化缓存，即使上述问题解决后也需要要关闭持久化缓存才能保障正常使用。

**Comment by ItsRyanWu** [comment]
> 我向@unocss/webpack中处理相关逻辑的依赖库提了一个[pr](https://github.com/unjs/unplugin/pull/129)，如被合入就可以解决该问题，不过@unocss/webpack目前的处理逻辑没有考虑webpack5持久化缓存，即使上述问题解决后也需要要关闭持久化缓存才能保障正常使用。

Nice, thanks anyway!
