### ISSUE TITLE
ext.json和project.config.json能打包进dist吗

### ISSUE THREAD

**Issue by huixu123** [didi/mpx#103]
ext.json和project.config.json能打包进dist吗
虽然 ext.json需要生成小程序包的时候手动写入，但是在测试的时候每次npm run watch 都需要把文件复制进去 比较麻烦。

**Comment by sky-admin** [comment]
建议用webpack-copy-plugin来复制支付宝小程序的ext.json。
微信的project.config.json不需要复制，里面有一项miniprogramRoot我们模板已经将其指向dist，所以微信小程序只需要打开项目根目录，而不是dist即可。

**Comment by huixu123** [comment]
好的,谢谢。另外微信小程序也有这个ext.json文件的

**Comment by sky-admin** [comment]
哦，查了下，第三方平台那个吧？我们后续更新下模板，在创建项目时问问用户是否需要复制什么东西，如果需要的话，我们给加上webpack-copy-plugin让用户方便使用。

**Comment by ChangeZhang** [comment]
请问这个怎么配置？
