### ISSUE TITLE
[Bug report]引入阿里巴巴图标文件编译报错

### ISSUE THREAD

**Issue by suweien** [didi/mpx#1031]
**问题描述**  
引入阿里巴巴图标文件编译报错，直接npm run watch:prod 就会报错
[mpx-icon.zip](https://github.com/didi/mpx/files/8916690/mpx-icon.zip)

**Comment by Blackgan3** [comment]
需要配置下对应的 loader 处理下 woff、woff2、ttf 文件，可以使用 file-loader 或者 url-loader

**Comment by suweien** [comment]
谢谢
