### ISSUE TITLE
引入echarts后无法调试或打包

### ISSUE THREAD

**Issue by dev-2099** [didi/mpx#1036]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
按照https://github.com/ecomfe/echarts-for-weixin文档指引，引入echarts组件

2. 期望的表现
能够正常调试，打包

3. 实际的表现
卡在编译中，node进程在后台一直跑，直到手动结束进程

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
Windows10 21H2
node：v16.15.1

2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
参见demo

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
微信小程序，跟开发工具和基础库版本无关，问题发生在编译阶段

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
参见下面最新的demo

**Comment by dev-2099** [comment]
通过配置eslint-webpack-plugin插件排除ec-canvas文件夹后，可以正常调试及编译，但是显示如下警告信息：

WARNING in ./src/pages/authorize.mpx?ctorType=page&index=0&isFirst&isPage&mpx&type=script (./src/pages/authorize.mpx.js?isFirst&isPage!=!./node_modules/@mpxjs/webpack-plugin/lib/selector.js!./src/pages/authorize.mpx?ctorType=page&index=0&isFirst&isPage&mpx&type=script) 22:20-32
export 'init' (imported as 'echarts') was not found in '@/components/ec-canvas/echarts' (module has no exports)
 @ ./src/pages/authorize.mpx?isFirst&isPage 13:0-150

WARNING in ./src/components/ec-canvas/ec-canvas.js?index=0&mpx&resourcePath=D%3A%5CGitBlit%5Cmpx-demo-next%5Csrc%5Ccomponents%5Cec-canvas%5Cec-canvas.js&type=script 52:4-32
export 'registerPreprocessor' (imported as 'echarts') was not found in './echarts' (module has no exports)
 @ ./node_modules/@mpxjs/webpack-plugin/lib/native-loader.js!./src/components/ec-canvas/ec-canvas.js 8:0-139

WARNING in ./src/components/ec-canvas/ec-canvas.js?index=0&mpx&resourcePath=D%3A%5CGitBlit%5Cmpx-demo-next%5Csrc%5Ccomponents%5Cec-canvas%5Cec-canvas.js&type=script 110:6-30
export 'setCanvasCreator' (imported as 'echarts') was not found in './echarts' (module has no exports)
 @ ./node_modules/@mpxjs/webpack-plugin/lib/native-loader.js!./src/components/ec-canvas/ec-canvas.js 8:0-139

WARNING in ./src/components/ec-canvas/ec-canvas.js?index=0&mpx&resourcePath=D%3A%5CGitBlit%5Cmpx-demo-next%5Csrc%5Ccomponents%5Cec-canvas%5Cec-canvas.js&type=script 149:8-32
export 'setCanvasCreator' (imported as 'echarts') was not found in './echarts' (module has no exports)
 @ ./node_modules/@mpxjs/webpack-plugin/lib/native-loader.js!./src/components/ec-canvas/ec-canvas.js 8:0-139

通过调试demo中的代码发现： this.ecComponent.init((canvas, width, height, dpr) 这里没有执行成功

**Comment by Blackgan3** [comment]
看该demo

showLine 方法中执行 this.initChart(500) 方法，chart 创建成功在 this.ecComponent.init 的异步回调

所以最下方的this.chart.setOption(option, true);执行时 this.chart为undefined导致报错

这里可以修改为setOption在init回调中来避免，或者采用微信官方的这种用来解决

https://github.com/ecomfe/echarts-for-weixin/blob/master/pages/bar/index.js

**Comment by dev-2099** [comment]
我修改了初始化的时机来避免undefined问题，错误仍在。作为对照，用wepy写了一个demo，表现正常。
mpx在编译阶段会爆出4个WARNING：
1、export 'init' (imported as 'echarts') was not found in '@/components/ec-canvas/echarts' (module has no exports)
2、export 'registerPreprocessor' (imported as 'echarts') was not found in './echarts' (module has no exports)
3、export 'setCanvasCreator' (imported as 'echarts') was not found in './echarts' (module has no exports)
4、export 'setCanvasCreator' (imported as 'echarts') was not found in './echarts' (module has no exports)

然后在小程序开发工具中，会继续报出2个错误：
1、TypeError: r.ds is not a function
2、TypeError: r.jQ is not a function

猜测问题根源在上面4个警告，似乎因为无法识别echarts中的方法，才导致了后续的一系列错误，请参考附带的demo。
[mpx-echarts-demo.zip](https://github.com/didi/mpx/files/8955653/mpx-echarts-demo.zip)

**Comment by Blackgan3** [comment]
这个warning应该是模块转换问题，你在babel.config.json 中的顶层加一个  "sourceType": "unambiguous",
试试
