### ISSUE TITLE
组件中使用wx:for渲染数据，在阿里下无法渲染数据

### ISSUE THREAD

**Issue by boljonggo** [didi/mpx#1039]
**问题描述**  
组件中使用wx:for渲染数据，采用部分导出组件的方式导出组件，在微信下组件能够正常渲染，在阿里下无法渲染数据

**环境信息描述**  
至少包含以下部分：
1. 系统类型：Mac
2. Mpx依赖版本：
@mpxjs/core：2.7.37
@mpxjs/webpack-plugin：2.7.38
@mpxjs/api-proxy：2.7.28
3. 小程序开发者工具信息(
小程序平台：阿里小程序
开发者工具版本：2.9.1
基础库版本：2.7.15

**最简复现demo**  
[demo-ali.zip](https://github.com/didi/mpx/files/8956415/demo-ali.zip)
[demo.zip](https://github.com/didi/mpx/files/8956405/demo.zip)

**Comment by boljonggo** [comment]
有遇到这种问题的朋友吗？

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.7.39 已修复
