### ISSUE TITLE
[Bug report] 使用mpx.reportEvent报错

### ISSUE THREAD

**Issue by paraself** [didi/mpx#1045]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
在代码中加入 `mpx.reportEvengt`，在开发工具和真机上都会报错。
``` ts
import mpx, { createPage } from '@mpxjs/core'
createPage({
  onLoad () {
    mpx.reportEvent('test_id', {
      a: 1,
      b: false
    })
  }
})
```
2. 期望的表现
不报错
3. 实际的表现
报错如下。
![image](https://user-images.githubusercontent.com/2179686/175805523-5383535b-98cb-4ad2-8df5-9c5c413c1b4b.png)

**环境信息描述**  
环境信息描述

系统类型(Mac或者Windows)
macOS Montery 2.3.1

Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)

"@mpxjs/api-proxy": "^2.7.1",
"@mpxjs/core": "^2.7.18",
"@mpxjs/miniprogram-simulate": "^1.4.8",
"@mpxjs/mpx-jest": "0.0.9",
"@mpxjs/webpack-plugin": "^2.7.18",
小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
小程序基础库：2.13.2
开发工具：1.05.220425
Node: 16.14.0
npm: 8.3.1

**Demo**  
[duo-build.zip](https://github.com/didi/mpx/files/8986218/duo-build.zip)

**Comment by Blackgan3** [comment]
api-proxy最新版，已修复该问题

@mpxjs/api-proxy@2.7.41
