### ISSUE TITLE
引入 antd-mini 运行后，支付宝报错

### ISSUE THREAD

**Issue by zyaxuan** [didi/mpx#1052]
**问题描述**  
运行 yarn watch:cross 在支付宝里面报错
![image](https://user-images.githubusercontent.com/19178664/178466230-2641f0ed-35b3-43ec-910a-cacbb86a5fa0.png)
引入方式
```json
<script type="application/json" mode="ali">
  {
    "pullRefresh": true,
    "usingComponents": {
      "search-bar": "antd-mini/es/SearchBar/index",
      "van-nav-bar": "@vant/weapp/dist/nav-bar/index",
      "van-empty": "@vant/weapp/dist/empty/index"
    }
  }
</script>
```

使用方式
```html
<search-bar wx:if="{{__mpx_mode__ === 'ali'}}" placeholder="请输入内容" />
```

**Comment by Blackgan3** [comment]
该issue中存在两个问题
* 第一个是支付宝sjs中不支持Object.defineProperty方法导致的报错，已经在新版本进行修复，这里需要更新mpxjs/webpack-plugin 为最新的 2.7.45 版本
https://github.com/didi/mpx/releases/tag/v2.7.45
* 第二个是需要对antd-mini 包配置 moderules 规则，具体规则配置链接[module](https://mpxjs.cn/api/compile.html#moderules)

**Comment by zyaxuan** [comment]
非常感谢，本来以为支付宝的组件不能用呢，感谢大佬指点，期望mpx越来越强大，做大做强！
