### ISSUE TITLE
mpx从1.0.27升级到1.1.14后，properties里的observer里改变data的值会失效

### ISSUE THREAD

**Issue by wayne0201** [didi/mpx#106]
@mpxjs/core从1.0.27升级到1.1.14后，**在组件首次加载的时候**，properties里的observer里改变data的值会失效。原生小程序低版本的mpx都ok，但是升级后就会无效。
<img width="763" alt="屏幕快照 2019-04-03 下午12 23 16" src="https://user-images.githubusercontent.com/18510501/55452693-48f2a000-560b-11e9-9bff-2492ad3aea17.png">

**Comment by cougarwww** [comment]
在observer里console了一下，初始化的时候 this.test 还是 undefined， 所以赋值应该没效果了，我猜应该是初始化的顺序问题， 换个思路，用到text的地方直接用item.text呢？

**Comment by wayne0201** [comment]
> 在observer里console了一下，初始化的时候 this.test 还是 undefined， 所以赋值应该没效果了，我猜应该是初始化的顺序问题， 换个思路，用到text的地方直接用item.text呢？

不是说直接用item.text的问题，这个只是我为了说清问题，简化的一个demo。用watch什么的可以实现功能。功能的话怎么实现都可以实现过去。而是想提醒一下，这块你们做的封装是不是里面有疏漏的地方，可以去看下，完善下去这样才能更好用实用。
