### ISSUE TITLE
[Bug report]配置rules无法加载 woff|woff2|eot|ttf|svg

### ISSUE THREAD

**Issue by qq97381013** [didi/mpx#1065]
[Bug report]配置rules无法加载 woff|woff2|eot|ttf|svg,以下是demo
[mpx-project.zip](https://github.com/didi/mpx/files/9372674/mpx-project.zip)

**Comment by Blackgan3** [comment]
loader需要配置再getRules.js文件中，不能配置再mpxLoader.conf.js中，mpxLoader.conf.js是专门配置mpx-loader选项的文件

**Comment by qq97381013** [comment]
> loader需要配置再getRules.js文件中，不能再配置mpxLoader.conf.js中，mpxLoader.conf.js是配置mpx-loader选项的文件

能提供一个例子嘛，我现在配置的build里面的->getRules.js    
配置 如下还是报错 {
      test: /\.(woff|woff2|eot|ttf|svg)$/,
      use: MpxWebpackPlugin.fileLoader({
        name: 'img/[name][hash].[ext]'
      })
    },

**Comment by Blackgan3** [comment]
demo中webpack我看还是4.x版本，然后Mpx用到了2.7版本，很多配置在2.7版本都有所改变，我给你个use iconfont的示例demo，按照这个来吧 https://github.com/didi/mpx/tree/master/examples/mpx-use-iconfont
