### ISSUE TITLE
MPX下载的插件模板，npm run watch后dist/miniprogram目录少了pages下面的页面

### ISSUE THREAD

**Issue by hwm09110** [didi/mpx#1071]
![image](https://user-images.githubusercontent.com/19773553/187867446-6b420c39-dfd5-42b0-800e-912ee2303727.png)

生成的app.json文件如下
![image](https://user-images.githubusercontent.com/19773553/187868141-43724531-548f-4a54-a30e-aad8f58a0184.png)

**Comment by Blackgan3** [comment]
排查了下，发现是miniprogram/app.mpx 中的 json 模块的 module.exports 单词拼错了，cli这边已经修复了，你可以直接修改下你的 miniprogram/app.mpx 中的 json 块

**Comment by hwm09110** [comment]
> 排查了下，发现是miniprogram/app.mpx 中的 json 模块的 module.exports 单词拼错了，cli这边已经修复了，你可以直接修改下你的 miniprogram/app.mpx 中的 json 块

好的，谢谢
