### ISSUE TITLE
[Bug report] 关于 打包 飞书小程序 后 vant 组件不包含 ttml 和 ttss 文件

### ISSUE THREAD

**Issue by IAKGnaHz** [didi/mpx#1077]
打包后 components文件夹中vant组件不包含 ttml 以及 ttss文件导致报错

![image](https://user-images.githubusercontent.com/32951819/192486220-5cea6622-bfd7-4f04-ae20-02842dfcab97.png)

![image](https://user-images.githubusercontent.com/32951819/192486336-6091d23f-0c0e-4d02-a205-5c5f3f7ad8f6.png)

**Comment by hiyuki** [comment]
没有问题了是吗？
