### ISSUE TITLE
[Bug report]我创建新的项目时遇到的config和webpack问题

### ISSUE THREAD

**Issue by mayingyun** [didi/mpx#1080]
**问题描述**  
我使用 npm i -g @mpxjs/cli 安装更新mpx,系统提示mpx版本@mpx/cli 3.2.0，使用mpx init初始化项目的时候，提示没有该命令，
![image](https://user-images.githubusercontent.com/6906903/193405732-4c83ecf7-79fc-4051-96f4-8eee6260cf9a.png)

根据提示我使用create命令创建了项目，但是create命令创建的项目没有生成config文件夹，我查看了package.json中也没有webpack的依赖，
![image](https://user-images.githubusercontent.com/6906903/193405752-abfe0c69-fa65-42e4-8f39-5c03ae92edef.png)

打开生成项目的目录：
![image](https://user-images.githubusercontent.com/6906903/193405944-cfc5d10e-2455-4a66-a40d-5a809722a563.png)
在mpx2.6的版本中设置rpx单位的rule就是在config文件夹下面，现在没有config文件夹了。rpx怎么设置？

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)   mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)   我上传了demo
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）不涉及开发者工具，使用ide是vscode

**最简复现demo**  
[property-manage.zip](https://github.com/didi/mpx/files/9690103/property-manage.zip)

**Comment by hiyuki** [comment]
3.x 版本项目目录结构发生了比较大的变化，具体使用可以参考：https://github.com/mpx-ecology/mpx-cli
如仍然需使用老的项目目录可以继续安装2.x 版本使用
