### ISSUE TITLE
跨平台编译到抖音小程序，在js文件使用wx或者mpx 的api会报错

### ISSUE THREAD

**Issue by wangkaile007** [didi/mpx#1083]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 创建一个js文件，js文件中使用wx.getStorageSync('string')
2. 获取到缓存中的值
3. 报错：__webpack_require__.n(...)(...).getStorageSync is not a function

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)：Windows
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)：“@mpxjs/api-proxy": "^2.2.26"   "@mpxjs/core": "^2.2.25" "@mpxjs/webpack-plugin": "^2.2.26",
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）：字节跳动开发者工具、V3.3.7-1、2.70.0.5

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）
[test.zip](https://github.com/didi/mpx/files/9738783/test.zip)

**Comment by Blackgan3** [comment]
## 问题原因
api-proxy plugin 的 use，晚于 city/store 的加载，导致city/store中api执行时 mpx 对象上还没挂载上对应环境api。

## 解决方案
* 1. 在  app.mpx script 中 使用 require('./city/store') 的方式，将city/store 的加载放在晚于 api-proxy use 后。
* 2. 也可以创建一个global_use文件，里边放置所有的插件use，global_use文件的引用放在app.mpx script 最顶层

## 额外建议

看到demo项目用的脚手架构建配置版本较旧，同时还在使用babel6，这里建议使用最新的脚手架模版。

https://mpxjs.cn/guide/basic/start.html
