### ISSUE TITLE
引用多个插件报错Error: Plugin "wx3065d5b05f433be9/0" is not defined

### ISSUE THREAD

**Issue by fu188-dev** [didi/mpx#1086]
**问题描述**  
小程序引用多个插件就会报错，报错信息：Error: Plugin "wx3065d5b05f433be9/0" is not defined
然后打开小程序就白屏，打开不了
![image](https://user-images.githubusercontent.com/68093183/194744949-09f90bf9-fe56-43c5-848e-4fd28d3e7f2a.png)
![6c1c007cfa8e9d69e1ad0b7bdfdc605](https://user-images.githubusercontent.com/68093183/194744988-b4e141b8-960b-4aeb-b2c5-2019c8d3ed6f.jpg)

**Comment by fu188-dev** [comment]
不知道是小程序的原因还是mpx的原因，麻烦康康

**Comment by hiyuki** [comment]
mpx对于引用插件没有做任何处理，理论上是插件的问题，可以使用原生demo进行验证

**Comment by fu188-dev** [comment]
好的
