### ISSUE TITLE
调用微信wx.makePhoneCal()接口会重新触发onShow()

### ISSUE THREAD

**Issue by huixu123** [didi/mpx#109]
调用微信wx.makePhoneCal()接口会重新触发onShow() 并且会改变store里的值

**Comment by pkingwa** [comment]
wx.makePhoneCal()触发onShow()是正常的，因为手机里面肯定是切后台（onHide），取消之后会回到前台（onShow），开发工具是本身模拟了这种场景的生命周期。至于修改store的值，你看看自己的onHide或者onShow里面有没有修改store的逻辑

**Comment by huixu123** [comment]
检查了下 onHide和onShow里并没有任何操作store的逻辑。用真机试了下，进入某个页面后在store存了个id。然后切换到其他app。然后在切换回来，刚存的值不在了
