### ISSUE TITLE
@mpxjs/cli 创建示例项目 打包 web 报错

### ISSUE THREAD

**Issue by jekip** [didi/mpx#1090]
**问题描述**  

1、示例项目引入， `vant button` 组件，运行正常显示，打包 `web`，无法访问
2、我以为是 `vant` 的问题，尝试把  `van-button` 隐藏，打包依旧一样
3、`node` 版本 `16.9.0` 使用 `pnpm` 构建

**index.mpx 代码如下**

![image](https://user-images.githubusercontent.com/19426584/194835972-99bc501e-baf6-4c3b-8aa5-e3b049f83448.png)

**报错信息如下**：

![image](https://user-images.githubusercontent.com/19426584/194835532-4522b4da-5eb6-4bef-b292-8f3feac3241b.png)

**Comment by hiyuki** [comment]
在web中使用vant组件需要配置条件编译将其替代为web版本的vant，具体方式可以参考https://github.com/didi/mpx/tree/master/examples/mpx-useuilib

**Comment by jekip** [comment]
> 在web中使用vant组件需要配置条件编译将其替代为web版本的vant，具体方式可以参考https://github.com/didi/mpx/tree/master/examples/mpx-useuilib

感谢，官网有没有相关文档说明，示例项目看着改动不少代码

**Comment by jekip** [comment]
> 在web中使用vant组件需要配置条件编译将其替代为web版本的vant，具体方式可以参考https://github.com/didi/mpx/tree/master/examples/mpx-useuilib

示例也构建不了 `web`，总是提示缺少依赖，依次安装也于事无补？

**Comment by CXY037** [comment]
pnpm确实构建会失败

**Comment by Blackgan3** [comment]
> pnpm确实构建会失败

应该是pnpm 安装的 npm 包都在硬盘 /path/to/.pnpm-store 中，导致项目 build/getRules.js 文件中 modules.rules 配置的  babel-loader include 规则失效，这里修改下 babel-loader 的 include 规则就可以了，主要是将 resolve('node_modules/@mpxjs') 修改为正则匹配的方式。

```js
{
    test: /\.js$/,
    loader: 'babel-loader',
    include: [/\.mpx\.js/, resolve('src'), resolve('test'), /node_modules\/@mpxjs/]
  }
```
