### ISSUE TITLE
[关于 mpx打包 飞书小程序  vant组件缺少 ttml以及ttss的问题]

### ISSUE THREAD

**Issue by IAKGnaHz** [didi/mpx#1098]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
使用 mpx 打包飞书小程序 （mode:tt） 但是未将 vant组件打包成功  打包出的vant 组件 缺少 ttml 和 ttss文件 

打包后文件
![image](https://user-images.githubusercontent.com/32951819/196080083-09e7d73e-e009-4cc3-b6b2-43063eb9badf.png)

打包报错
![image](https://user-images.githubusercontent.com/32951819/196080118-d040f71b-9b2a-413f-b82f-cfed8605929b.png)

vant 组件引用
![image](https://user-images.githubusercontent.com/32951819/196080149-81172ef4-c1dd-4407-a83a-ee30d951543d.png)

2. 期望的表现

能正常打包编译

4. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)

2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

3. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)。mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看) 
  "@mpxjs/core": "^2.7.18",  "@mpxjs/webpack-plugin": "^2.7.18",  "@mpxjs/api-proxy": "^2.7.1",
4. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
 飞书小程序。基础库 1.9.75.5  开发者工具版本2.18.1

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by Blackgan3** [comment]
确定下是不是组件路径写错了，我这边看到@vant/weapp 组件的引入路径应该是：

```js
        'v-icon': '@vant/weapp/dist/icon/index'
```

**Comment by Blackgan3** [comment]
问题已解决，根因为项目某处存在循环引用，在2.7.52版本导致构建死循环，升级至2.7.53版本解决
