### ISSUE TITLE
[Bug report]pnpm打包微信小程序上传文件报错

### ISSUE THREAD

**Issue by CXY037** [didi/mpx#1099]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件 pnpm打包上传
2. 期望的表现 成功
3. 实际的表现
message：Error: 非法的文件，错误信息：invalid file: bundle.js, 317:79, SyntaxError: Unexpected token .        return Promise.reject(new Error(`xfetch参数校验错误 ${config.url} ${checkRes?.message?.length ? 'error:' + checkRes.message.join(',') : ''}`)) [20221017 12:22:31][wx56f91d6d86da5f35]
appid: wx56f91d6d86da5f35
openid: o6zAJswqokTzVfbzShCusQDslYaY
ideVersion: 1.06.2209190
osType: darwin-arm64
time: 2022-10-17 12:22:50

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows) Mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看) 
 "@mpxjs/api-proxy": "^2.8.0",
    "@mpxjs/core": "^2.8.0",
    "@mpxjs/fetch": "^2.8.0",
    "@mpxjs/pinia": "^2.8.0",
    "@mpxjs/store": "^2.8.0",
    "@mpxjs/utils": "^2.8.0",
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
最新版本开发者工具

**Comment by CXY037** [comment]
经测试yarn可以正常打包

**Comment by Blackgan3** [comment]
应该是pnpm 安装的 npm 包都在硬盘 /path/to/.pnpm-store 中，导致项目 build/getRules.js 文件中 modules.rules 配置的  babel-loader include 规则失效，这里修改下 babel-loader 的 include 规则就可以了，主要是将 resolve('node_modules/@mpxjs') 修改为正则匹配的方式。

```js
{
    test: /\.js$/,
    loader: 'babel-loader',
    include: [/\.mpx\.js/, resolve('src'), resolve('test'), /node_modules\/@mpxjs/]
  }
```

**Comment by CXY037** [comment]
> 应该是pnpm 安装的 npm 包都在硬盘 /path/to/.pnpm-store 中，导致项目 build/getRules.js 文件中 modules.rules 配置的 babel-loader include 规则失效，这里修改下 babel-loader 的 include 规则就可以了，主要是将 resolve('node_modules/@mpxjs') 修改为正则匹配的方式。
> 
> ```js
> {
>     test: /\.js$/,
>     loader: 'babel-loader',
>     include: [/\.mpx\.js/, resolve('src'), resolve('test'), /node_modules\/@mpxjs/]
>   }
> ```

我现在测试下

**Comment by CXY037** [comment]
> ```js
> {
>     test: /\.js$/,
>     loader: 'babel-loader',
>     include: [/\.mpx\.js/, resolve('src'), resolve('test'), /node_modules\/@mpxjs/]
>   }
> ```

经测试完全正常，感谢～

**Comment by CXY037** [comment]
> 应该是pnpm 安装的 npm 包都在硬盘 /path/to/.pnpm-store 中，导致项目 build/getRules.js 文件中 modules.rules 配置的 babel-loader include 规则失效，这里修改下 babel-loader 的 include 规则就可以了，主要是将 resolve('node_modules/@mpxjs') 修改为正则匹配的方式。
> 
> ```js
> {
>     test: /\.js$/,
>     loader: 'babel-loader',
>     include: [/\.mpx\.js/, resolve('src'), resolve('test'), /node_modules\/@mpxjs/]
>   }
> ```

已经关闭issue啦谢谢～～～
