### ISSUE TITLE
[Bug report] mpx打包成飞书小程序 vant组件报错

### ISSUE THREAD

**Issue by IAKGnaHz** [didi/mpx#1102]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
使用 watch:cross 打包飞书小程序 组件引入报错
![image](https://user-images.githubusercontent.com/32951819/196360710-bc7bf4da-45ff-4d16-8058-0c4a17b9fb2d.png)
是打包后的 vant组件不支持在tt环境使用嘛
2. 期望的表现
3. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by Blackgan3** [comment]
vant 中的微信内建behavior，例如 `wx://form-field`无法支持，这里应该只对使用vant中的form表单时会有影响，你会使用到vant中的form表单吗

**Comment by IAKGnaHz** [comment]
没有用到 form 表单。目前使用的组件是 popup 和collapse 组件，报错中目前用到的组件都不支持了。应该是某些特性。但是类型button组件样式是可以正常展示的。

**Comment by IAKGnaHz** [comment]
![image](https://user-images.githubusercontent.com/32951819/196633224-891b249a-ad81-4a3c-997c-b2abe965025d.png)

我使用mpx官网的 mpx-useuilib 打包的飞书小程序（mode=tt） 也会存在这样的问题  目前用了这些组件
![image](https://user-images.githubusercontent.com/32951819/196633573-466d5179-ce6b-4d27-9b0c-b0490a8265b8.png)
 版本号
"@mpxjs/api-proxy": "^2.7.28",
"@mpxjs/core": "^2.7.33",
"@mpxjs/webpack-plugin": "^2.7.33",

**Comment by Blackgan3** [comment]
> 

OK，复现了，字节下确实存在问题，我们修复下

**Comment by IAKGnaHz** [comment]
好的 感谢

**Comment by Blackgan3** [comment]
@mpxjs/webpack-plugin@2.7.56 版本已经修复

**Comment by IAKGnaHz** [comment]
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/32951819/197952207-ac90ccbd-4a8b-4970-8ac2-b0e424142eea.png">
是我的编译打包方式有问题吗 mpx-useuilib 打包出来飞书开发者工具还是会有这个报错

<img width="529" alt="image" src="https://user-images.githubusercontent.com/32951819/197952445-b2106d39-2d5a-43b9-980c-7fdadc368d27.png">
<img width="663" alt="image" src="https://user-images.githubusercontent.com/32951819/197952516-18b5171f-8c05-42de-a2c8-da29ad3f9328.png">
<img width="540" alt="image" src="https://user-images.githubusercontent.com/32951819/197952596-7001c0d7-64bf-4aca-9303-05e511a1b118.png">

**Comment by Blackgan3** [comment]
> 
这个包也需要升级下 @mpxjs/core@2.7.56
