### ISSUE TITLE
yarn watch 启动项目报错

### ISSUE THREAD

**Issue by hwm09110** [didi/mpx#1103]
yarn watch 启动项目报错

"@mpxjs/core": "^2.6.110",
"@mpxjs/webpack-plugin": "^2.6.110",

![image](https://user-images.githubusercontent.com/19773553/196590752-2b387109-5fd3-4eb4-a5db-00968c676189.png)

**Comment by Blackgan3** [comment]
webpack 版本是多少

**Comment by hwm09110** [comment]
> webpack 版本是多少

4.46.0

**Comment by liang511** [comment]
@hwm09110 遇上了一样的问题，请问怎么解决的
