### ISSUE TITLE
[Bug report]MPX升级到2.7时，编译报错

### ISSUE THREAD

**Issue by hwm09110** [didi/mpx#1107]
MPX升级到2.7时，编译报错如下：
![image](https://user-images.githubusercontent.com/19773553/196874103-84d82d3e-30ff-41ac-b4a4-f5423cbfa907.png)

分包入口文件写法：
![image](https://user-images.githubusercontent.com/19773553/196874016-8f1b478e-fda7-4763-ad4c-8fd39a6077e3.png)

**Comment by sky-admin** [comment]
require的这个文件存在么？后缀是啥写完整试试？

**Comment by hwm09110** [comment]
> require的这个文件存在么？后缀是啥写完整试试？

文件存在的，后缀.js，加上也不行

app.mpx文件require这个文件是正常的
![企业微信截图_1666259018179](https://user-images.githubusercontent.com/19773553/196914968-8b295cdc-2a5e-4175-8eb2-a52c3f5a1c9f.png)

分包入口改成如下这样是没问题
![image](https://user-images.githubusercontent.com/19773553/196915182-42dd79ef-43ef-468b-98c3-351143c2dfa8.png)

**Comment by Blackgan3** [comment]
> > require的这个文件存在么？后缀是啥写完整试试？
> 
> 文件存在的，后缀.js，加上也不行
> 
> app.mpx文件require这个文件是正常的 ![企业微信截图_1666259018179](https://user-images.githubusercontent.com/19773553/196914968-8b295cdc-2a5e-4175-8eb2-a52c3f5a1c9f.png)
> 
> 分包入口改成如下这样是没问题 ![image](https://user-images.githubusercontent.com/19773553/196915182-42dd79ef-43ef-468b-98c3-351143c2dfa8.png)

提供下编译报错的复现demo吧

**Comment by hwm09110** [comment]
> > > require的这个文件存在么？后缀是啥写完整试试？
> > 
> > 
> > 文件存在的，后缀.js，加上也不行
> > app.mpx文件require这个文件是正常的 ![企业微信截图_1666259018179](https://user-images.githubusercontent.com/19773553/196914968-8b295cdc-2a5e-4175-8eb2-a52c3f5a1c9f.png)
> > 分包入口改成如下这样是没问题 ![image](https://user-images.githubusercontent.com/19773553/196915182-42dd79ef-43ef-468b-98c3-351143c2dfa8.png)
> 
> 提供下编译报错的复现demo吧

**复现demo**
[demo-project.zip](https://github.com/didi/mpx/files/9836126/demo-project.zip)

**Comment by Blackgan3** [comment]
@mpxjs/webpack-plugin@2.7.56 版本已经修复
