### ISSUE TITLE
[Bug report] Still watching  error

### ISSUE THREAD

**Issue by dev-2099** [didi/mpx#1109]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
npm install  安装依赖包
npm run dev  启动调试

2. 期望的表现

3. 实际的表现
Still watching...
Error: EPERM: operation not permitted

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
Windows10 22H2
"node": ">= 16.18.0",
"npm": ">= 8.19.2"

2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
参考demo中配置

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
参考demo中配置

**最简复现demo**

**Comment by Blackgan3** [comment]
下载demo尝试了下，构建时报错not found @babel/core 和 @mpxjs/store

安装下这两个包再构建试试呢

**Comment by Blackgan3** [comment]
脚手架中对于static/wx/project.config 的copy用到了fs.symlink方法，symlink的创建在windows下只有admin有权限，这块我们脚手架修改下，你这边也可以先通过 以管理员身份运行命令行的方式来规避掉

**Comment by dev-2099** [comment]
fs.symlink的问题已解决。另有编译卡住问题请参见demo。

[mpx-demo-next.zip](https://github.com/didi/mpx/files/9867947/mpx-demo-next.zip)

**Comment by Blackgan3** [comment]
项目存在以下问题：

### 1. babel-loader exclude echarts.js 的配置有问题，修改为以下：
```js
config.module.rule("js").exclude.add(path.join(__dirname, "./src/components/ec-canvas/echarts.js")).end()
```
### 2. 项目缺少@babel/core 的依赖

### 3. 不存在 assets/images/logo.png 资源

**Comment by dev-2099** [comment]
本次上传2个demo，都包含echarts，npm包版本，项目配置都一样，测试结果如下：
[mpx-demo-bad.zip](https://github.com/didi/mpx/files/9886687/mpx-demo-bad.zip)
[mpx-demo-good.zip](https://github.com/didi/mpx/files/9886697/mpx-demo-good.zip)

对于 mpx-demo-bad.zip
1、已经按照 Blackgan3 回复的3点修改，仍然卡在编译

对于mpx-demo-good.zip
1、可以正常编译，会提示 The code generator has deoptimised the styling of echarts.js as it exceeds the max of 500KB。

2、加入config.module.rule("js").exclude.add(path.join(__dirname, "./src/components/ec-canvas/echarts.js")).end()配置项，提示消失，可以正常编译。

3、如果注释掉下面的配置，不管加不加config.module.rule("js").exclude.add(path.join(__dirname, "./src/components/ec-canvas/echarts.js")).end()配置项，都会卡在编译阶段。
config.plugin("eslint-webpack-plugin").tap((args) => {
      args[0].exclude = ["node_modules", "src/components/ec-canvas"];
      return args;
    });

**Comment by Blackgan3** [comment]
eslint 也 exclude 掉echarts.js，项目是可以正常编译的是吧

**Comment by dev-2099** [comment]
mpx-demo-good.zip 这个是好的。
mpx-demo-bad.zip 这个 eslint 也 exclude 掉echarts.js，并且加上babel-loader exclude的配置，@babel/core 的依赖，刚刚又把脚手架更新到1.6.13，还是无法编译。

**Comment by Blackgan3** [comment]
将 weapp.socket.io.js 也配置在 eslint 的 exclude 中试下

```js
config.plugin("eslint-webpack-plugin").tap((args) => {
      args[0].exclude = ["node_modules", "src/components/ec-canvas", "src/common/weapp.socket.io.js"];
      return args;
    });
```
