### ISSUE TITLE
[Bug report]跨平台编译时，百度小程序原生语法编写的组件编译错误

### ISSUE THREAD

**Issue by Bowenn** [didi/mpx#1117]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件

- 创建项目选择跨平台
- 在mode="swan"的部分引入了原生语法编写的百度小程序组件
- build

2. 期望的表现

- 正常编译

3. 实际的表现

- 编译产物中mpx单文件语法部分编译正常，原生组件编译产出异常，缺少组件对应的swan文件
<img width="238" alt="image" src="https://user-images.githubusercontent.com/28996450/198252804-8cd76bce-4d55-4718-a5fb-1ab0aa3cd1e6.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/28996450/198252159-d19d6c02-a350-4902-8a8f-8d30d813b155.png">

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
MacOs
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
<img width="296" alt="image" src="https://user-images.githubusercontent.com/28996450/198252332-46fcc32f-f644-4cf3-a177-e4376cd278d7.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/28996450/198252355-3576eb5b-e472-41d2-a6c8-ffd15404b787.png">

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
百度开发者工具

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传

[webswantest.zip](https://github.com/didi/mpx/files/9878291/webswantest.zip)

**Comment by Blackgan3** [comment]
在构建代码中存在原生组件/页面时，需要声明该原生代码的平台，若不声明，会默认为微信小程序的原生代码，你这个问题是testSwan组件被认定为了微信小程序原生组件，倒是test.swan 和 test.css文件丢失，这里需要做下原生平台声明，声明的方式有两种：

1.使用 Mpx 框架提供 [moduleRules](https://mpxjs.cn/api/compile.html#moderules) 规则，在@mpxjs/webpack-plugin中加入类似如下配置：

```js
   modeRules: {
      swan: {
        include: ['src/components/testSwan']
      }
    }
```

2. 原生组件加入mode后缀，将testSwan组件的文件名改为如下形式:
```js
#### index.swan.js
#### index.swan.css
#### index.swan.json
#### index.swan.swan
```
以上两种方式任选其一即可
