### ISSUE TITLE
[Bug report]output h5 and use 'mpx.showModal',it's wrong modal size

### ISSUE THREAD

**Issue by zengtv** [didi/mpx#1128]
when I choose 'iphone 12 pro', it's right
![image](https://user-images.githubusercontent.com/38457386/203223333-9dee924e-f3b9-4037-b7eb-af84ae66084d.png)
but when I choose 'ipad', the modal size and font size is too small
![image](https://user-images.githubusercontent.com/38457386/203223515-b7d2601a-c427-4f23-ab60-8e310eded1eb.png)
because it used 'px'
![image](https://user-images.githubusercontent.com/38457386/203223657-b851faeb-06f7-411f-bb53-e921c9e02fa4.png)
and html style it changed to 'vw'
![image](https://user-images.githubusercontent.com/38457386/203223839-9a92ba10-12ba-4ca9-bf2f-912880b6eec1.png)

windows 10 , chrome v107.0.5304.107, node v16.17, @mpx/cli 3.2.0  mode:vue3+pinia , npm run serve:web
![image](https://user-images.githubusercontent.com/38457386/203224626-96d22e2d-97d2-436e-bed5-97708ba7a75d.png)

**Comment by yandadaFreedom** [comment]
Mpx 内置的组件样式使用 px 单位，如果想转换为 vw，可以通过配置 [transRpxRules](https://mpxjs.cn/api/compile.html#transrpxrules) 属性进行转换；include 配置为 @mpxjs 所在路径，designWidth 配置为 375 即可~

**Comment by yandadaFreedom** [comment]
可以参考下这个配置哈
![image](https://user-images.githubusercontent.com/24402059/204701199-e1d1b07f-b99f-4e6a-8eb9-7ea944a35388.png)

**Comment by yandadaFreedom** [comment]
可以参考下这个配置哈
![image](https://user-images.githubusercontent.com/24402059/204702152-a91ed4ce-16df-4bfb-b1c6-0f48e9dd5520.png)

**Comment by hiyuki** [comment]
先关闭了，又后续问题再open
