### ISSUE TITLE
开启i18n后原来已经有的wxs代码不能正确执行

### ISSUE THREAD

**Issue by CXY037** [didi/mpx#1133]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件 开启i18n后原来已经有的wxs代码不能正确执行
2. 期望的表现 wxs正常执行
3. 实际的表现 TypeError: Cannot read property 'getTimeFromIndexLast' of undefined
    at Uo._i1 (bookLockMap.mpx?99b3:60)
    at ReactiveEffect.run (effect.js:31)
    at RefImpl.get [as value] (computed.js:25)
    at Uo.get [as _i1] (object.js:120)
    at Uo.render (bookLockMap.mpx?99b3:20)
    at ReactiveEffect.fn (proxy.js:512)
    at ReactiveEffect.run (effect.js:31)
    at callWithErrorHandling (errorHandling.js:7)
    at flushJobs (scheduler.js:152)(env: macOS,mp,1.06.2210141; lib: 2.26.0)

已经更新为最新版本mpx 使用的包管理器是pnpm

**Comment by CXY037** [comment]
i18n: {
    locale: 'zh-CN',
    messagesPath: path.resolve(__dirname, '../src/i18n/i18n.js')
  }

**Comment by CXY037** [comment]
查看调试器中的注入代码是
<img width="509" alt="image" src="https://user-images.githubusercontent.com/2595427/203942882-14709124-9e0b-4593-ac20-a67cdb585e6b.png">

**Comment by CXY037** [comment]
开启与不开启i18n生成代码比对如下
<img width="1702" alt="image" src="https://user-images.githubusercontent.com/2595427/203945032-aa3e2be8-ef85-4d15-ade8-b5480475beff.png">

**Comment by Blackgan3** [comment]
有可以复现的demo吗

**Comment by Blackgan3** [comment]
> [<img alt="@CXY037" width="20" height="20" src="https://avatars.githubusercontent.com/u/2595427?s=40&amp;v=4">](/CXY037) [CXY037](/CXY037) changed the title ~[Bug report]~ 开启i18n后原来已经有的wxs代码不能正确执行 [Nov 25, 2022](#event-7891322987)

你这个是开启了useComputed 选项是吧，可以检查下组件实例上的tools 为啥为undefined，或者给个复现demo吧

**Comment by CXY037** [comment]
开启不开启都报错，我写个最小复现
2022年11月28日 +0800 PM8:06 BlackGan ***@***.***>，写道：

**Comment by CXY037** [comment]
git@github.com:CXY037/i18nbug.git

**Comment by CXY037** [comment]
> [git@github.com:CXY037/i18nbug.githttps://github.com/CXY037/i18nbug.git](https://github.com/CXY037/i18nbug.git)

**Comment by Blackgan3** [comment]
> > [git@github.com:CXY037/i18nbug.githttps://github.com/CXY037/i18nbug.git](https://github.com/CXY037/i18nbug.git)

这个demo我测试了下运行时正常的

**Comment by CXY037** [comment]
> > > [git@github.com:CXY037/i18nbug.githttps://github.com/CXY037/i18nbug.git](https://github.com/CXY037/i18nbug.git)
> 
> 这个demo我测试了下运行时正常的

我这里会报错，我升级下微信开发者工具

**Comment by CXY037** [comment]
> 

可以截图个打开的页面么

**Comment by CXY037** [comment]
> > > [git@github.com:CXY037/i18nbug.githttps://github.com/CXY037/i18nbug.git](https://github.com/CXY037/i18nbug.git)
> 
> 这个demo我测试了下运行时正常的

可否加个微信联系，或者截图个开发者工具的页面，谢谢

**Comment by CXY037** [comment]
global.currentInject.injectComputed = {
  _i1() {
    return this.tools.getDate(this.order.lock_time);
  }
};
会生成这个代码么？

**Comment by CXY037** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/2595427/204691337-d5128abc-9a49-4f05-b974-c2600ddcbbf8.png">

**Comment by hiyuki** [comment]
应该是我们的i18n调用检测误匹配了，我们修复一下

**Comment by CXY037** [comment]
> 应该是我们的i18n调用检测误匹配了，我们修复一下

谢谢

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.8.12 已修复

**Comment by CXY037** [comment]
> https://github.com/didi/mpx/releases/tag/v2.8.12 已修复

感谢～～牛批
