### ISSUE TITLE
云开发目录问题

### ISSUE THREAD

**Issue by 0227vera** [didi/mpx#1135]
按照文档中的init云开发项目，无法上传云函数
发现static/wx/project.config.json的配置未同步打包到dist/wx/project.config.json，而是打包到dist/miniprogram/project.config.json
导致没有云函数的入口配置，需要手动在dist中进行配置

**Comment by hiyuki** [comment]
@mpxjs/cli的版本是多少呢？

**Comment by 0227vera** [comment]
> @mpxjs/cli的版本是多少呢？

@mpx/cli 3.2.0

**Comment by Blackgan3** [comment]
脚手架的问题，我们修复下

**Comment by Blackgan3** [comment]
相应的cli 插件已经完成修复，项目重新执行下 `npm i `即可更新。
