### ISSUE TITLE
WXML中模板import的支持和data变量展开支持

### ISSUE THREAD

**Issue by cougarwww** [didi/mpx#114]
rt，类似这样

`<import src="./towxml/entry.wxml"/>`
`<template is="entry" data="{{...article}}"/>`

**Comment by sky-admin** [comment]
2.0版本即将支持

**Comment by sky-admin** [comment]
https://github.com/didi/mpx/releases/tag/v2.0.0
2.0版本已发布，完美支持以上需求，欢迎尝试，有问题随时反馈。

**Comment by wind4gis** [comment]
@sky-admin 
有没有示例，我直接用template后直接报错了
