### ISSUE TITLE
[Bug report] reactive<Array>未生效响应式

### ISSUE THREAD

**Issue by pagnkelly** [didi/mpx#1140]
```js
  it.only('should work with reactive source', async () => {
    const spy = vitest.fn((newList, oldList, added, removed) => {
      expect(newList).toEqual([1, 2, 3, 4])
      expect(oldList).toEqual([1, 2, 3])
      expect(added).toEqual([4])
      expect(removed).toEqual([])
    })

    const num = reactive([1, 2, 3])
    watch(num, spy)
    num.push(4)
    await nextTick(noop)
    expect(spy).toBeCalledTimes(1)
  })
```

`reactive`数组貌似响应式不生效，没有触发相应的watch

看了下源码，为什么数组要单独处理，且没做依赖收集。
![image](https://user-images.githubusercontent.com/16016300/205480764-93872a67-247d-45c2-8e02-9365ab020be6.png)

**Comment by hiyuki** [comment]
额。。这个问题我在内部分享的时候应该解释过不止一次了。。建议仔细阅读这个章节https://www.mpxjs.cn/articles/2.8-release.html#%E6%95%B0%E6%8D%AE%E5%93%8D%E5%BA%94%E9%99%90%E5%88%B6%E5%B8%A6%E6%9D%A5%E7%9A%84%E5%B7%AE%E5%BC%82
