### ISSUE TITLE
接入三方sdk报错

### ISSUE THREAD

**Issue by xuangel5052** [didi/mpx#1141]
mpx项目中引入云信令sdk，[下载地址](https://docs.agora.io/cn/Real-time-Messaging/downloads)（sdk内含ES6代码）。
业务页面内import引入，npm run watch后报错如下：
![image](https://user-images.githubusercontent.com/37662985/205655534-026a6b9f-d8f9-4fd8-9450-699a5c7118f1.png)

后在babel-loader中exclude掉该文件，也无法构建成功，报错如下：
![image](https://user-images.githubusercontent.com/37662985/205655941-073b4e09-c061-42d6-9e42-b87f210ad718.png)

请问这类sdk该如何修改配置接入

  
@mpxjs/core: "^2.6.31"
@mpxjs/webpack-plugin: "^2.6.31"
@mpxjs/api-proxy: "^2.5.10"

微信小程序基础库 2.28.0

**Comment by Blackgan3** [comment]
如果SDK中存在ES6语法，不可以直接在babel中exclude，确定下在babel.config.json中是否有配置项

```js
  "sourceType": "unambiguous"
```
如果没有，就配置试下
如果已配置还是报错，可以把你的demo上传下
