### ISSUE TITLE
[Bug report] 当使用 tailwindcss 插件开发页面时，文件热重载没有触发 tailwindcss，导致 app.wxss 没有重新生成从而 tailwindcss 失效

### ISSUE THREAD

**Issue by sonofmagic** [didi/mpx#1146]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 使用 postcss tailwindcss 插件开发页面时，保存 `pages/*.mpx` ,`components/*.mpx` 这类的文件，HMR 并没有触发 tailwindcss 插件，导致 app.wxss 没有重新生成。
2. 保存 `app.mpx`/ `tailwind.config.js` / `package.json` 会走全量，重新生成 `app.wxss`

**环境信息描述**  
至少包含以下部分：
1. Windows11
3. Mpx 2.8 (LTS) 刚从官网教程里新建的
4. 小程序平台 wx 、开发者工具版本: 微信开发者工具 1.062209190 LTS.、基础库版本:2.28.0

**最简复现demo**  
https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin/tree/feature/mpx-demo/demo/mpx-app

先执行 yarn ,
yarn  serve
此时全量情况下 `pages/index.mpx` 中的 `text-[#3f6e47]` 样式顺利生成
更改为 `text-[#aa88cc]` 保存。

此时 `dist/wx/app.wxss` 并没有重新生成，也没有生成  `text-[#aa88cc]` 的工具类。

后来我进行了调试，发现在hmr下

全量情况，进入了 `tailwindcss` 源码中：
单个保存页面文件的情况下，居然没有命中 `tailwindcss` 的入口断点，

所以前来请教一下

**Comment by sonofmagic** [comment]
发现只有在 mpx 文件里，存在 <style> 代码块，再进行保存的时候，才进入 tailwindcss 插件的断点。

期望的行为：
不加 <style> 代码块，标签上直接使用 tailwindcss 就可以自动重新生成 app.wxss

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.8.16 感谢反馈，该问题目前已经修复~
