### ISSUE TITLE
[Bug report]最新mpxjs/cli初始化出来的模板，static文件夹打包后路径错误

### ISSUE THREAD

**Issue by wiexin** [didi/mpx#1159]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
在static文件夹的wx子文件夹下面随便新建一个文件夹，旧版本中会将wx文件夹里的所有内容复制到dist目录中，现在变成dist目录下面多一层wx文件夹
![image](https://user-images.githubusercontent.com/18095039/209948831-7524cd30-ae6c-4b39-b386-83db3d87caba.png)

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows) 
Windows
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本
@mpxjs/core 2.8.15
@mpxjs/webpack-plugin 2.8.16
@mpxjs/api-proxy 2.8.8

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
微信小程序平台

**最简复现demo**  
1、脚手架生成微信小程序项目
2、static的wx文件夹下新建个文件夹，里面放点文件
3、执行打包
4，生成的dist文件夹中 多一个wx文件夹

**Comment by mater1996** [comment]
1. 更新@mpxjs/vue-cli-plugin-mpx-mp到v1.6.25来解决这个问题。
2. 建议不要在static/wx下放置需要参与构建的资源文件，因为这样会导致资源的两次输出。
