### ISSUE TITLE
style 里面部分图片没有转成base64

### ISSUE THREAD

**Issue by hwm09110** [didi/mpx#1165]
MPX升级到2.7+后，style 里面引用的图片中，有个别没有转成base64
![image](https://user-images.githubusercontent.com/19773553/212036091-506874de-8b2f-46e0-926d-a674e9e51ee3.png)

"@mpxjs/core": "2.7.37"
"@mpxjs/webpack-plugin": "2.7.56",

**Comment by hwm09110** [comment]
同一张图片，mpx2.6 是正常的

**Comment by Blackgan3** [comment]
OK，我看下

**Comment by Blackgan3** [comment]
你2.7项目中的getRules.js 文件中的 urlLoader 是怎么配置的？ 或者把你2.7有问题的项目提供下也行

**Comment by hwm09110** [comment]
> 你2.7项目中的getRules.js 文件中的 urlLoader 是怎么配置的？ 或者把你2.7有问题的项目提供下也行

![image](https://user-images.githubusercontent.com/19773553/212246648-6b844b23-b691-45c3-b46c-38d12df1bc0e.png)
配置没改

**Comment by hwm09110** [comment]
> > 你2.7项目中的getRules.js 文件中的 urlLoader 是怎么配置的？ 或者把你2.7有问题的项目提供下也行
> 
> ![image](https://user-images.githubusercontent.com/19773553/212246648-6b844b23-b691-45c3-b46c-38d12df1bc0e.png) 配置没改

测试发现，template块 image 引用的图片，跟style引用的图片是同一张的情况下，style里面的不会转成base64
![image](https://user-images.githubusercontent.com/19773553/212272711-61487dd2-268c-431b-aa83-46334bb3eb14.png)
![image](https://user-images.githubusercontent.com/19773553/212272805-aaaad197-65ea-44b8-80f5-59fbc0a8dfb2.png)

**Comment by Blackgan3** [comment]
和这个应该也没关系，这种场景我也测试并没复现，还是辛苦上传下你的复现demo项目吧

**Comment by hwm09110** [comment]
[demo-project.zip](https://github.com/didi/mpx/files/10526571/demo-project.zip)
![image](https://user-images.githubusercontent.com/19773553/215253011-6440226c-6614-4d68-9319-76819a026035.png)

**Comment by Blackgan3** [comment]
好的，确实有问题，我跟进下

**Comment by Blackgan3** [comment]
@mpxjs/webpack-plugin@2.7.60 版本已修复这个问题

https://github.com/didi/mpx/releases/tag/v2.7.60

**Comment by hwm09110** [comment]
好滴，3Q
