### ISSUE TITLE
wx:if 中不能使用 WXS 模块的函数

### ISSUE THREAD

**Issue by arbing** [didi/mpx#117]
模版

```
<view
  class="msg-time"
  wx:if="{{index === 0 || !utils.isSameMinute(item.msgTime, list[index - 1].msgTime)}}"
>
</view>
```

报如下错误

> Expressions in wx:if/wx:elif/wx:for can not contain wxs module data.

**Comment by sky-admin** [comment]
这个错误应该没有对程序运行产生什么影响对吧？
错误产生的原因是我们的一个性能优化手段是对模板做分析得到一个渲染函数，通过渲染函数我们可以找到用户真实使用的数据，用来精确地改变那一个数据而不是全量setData，但如果用户在if/elif/for里使用了wxs，我们无法获取wxs里地数据，只能抛出一个错误，然后降级为，仅做简单diff，而不分析用户使用了哪些变量地setData。
表现形式我们可能会考虑再变化一下对开发者更友好一些。

**Comment by arbing** [comment]
确实不影响渲染，只是会抛出一个异常，暂时用 hidden 替代实现了。

**Comment by sky-admin** [comment]
我们将会在2.0版本彻底解决这个问题，wxs的优势和我们的优化能一起正常work

**Comment by sky-admin** [comment]
https://github.com/didi/mpx/releases/tag/v2.0.0
2.0版本已发布，完美解决了这个问题，欢迎体验。

**Comment by clevergod** [comment]
> https://github.com/didi/mpx/releases/tag/v2.0.0
> 2.0版本已发布，完美解决了这个问题，欢迎体验。

wxs怎么使用？我在mpx文件 添加wxs标签 提示undefined
```
<wxs module="tool">
function test (str) {
  return str && str.indexOf('辅导') != -1
}
module.exports = {
  test : test,
}
</wxs>
```
