### ISSUE TITLE
[Bug report] defineProps 在typescript下的类型不正确

### ISSUE THREAD

**Issue by paraself** [didi/mpx#1172]
**问题描述**  
根据文档：
<img width="762" alt="image" src="https://user-images.githubusercontent.com/2179686/218268437-3e95c8aa-90f9-4e0c-9334-94f6b2085574.png">

按照以上方法在ts脚本中定义properties，defineProps报错：
<img width="542" alt="image" src="https://user-images.githubusercontent.com/2179686/218268530-83efb5c7-d312-4ec2-a753-213b0dafb0ee.png">

defineProps目前的类型定义，需要传入至少一个参数，与文档中不符合。

另外使用 ts-ignore 忽略报错之后，编译后的脚本文件，产生了错误，如下：
<img width="294" alt="image" src="https://user-images.githubusercontent.com/2179686/218268621-01cb0c2d-206e-42d0-9d09-9cd7b36f2cc2.png">

**环境信息描述**  
Mac OS 12.6
"@mpxjs/api-proxy": "^2.8.8",
"@mpxjs/core": "^2.8.20",
"@mpxjs/fetch": "^2.8.6",
"@mpxjs/pinia": "^2.8.15",
"@mpxjs/store": "^2.8.15",
"@mpxjs/utils": "^2.8.15",
---
"@mpxjs/babel-plugin-inject-page-events": "^2.8.1",
"@mpxjs/eslint-config-ts": "^1.0.7",
"@mpxjs/mpx-cli-service": "^1.6.28",
"@mpxjs/size-report": "^2.8.19",
"@mpxjs/vue-cli-plugin-mpx": "^1.6.28",
"@mpxjs/vue-cli-plugin-mpx-eslint": "^1.6.28",
"@mpxjs/vue-cli-plugin-mpx-mp": "^1.6.28",
"@mpxjs/vue-cli-plugin-mpx-typescript": "^1.6.28",
"@mpxjs/webpack-plugin": "^2.8.20",

**Comment by Blackgan3** [comment]
升级下 @mpxjs/core@2.8.21 @mpxjs/webpack-plugin@2.8.21 试试

**Comment by Blackgan3** [comment]
另外需要注意的是，script setup中使用ts类型定义properties，不支持复杂类型和import 引用类型哈，例如下方这种写法就不支持

```js
interface B {
  name: string
}

interface A {
  age: number
  alisa: B
}
const props = defineProps<A>()
```

**Comment by paraself** [comment]
> 不支持复杂类型和import 引用类型

那这样的话，限制太大了。。。
我又试了试，发现这样是可以的
```
interface B {
  name: string
}

interface A {
  age: number
  alisa: B
}

const props: A = defineProps({
  age: Number,
  xxxxxxxx
})
```

**Comment by Blackgan3** [comment]
这种不用 ts 类型来初始化 properties 的写法是没问题的
