### ISSUE TITLE
[Bug report]  Property 'xfetch' does not exist on type 'Mpx & Pick<Wx, GetFunctionKey<Wx>>'.

### ISSUE THREAD

**Issue by cococa** [didi/mpx#1178]
{
  "name": "next",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "mpx-cli-service serve:mp",
    "build": "mpx-cli-service build:mp",
    "lint": "eslint --ext .js,.ts,.mpx src/",
    "build:web": "mpx-cli-service build:web",
    "serve:web": "mpx-cli-service serve:web"
  },
  "dependencies": {
    "@mpxjs/api-proxy": "^2.8.0",
    "@mpxjs/core": "^2.8.0",
    "@mpxjs/fetch": "^2.8.0",
    "@mpxjs/pinia": "^2.8.0",
    "@mpxjs/store": "^2.8.0",
    "@mpxjs/utils": "^2.8.0",
    "pinia": "^2.0.14",
    "vue": "^2.6.14",
    "vue-demi": "^0.13.11",
    "vue-i18n": "^8.27.2",
    "vue-i18n-bridge": "^9.2.2",
    "vue-router": "^3.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.10.4",
    "@babel/preset-env": "^7.10.4",
    "@babel/runtime-corejs3": "^7.10.4",
    "@mpxjs/babel-plugin-inject-page-events": "^2.8.0",
    "@mpxjs/eslint-config-ts": "^1.0.5",
    "@mpxjs/mpx-cli-service": "^1.0.0",
    "@mpxjs/size-report": "^2.8.0",
    "@mpxjs/vue-cli-plugin-mpx": "^1.0.0",
    "@mpxjs/vue-cli-plugin-mpx-eslint": "^1.0.0",
    "@mpxjs/vue-cli-plugin-mpx-mp": "^1.0.0",
    "@mpxjs/vue-cli-plugin-mpx-typescript": "^1.0.0",
    "@mpxjs/vue-cli-plugin-mpx-web": "^1.0.0",
    "@mpxjs/webpack-plugin": "^2.8.0",
    "@vue/cli-service": "~5.0.0",
    "autoprefixer": "^10.2.4",
    "eslint": "^7.0.0",
    "postcss": "^8.2.6",
    "stylus": "^0.55.0",
    "stylus-loader": "^6.1.0",
    "typescript": "^4.1.3",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^5.43.0"
  },
  "browserslist": "ios >= 8, chrome >= 47"
}

**Comment by hiyuki** [comment]
是否引入使用的@mpxjs/fetch，如果确定没有问题上传一个复现demo吧

**Comment by cococa** [comment]
试一下用 TypeScript
