### ISSUE TITLE
[Feature Request]响应式系统是否有用Proxy重构的计划？

### ISSUE THREAD

**Issue by theozhang32** [didi/mpx#1182]
从当前基础库对Proxy的支持度来看，貌似现在使用Proxy也是可行的？https://wechat-miniprogram.github.io/miniprogram-compat/

**Comment by hiyuki** [comment]
嗯，有相关计划，我们尽量在上半年支持上

**Comment by CS-liujf** [comment]
> 嗯，有相关计划，我们尽量在上半年支持上

请问从目前进度来看，用Proxy重构响应式还可能在上半年完成吗，主要是觉得Proxy替代defineProperty后，一些响应限制就没了，感觉非常方便，因此很期待

**Comment by HardenSG** [comment]
> 嗯，有相关计划，我们尽量在上半年支持上

那这会受到兼容性的问题吗

**Comment by RanierYu** [comment]
请问进度如何了

**Comment by PlutoCRown** [comment]
请问进度如何了
