### ISSUE TITLE
[Bug report] web是不是不支持wxml

### ISSUE THREAD

**Issue by leechuichui** [didi/mpx#1186]
微信小程序原生语法是不是不支持输出为web?
![image](https://user-images.githubusercontent.com/10825690/223897587-174cb29b-55c0-4127-8413-046728715bfc.png)
![image](https://user-images.githubusercontent.com/10825690/223897699-d2169055-34f3-4693-b460-6a7399452541.png)

**Comment by hiyuki** [comment]
是的，输出web目前仅支持.mpx单文件形式编写的组件
