### ISSUE TITLE
咨询下什么时候会支持快应用?

### ISSUE THREAD

**Issue by QinPoetry** [didi/mpx#1191]
在master里面看到了很多qa相关的代码，MPX是准备正式支持快应用了吗

**Comment by hiyuki** [comment]
目前我们已经支持输出快应用的web版，输出mode设置为qa即可，快应用的原生版目前没有支持计划

**Comment by QinPoetry** [comment]
现在mpx cli里还不支持mode为qa，
https://github.com/mpx-ecology/mpx-cli/blob/master/packages/vue-cli-plugin-mpx/constants/mode.js
我们是华为的快应用团队，对mpx cli做了部分代码修复，是否可以将修改通过mr提交上来？

**Comment by mater1996** [comment]
@QinPoetry 可以的，感谢。
