### ISSUE TITLE
[Bug report] Mpx单次构建中只能存在一个App

### ISSUE THREAD

**Issue by tuhe32** [didi/mpx#1193]
**问题描述**  
使用模板新建一个项目，编译输出web端时报错：
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/18496264/226837070-12ed91cd-fb45-4827-abe4-675f6b87d043.png">

执行步骤
1、mpx create mpx-demo
2、yarn build:web

3. 期望的表现
4. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型 ：Mac
3. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
@mpxjs/core: version "2.8.26"
@mpxjs/webpack-plugin: version "2.8.25"
@mpxjs/api-proxy: version "2.8.8"
5. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
web端页面

**最简复现demo**  
[mpx-demo.zip](https://github.com/didi/mpx/files/11037651/mpx-demo.zip)

**Comment by hfstack** [comment]
后面怎么解决的了

**Comment by tuhe32** [comment]
> 

我这还是这样

**Comment by hfstack** [comment]
> > 
> 
> 我这还是这样

我找到了问题原因：app对公共less文件的引用导致这个报错
<style lang="less">
  @import 'static/css/default';
  @import 'static/css/var';
  @import 'static/css/van';
</style>
我将less文件的引用放到script下就可以了
  import '../static/css/main.less'

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.8.29 已修复
