### ISSUE TITLE
[Bug report] 选项式组件中无法使用setup语法糖组件

### ISSUE THREAD

**Issue by paraself** [didi/mpx#1194]
**问题描述**  
如题，打开项目，执行npm run serve 之后小程序开发工具报错: “defineProps is not defined”

![dc9576350752a7f52fcd5d8599e0665](https://user-images.githubusercontent.com/2179686/227774436-75041589-09fb-4ebb-b194-a215e46f6739.png)

**环境信息描述**  
至少包含以下部分：
1. Win 10

**最简复现demo**  
https://github.com/paraself/mpx-test/tree/setup-comp
运行该分支，执行npm run serve

**Comment by Blackgan3** [comment]
defineProps 是个纯编译语法糖，并且在编译时只识别 callExpression，不能用 defineProps() as InterfaceA 这种ts asExpression 类型语法，这在编译时是不被识别的

**Comment by paraself** [comment]
TT Sorry忘记了，改成
```
const props: IEntrySequence = defineProps({})
```
就好了。
