### ISSUE TITLE
[Bug report] 新建项目啥都不改直接编译上传就 645k 了

### ISSUE THREAD

**Issue by zhujiageng** [didi/mpx#1197]
我看到 mpx 的介绍说压缩后只占用 60K，很感兴趣就试用了下，发现新建项目后什么都不做，bundle.js 就达到了 592k，是需要怎么配置才能降低到 60k 吗？

**Comment by hiyuki** [comment]
因为你使用的未压缩的开发模式，走生产模式构建，`npm run build`，以及初始项目构建产物除了mpx框架运行时之外还包含core-js polyfill，如果想要达到极致的体积可以把babel关闭，这样构建出来的bundle.js就<60k了，具体体积构成你可以使用@mpxjs/size-report这个插件进行可视化分析查看
