### ISSUE TITLE
[分包异步化引用js构建报错]

### ISSUE THREAD

**Issue by asself** [didi/mpx#1206]
**问题描述**  
1. 问题触发的条件
分包异步化引用js
<img width="718" alt="image" src="https://user-images.githubusercontent.com/17953208/234443825-9327225a-8b1a-44a9-8db1-84773f474916.png">

2. 期望的表现
构建不报错

3. 实际的表现
构建报错，Cannot statically analyse 'require(…, …)' in line 4
<img width="806" alt="image" src="https://user-images.githubusercontent.com/17953208/234444030-cf4bb526-df8a-45a1-a76f-78f0f44cde38.png">

**环境信息描述**  

至少包含以下部分：
1. 系统类型 Mac

2. Mpx依赖版本
 "@mpxjs/core": "^2.8.0",
 "@mpxjs/webpack-plugin": "^2.8.0",
 "@mpxjs/api-proxy": "^2.8.0",

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

微信小程

**最简复现demo**  
[mpx-demo.zip](https://github.com/didi/mpx/files/11328200/mpx-project.zip)

**Comment by Blackgan3** [comment]
这里应该是 require不能传入多个参数的限制导致的报错，关于分包异步js的使用，当前应该只能使用require.async这种方式，这块先采用require.async 的方式吧

**Comment by asself** [comment]
文档不是说支持require，这不是一个bug吗

**Comment by Blackgan3** [comment]
> 文档不是说支持require，这不是一个bug吗

嗯嗯，文档那块的描述有点问题，文档已经修改过来了
