### ISSUE TITLE
mixins在传递对象数组时长度异常

### ISSUE THREAD

**Issue by wangtunan** [didi/mpx#121]
版本：@mpxjs/core": "^1.1.0 "@mpxjs/webpack-plugin": "^1.1.0"
操作系统：windows10
浏览器：谷歌74.0.3702.0
问题描述：组件使用mixins引入时，定义在mixin.js中的数组对象，长度异常，原来写了3个对象，传递过去后数组对象的长度变为1000，其中前3个位正常数据，后面997个全部为undefined

// mixins.js代码
![image](https://user-images.githubusercontent.com/48847606/57502889-7de7c600-7320-11e9-8d6d-41b2377fb4c0.png)

// component代码
![image](https://user-images.githubusercontent.com/48847606/57502899-89d38800-7320-11e9-9592-c3869deef136.png)

异常结果：
![image](https://user-images.githubusercontent.com/48847606/57502688-678d3a80-731f-11e9-981c-84e2cac33972.png)

控制台警告信息：
![image](https://user-images.githubusercontent.com/48847606/57502715-855a9f80-731f-11e9-8bc4-0f77cc8b7e5b.png)

**Comment by sky-admin** [comment]
https://mobx.js.org/refguide/array.html  看下方Array limitations in MobX 4 and below一节
中文版：https://cn.mobx.js.org/refguide/array.html

**Comment by wangtunan** [comment]
已通过toPureObject拿到原生Js对象
