### ISSUE TITLE
scroll-view的bindscrolltolower转成web之后不执行

### ISSUE THREAD

**Issue by chinalihongxiang** [didi/mpx#1218]
小程序正常可以触发bindscrolltolower，但web触底没反应
[src.zip](https://github.com/didi/mpx/files/11566176/src.zip)
demo可复现

**Comment by yandadaFreedom** [comment]
经沟通提供的src代码未复现，暂时先关闭处理了，后续如果有稳定的复现路径和环境，欢迎重新提issue联系我们~
