### ISSUE TITLE
[Bug report]字节小程序引入vant组件后报错

### ISSUE THREAD

**Issue by zengtv** [didi/mpx#1220]
**问题描述**  
Windows 10   @mpx/cli 3.2.0   node 18.16.0  mpx core 2.8.0

mpx create project  => 选择平台 tt

npm i @vant/weapp

页面引入
"usingComponents": {
      "tlist": "../components/list",
      "van-button": "../../node_modules/@vant/weapp/dist/button/index"
    }

npm run serve 后报错 

编译错误 can't find component: components/vant/dist/button/index corresponding components/vant/dist/button/index.ttml
at components/vant/dist/button/index.json

![image](https://github.com/didi/mpx/assets/38457386/453351f6-c955-4fd9-a8ae-11794e64441a)
![image](https://github.com/didi/mpx/assets/38457386/51f2d456-43a6-49bc-b901-a4b9b769826d)
![image](https://github.com/didi/mpx/assets/38457386/753f0f9c-bd33-41a3-86cb-aa6bb790fffd)
![image](https://github.com/didi/mpx/assets/38457386/170bc5ff-479e-484f-9380-5cf5ad413e73)

**最简复现demo**  

[tiktok-miniprogram.zip](https://github.com/didi/mpx/files/11591001/tiktok-miniprogram.zip)

**Comment by Blackgan3** [comment]
下载代码看了下，这里在vue.config.json中对 mpxPlugin 中的 srcMode 配置填写了tt

如果srcMode 为 tt 的话，框架在构建编译时，碰到原生组件，会去依据srcMode去索引对应组件文件，例如去索引查找 button/index.ttml，button/index.ttss，但这里引用的vant组件库是微信原生语法来书写的，组件库中只有button/index.wxml、button/index.wxss，因此template 和 css 就会找不到，也就不会输出

当我们需要使用vant组件库并且输出到其他平台小程序时，我们的srcMode需要设置为wx，targetMode设置为tt，这里需要将vue.config.json 中的 srcMode 改为 wx，然后在构建时传入targetMode就行，构建命令的书写类似下方：

```js
    "build:tt": "mpx-cli-service build:mp --targets=tt",

```
