### ISSUE TITLE
[Bug Report] scss编译报错

### ISSUE THREAD

**Issue by ASkyBig** [didi/mpx#1221]
**问题描述**  
当样式里出现calc语句时，例如 `padding-bottom: calc(env(safe-area-inset-bottom) + 140rpx + 56px);` , 转换成 rpx 就编译报错了，`Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "UNKNOWN_DIMENSION"`

<img src="https://github.com/didi/mpx/assets/26340566/21626a66-1029-4f5d-8b0a-d22f63872de0"  width="800"/>

搜索了一下，应该是postcss不支持小数，有什么方式可以解决这个问题吗？

**Comment by Blackgan3** [comment]
没有复现该报错，请上传下复现demo

**Comment by ASkyBig** [comment]
[https://github.com/ASkyBig/mpx-project](https://github.com/ASkyBig/mpx-project)
![image](https://github.com/didi/mpx/assets/26340566/73c52a51-d27b-4076-966d-1dd0106e935d)
