### ISSUE TITLE
[Bug report] 支付宝小程序调试模式http校验问题

### ISSUE THREAD

**Issue by WynterW** [didi/mpx#1222]
**问题描述**  
1. 问题：每次重新编译后，打开支付宝小程序都要重新选择忽略http校验，测试环境ip地址无法加白名单
2. 问题复现方式：下载底部demo，编译后在支付宝编译器中打开-》选择关联小程序-》刷新-》提示没在白名单内
3. 期望解决方案：模拟器或watch模式，默认忽略http检验或者支持静态文件可配置

**环境信息描述**  
至少包含以下部分：
1. 系统类型：mac
3. Mpx依赖版本：mpxjs/core 2.8.0
4. 小程序开发者工具信息:支付宝平台，支付宝编译器版本3.3.3 ，基础库2.0 

**最简复现demo**  

[mpx-project.zip](https://github.com/didi/mpx/files/11623154/mpx-project.zip)

**Comment by Blackgan3** [comment]
对于项目配置相关，Mpx框架支持用户在项目根目录下创建static文件夹，创建文件夹之后可以根据不同平台放置不同项目配置，如果你是mpxjs/cli生成的项目，可以在你的项目根目录看到这个static文件夹

针对本issue提出的忽略http安全校验配置，我看了下目前微信和支付宝小程序的项目配置中都没有开放这个配置，可能官方还是希望能在开发者环境帮开发者拦掉没加白的域名，因此这个暂时无法通过项目配置来关闭
