### ISSUE TITLE
[Bug report]抖音小程序引入插件页面时，编译异常

### ISSUE THREAD

**Issue by zengtv** [didi/mpx#1225]
简单来说就是，目前在使用mpx开发抖音小程序涉及到交易系统。
而根据tt小程序文档，他们的通过插件方式内置了一些固定的订单相关的页面，使用方式是需要在package.json里定义插件，再在app.js(app.mpx)里通过pages里引入插件内置页面来用

[相关文档：](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/component/industry/trading-system/guide)

然后在如下实践中
![image](https://github.com/didi/mpx/assets/38457386/78b10a9e-52a1-4268-b0ad-f662f9f0487c)
![image](https://github.com/didi/mpx/assets/38457386/3e64cabe-9745-4991-9f61-9d90d15ddaaa)
![image](https://github.com/didi/mpx/assets/38457386/299d14e3-1af4-4a6f-aa1c-56e2c2a01d66)
![image](https://github.com/didi/mpx/assets/38457386/453b4c41-f98d-4dbb-b956-4f299ff6bf6e)

引入的三个页面只能成功编译出一个

希望帮忙看看

**Comment by Blackgan3** [comment]
@mpxjs/webpack-plugin@2.8.33 @mpxjs/core@2.8.33

此问题已修复
