### ISSUE TITLE
mode="date"的picker，bindchange事件的event，小程序会返回target/currentTarget，web没有返回[Bug report]

### ISSUE THREAD

**Issue by chinalihongxiang** [didi/mpx#1226]
![QQ图片20230605185135](https://github.com/didi/mpx/assets/25007284/a70c722f-d335-4173-9ab6-8ab0e409ad72)
![QQ图片20230605185113](https://github.com/didi/mpx/assets/25007284/a86c7535-7645-42ee-8ef9-f828f8ce037f)
![QQ图片20230605185122](https://github.com/didi/mpx/assets/25007284/c099c8c7-17ac-402e-830d-f0c98602cae1)
<picker mode="date" value="{{item.beginDate}}" data-index="{{index}}" bindchange="bindOtherStartChange">
      <view class="picker"></view>
  </picker>

**Comment by hiyuki** [comment]
目前最新版本已修复
