### ISSUE TITLE
web端底部菜单点击失效问题[Bug report]

### ISSUE THREAD

**Issue by chinalihongxiang** [didi/mpx#1227]
已上传demo，按以下操作可复现
1、进入应用，切换至副页，刷新页面（模拟从副页链接进入应用）
2、刷新后，点击底部菜单切换至主页
3、在主页点击进入二级页面
4、进入后什么操作也不做，直接用浏览器的返回
5、此时底部菜单全部失效
[src.zip](https://github.com/didi/mpx/files/11671929/src.zip)

**Comment by Blackgan3** [comment]
@mpxjs/webpack-plugin@2.8.34 版本已经修复

**Comment by chinalihongxiang** [comment]
收到，非常感谢！！




李鸿翔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/mpx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月13日(星期二) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [didi/mpx] web端底部菜单点击失效问题[Bug report] (Issue #1227)





 
@***@***.*** 版本已经修复
