### ISSUE TITLE
[Bug report] textarea's blur event lacks of error report in 2.7.52

### ISSUE THREAD

**Issue by LikeDreamwalker** [didi/mpx#1235]
**问题描述**  
not sure if this issue still exists in the newest version.

```
    <textarea
      class="textarea"
      wx:model="{{text}}"
      bindinput="checkLength"
      bindfocus="activeFocus"
      bindblur="deactiveFocus"
      wx:ref="textarea"
    ></textarea>
```
In upper codes, I try to use textarea component, and I wish to do something when is focused and blurred:
```
    activeFocus() {
      this.isFocus = true
      this.triggerEvent('focus')
      console.log('focus')
    },
    deactiveFocus() {
      this.deactiveFocus = false
      console.log('blur')
      this.triggerEvent('blur')
    },
```
And by my issues, I am trying to edit `deactiveFocus` as a boolean data. This is not correct but MPX didn't throw out any errors or warnings and *block the blur event fired*. I think this might be like MPX is trying to execute the callback function but got an error, so stop executing the later blur event which MPX should bring back to me. In this scene, textarea is blurred but blur event didn't fired, and there is not any more infomation about this, need time to figure out what happend.
And by my tests, in this scene I can still add these functions into `<textarea>` element itself and works fine even I am trying to edit the callback function:
```
  ready() {
    const textarea = this.$refs.textarea._selector
    textarea.addEventListener('focus', this.activeFocus)
    textarea.addEventListener('blur', this.deactiveFocus)
  },
```
So I expect textarea compoent works as below:
· textarea should throw out an error when callback function is illegal, or meet some issues in execution.

**环境信息描述**  
至少包含以下部分：
Mac
```
    "@mpxjs/api-proxy": "2.7.53",
    "@mpxjs/core": "2.7.52",
    "@mpxjs/webpack-plugin": "2.7.55",
```
only tests in web scene

**Comment by yandadaFreedom** [comment]
感谢反馈，我们尝试复现了这个 issue 中提到的问题，经测试，直接将 method 方法重置为其它类型值，在未触发 render 更新的情况下，确实是不会触发报错，但是在触发 render 重新渲染的情况下，控制台会报出 warning。method 与 data 数据监听的方式不一致，目前 Mpx 或 Vue 都不会对 method  进行监听与拦截，所以对于 method 的再次 set 操作，我们无法感知，建议还是纠正下这种写法哈
