### ISSUE TITLE
如何编译所有平台,脚本需要怎么写?

### ISSUE THREAD

**Issue by ynyjyz** [didi/mpx#1237]
[v2.8.33]项目由cli生成,官方文档讲的也使不清不楚,尝试几次都失败,谁能帮忙解答?

**Comment by mater1996** [comment]
需要编译到哪些平台？可以看看目前运行的命令吗？

**Comment by ynyjyz** [comment]
> 需要编译到哪些平台？可以看看目前运行的命令吗？

编译到字节平台,尝试失败后回滚代码了,现在就使cli生成的默认脚本,能发个有效的给我吗?

**Comment by mater1996** [comment]
失败是指？可以看下报错吗

**Comment by ynyjyz** [comment]
![image](https://github.com/didi/mpx/assets/10368659/f75bb620-df40-49d4-b1bd-03fa05158966)
编译结果只有一个undefined

**Comment by mater1996** [comment]
https://github.com/mpx-ecology/mpx-cli/tree/next
新的版本文档在这里 
你需要将build:mp换成build
