### ISSUE TITLE
npm安装第三方组件项目,引用时候无法识别部分es6扩展运算符语法

### ISSUE THREAD

**Issue by flyjin** [didi/mpx#124]
> npm安装第三方组件项目,引用时候无法识别部分es6扩展运算符语法,

以wux-weapp为例:
在index.mpx中引入
`{
 "navigationBarTitleText": "首页,
 "usingComponents": {
    "wux-filterbar": "../components/dist/filterbar"
 }
}`

> 在webpack.base.config.js中配置babel,在谷歌搜的解决办法

`{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/@mpxjs'),
          resolve('node_modules/wux-weapp')
        ],
        options: {
          presets: ['env', 'es2015', 'react', 'stage-3']
        }
      }`

> 编译提示

 ./src/components/dist/checkbox-group/index.js (./node_modules/babel-loader/lib!./src/components/dist/checkbox-group/index.js)
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: E:/vueTest/5/demo-test/src/components/dist/checkbox-group/index.js: Unexpected token (46:42)

  44 |         },
  45 |         emitEvent(item) {
 46 |             this.triggerEvent('change', { ...item, name: this.data.name })
     |                                           ^
  47 |         },
  48 |     },
  49 | })
 @ ./src/components/dist/checkbox-group/index.js (./node_modules/@mpxjs/webpack-plugin/lib/native-loader.js!./src/components/dist/checkbox-group/index.js) 5:0-41 5:0-41

> 拷到src下面引入使用,正常编译无报错

**Comment by sky-admin** [comment]
无法复现，这边安装最新版的wux-weapp直接就是不可用的，因为wux的作者在其helper文件夹里的多个js文件中混用了import和 module.exports。然后我安装了3.0.2版本的wux-weapp，引用filterbar并无问题。
如果方便的话提供一下wux-weapp的版本，或者一个必现的demo。

**Comment by flyjin** [comment]
> 无法复现，这边安装最新版的wux-weapp直接就是不可用的，因为wux的作者在其helper文件夹里的多个js文件中混用了import和 module.exports。然后我安装了3.0.2版本的wux-weapp，引用filterbar并无问题。
> 如果方便的话提供一下wux-weapp的版本，或者一个必现的demo。

他混用了import和 module.exports的这个问题 我手动修改了,然后没报错 引用就提示语法报错

**Comment by sky-admin** [comment]
需要删掉它的babelrc，或者再加一个stage-2，抱歉这么晚才验证这个问题。

**Comment by sky-admin** [comment]
查了下，stage-2里确实包含transform-object-reset-spread，但是env应该也带这个才对，然后发现是我们声明的env版本有点老，`npm i babel-preset-env@latest` 后再跑即可。我马上去更新下脚手架模板。
