### ISSUE TITLE
mpx文件中引入原生组件报错

### ISSUE THREAD

**Issue by ialmost** [didi/mpx#125]
![image](https://user-images.githubusercontent.com/6847189/57818540-e5859180-77b6-11e9-8014-6820d93bb4e9.png)
![image](https://user-images.githubusercontent.com/6847189/57818558-f9c98e80-77b6-11e9-8fc5-64a25e4aaa20.png)

无法引入原生小程序组件

`jsEnginScriptError
Component is not found in path "components/mpx-demo95b0aa24/src/components/test/test" (using by "pages/index");onAppRoute
Error: Component is not found in path "components/mpx-demo95b0aa24/src/components/test/test" (using by "pages/index")`

**Comment by hiyuki** [comment]
给的示例中无法运行的组件是用Page创建的，不符合小程序本身技术规范
