### ISSUE TITLE
sourcemap不对

### ISSUE THREAD

**Issue by jimwmg** [didi/mpx#126]
* node版本 10.9 
* npm版本6.2
* 微信小程序端
执行
npm i -g @mpxjs/cli
npm init mpx-test

修改 build/webpack.base.conf.js
增加
devtool: 'inline-cheap-module-source-map',

以及inline-source-map 等 sourcemap都不对。

**Comment by sky-admin** [comment]
好的我们check一下。
话说非压缩的 npm run build / watch 还好吧，基本能对上自己的代码，不是很需要sourcemap的感觉

**Comment by hiyuki** [comment]
目前最新版本已经完善支持sourcemap，https://github.com/didi/mpx/releases/tag/v2.6.11
