### ISSUE TITLE
当初对 chameleon 期待挺高的，现在不更新烂尾，又出一个没什么特点的跨端框架，kpi 开源何必呢

### ISSUE THREAD

**Issue by hooper-hc** [didi/mpx#1260]
当初对 chameleon 期待挺高的，现在不更新烂尾，又出一个没什么特点和优势的跨端框架，kpi 开源何必呢

**Comment by hiyuki** [comment]
我们的框架在chameleon之前一年就立项开源了，到目前为止已经高频迭代维护了近六年，目前已经覆盖了滴滴集团内部全量小程序业务的开发，并且在年初被评为滴滴首个开源精品项目。

性能体验和包体积优化是我们的核心特点与优势，如果你需要开发大型复杂的小程序且对性能有要求，非常欢迎尝试试用哦~
