### ISSUE TITLE
[Bug report] 使用mpx create创建项目报错

### ISSUE THREAD

**Issue by perchecc** [didi/mpx#1263]
**问题描述**  
1. 问题触发的条件
使用mpx create创建项目,选择使用小程序云开发能力，选择不需要typescript
截图
![image](https://github.com/didi/mpx/assets/17824405/0fb9d7b8-6f07-4b3a-aa56-e18a801e96c4)
2. 实际的表现
初始化后，pnpm run serve报错
![image](https://github.com/didi/mpx/assets/17824405/1d167d26-aec9-469e-bed8-1cc6b16a4007)

**环境信息描述**  
1. Windows系统
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
![image](https://github.com/didi/mpx/assets/17824405/e18aa979-96fa-4be8-9b50-cec2a7704644)

**Comment by mater1996** [comment]
默认模板不符合eslint规则了，这个我们修复下，可以先执行`npm run lint -- --fix`或者手动修复eslint错误。
