### ISSUE TITLE
mpx-keep-alive 组件render()清掉了__mpx_action 导致 tab页跳转到其他page 时EventChannel通信失效

### ISSUE THREAD

**Issue by zhoujinfu** [didi/mpx#1265]
https://github.com/didi/mpx/blob/f1066822d83e958f6266218c51c21b2ebb2ad04b/packages/webpack-plugin/lib/runtime/components/web/mpx-keep-alive.vue#L89

**Comment by hiyuki** [comment]
ok，我们修复一下

**Comment by hiyuki** [comment]
已修复，需要同时升级release中的三个包，https://github.com/didi/mpx/releases/tag/v2.8.44
