### ISSUE TITLE
[Bug report]增强的模板语法，编译后的wxml属性值是单引号包裹

### ISSUE THREAD

**Issue by forzgc** [didi/mpx#1267]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：

1. 问题触发的条件：使用增强的模板语法，例如wx:style wx:class 等
2. 期望的表现：编译出来的wxml中对应属性值用的是双引号包裹
3. 实际的表现：编译出来的wxml中对应属性值用的是单引号包裹

不确定这算不算bug，微信小程序官方是说单双引号都可以，但是属性值使用双引号更规范一些。所以想咨询一下编译后的wxml使用单引号的原因。

提这个issue的背景：我在mpx中使用weapp-tailwindcss遇到一个问题，weapp-tailwindcss会自动将属性值单引号改成双引号，此时如果属性值内部已经有双引号，那么就会造成wxml格式问题，这个问题已经先提了issue给weapp-tailwindcss。

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Windows)
2. Mpx依赖版本(@mpxjs/core 2.8.44、@mpxjs/webpack-plugin 2.8.46、 @mpxjs/api-proxy 2.8.46)
3. 小程序开发者工具信息(小程序平台：微信、开发者工具版本：1.06.2308310、基础库版本：2.32.0）

**最简复现demo**  
无

**Comment by hiyuki** [comment]
由于小程序模版引擎对于转义字符的支持不好，所以mpx在模版编译时如果attrs的value中包含双引号，则外层就用单引号包裹，如果value中本身不含双引号则还是会用双引号包裹，wx:style/wx:class按照此规则生成的attrs使用单引号包裹是符合预期，不属于bug；

另外再我们即将发布的2.9版本中包含了基于unocss的完整的原子类支持，除了支持常规的转义字符处理，还支持分包输出和样式隔离适配等高级能力，如果要用原子类的话欢迎使用哦~
