### ISSUE TITLE
vscode 插件

### ISSUE THREAD

**Issue by MIyulong** [didi/mpx#127]
vscode没有相关的语法提示、希望能提供相应的开发辅助工具

**Comment by sky-admin** [comment]
文档有写哦，https://didi.github.io/mpx/single/what-is-single-file.html#vscode
来源也是社区同学自己摸索的，官方的话后续有精力的话可能会提供吧。

**Comment by linchwei** [comment]
vscode 重度使用者，按照社区的配置体验不是很好，希望提供类似于vetur这样的插件

**Comment by erguotou520** [comment]
目前有一个问题，在script标签中无法使用`npm intellisense`的输入提示

**Comment by zqjimlove** [comment]
> vscode 重度使用者，按照社区的配置体验不是很好，希望提供类似于vetur这样的插件

可以自行修改*.mpx后缀为*.vue 

**build/webpack.conf.js**
```diff
const webpackConf = {
  entry: {
+    app: resolveSrc('app.vue')
-    app: resolveSrc('app.mpx')
  },
  module: {
    rules: [
      {
        test: /\.(js|ts|mpx|vue)$/,
        loader: 'eslint-loader',
        enforce: 'pre',
        include: [resolve('src')],
        options: {
          formatter: require('eslint-friendly-formatter')
        }
      },
      {
        test: /\.ts$/,
        use: ['babel-loader', 'ts-loader']
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/@mpxjs')
        ],
        exclude: [resolve('node_modules/@mpxjs/webpack-plugin')]
      },
      {
        test: /\.json$/,
        resourceQuery: /__component/,
        type: 'javascript/auto'
      },
      {
        test: /\.(wxs|qs|sjs|filter\.js)$/,
        loader: MpxWebpackPlugin.wxsPreLoader(),
        enforce: 'pre'
      },
      {
        test: /\.(png|jpe?g|gif|svg)$/,
        loader: MpxWebpackPlugin.urlLoader({
          name: 'img/[name][hash].[ext]'
        })
      }
    ]
  },
  performance: {
    hints: false
  },
  mode: 'none',
  resolve: {
    alias: {
      '@': resolveSrc()
    },
-    extensions: ['.mpx', '.js', '.wxml', '.ts'],
+    extensions: ['.vue', '.js', '.wxml', '.ts'],
    modules: ['node_modules']
  },
  devtool: 'inline-cheap-module-source-map'
};
```
**build/build.js**
```diff
const transModuleRules = [
  {
-    test: /\.(mpx)$/,
+    test: /\.(vue)$/,
    use: MpxWebpackPlugin.loader(mpxLoaderConfig)
  }
];
```

**Comment by erguotou520** [comment]
@zqjimlove 这样无法使用小程序相关api的提示，比如输入`wx.`然后出各种api的提示

**Comment by zqjimlove** [comment]
@erguotou520 
wxml 的提示可以使用 minapp 插件，template 中 lang 设置成 wxml。

至于JS的代码的智能提示，我创建了一个新的项目是完全支持的。前提是需要 `import '@mpxjs/core'`，因为 mpxjs 里面引用了 wx 的定义文件。

![image](https://user-images.githubusercontent.com/3240259/79203439-a00d9080-7e6d-11ea-8572-6161339734eb.png)

![image](https://user-images.githubusercontent.com/3240259/79203564-cc291180-7e6d-11ea-9c48-5c8d1338ad90.png)

**如果你不想以这种方式引入智能提示，可以通过reference引入指定的定义文件**

`/// <reference path="../../node_modules/vue/types/index.d.ts" />`

![image](https://user-images.githubusercontent.com/3240259/79206074-650d5c00-7e71-11ea-9e14-772c1358767c.png)

## 觉得麻烦可以用typings

跟目录创建 typings 目录，创建文件`index.d.ts`。内容如下：
```javascript
import '@mpxjs/core'
```
![image](https://user-images.githubusercontent.com/3240259/79209173-a273e880-7e75-11ea-9526-6423e1ece2fe.png)

所有多余的代码都没有了。

**Comment by erguotou520** [comment]
新项目可以试试，之前还没试过改后缀这种方案

**Comment by pagnkelly** [comment]
vscode-mpx插件已上线，大部分功能同vetur，[插件地址](https://marketplace.visualstudio.com/items?itemName=pagnkelly.mpx)

**Comment by pagnkelly** [comment]
插件的相关问题可到vscode-mpx项目提相关issue [git地址](https://github.com/pagnkelly/vscode-mpx)
