### ISSUE TITLE
[Bug report] 数据变化无法更新页面的问题

### ISSUE THREAD

**Issue by dev-2099** [didi/mpx#1291]
**问题描述**  
数据变化无法更新页面

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Windows10，node：18.18.0 lts)
2. Mpx依赖版本(见demo)
3. 小程序开发者工具信息(开发者工具版本：最新稳定版、基础库版本：2.20.2）

**最简复现demo**  ：[mpx-demo.zip](https://github.com/didi/mpx/files/12924918/mpx-demo.zip)

**页面1**（老的写法，以前项目遗留）：

问题1、进入页面1，依次点击“测试1”，“测试2”，“测试3”，三个按钮，页面数值跟随改变。此时退出页面后，再次进入该页面，test4的值并不是初始值0，而是上次的3。

问题2、点击开发工具上的“编译”按钮以便全新开始。依次点击““测试2”，测试1”，“测试3”，三个按钮，开发者工具报错后，页面数值跟随改变。此时退出页面后，再次进入该页面，detail不是初始的空对象，而是{"test1":2}， test4的值并不是初始值0，而是上次的3。

**页面2**（新功能一般是这种写法）：

问题1、进入页面2，依次点击“测试1”，“测试2”，“测试3”，三个按钮，test2的值无法页面上动态改变。

问题2、在问题1基础上，再依次点击“测试3”，“测试2”，“测试1”，三个按钮，test2的值可以动态变化了，why？

**问题总结**：页面1是重新进入页面后，data中部分数据无法再次初始化；页面2是如何动态更新数组中的对象属性。
**期待解决**：两个页面都能动态更新数据，页面1重新进入能正确初始化data中的数据。

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.8.52，已修复
