### ISSUE TITLE
[Bug report]跨端转百度小程序执行报错Page not found

### ISSUE THREAD

**Issue by zhangcai93** [didi/mpx#1294]
**问题描述**  
初始化一个项目: mpx init xxx
安装依赖完毕后, pages/index.mpx文件中使用setup选项, 导入开发者工具, 运行时报错

**环境信息描述**  
至少包含以下部分：
1. 系统类型: Mac
2 . Mpx依赖版本:  "@mpxjs/core": "^2.8.51", "@mpxjs/webpack-plugin": "^2.8.51", "@mpxjs/api-proxy": "^2.8.0",
3. 小程序开发者工具信息: 百度小程序

**最简复现demo**  
<img width="765" alt="3ab8d6d3f30490a2a282e42c6d3b5c5f" src="https://github.com/didi/mpx/assets/23694441/8658971a-0a6c-4ea4-a6fe-6680b64b45a1">

[mpx-project2_副本.zip](https://github.com/didi/mpx/files/12976691/mpx-project2_.zip)

问题2: 
若开启forceUsePageCtor: true; 报错同https://github.com/didi/mpx/issues/1284

**Comment by hiyuki** [comment]
可以先手动在页面json中添加一个component:true规避问题，框架后续修复版本中也会根据构造选项自动添加

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.8.53
问题1,2均已修复
