### ISSUE TITLE
事件名带有连字符-的情况下，无法使用mpx的事件处理内联传参的增强机制

### ISSUE THREAD

**Issue by rcocco** [didi/mpx#1314]
Mpx模板中的
```html
<van-field bind:click-icon="scan(4)"/>
```
在编译后不会变化，不会像其他事件一样被编译为`__invoke`。

**Comment by hiyuki** [comment]
这是因为事件名带-时按照现有规则编译为data-event-config时不符合小程序模版引擎解析规则，小程序模版引擎中不允许对象的key值用引号包裹，但是这种带-的事件名作为key时必须要用引号包裹，编译的时候会报出相关的warning

**Comment by hiyuki** [comment]
最新版本中通过对-字符转义进行了支持，可以更新使用：
https://github.com/didi/mpx/releases/tag/v2.8.60
