### ISSUE TITLE
过滤白名单判断与文档不一致

### ISSUE THREAD

**Issue by funme** [didi/mpx#132]
https://github.com/didi/mpx/blob/5d4054c71018198c4d786db1986fd7b342e082ea/packages/api-proxy/src/promisify.js#L43

如 'showToast' 在白名单中,map[showToast] = true,经过 !!map[showToast] 任然为true, 文档中描述位 whiteList 不需要转化 promise 格式的 api,
[文档](https://github.com/didi/mpx/tree/master/packages/api-proxy)

另外
```
  const whiteListMap = getMapFromList(whiteList)
  const blackListMap = getMapFromList(blackList)
```

这两个map计算提到外层是否更好

如需PR...

**Comment by httpsxiao** [comment]
已采纳，感谢支持，欢迎下次直接 PR
