### ISSUE TITLE
[Bug report]微信小程序provide/inject使用无效

### ISSUE THREAD

**Issue by sky-chy** [didi/mpx#1329]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 微信小程序provide/inject使用无效

**环境信息描述**  
至少包含以下部分：
1. Windows
2. @mpxjs/core@2.3.4、@mpxjs/webpack-plugin@2.3.4、@mpxjs/api-proxy@2.3.4
3. 小程序平台：微信开发者工具、开发者工具版本：1.06.230720、基础库版本：3.1.1

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. provide/inject该如何写才能实现父子孙甚至更深层次组件的传参

**Comment by hiyuki** [comment]
由于小程序环境限制，目前Mpx不支持provide/inject特性，如需跨组件数据通信可以使用全局状态管理@mpxjs/pinia(pinia style)或者@mpxjs/store(vuex style)
