### ISSUE TITLE
和 chameleon 项目什么关系?

### ISSUE THREAD

**Issue by kid1412621** [didi/mpx#133]
毕竟, 现在"号称"支持多端的框架太多了

**Comment by hiyuki** [comment]
没有直接关系，从设计理念来说Mpx更加专注小程序开发本身，2.0的跨平台也指的是跨小程序平台

**Comment by kid1412621** [comment]
看不支持 h5 ，后续会考虑吗？

**Comment by kid1412621** [comment]
btw 要是出了 vue 项目迁移指南就好了

**Comment by hiyuki** [comment]
H5的话短期内还没有规划，后续会考虑支持将已有的mpx项目转换到web平台上运行，但是不太可能直接支持vue或者react的DSL

**Comment by justindeng0405** [comment]
现在小程序跨端轮子太多了，时不时就出一个，不看好。（逃）

**Comment by kid1412621** [comment]
比「能用」的小程序平台还多

**Comment by AibiTi** [comment]
滴滴真是无聊，纯属搞 KPI 的居多，造完一套又一套，每次都吹得一逼的厉害，我敢赌 100 包辣条，这个项目活不过 3 个月。

附上 chameleon 的图，BUG 多得一批，谁用谁坑爹，README 上到是吹的很厉害。

![image](https://user-images.githubusercontent.com/40224479/59166828-38592b80-8b60-11e9-8b03-631085018131.png)

**Comment by beatles-chameleon** [comment]
> 滴滴真是无聊，纯属搞 KPI 的居多，造完一套又一套，每次都吹得一逼的厉害，我敢赌 100 包辣条，这个项目活不过 3 个月。
> 
> 附上 chameleon 的图，BUG 多得一批，谁用谁坑爹，README 上到是吹的很厉害。
> 
> ![image](https://user-images.githubusercontent.com/40224479/59166828-38592b80-8b60-11e9-8b03-631085018131.png)

现在还处于 beta 版本，请问有什么具体 bug？
