### ISSUE TITLE
[Feature Request] 是否支持入口文件是app.xxx呢

### ISSUE THREAD

**Issue by Anonlyy** [didi/mpx#1330]
**问题描述**  
MPX的默认入口文件是 `app.mpx`, 想说支持入口文件为[app.json, app.js, app,wxss]，那么在迁移时，就无须对app.xxx的几个文件的代码手动迁移到app.mpx文件里.

**Comment by hiyuki** [comment]
可以考虑支持

**Comment by Anonlyy** [comment]
非常感谢大佬支持，看了下代码已经实现了，如果方便的话，希望能尽快合入主版本
