### ISSUE TITLE
[Bug report] npm run serve 报错Error: Build error

### ISSUE THREAD

**Issue by wanggongcun** [didi/mpx#1334]
按照文档用最新脚手架新建项目
npm i -g @mpxjs/cli
mpx create mpx-project
cd mpx-project
npm run serve

报错Error: Build error

环境
@mpx/cli: 3.4.0
nodejs： v16.18.0

**Comment by mater1996** [comment]
辛苦提供下mpx info

**Comment by wanggongcun** [comment]
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
    Edge: Not Found
    Safari: 14.1.2
  npmPackages:
    @intlify/vue-devtools:  9.7.0 
    @mpxjs/api-proxy: ^2.9.0 => 2.9.0 
    @mpxjs/babel-plugin-inject-page-events: ^2.9.0 => 2.9.0 
    @mpxjs/cli-shared-utils:  2.1.1 
    @mpxjs/core: ^2.9.0 => 2.9.0 
    @mpxjs/eslint-config:  1.0.10 
    @mpxjs/eslint-config-ts: ^1.0.5 => 1.0.10 
    @mpxjs/fetch: ^2.9.0 => 2.9.0 
    @mpxjs/mpx-cli-service: ^2.0.0 => 2.1.1 
    @mpxjs/pinia: ^2.9.0 => 2.9.0 
    @mpxjs/size-report: ^2.9.0 => 2.9.0 
    @mpxjs/store: ^2.9.0 => 2.9.0 
    @mpxjs/utils: ^2.9.0 => 2.9.0 
    @mpxjs/vue-cli-plugin-mpx: ^2.0.0 => 2.1.1 
    @mpxjs/vue-cli-plugin-mpx-eslint: ^2.0.0 => 2.1.1 
    @mpxjs/vue-cli-plugin-mpx-typescript: ^2.0.0 => 2.1.1 
    @mpxjs/webpack-plugin: ^2.9.0 => 2.9.0 
    @vue/cli-overlay:  5.0.8 
    @vue/cli-plugin-router:  5.0.8 
    @vue/cli-plugin-vuex:  5.0.8 
    @vue/cli-service: ~5.0.0 => 5.0.8 
    @vue/cli-shared-utils:  5.0.8 
    @vue/compiler-sfc:  2.7.15 
    @vue/component-compiler-utils:  3.3.0 
    @vue/devtools-api:  6.5.1 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-mpx:  0.2.17 
    mpx-eslint-parser:  0.0.9 
    typescript: ^4.1.3 => 4.9.5 
    vue: ^2.7.0 => 2.7.15 
    vue-demi: ^0.13.11 => 0.13.11 (0.14.6)
    vue-eslint-parser:  7.11.0 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.27.2 => 8.28.2 
    vue-i18n-bridge: ^9.2.2 => 9.7.0 
    vue-loader:  17.3.1 (15.11.1)
    vue-router: ^3.1.3 => 3.6.5 
    vue-style-loader:  4.1.3 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @mpxjs/cli: 3.4.0
    @vue/cli: 4.5.6

npm run serve

> mpx-project@0.1.0 serve
> mpx-cli-service serve

 ERROR  Error: Build error
Error: Build error
    at /Users/mpx-project/node_modules/@mpxjs/vue-cli-plugin-mpx/utils/webpack.js:28:33
    at FancyReporter._renderStates (/Users/mpx-project/node_modules/@mpxjs/vue-cli-plugin-mpx/utils/reporter.js:215:13)
    at /Users/mpx-project/node_modules/@mpxjs/vue-cli-plugin-mpx/utils/webpack.js:17:19
    at new Promise (<anonymous>)
    at handleWebpackDone (/Users/mpx-project/node_modules/@mpxjs/vue-cli-plugin-mpx/utils/webpack.js:5:10)
    at /Users/mpx-project/node_modules/@mpxjs/vue-cli-plugin-mpx/commands/serve/mp.js:14:7
    at processQueueWorker (/Users/mpx-project/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by mater1996** [comment]
没有复现，辛苦建一个复现repo，发一下链接。

**Comment by mater1996** [comment]
修改`srcMode`为`dd`后需要执行`yarn build --targets=dd`
