### ISSUE TITLE
[Bug report] serve web ts报错

### ISSUE THREAD

**Issue by forzgc** [didi/mpx#1337]
**问题描述**  
使用 mpx-cli-service serve --targets=web 会出现下面几种ts错误，--targets=wx没有这个问题

TS2307: Cannot find module
TS2614: Module '"aaa"' has no exported member 'bbb'
TS7016: Could not find a declaration file for module

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Windows)
2. Mpx依赖版本
```
    "@mpxjs/api-proxy": "^2.9.1",
    "@mpxjs/core": "^2.9.1",
    "@mpxjs/fetch": "^2.9.1",
    "@mpxjs/pinia": "^2.9.1",
    "@mpxjs/store": "^2.9.1",
    "@mpxjs/utils": "^2.9.1",
```

**最简复现demo**  
[mpx-project.zip](https://github.com/didi/mpx/files/13455443/mpx-project.zip)

执行 yarn serve:web，如果没有出现错误，那么选择一个serve监听到的文件比如 src/pages/index ，按ctrl+s保存两次以上，就会出现错误

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.6 已修复
