### ISSUE TITLE
[Bug report] 2.9.x版本 eslint 报错导致 serve 跑不起来

### ISSUE THREAD

**Issue by forzgc** [didi/mpx#1338]
**问题描述**  
eslint 检查mpx文件代码抛出的错误会导致 serve 运行不起来，并且这个错误输出会被覆盖掉导致看不到错误

![图片](https://github.com/didi/mpx/assets/43092118/d77ca8a1-c379-4a84-bde6-9c704a62dee9)

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Windows)
2. Mpx依赖版本
```
    "@mpxjs/api-proxy": "^2.9.1",
    "@mpxjs/core": "^2.9.1",
    "@mpxjs/fetch": "^2.9.1",
    "@mpxjs/pinia": "^2.9.1",
    "@mpxjs/store": "^2.9.1",
    "@mpxjs/utils": "^2.9.1",
```

**最简复现demo**  
[mpx-project.zip](https://github.com/didi/mpx/files/13455938/mpx-project.zip)

app.mpx 中创建了一个未使用的变量，eslint会提示错误
```
const aaa = 1
```

**Comment by mater1996** [comment]
已修复，升级@mpxjs/vue-cli-plugin-mpx 到 v2.1.2 解决该问题
