### ISSUE TITLE
[Bug report] `onLoad`, `onShow` and so on hooks not found in node_modules/@mpxjs/core/src/index.js

### ISSUE THREAD

**Issue by LikeDreamwalker** [didi/mpx#1340]
**问题描述**  
在MPX 2.9.1引用上述钩子时会有ESLint报错`not found`
`import mpx, { createPage, ref, computed, onLoad, onShow } from '@mpxjs/core'`
该问题可通过关闭ESLint解决，不影响实际使用
![image](https://github.com/didi/mpx/assets/45194556/2ca84f1e-6ecc-4691-915f-70f306a96563)
   

**环境信息描述**  
Mac OS
`
    "@mpxjs/api-proxy": "2.9.1",
    "@mpxjs/babel-plugin-inject-page-events": "2.9.1",
    "@mpxjs/core": "2.9.1",
    "@mpxjs/fetch": "2.9.1",
    "@mpxjs/pinia": "2.9.1",
    "@mpxjs/size-report": "2.9.1",
    "@mpxjs/store": "2.9.1",
    "@mpxjs/utils": "2.9.1",
    "@mpxjs/webpack-plugin": "2.9.1"
`
Node.js v18.18.0
npm@9.8.1

**最简复现demo**  
`import { onLoad, onShow } from '@mpxjs/core'`

**Comment by Blackgan3** [comment]
mpx-cli 创建的demo项目没有复现，请上传一个可复现的demo

**Comment by LikeDreamwalker** [comment]
感谢回复
