### ISSUE TITLE
[Bug report] 最新的core类型声明为什么删除了对PropType类型的支持？

### ISSUE THREAD

**Issue by forzgc** [didi/mpx#1342]
**问题描述**  
![图片](https://github.com/didi/mpx/assets/43092118/204a3aca-9288-4228-bbf6-56dfc9e9f943)

这里删除PropType类型会导致使用 as PropType<xxx>报错

**Comment by hiyuki** [comment]
之前的修改会导致Properties不满足微信内部的类型约束，需要做处理规避掉该问题后才能开启该能力
![image](https://github.com/didi/mpx/assets/6810697/46215c83-dae9-4b2d-9b9a-32596b5d4d7d)
