### ISSUE TITLE
能直接将微信原生的小程序转成 QQ 小程序么？有相关文档么？

### ISSUE THREAD

**Issue by neo-yuanyanjun** [didi/mpx#136]

**Comment by hiyuki** [comment]
可以的，对于原生的小程序项目，你需要创建一个app.mpx把原先的app.js/app.json/app.wxss包含进来，作为项目entry。webpack plugin的配置传递srcMode=wx，mode=qq，编译构建即可，更多详细信息可以[点击查看](https://didi.github.io/mpx/platform.html#%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BC%96%E8%AF%91)
