### ISSUE TITLE
[Bug report] 使用setData更新数据时，某些场景会报错：TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by vivine** [didi/mpx#1364]
**问题描述**  

使用setData更新数据时，某些场景会报错：TypeError: Cannot read property 'length' of null

如下图：

![image](https://github.com/didi/mpx/assets/1614610/674a14d3-5f76-4d4b-9c83-13dc7345905d)

具体代码关联为：

https://github.com/didi/mpx/blob/7ec6526f024c00f9c6b935c631bfdc61be27b69b/packages/core/src/observer/scheduler.js#L96-L116

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.10，已修复
