### ISSUE TITLE
web平台 onReachBottom 事件报错

### ISSUE THREAD

**Issue by MrBaoquan** [didi/mpx#1375]
**问题描述**  
web平台下onReachBottom事件报错

**环境信息描述**  
1. 系统类型 Windows
2. 脚手架版本 @mpx/cli 3.4.0

**最简复现demo**  
1. 使用脚手架创建模板
2. index页面添加onReachBottom事件
3. 建立一个view高度超出页面
4. 运行serve --targets=web
5. 滚动至页面底部即报错
![image](https://github.com/didi/mpx/assets/36908656/3fff95b7-5bf5-4ffb-affb-7ad6aa6171ae)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.13 
已修复
