### ISSUE TITLE
跨平台编译

### ISSUE THREAD

**Issue by cxh1991** [didi/mpx#138]
new MpxWebpackPlugin({
          mode:  'tt',
          srcMode: 'wx'
        })
修改了这个 重新编译 没有编译成头条小程序的语法 也无法在头条小程序开发工具打开 请问我配置的有问题吗？

**Comment by sky-admin** [comment]
方便给一个demo吗？或者可以看看这个例子 https://github.com/didi/mpx/blob/master/examples/mpx-webview/ 对照一下区别，这个是微信、支付宝、百度、头条都可以跑的

**Comment by cxh1991** [comment]
我完全是按照官方的脚手架生成的build.js 我换成https://github.com/didi/mpx/blob/master/examples/mpx-webview/ 这个build.js才可以跑起来 楼主可以试试

**Comment by cxh1991** [comment]
我完全是按照官方的脚手架生成的build.js 我换成https://github.com/didi/mpx/blob/master/examples/mpx-webview/ 这个build.js才可以跑起来 大佬可以试试😁

**Comment by cxh1991** [comment]
两个build.js我对比了  逻辑写的有区别

**Comment by sky-admin** [comment]
可以发下你的build.js内容吗？mpx-webview的build.js也是脚手架生成的。

**Comment by cxh1991** [comment]
var ora = require('ora')
var rm = require('rimraf')
var path = require('path')
var chalk = require('chalk')
var webpack = require('webpack')
var merge = require('webpack-merge')
var program = require('commander')
const MpxWebpackPlugin = require('@mpxjs/webpack-plugin')
var webpackMainConfig = require('./webpack.main.conf')
var webpackWxConfig = require('./webpack.wx.conf')

var webpackConfigArr = []
let isPluginProject = false
const userSelectedMode = 'wx'

function resolveDist (file, pathStr = '../dist') {
  return path.resolve(__dirname, pathStr, file || '')
}

const supportedCrossMode = ['wx', 'ali', 'swan', 'qq', 'tt']
const npmConfigArgvOriginal = (process.env.npm_config_argv && JSON.parse(process.env.npm_config_argv).original) || []
const modeArr = npmConfigArgvOriginal.filter(item => typeof item === 'string').map(item => item.replace('--', '')).filter(item => supportedCrossMode.includes(item))

if (modeArr.length === 0) {
  if (isPluginProject) {
    webpackConfigArr.push(merge(userSelectedMode === 'wx' ? webpackWxConfig : webpackMainConfig, {
      plugins: [
        new MpxWebpackPlugin({mode: userSelectedMode})
      ]
    }))
  } else {
    webpackConfigArr.push(merge(userSelectedMode === 'wx' ? webpackWxConfig : webpackMainConfig, {
      output: {
        path: resolveDist('', '../dist/')
      },
      plugins: [
        new MpxWebpackPlugin({mode: userSelectedMode})
      ]
    }))
  }
} else {
  modeArr.forEach(item => {
    const webpackCrossConfig = merge(item === 'wx' ? webpackWxConfig : webpackMainConfig, {
      name: item + '-compiler',
      output: {
        path: resolveDist('', '../dist/' + item)
      },
      plugins: [
        new MpxWebpackPlugin({
          mode: item,
          srcMode: 'wx'
        })
      ]
    })
    webpackConfigArr.push(webpackCrossConfig)
  })
}

var prodEnv = require('../config/prod.env')
var devEnv = require('../config/dev.env')

program
  .option('-w, --watch', 'watch mode')
  .option('-p, --production', 'production release')
  .parse(process.argv)

function runWebpack (cfg) {
  // env
  if (Array.isArray(cfg)) {
    cfg.forEach(item => item.plugins.unshift(new webpack.DefinePlugin(program.production ? prodEnv : devEnv)))
  } else {
    cfg.plugins.unshift(new webpack.DefinePlugin(program.production ? prodEnv : devEnv))
  }

  if (program.production || program.watch) {
    const extendCfg = program.production ? { mode: 'production' } : { cache: true }
    if (Array.isArray(cfg)) {
      cfg = cfg.map(item => merge(item, extendCfg))
    } else {
      cfg = merge(cfg, extendCfg)
    }
  }
  if (process.env.npm_config_report) {
    var BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin
    var mainCfg = Array.isArray(cfg) ? cfg[0] : cfg
    mainCfg.plugins.push(new BundleAnalyzerPlugin())
  }
  if (program.watch) {
    webpack(cfg).watch({}, callback)
  } else {
    webpack(cfg, callback)
  }
}

function callback (err, stats) {
  spinner.stop()
  if (err) return console.error(err)
  if (Array.isArray(stats.stats)) {
    stats.stats.forEach(item => {
      console.log(item.compilation.name + '打包结果：')
      process.stdout.write(item.toString({
        colors: true,
        modules: false,
        children: false,
        chunks: false,
        chunkModules: false,
        entrypoints: false
      }) + '\n\n')
    })
  } else {
    process.stdout.write(stats.toString({
      colors: true,
      modules: false,
      children: false,
      chunks: false,
      chunkModules: false,
      entrypoints: false
    }) + '\n\n')
  }

  console.log(chalk.cyan('  Build complete.\n'))
  if (program.watch) {
    console.log(chalk.cyan('  Watching...\n'))
  }
}

var spinner = ora('building...')
spinner.start()

try {
  rm.sync(path.resolve(__dirname, '../dist/{*,.*}'))
} catch (e) {
  console.error(e)
  console.log('\n\n删除dist文件夹遇到了一些问题，如果遇到问题请手工删除dist重来\n\n')
}
if (webpackConfigArr.length === 1) {
  runWebpack(webpackConfigArr[0])
} else {
  runWebpack(webpackConfigArr)
}

**Comment by cxh1991** [comment]
然后我把上面的mode: item 换成 mode: ‘tt’ 就不行了

**Comment by sky-admin** [comment]
是这样的，下面那个item（第50行）是针对同时跨多平台的，这个是不能直接改的。如果你是想只针对某个平台转，可以简单地执行`npm run watch --tt`。

**Comment by cxh1991** [comment]
好的 谢谢
下面的官网文档说的：
使用方法
为了使用上述跨平台编译特性，你只需要进行简单的配置修改，打开项目的webpack配置，找到@mpxjs/webpack-plugin的声明位置，传入mode和srcMode参数即可，示例如下

// 下面的示例配置能够将mpx微信小程序源码编译为支付宝小程序
new MpxWebpackPlugin({
  // mode为mpx编译的目标平台，可选值有(wx|ali|swan|qq|tt)
  mode: 'ali',
  // srcMode为mpx编译的源码平台，目前仅支持wx   
  srcMode: 'wx' 
})

也没有这个npm run watch --tt这个得说明哈

**Comment by sky-admin** [comment]
如果你希望更好地自己来掌控这个部分，可以把41行起的else删掉（或注释掉），24行起的if里，25行起的if是插件模式的，31行起的else是最基础的，你应该只保留调整31行起的else里的逻辑，将其加入srcMode为wx，mode为tt即可。

**Comment by sky-admin** [comment]
好的，文档中这个部分我们会改进，因为build脚本可能还会再调整优化一番，我们会在确定build脚本后更新文档，感谢反馈支持。

**Comment by cxh1991** [comment]
好了 收到 感谢👍
