### ISSUE TITLE
转 web 时 `scss` 通过 additionalData  引入的全局变量 px 不会被转化为 vw 或 rem

### ISSUE THREAD

**Issue by soulmate126** [didi/mpx#1382]
转web时通过 `css.loaderOptions.scss.additionalData`引入全局变量
```javascript
// vue.config.js
module.exports = defineConfig({
  css: {
      // sourceMap: true,
      loaderOptions: {
          scss: {
            additionalData: '@import "@/styles/var.scss";'
          }
      }
    }
})
```
```scss
// styles/var.scss
$--fs-xs: 14px;
```

```html
<!-- ./src/pages/index.mpx -->
<style lang="scss">
.list{
  font-size: $--fs-xs;
}
</style>
```
输出
![image](https://github.com/didi/mpx/assets/20768176/8adb9646-ef4e-425a-98e4-7fefe405881a)

应改转化为对应的 `vw`单位

[mpx-project-2.9 2.zip](https://github.com/didi/mpx/files/13975152/mpx-project-2.9.2.zip)

**Comment by yandadaFreedom** [comment]
px 转成 vw  需要给 @mpxjs/webpack-plugin 插件配置 transRpxRules 转换规则，具体配置可参考 https://mpxjs.cn/api/compile.html#transrpxrules
