### ISSUE TITLE
wx 转 web 时 externalClasses 不生效

### ISSUE THREAD

**Issue by soulmate126** [didi/mpx#1384]
**问题描述**  
wx 转 web 时 externalClasses 配置不生效

![image](https://github.com/didi/mpx/assets/20768176/d0555d0f-acbe-4c91-b8df-23c05584e171)

输出
![image](https://github.com/didi/mpx/assets/20768176/f3737737-7346-4928-8bf7-e9308215c56b)

**环境信息描述**  
最新版本脚手架创建的项目

**最简复现demo**  
https://github.com/soulmate126/mpx-demo/tree/custom-class

**Comment by hiyuki** [comment]
需要添加一个编译配置 externalClasses 来辅助我们进行跨平台转换，详情查看：https://mpxjs.cn/api/compile.html#externalclasses

**Comment by soulmate126** [comment]
@hiyuki 
![image](https://github.com/didi/mpx/assets/20768176/aef758db-704b-4277-b92c-baf7f81d043e)
添加 externalClasses 配置依然不能生效
![image](https://github.com/didi/mpx/assets/20768176/b2f09bc6-7c26-4142-ac4f-da284cf0c099)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.16
已修复，感谢反馈
