### ISSUE TITLE
[Bug report] 转 web时通过 js 引用图片时生成的 原子类代码会有乱码

### ISSUE THREAD

**Issue by soulmate126** [didi/mpx#1391]
**问题描述**  
在 js 中引用静态资源 ` import IMG_1 from '@/assets/img/img-1.png`
生成的 css 中会有 乱码
![image](https://github.com/didi/mpx/assets/20768176/10c365a4-9442-4b06-b0d2-f5ceea64eace)
去掉图片引用就没有

**最简复现demo**  

https://github.com/soulmate126/mpx-demo/tree/task-import-img

**Comment by mater1996** [comment]
运行的命令式哪个？

**Comment by Blackgan3** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.17
最新版本已修复
