### ISSUE TITLE
父组件slot子组件 默认会产生一层，但是产生的这一层不会自动撑满父组件

### ISSUE THREAD

**Issue by ethanbing** [didi/mpx#140]
父组件slot子组件 默认会产生一层，但是产生的这一层不会自动撑满父组件
因此造成  子组件写width:50%  百分比时，无法根据父组件布局

**Comment by hiyuki** [comment]
微信的自定义组件是基于shadow dom实现，在组件上直接写的width:50%这种非继承样式并不会在组件内部的root上直接生效，如果需要传递style可以考虑通过props把style传递给子组件，子组件接收到之后再将其应用到子组件模板的root上。

**Comment by ethanbing** [comment]
你说的解决方案   好像没太理解我说的  你看了demo就理解了   我不是在组件上直接写width50%
而是  直接在子组件里写width:50%  也不能布局，好像是根据自身计算的，没有根据父组件计算
因此 传递style也是无效  没用的

**Comment by ethanbing** [comment]
最终问题是  slot之后的子组件  width:50%  不会根据父组件的宽度计算，而是根据自身的宽度计算

**Comment by hiyuki** [comment]
嗯，确实是我理解有误，不过你的这个case也是由于shadow dom的标准造成的，可以直接在自定义组件的标签上写width:50%来处理

**Comment by sky-admin** [comment]
经群聊沟通，此表现为小程序原生表现，有布局需求可参考第三方UI库里布局组件的实现，用float解决
