### ISSUE TITLE
XXI centaury

### ISSUE THREAD

**Issue by cojack** [didi/mpx#141]
Hi dude,
What's the reason that you publish a package with Chinese language docs? I know that there a 1/4 ppl on earth are Chinese, but not programmers.

This trend from Chinese developers is growing, and your packages are useless for rest of the world. I'm writing this not to complain you about your code, but to improve your work, English first and we will live in much more useful packages world.

Thanks in advance.

**Comment by hiyuki** [comment]
Hi @cojack 
Thank you for your suggestion. Our project mpx is a development framework for miniprogram, which is a Chinese specific technical standard proposed by Chinese companies such as Tencent and Alibaba. This means, our target users are almost Chinese developers for now. This is why we document our project in Chinese only. If the miniprogram technical standard could be widely used worldwide in the future, and our project may serve developers in rest of the world, we will supplement the full English docs as soon as possible.
