### ISSUE TITLE
组件内import，真机报错

### ISSUE THREAD

**Issue by heiye9** [didi/mpx#142]
系统版本：MIUI10，Android8.0
微信版本：7.0.4
mpx版本：
![image](https://user-images.githubusercontent.com/24930493/59025040-d493e180-8885-11e9-8d77-19447faaf302.png)
我写了一个组件，其中需要引用`api/Sports`获取数据。使用require().default一切正常，但当我使用import时，工具调试正常，真机调试报错:
![image](https://user-images.githubusercontent.com/24930493/59024161-e3799480-8883-11e9-80d0-31695fbd95e4.png)
## sportNotice.mpx
```js
<script>
  import { createComponent } from '@mpxjs/core'
  import Sports from '../api/sports'

  createComponent({
    properties: {},
    data: {
      isSelected: false,
      list: [],
      show: false
    },
    async created () {
      console.log('Sports:', Sports)
    },
    pageLifetimes: {
      async show () {
        // 获取选课列表
        // const Sports = require('../api/sports').default
        const res = await Sports.getList()
        if (res.error_code !== 0) {
          return
        }
        // 是否已经预约课程
        this.isSelected = res.data.findIndex(({ isselect }) => isselect * 1 === 1) !== -1
        if (this.isSelected) {
          // 如果选了课程，获取预约历史，筛选出已预约但没有上课的课程
          const history = await Sports.getHistory()
          this.list = history.data.filter(({ attend }) => attend === '已预约').reverse()
        }
        this.show = true
      }
    },
    methods: {
      navigateToSports () {
        wx.navigateTo({ url: '/pages/sport/index?history=true' })
      }
    },
    options: {
      addGlobalClass: true
    }
  })
</script>
```

## Sports.js
```js
import Base from './base'

export default class Sports extends Base {
  static async getList () {
    const res = await this.get({ url: '/v1/sports' })
    return res
  }

  static async getHistory () {
    const res = await this.get({ url: `/v1/sports/history` })
    return res
  }

  static async submit (id) {
    const res = await this.post({ url: `/v1/sports/${id}` })
    return res.data
  }
}
```
## Base.js
```js
import Http from './http'

export default class Base {
  static get = Http.get.bind(Http)
  static put = Http.put.bind(Http)
  static post = Http.post.bind(Http)
  static delete = Http.delete.bind(Http)
}

```

## Http.js

![image](https://user-images.githubusercontent.com/24930493/59024504-a235b480-8884-11e9-9480-d2228a8234e7.png)

**Comment by heiye9** [comment]
后来我尝试减少import层级，将Sports.js改成直接调用Http：
![image](https://user-images.githubusercontent.com/24930493/59024880-75ce6800-8885-11e9-8b53-c6c33ac391ff.png)
**报错变为：**
![image](https://user-images.githubusercontent.com/24930493/59024813-4e779b00-8885-11e9-8808-ac0bf7d564cc.png)

**Comment by heiye9** [comment]
我发现如果把`require('../api/sports').default`提到createComponent()之外的话，也是会报错的！
只有在组件创建后动态require才不会报错。

**Comment by heiye9** [comment]
小弟才学疏浅，虽然解决了问题，但是希望得到解答。谢谢:blush:

**Comment by hiyuki** [comment]
目测是因为你的项目中存在循环依赖，不过从你贴出来的部分看不出完整的依赖关系，可以把完整的复现demo发上来看一下

**Comment by heiye9** [comment]
> 目测是因为你的项目中存在循环依赖，不过从你贴出来的部分看不出完整的依赖关系，可以把完整的复现演示发上来看一下

https://github.com/heiye9/wtbuer-bug-demo.git
取消`components/sportsNotice.mpx`中第57行注释后，真机预览即可复现。
要先打开调试，不然会卡在微信三个小白点的页面一直loading进不去，也看不到报错。

**Comment by sky-admin** [comment]
确实是循环依赖，问题主要出现在http.js 和 store/index.js，api/daily.js -> api/http.js -> store/index.js -> api/course.js -> http.js，解开这个循环的关键在http.js里，它对store的依赖是可以后置的，所以应该把http.js 里第三行
import 'store' from '../store'删掉，在拦截器的方法里写const store = require('../store')

**Comment by heiye9** [comment]
大概懂了，谢谢解答😄
