### ISSUE TITLE
<input> does not support [confirm-type] property in bytedance environment![Bug report]

### ISSUE THREAD

**Issue by luoxianchao** [didi/mpx#1436]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件 wx编译目标小程序是头条 设置input的confirm-type=“search”
2. 期望的表现 可以顺利通过编译，解除警告
3. 实际的表现 出现如标题所示的错误警告

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows) windows
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看) 2.9.0
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.29 
已修复
