### ISSUE TITLE
构建出的ali 的 bundle.js 的getRootMixin方法语法错误

### ISSUE THREAD

**Issue by lonelyWalkor** [didi/mpx#145]
使用npm run prod:cross
运行时构建ali失败，报错

_ERROR in bundle.js from Terser
Unexpected token: operator (!==) [bundle.js:6863,34]_

后来使用npm run build:cross
命令构建出未压缩的js
检查ali下的bundle.js 发现getRootMixin方法语法错误，导致压缩报错

function getRootMixin (mixin) {

  const supportBehavior = typeof  !== 'undefined'

 // 对比其他平台的生成的此方法 此处应该为
// const supportBehavior = typeof Behavior !== 'undefined'

  if (supportBehavior) {
    return {
      // eslint-disable-next-line no-undef
      behaviors: [(mixin)]
    }
  } else {
    return mixin
  }
}

**Comment by sky-admin** [comment]
刚刚试了一下没有问题，是一个全新的项目吗？操作系统和mpx的core/webpack-plugin版本号方便提供一下吗？如果不是一个全新项目，方便提供一下demo吗？

**Comment by lonelyWalkor** [comment]
是一个全新的项目，刚刚使用cli生成出来的，
操作系统 win7
"@mpxjs/core": "^2.0.8"
"@mpxjs/webpack-plugin": "^2.0.9",

**Comment by lonelyWalkor** [comment]
将"@mpxjs/webpack-plugin": "^2.0.9",
升级到2.0.10，问题解决
