### ISSUE TITLE
[Bug report] wxml 存在 <template is="xxx" /> 引用模板的时候，template 里边的事件没法编译，使用不了proxyEventHandler

### ISSUE THREAD

**Issue by vivine** [didi/mpx#1465]
**问题描述**  

wxml 如果存在 <template is="xxx" /> 引用模板的时候，template 里边的事件没法编译，无法使用 proxyEventHandler。

导致在 proxyEventHandler 里做的一些埋点不起作用。

比如：

```html
<template name="xxx">
  <view bindtap="clickMe">点击一下</view>
</template>

<template is="xxx" />
```

**期望编译结果**

```html
<view bindtap="__invoke" data-eventconfigs='{{ {tap:[["clickMe"]]} }}'>点击一下</view>
```

**实际编译结果**

```html
<view bindtap="clickMe">点击一下</view>
```

**另外，使用 import 或者 include 引入模板的时候估计也会有这个问题，希望一起修复一下**

template 文档：https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/template.html

import/include 文档：https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/import.html

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.33
已支持

**Comment by hiyuki** [comment]
该增强特性开启后会影响原生组件的使用（https://github.com/didi/mpx/issues/1565），因为template本身可以被.mpx组件引用也可以被原生组件引用， 故回退到之前的逻辑，template内不再支持mpx模版增强特性，如需使用增强特性请在.mpx的根级模版中使用

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.54
该能力已回滚。

**Comment by vivine** [comment]
> https://github.com/didi/mpx/releases/tag/v2.9.54 该能力已回滚。

已知晓，后续如果确实有需要，我们可以按照期望编译后的结果，手动给 template 里边的内容加上 `bindtap="__invoke" data-eventconfigs='{{ {tap:[["clickMe"]]} }}'`。

这样应该可以的吧，之前这么解决过。
