### ISSUE TITLE
请问有能让astro或mdx支持适配mpx的集成包吗

### ISSUE THREAD

**Issue by Zeij** [didi/mpx#1466]
或者有别的思路吗,先用webpack打包mpx成vue,但是astro 基于 Vite 构建,webpack的plugin可能不被支持

**Comment by hiyuki** [comment]
没有研究过，不过理论上应该可以，目前可以支持将.mpx组件独立构建为.js格式的vue组件（为了避免底层冗余可能需要配置一系列externals），如果vite/astro支持二次构建该文件就可以，以及mpx目前的构建目标是vue2.7而不是vue3

**Comment by Zeij** [comment]
> 没有研究过，不过理论上应该可以，目前可以支持将.mpx组件独立构建为.js格式的vue组件（为了避免底层冗余可能需要配置一系列externals），如果vite/astro支持二次构建该文件就可以，以及mpx目前的构建目标是vue2.7而不是vue3

大佬请问有webpack打包构建mpx的最小子集配置吗,没有基于cli创建项目,打包出来的js产物放到vue中使用遇到了各种问题😭
