### ISSUE TITLE
使用平台微信转头条小程序，mpx.getStorageSync is not a function

### ISSUE THREAD

**Issue by iceinkbamboo** [didi/mpx#148]
mpx.getStorageSync is not a function
转化的头条小程序报这个错，是本身不支持吗？

**Comment by sky-admin** [comment]
是否use了api-proxy?
https://github.com/didi/mpx/tree/master/packages/api-proxy

**Comment by iceinkbamboo** [comment]
是我的问题，没有全局引用api-proxy

**Comment by sky-admin** [comment]
我们更新下模板，对于选择了需要跨平台构建的我们默认在app.mpx里引入并use api-proxy吧。
