### ISSUE TITLE
[Feature Request] 支持 Skyline app-bar（全局工具栏）

### ISSUE THREAD

**Issue by ItsRyanWu** [didi/mpx#1488]
app-bar 是 Skyline 推出的 WebView 版本小程序中 custom-tab-bar 的全新替代

参考: https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/appbar.html

启用该功能需要将 app bar 文件夹放置在 dist 根目录，经过测试发现 MPX 不支持将具有自定义名称的文件夹生成至 dist 根目录，希望可以像支持 custom-tab-bar 一样支持 app-bar

![image](https://github.com/didi/mpx/assets/17338101/745de919-5534-48dd-9940-8c00b34896b6)
![image](https://github.com/didi/mpx/assets/17338101/9d465511-873f-46fd-a479-de752677643c)
![image](https://github.com/didi/mpx/assets/17338101/c003855b-07e9-40a9-8b95-8add4bbb8429)

**Comment by ItsRyanWu** [comment]
在官方更新支持 app bar 之前，可以在 vue.config.js 里通过声明 custom output 实现 app bar
在这个例子中，我将 tabbar.mpx 组件放在 components 文件夹中，然后输出到根目录并改名为微信官方要求的 'app-bar'
```javascript
          customOutputPath: (type, name, hash, ext) => {
          // type: 资源类型(page | component | static)
          // name: 资源原有文件名
          // hash: 8位长度的hash串
          // ext: 文件后缀(.js｜ .wxml | .json 等)
          if (name === 'tabbar') {
            return path.join('app-bar', 'index' + ext)
          } else if (type === 'wxs') {
            return path.join('wxs', name + hash + ext)
          } else {
            return path.join(type + 's', name + hash, 'index' + ext)
          }
        },
```

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.42 
已经支持
