### ISSUE TITLE
[Bug report] 接入火山埋点SDK后报错

### ISSUE THREAD

**Issue by linking2014** [didi/mpx#1492]
**问题描述**  
使用Mpx框架，接入火山埋点后，运行报错，提示 Module not found: Error: Recursion in resolving
1. 问题触发的条件：安装火山埋点SDK，import 之后，运行 npm run serve
2. 期望的表现：可以正常接入火山埋点SDK
3. 实际的表现：提示 Module not found: Error: Recursion in resolving

**环境信息描述**  
至少包含以下部分：
1. 系统类型：Mac
2. Mpx依赖版本：2.7.56、2.8.39、2.9.33 都有复现
3. 小程序开发者工具信息：小程序平台：微信；开发者工具版本：1.06.2404301；基础库版本：2.33.0、3.3.2
4. 火山埋点微信小程序SDK集成文档 https://www.volcengine.com/docs/6285/65981

**最简复现demo**  
[mpx-huoshan.zip](https://github.com/didi/mpx/files/15470400/mpx-huoshan.zip)

![47141716894899_ pic](https://github.com/didi/mpx/assets/8596179/3a3f5e31-80f4-4e85-bec1-6b38db24a1e8)

![47161716894992_ pic](https://github.com/didi/mpx/assets/8596179/e3cb00a6-4710-4383-8c9e-c1d2d7548648)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.34
已修复
