### ISSUE TITLE
[Bug report]@mpxjs/size-report 插件启动可视化平台显示异常

### ISSUE THREAD

**Issue by fu188-dev** [didi/mpx#1498]
**问题描述**  
为什么我使用 @mpxjs/size-report 插件查看包体积分析，当启动可视化平台显示这个呢？
![image](https://github.com/didi/mpx/assets/68093183/dda92c1f-5c94-4a69-9a58-b65f69c0bdf0)
项目已经编译完成，控制台没有报错：
![image](https://github.com/didi/mpx/assets/68093183/bfa40956-8a12-43ff-819e-c0df9c93eb02)

**环境信息描述**  
至少包含以下部分：
1. 系统类型：Windows
2. Mpx依赖版本(@mpxjs/core：2.9.0、@mpxjs/webpack-plugin：2.9.0、@mpxjs/api-proxy：2.9.0)

**最简复现demo**  
vue.config.js配置如下：
![image](https://github.com/didi/mpx/assets/68093183/479ad041-2e6d-4a24-ba07-710314bbabf0)

**Comment by Blackgan3** [comment]
更新@mpxjs/size-report@2.9.41，已修复
