### ISSUE TITLE
怎么在正常流程中使用node_modules中的第三方组件呢

### ISSUE THREAD

**Issue by nan1010082085** [didi/mpx#15]
比如说 vant-weapp

我vant-weapp安装后 要把dist拿出来用？
还是有更方便的方法 直接引入？

**Comment by sky-admin** [comment]
接下来的升级就会提供解决方案，非常舒服，还可以按需加载，稍等就好。

**Comment by hiyuki** [comment]
目前对应功能已经开发完成，待测试完善后会在本周内发布~

**Comment by sky-admin** [comment]
https://didi.github.io/mpx/native-component.html
已经发布了，可以尝试了，明天会出个example。
