### ISSUE TITLE
setComponentRef 方法在支付宝的分包异步化下读缓存是否存在问题？

### ISSUE THREAD

**Issue by lp0124** [didi/mpx#1503]
我看支付宝也默认开启了分包异步化 这里的条件判断是否要加上支付宝端呢

![WechatIMG1](https://github.com/didi/mpx/assets/22974194/8502faff-9585-4dbb-9b91-26d44d3e7a6f)

**Comment by hiyuki** [comment]
确实存在相似问题，已处理
https://github.com/didi/mpx/releases/tag/v2.9.36
