### ISSUE TITLE
vant-weapp 在支付宝小程序内引用组件多显示出""

### ISSUE THREAD

**Issue by bugkill** [didi/mpx#152]
![image](https://user-images.githubusercontent.com/3804601/59753297-681dd700-92b6-11e9-9c5a-d3f1f2b21ad1.png)
![image](https://user-images.githubusercontent.com/3804601/59753329-7966e380-92b6-11e9-92ca-544c41fe7e00.png)

vant-weapp 在支付宝小程序内引用组件多显示出""

**Comment by hiyuki** [comment]
这个具体是哪个组件？

**Comment by 3cfood** [comment]
> 这个具体是哪个组件？

icon 哦

**Comment by sky-admin** [comment]
问题是由于core在微信转支付宝时候对props做转换时未处理好null类型导致的。
2.0.17版本已修复，请升级@mpxjs/core和@mpxjs/webpack-plugin到2.0.17版本。感谢反馈。
