### ISSUE TITLE
是否支持 自动生成页面分包 json 和 统一生成页面路径 .js 或 .ts 

### ISSUE THREAD

**Issue by Rainer-Yu** [didi/mpx#1536]
请问是否支持 自动生成页面分包 json 和 统一生成页面路径 .js 或 .ts 
每次添加页面都要手动添加 页面json 信息 页面跳转使用的路径字符串也不利于维护

**Comment by Blackgan3** [comment]
是希望通过命令行的方式新建分包/页面吗？

“页面跳转使用的路径字符串也不利于维护”，这个可以使用Mpx 的 ?resolve 功能来解决：
https://mpxjs.cn/api/compile.html#resolve

**Comment by Rainer-Yu** [comment]
> 是希望通过命令行的方式新建分包/页面吗？
> 
> “页面跳转使用的路径字符串也不利于维护”，这个可以使用Mpx 的 ?resolve 功能来解决： https://mpxjs.cn/api/compile.html#resolve

我们项目里是把页面的一些信息写在页面 json 内,
```json
{
  "pageName": "XXX",
  "usingComponents": {
    "share-popup": "/components/share-popup/index"
  },
  "navigationStyle": "custom",
  "enablePullDownRefresh": true,
  "backgroundTextStyle": "dark"
}
```
开发运行或 build 时会根据此信息将所有页面路径统一生成一个 pages.ts , app.json 内关于页面以及分包的部分也是统一自动生成

跳转
``` js
import pages from '@/pages'

mpx.navigateTo({
  url: pages.XXX
})
```

所以想问问有没有对应的方式

**Comment by hiyuki** [comment]
意思是扫描特定文件目录下的文件自动生成app.json和页面信息的ts？
Mpx目前没有类似的支持，不过这个你们可以通过一个预编译的来进行同样的实现吧

**Comment by Rainer-Yu** [comment]
> 意思是扫描特定文件目录下的文件自动生成app.json和页面信息的ts？ Mpx目前没有类似的支持，不过这个你们可以通过一个预编译的来进行同样的实现吧

是的, 只是问一下有没有已集成的方案, 感谢回答
