### ISSUE TITLE
[Bug report]是否支持getOpenerEventChannel

### ISSUE THREAD

**Issue by keke599** [didi/mpx#1540]
A页面
wx.navigateTo({
  url: 'b?id=1',
  success: function(res) {
    res.eventChannel.emit('acceptDataFromOpenerPage', { data: 'test' })
  }
})
B页面 
  import { createPage,  onLoad,  getOpenerEventChannel } from "@mpxjs/core";
  onLoad((option) => {
       const eventChannel = getOpenerEventChannel();
 });
这里导入getOpenerEventChannel报错log.js:35 TypeError: Cannot read property 'getOpenerEventChannel' of undefined

**Comment by Blackgan3** [comment]
getOpenerEventChannel 是页面实例方法，尝试下使用 this.getOpenerEventChannel

**Comment by keke599** [comment]
> getOpenerEventChannel 是页面实例方法，尝试下使用 this.getOpenerEventChannel

使用setup语法糖的话这个需要导入

**Comment by Blackgan3** [comment]
先使用 getCurrentInstance 吧，目前context上没透出这个方法。大概如下：

```js
import { getCurrentInstance } from "@mpxjs/core"

const { proxy } = getCurrentInstance()
proxy.getOpenerEventChannel()
```

**Comment by keke599** [comment]
> 先使用 getCurrentInstance 吧，目前context上没透出这个方法。大概如下：
> 
> ```js
> import { getCurrentInstance } from "@mpxjs/core"
> 
> const { proxy } = getCurrentInstance()
> proxy.getOpenerEventChannel()
> ```

👌
