### ISSUE TITLE
MpxWebpackPlugin.loader 全局转换px为rpx失效

### ISSUE THREAD

**Issue by zengtv** [didi/mpx#155]
版本
"@mpxjs/webpack-plugin": "^2.0.0",
代码片段
// webpack.config.js
`{
        test: /\.mpx$/,
        use: MpxWebpackPlugin.loader({
          transRpx: {
            mode: 'all',
            comment: 'use px',
            designWidth: 750,
            include: resolve('src')
          }
        })
      },`
// index.mpx
`<style lang="less">
  .abc {
    /* use px */
    width: 200px;
    height: 20px;
    font-size: 40px;
  }
</style>`
预期表现
    width: 200rpx;
    height: 20rpx;
    font-size: 40rpx;
实际表现
![image](https://user-images.githubusercontent.com/38457386/59910899-6b939880-9445-11e9-96e6-3540d25d72e4.png)

ps: mode:'only'时有效

**Comment by sky-admin** [comment]
按你的配置及样式代码试了下，没有问题啊。
![image](https://user-images.githubusercontent.com/6292668/59913136-2cb41180-944a-11e9-8dbb-4bf6406ddb46.png)

如果方便的话可以给个demo吗？自建一个仓库传上去或者发我邮箱。

**Comment by sky-admin** [comment]
以及你写的预期表现有一点点不对，我给的图里的才是对的，第一个200px由于注释应该不转换，是打错了吗还是文档没看清？

**Comment by zengtv** [comment]
你好，刚刚试了一下还是不行。代码打包成附件了，
预期里的宽度多写了一个‘r’
________________________________
zengtv@outlook.com

发件人： Huanyu Li<mailto:notifications@github.com>
发送时间： 2019-06-21 17:31
收件人： didi/mpx<mailto:mpx@noreply.github.com>
抄送： Zeng TianWei<mailto:zengtv@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [didi/mpx] MpxWebpackPlugin.loader 全局转换px为rpx失效 (#155)

以及你写的预期表现有一点点不对，我给的图里的才是对的，第一个200px由于注释应该不转换，是打错了吗还是文档没看清？

**Comment by sky-admin** [comment]
没有看到附件哦

**Comment by zengtv** [comment]
在邮箱里

发自我的 iPhone

在 2019年6月21日，17:49，Huanyu Li <notifications@github.com<mailto:notifications@github.com>> 写道：


没有看到附件哦

**Comment by sky-admin** [comment]
邮箱里也没有，你这样回复发出的文件附件应该不行

**Comment by zengtv** [comment]
度盘吧
链接: https://pan.baidu.com/s/18zp9GPh14pxbDe9fxK9RVg 提取码: 13vw 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by sky-admin** [comment]
收到了，我用`npm ci`安装依赖保证和你的依赖一致，然后尝试发现并没有问题？请确认问题是否存在？

使用only模式加一条注释，结果第一条转换，第二三条不转换。
![image](https://user-images.githubusercontent.com/6292668/59988716-b6442900-966e-11e9-8ef0-90131a2904e3.png)

使用all模式不加注释，全部转换。
![image](https://user-images.githubusercontent.com/6292668/59988778-ea1f4e80-966e-11e9-8d85-e5041ba91545.png)

**Comment by zengtv** [comment]
见鬼了，录了个gif..
[cid:_Foxmail.1@514b8e29-f236-c522-2fd9-f2b32a03c750]
________________________________
zengtv@outlook.com

发件人： Huanyu Li<mailto:notifications@github.com>
发送时间： 2019-06-24 10:58
收件人： didi/mpx<mailto:mpx@noreply.github.com>
抄送： Zeng TianWei<mailto:zengtv@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [didi/mpx] MpxWebpackPlugin.loader 全局转换px为rpx失效 (#155)

收到了，我用npm ci安装依赖保证和你的依赖一致，然后尝试发现并没有问题？请确认问题是否存在？

使用only模式加一条注释，结果第一条转换，第二三条不转换。
[image]<https://user-images.githubusercontent.com/6292668/59988716-b6442900-966e-11e9-8ef0-90131a2904e3.png>

使用all模式不加注释，全部转换。
[image]<https://user-images.githubusercontent.com/6292668/59988778-ea1f4e80-966e-11e9-8d85-e5041ba91545.png>

**Comment by sky-admin** [comment]
用邮箱回复的gif图这边看不到哦

**Comment by sky-admin** [comment]
要不QQ / 微信沟通？

**Comment by zengtv** [comment]
方便的话qq？这个问题的确有点尴尬啊，在我这边始终无法转换成功

________________________________
zengtv@outlook.com

发件人： Huanyu Li<mailto:notifications@github.com>
发送时间： 2019-06-24 13:28
收件人： didi/mpx<mailto:mpx@noreply.github.com>
抄送： Zeng TianWei<mailto:zengtv@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [didi/mpx] MpxWebpackPlugin.loader 全局转换px为rpx失效 (#155)

要不QQ / 微信沟通？

**Comment by sky-admin** [comment]
QQ群里艾特下群主即可，QQ群的入群二维码在readme及文档首页的最下方都有

**Comment by kyuuube** [comment]
两年后，我也遇到了

**Comment by lupingW** [comment]
现在我也遇到了

**Comment by hiyuki** [comment]
> 现在我也遇到了

相关配置已迁移，详情查看：https://www.mpxjs.cn/api/compile.html#transrpxrules
