### ISSUE TITLE
[Bug report] wx:class 不兼容多个 class name

### ISSUE THREAD

**Issue by ItsRyanWu** [didi/mpx#1550]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
![image](https://github.com/user-attachments/assets/511fac7f-9ad9-4437-8825-5386736c08e4)

2. 期望的表现
兼容多个 class name，这对于用 atomic CSS 的应用场景十分有帮助

3. 实际的表现
![image](https://github.com/user-attachments/assets/f956e180-16ef-400e-b67e-b17f015cbaa9)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.9.43
已经支持，在原子类场景下，由于模版中的对象key值为了避免微信模版编译报错需要进行转义，动态class中使用的原子类无法在编译时被自动检测收集，需要结合safelist使用，实例如下：
![image](https://github.com/user-attachments/assets/246fb384-2681-4d80-9b3f-c47905a6476b)
