### ISSUE TITLE
[Bug report]初始化微信小程序插件项目后，yarn serve报错

### ISSUE THREAD

**Issue by ursazoo** [didi/mpx#1558]
**问题描述**  

初始化时的选项
<img width="740" alt="image" src="https://github.com/user-attachments/assets/783c3c16-f7c3-4461-92e9-381d11593c93">

报错信息
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/da93e093-728b-4b79-8f41-445b073be827">
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/e6549b30-b41c-449a-88aa-d0427a660052">

**环境信息描述**  
至少包含以下部分：
1. 系统类型：
<img width="228" alt="image" src="https://github.com/user-attachments/assets/0a7d16bd-c04e-43a9-a1bb-d5213424dc21">

<img width="391" alt="image" src="https://github.com/user-attachments/assets/a83c0ba9-645a-4165-8b10-7d1e41b12f14">

2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
<img width="763" alt="image" src="https://github.com/user-attachments/assets/ffa29cd8-759c-487b-b0bc-81c4622923c2">

**最简复现demo**  
仓库地址：https://github.com/ursazoo/mpx-demo

**Comment by ursazoo** [comment]
选择不使用ts，可以正常启动项目

**Comment by mater1996** [comment]
修复：https://github.com/mpx-ecology/mpx-cli/pull/92
