### ISSUE TITLE
function 加上 async 后代码发生错误也不会抛出

### ISSUE THREAD

**Issue by hejinzhi** [didi/mpx#156]
如图，toPureObject 没有被引入，理应抛出错误。但在onShow 前面加上了 async，错误就消失了，但代码没有继续执行下去。去掉 async 会抛出错误。
![image](https://user-images.githubusercontent.com/18588816/59972395-d1f0f600-95c0-11e9-8db2-030fda54beb0.png)

**Comment by sky-admin** [comment]
问题应该是由于babel转换出的promise在reject中notify里的onUnhandled方法会检查global上的console对象是否存在，由于小程序的特殊性这个检查失败了导致错误未能被打印。我们今天会fix这个问题。

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.0.15 已修复，感谢反馈
