### ISSUE TITLE
同样是didi出品的chameleon和mpx具体什么区别？该如何选择？

### ISSUE THREAD

**Issue by jiji262** [didi/mpx#157]
看到chameleon项目负责人的言论：

https://github.com/didi/chameleon/issues/224
```

这很早就已经开源了，一开始是微信小程序增强框架。2.0继续使用微信DSL语法转成其他小程序语法，”转译原则在于，能转则转，转不了则报错提示“；api等也做了能抹平则抹平不能抹平则报错；这也是一种设计模式。目前mpx不支持web H5和native，希望继续努力。对 Chameleon 来说无论内部和外部的有重合点的开源产品体现了这个方向的勃勃生机，同行各自努力。
--
```

**Comment by sky-admin** [comment]
MPX是小程序框架，追求在小程序范围（或者说类小程序范围）内做到**极致开发体验与执行性能**。因为更专注于小程序，所以**对小程序特有的一些特性支持的比较好，例如小程序组件、wxs等**。也**能够直接使用业内的一些小程序组件库，例如vant、iView**。代码上是基于小程序自身的标准进行增强，可直接使用现有原生小程序项目渐进式迁移。
Chameleon是跨端框架，追求更广泛的端适配，特点是能够一套代码产出多个小程序、Native端等。为了尽可能的适配多端，所以是自定义了另一套DSL，有一定的学习与迁移成本，且因为需要适配多端所以需要面临的问题也会更多一些，但好处是不仅适用于小程序，也可以同时产出Native及H5等
算是两个框架各有侧重，如果主要研发小程序，建议MPX，性能与开发体验一定更好；如果有跨端需求，例如产出Native端，则可以选用Chameleon，可以节省不同端的开发量。
都是滴滴团队非常优秀的框架，可以根据实际需求选用~
