### ISSUE TITLE
[Bug report] mpx每次build，开发者工具报错：在项目根目录未找到 app.json

### ISSUE THREAD

**Issue by linking2014** [didi/mpx#1588]
**问题描述**  

1. 问题触发的条件
	- 按官网流程创建 mpx 项目
	- 运行 `npm run serve`，并在小程序开发者工具中打开项目（dist/wx 文件夹）
	- 中止上面的服务，运行 `npm run build`，此时小程序开发者工具会报错：[app.json 文件内容错误] app.json: 在项目根目录未找到 app.json (env: macOS,mp,1.06.2407110; lib: 3.4.7)。
	- 此时必须关闭当前项目并重新打开，小程序开发者工具才可以正常预览、使用
2. 期望的表现
	- 运行 `npm run build` 后可以重新加载 build 后的代码，小程序开发者工具才可以正常使用不报错
3. 实际的表现
<img width="420" alt="image" src="https://github.com/user-attachments/assets/d7ad8920-3d2a-4725-b3d8-2a7230a13a7a">
<img width="420" alt="image" src="https://github.com/user-attachments/assets/8c09570a-b0ac-436d-94f5-e27ba1a18121">

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
	- Mac  
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
	- @mpxjs/core 2.9.58
	- @mpxjs/webpack-plugin 2.9.58
	- @mpxjs/api-proxy 2.9.58
4. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
	- 小程序平台 微信小程序
	- 开发者工具版本 1.06.2407110
	- 基础库版本 3.4.7

**最简复现demo**  
[mpx-project.zip](https://github.com/user-attachments/files/16780853/mpx-project.zip)

**Comment by shulaoda** [comment]
这似乎是因为终止 serve 服务后 build 打包失败导致的：
<img width="808" alt="image" src="https://github.com/user-attachments/assets/788ead5f-5957-4857-93ca-d269a74c66ab">

**Comment by linking2014** [comment]
> 我控制台也报了这个错误，但是似乎可以正常展示。 这个问题我以前在开发 Taro 小程序的时候也遇到过，你其实可以通过刷新重新编译即可，无需关闭当前项目并重新打开。 <img alt="image" width="435" src="https://private-user-images.githubusercontent.com/165626830/362298931-40309a37-6c15-4215-91dd-b1be46deda61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTQwMTMsIm5iZiI6MTcyNDg1MzcxMywicGF0aCI6Ii8xNjU2MjY4MzAvMzYyMjk4OTMxLTQwMzA5YTM3LTZjMTUtNDIxNS05MWRkLWIxYmU0NmRlZGE2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxNDAxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NmY0ODJjMTg0YjUxMjcxNWNkODUwOWRiNjA1ZmI4MmEyN2NmM2VkY2RjYTVmZGE1YzA2NjM1NTY1MTQ0NWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yy59wY2-9TIgnMkq7rkwfgWDJ-mEHR-beNk7djo9NDA">

不行的，mpx这种情况下只能关闭项目，然后重新打开，群里很多人都这样

**Comment by mater1996** [comment]
这个问题一开始考虑的是构建产物如果不清除，会保留历史构建产物，但是目前看起来会导致开发者工具在默认打开项目的情况下报错，现都调整为不清除产物，可以更新以下版本。
https://github.com/mpx-ecology/mpx-cli/releases/tag/v2.1.16
如果有需要，可以添加 --clean参数来自动清除产物。
