### ISSUE TITLE
[Bug report]通过refs获取的 组件实例top怎么获取

### ISSUE THREAD

**Issue by keke599** [didi/mpx#1613]
类似小程序中的 
const query = wx.createSelectorQuery()
query.select('#the-id').boundingClientRect(function(res){
  res.top // #the-id 节点的上边界坐标（相对于显示区域）
})
query.selectViewport().scrollOffset(function(res){
  res.scrollTop // 显示区域的竖直滚动位置
})
query.exec()

**Comment by kimi233** [comment]
你现在的代码就已经可以在mpx中正常工作了
推荐通过 mpx.createSelectorQuery() 或者 this.createSelectorQuery()获取 SelectorQuery 对象
mpx.createSelectorQuery() 在微信小程序最终会被编译为 wx.createSelectorQuery()。所以使用方式和原生微信小程序的使用方式完全一致

**Comment by kimi233** [comment]
<view wx:ref="box"></view>

this.$refs.box.boundingClientRect(function(res){
  // ...
})
