### ISSUE TITLE
运行examples\mpx-todoMVC报错  Cannot find module 'cssnano'

### ISSUE THREAD

**Issue by hm496** [didi/mpx#163]
![1561948374](https://user-images.githubusercontent.com/17252784/60407044-9de28a00-9beb-11e9-9a8d-cb577bfac748.png)
如图运行
npm i
npm run watch
报错 Error loading PostCSS config: Cannot find module 'cssnano';

**Comment by sky-admin** [comment]
fixed，这个是因为0.x版本的css-loader被报告有一个安全问题，于是被我们升级到了2.x版本，然而这个升级有一些breaking change，比如2.x版本的它没有了cssnano。目前我们暂时临时降回了0.x版本，后续会用postcss来替换。
