### ISSUE TITLE
[Bug report]项目引入form-data 包后报错

### ISSUE THREAD

**Issue by saperliu** [didi/mpx#1637]
**问题描述**  
1、增加 “form-data” 包后，运行报错：form_data__WEBPACK_IMPORTED_MODULE_0___default(...) is not a constructor

**环境信息描述**  
1、创建项目后，在package.json 中增加依赖 "form-data": "4.0.0"

**最简复现demo**  
1、创建项目后，在package.json 中增加依赖 "form-data": "4.0.0"
2、安装依赖，运行。
3、使用微信小程序打开项目编译的项目。运行就报错。
![image](https://github.com/user-attachments/assets/32d2c583-94e6-4ae5-93c3-4d2f856b9989)
![image](https://github.com/user-attachments/assets/2c4c7a14-53cd-44db-b759-491c19da121a)
![image](https://github.com/user-attachments/assets/25ef7333-de10-456d-8b84-7b0325328cdd)

**Comment by Blackgan3** [comment]
form-data 这个包是commonjs，需要使用require

不过小程序环境也不支持formData，这里如果上传文件的话，可以直接试试wx.uploadFile?

**Comment by saperliu** [comment]
@Blackgan3  感谢, 最后使用的wx.uploadFile. 这是一个H5和小程序同时考虑的项目.
