### ISSUE TITLE
不太明白 <component is="{{componentName}}"></component>为什么报错

### ISSUE THREAD

**Issue by briquet0605** [didi/mpx#164]
Expected‘<component>’elements to have 'v-bind:is'attribute.eslint-plugin-vue
我新手小白，照着教程复制然后有这个错误提示。

**Comment by sky-admin** [comment]
报的什么错呢？

**Comment by sky-admin** [comment]
这是个lint错误吧？应该可以无视掉，是VS code编辑器+vue插件报的吗？不影响代码实际运行对吧？

**Comment by briquet0605** [comment]
![微信截图_20190701133531](https://user-images.githubusercontent.com/31877557/60412814-3c2f1980-9c05-11e9-98db-b1e1bdbeed1e.png)
但是在微信开发者工具中有这个报错

**Comment by sky-admin** [comment]
可以确认下json部分是否有错误？没错误的话方便提供一份demo吗？

**Comment by briquet0605** [comment]
还是没明白问题出在哪里，麻烦帮忙看一下吧
链接：https://pan.baidu.com/s/1h0coj8cpjDUGmnEo_KHxdw 
提取码：smju

**Comment by sky-admin** [comment]
已收到（ps: 下次发可以删掉node_modules文件夹，体积会非常小，百度网盘速度实在太慢了）
问题有很多，首先你应该看命令行里提示的错误，就是编译错误，这是优先于运行时错误的，有编译错误大概率运行会有错误。

首先是无法找到index页面，app.mpx里声明的页面为什么要多加一层index？
然后是index页面里，组件的路径也有问题，应该是一层为什么写两层../？
我猜你是之前开发过原生小程序？原生小程序之所以喜欢多一层文件夹来包裹是因为它一个页面/组件由4个文件组成，不用一个同名文件夹来包裹很容易混在一起，mpx没有这个问题就消减了一层，降低开发人员路径负担。

然后是components里并没有mixin，也没有testA组件和testB组件。

**Comment by briquet0605** [comment]
谢谢啦，我知道怎么回事了

**Comment by sky-admin** [comment]
[mpx.zip](https://github.com/didi/mpx/files/3344404/mpx.zip)
