### ISSUE TITLE
[Bug report]只输出了wx平台的小程序

### ISSUE THREAD

**Issue by UchihaYuki** [didi/mpx#1640]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
以下是我运行`wpx create project-name`时的选项。
![image](https://github.com/user-attachments/assets/4b98770e-5d86-41e6-8930-4b8b12c72642)
3. 期望的表现
package.json
···json
  "scripts": {
    "serve": "mpx-cli-service serve",
    "build": "mpx-cli-service build",
    "build:cross": "???",
    "lint": "eslint --ext .js,.ts,.mpx src/"
  },
···
4. 实际的表现
package.json
···json
  "scripts": {
    "serve": "mpx-cli-service serve",
    "build": "mpx-cli-service build",
    "lint": "eslint --ext .js,.ts,.mpx src/"
  },
···

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)Windows
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
```
@mpxjs/core@2.9.62
@mpxjs/size-report@2.9.41
@mpxjs/api-proxy@2.9.62
```
**根据[文档](https://mpxjs.cn/guide/basic/start.html#%E5%BC%80%E5%A7%8Bcode)最后一行，package.json里面应该有个`build:cross`指令，用来生成所有平台的小程序，但是没有。如果执行`npm build`也只生成`wx`。**

**Comment by mater1996** [comment]
https://github.com/mpx-ecology/mpx-cli
辛苦查看cli文档，这里应该替换为 npm run build -- --targets=wx,ali...
