### ISSUE TITLE
import fetch 编译报错

### ISSUE THREAD

**Issue by zhupaizhang** [didi/mpx#169]
`  import mpx from '@mpxjs/core'
  import mpxFetch from '@mpxjs/fetch'`

`ERROR in ./src/pages/index.mpx (./node_modules/babel-loader/lib!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=script&index=0!./src/pages/index.mpx)
Module not found: Error: Can't resolve '@mpxjs/fetch' in 'D:\wwwroot\cwenti\mpx\chaoyue\src\pages'
 @ ./src/pages/index.mpx (./node_modules/babel-loader/lib!./node_modules/@mpxjs/webpack-plugin/lib/selector.js?type=script&index=0!./src/pages/index.mpx) 8:0-36 9:8-16
 @ ./src/pages/index.mpx`

以第二种方式
` this.$xfetch.fetch({url: 'http://test.com'})`  fetch  也是 undefined。请问，是要单独安装吗？

**Comment by sky-admin** [comment]
对，'@mpxjs/fetch' 是个npm包，是要单独安装

**Comment by zhupaizhang** [comment]
> 对，'@mpxjs/fetch' 是个npm包，是要单独安装

好的，谢谢。

**Comment by zhupaizhang** [comment]
谢谢
