### ISSUE TITLE
[Bug report]支付宝小程序，组件间关系relations 不支持通过设定target指定behavior

### ISSUE THREAD

**Issue by wongzzh** [didi/mpx#1698]
**问题描述**  

1. 开发支付宝小程序时，组件间关系relations 想通过target关联一类组件，微信小程序是通过Behavior来设定的，支付宝则是由Mixin设定，Behavior和Mixin 都尝试过，没能解决问题。
2. 期望能告知正确的实现方法或指出错误
3.支付宝小程序报错信息为： Options.relations > target is not supported in runtime conversion from wx to ali.

**开发环境信息描述**  
System:
    OS: macOS 14.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 130.0.6723.117
    Edge: 130.0.2849.80
    Safari: 17.3.1
  npmPackages:
    @intlify/vue-devtools:  9.14.1 
    @mpxjs/api-proxy: ^2.9.0 => 2.9.66 
    @mpxjs/babel-plugin-inject-page-events: ^2.9.0 => 2.9.5 
    @mpxjs/cli-shared-utils:  2.1.16 
    @mpxjs/core: ^2.9.0 => 2.9.66 
    @mpxjs/eslint-config:  1.0.10 
    @mpxjs/eslint-config-ts: ^1.0.5 => 1.0.10 
    @mpxjs/fetch: ^2.9.0 => 2.9.66 
    @mpxjs/mpx-cli-service: ^2.0.0 => 2.1.16 
    @mpxjs/pinia: ^2.9.0 => 2.9.65 
    @mpxjs/size-report: ^2.9.0 => 2.9.41 
    @mpxjs/store: ^2.9.0 => 2.9.65 
    @mpxjs/template-engine:  2.8.7 
    @mpxjs/unocss-base: ^2.9.0 => 2.9.48 
    @mpxjs/unocss-plugin: ^2.9.0 => 2.9.54 
    @mpxjs/utils: ^2.9.0 => 2.9.65 
    @mpxjs/vue-cli-plugin-mpx: ^2.0.0 => 2.1.16 
    @mpxjs/vue-cli-plugin-mpx-eslint: ^2.0.0 => 2.1.16 
    @mpxjs/vue-cli-plugin-mpx-typescript: ^2.0.0 => 2.1.16 
    @mpxjs/vue-cli-plugin-mpx-utility-first-css: ^2.0.0 => 2.1.16 
    @mpxjs/webpack-plugin: ^2.9.0 => 2.9.66 
    @vue/cli-overlay:  5.0.8 
    @vue/cli-plugin-router:  5.0.8 
    @vue/cli-plugin-vuex:  5.0.8 
    @vue/cli-service: ~5.0.0 => 5.0.8 
    @vue/cli-shared-utils:  5.0.8 
    @vue/compiler-sfc:  2.7.16 
    @vue/component-compiler-utils:  3.3.0 
    @vue/devtools-api:  6.6.4 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-mpx:  0.2.19 
    mpx-eslint-parser:  0.0.9 
    typescript: ^4.1.3 => 4.9.5 
    vue: ^2.7.0 => 2.7.16 
    vue-demi: ^0.14.6 => 0.14.10 
    vue-eslint-parser:  7.11.0 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.27.2 => 8.28.2 
    vue-i18n-bridge: ^9.2.2 => 9.14.1 
    vue-loader:  17.4.2 (15.11.1)
    vue-router: ^3.1.3 => 3.6.5 
    vue-style-loader:  4.1.3 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @mpxjs/cli: 3.4.1
    @vue/cli: Not Found

**最简复现demo**  
[mpx-demo.zip](https://github.com/user-attachments/files/17712947/mpx-demo.zip)

**Comment by hiyuki** [comment]
最新版本已支持，用法与微信完全一致，使用Behavior进行关系定义

**Comment by wongzzh** [comment]
好嘞，已在新版本上成功使用上了，感谢～
