### ISSUE TITLE
[Feature Request] unocss-plugin 路径扫描支持带 dot 的路径

### ISSUE THREAD

**Issue by lp0124** [didi/mpx#1703]
希望能匹配到 node_modules里某个 npm包里的 mpx 文件
```
unocss: {
        styleIsolation: 'isolated',
        scan: {
          include: ['**/*', '**/node_modules/**/design-mpx/**'],
        },
},
```
实际的 file 为 /mpx-project/node_modules/.pnpm/design-mpx@1.0.0_typescript@4.9.5/node_modules/design-mpx/components/button/index.mpx

由于 unocss-plugin 里使用了 minimatch 这个库，默认不支持带.的路径
<img width="775" alt="image" src="https://github.com/user-attachments/assets/fb8e6864-561f-4aa8-8ab0-e7f820bb290a">
希望修改为
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/79a7699e-1aa5-4ad8-bbd5-bfefad099acf">

**Comment by hiyuki** [comment]
可以直接提pr

**Comment by lp0124** [comment]
好的
