### ISSUE TITLE
微信转百度报错

### ISSUE THREAD

**Issue by iceinkbamboo** [didi/mpx#171]
小程序逻辑代码运行在v8/jscore环境中，请不要使用web api: CSSRuleList
小程序逻辑代码运行在v8/jscore环境中，请不要使用web api: CSSStyleDeclaration
小程序逻辑代码运行在v8/jscore环境中，请不要使用web api: DOMStringList
出现了很多这种错误，还有很多。

这是什么原因？有解决方法吗？

**Comment by hiyuki** [comment]
能够提供个demo吗

**Comment by hiyuki** [comment]
已确认问题，是babel中core-js访问了这些api导致的warning，本身不影响使用。
