### ISSUE TITLE
配置subpackages出错

### ISSUE THREAD

**Issue by changjianhong** [didi/mpx#172]
![7c0085a2d304cef06c2006fe518ac68](https://user-images.githubusercontent.com/12869683/61062104-294fec80-a430-11e9-98fa-e309bb9f2772.png)

![image](https://user-images.githubusercontent.com/12869683/61062181-4be20580-a430-11e9-8c3e-f965158c7898.png)

**Comment by changjianhong** [comment]
![image](https://user-images.githubusercontent.com/12869683/61096021-8f685e00-a488-11e9-940b-efae021ae9b3.png)

**Comment by sky-admin** [comment]
https://github.com/didi/mpx/pull/176 看下这个示例试试？

**Comment by changjianhong** [comment]
谢谢，可以

**Comment by lp0124** [comment]
对于微信原生的 subpackages 配置是否支持呢 页面都是原生的

**Comment by Blackgan3** [comment]
> 对于微信原生的 subpackages 配置是否支持呢 页面都是原生的

支持的
