### ISSUE TITLE
转百度小程序this获取data值，undefined

### ISSUE THREAD

**Issue by iceinkbamboo** [didi/mpx#178]
createPage({
    data: {
      name: 'jack'
    },
    onLoad () {
      console.log('name', this.name)
    }
  })

结果值：name undefined

**Comment by pkingwa** [comment]
我们修复下

**Comment by pkingwa** [comment]
已修复。v2.1.9

**Comment by wahsggx** [comment]
npm 上并没有v2.1.9  目前是v2.1.0，请问什么时候更新呢 @pkingwa

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/61507447-4aa86e00-aa18-11e9-8df6-612850929c2d.png)
