### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by mrgeneralgoo** [didi/mpx#186]

**Comment by mrgeneralgoo** [comment]
mpx代码

```js
<script type="application/json">
  {
    "usingComponents": {
      "i-steps": "../components/iviewui/steps",
      "i-step": "../components/iviewui/step"
    }
  }
</script>
```

被引用的 xwml 文件，https://github.com/TalkingData/iview-weapp/blob/master/dist/step/index.wxml

**Comment by sky-admin** [comment]
？什么问题？
使用组件库可以看这个示例：https://github.com/didi/mpx/tree/master/examples/mpx-useuilib

**Comment by mrgeneralgoo** [comment]
引入了 i-step 组建之后，编译就会报错，其他组件都没问题，对比了下，发现编译出错是因为组件的 xwml 文件中含有 `<wxs module="parse"> </wxs>`，如果我手动把这段代码去掉，就可以编译成功了，但是该组件无法正常运转。

组件具体内容可以查看：https://github.com/TalkingData/iview-weapp/blob/master/dist/step/index.wxml

编译错误信息

> ERROR in ./src/components/iviewui/step/index.wxml?__resource=/miniprogram/src/components/iviewui/step/index (./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=template&index=0&resource=/miniprogram/src/components/iviewui/step!./node_modules/@mpxjs/webpack-plugin/lib/wxml/wxml-loader.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/template-compiler?{"usingComponents":["i-icon"],"hasScoped":false,"hasComment":false,"isNative":true,"moduleId":"493b57a3"}!./src/components/iviewui/step/index.wxml?__resource=/miniprogram/src/components/iviewui/step/index)
Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/extractor.js):
ModuleBuildError: Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/wxs/wxs-loader.js):
ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <view class="i-class i-step-item {{parse.getClass(status,current,index)}} {{ direction === 'vertical' ? 'i-step-vertical' : 'i-step-horizontal' }}" style="{{parse.getItemStyle(len,direction)}}">

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/61587031-60529a80-abb4-11e9-9fcd-0dc40439a2c1.png)
这个错误是吗？
wxs里用了class作为变量名产生的问题，具体原因在查，改成className可解，可向iview团队反馈。

**Comment by mrgeneralgoo** [comment]
改了之后发现还是不行。

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/13347471/61587086-c55ac000-abb5-11e9-8aa3-70fa5a3d80d4.png">

```
<view class="i-class i-step-item {{parse.getClassName(status,current,index)}} {{ direction === 'vertical' ? 'i-step-vertical' : 'i-step-horizontal' }}" style="{{parse.getItemStyle(len,direction)}}">
    <view class="i-step-item-ico">
        <view class="i-step-ico" wx:if="{{parse.noIco(status,current,index,icon)  }}">{{ index+1 }}</view>
        <view class="i-step-ico" wx:else>
            <i-icon i-class="i-step-ico-in" type="{{parse.getIcoClass(status,icon)}}"></i-icon>
        </view>
        <view class="i-step-line" wx:if="{{ index !== len - 1 }}"></view>
    </view>
    <view class="i-step-item-main">
        <view class="i-step-item-title" wx:if="{{title !== ''}}">
            {{title}}
        </view>
        <view class="i-step-item-title" wx:else>
            <slot name="title"></slot>
        </view>
        <view class="i-step-item-content" wx:if="{{content !== ''}}">
            {{content}}
        </view>
        <view class="i-step-item-content" wx:else>
            <slot name="content"></slot>
        </view>
    </view>
</view>
<wxs module="parse">
var allStatus = ['wait','process','finish','error'];
module.exports = {
    noIco : function( status,current,index,icon ){
        var aindex = allStatus.indexOf(status);
        var noIcon = true;
        if( index < current || icon !== '' ){
            noIcon = false;
        }
        return noIcon;
    },
    getIcoClass : function( status,ico ){
        var className = '';
        if( status === 'error' ){
            className = 'close';
        }else{
            className = 'right';
        }
        if( ico !== '' ){
            className = ico;
        }
        return className;
    },
    getItemStyle : function(len,direction){
        if( direction === 'horizontal' ){
            return 'width :'+100/len + '%';
        }else{
            return 'width : 100%;';
        }
    },
    getClassName : function( status,current,index ) {
        //wait、process、finish、error
        var startClass = 'i-step-'
        var className = '';
        var cindex = allStatus.indexOf( status );
        if( cindex !== -1 ){
            className = startClass + allStatus[cindex];
        }
        if( index < current ){
            className = startClass + 'finish';
        }else if( index === current ){
            className = startClass + 'process';
        }
        return className;
    }
}
</wxs>
```

**Comment by sky-admin** [comment]
报下版本号，mpxjs/core, mpxjs/webpack-plugin, iview-weapp的版本号

**Comment by mrgeneralgoo** [comment]
mpxjs/core:2.1.10
mpxjs/webpack-plugin:2.1.12
iview-weapp:2.0.0，手动引入：https://github.com/TalkingData/iview-weapp/archive/v2.0.0.zip

webpack配置是 mpx 脚手架自动生成的，没有任何修改

**Comment by sky-admin** [comment]
OK，可以复现，我们查下，可以先试试降级回2.0.x版本。我之前是2.0.14版本是正常的。

**Comment by mrgeneralgoo** [comment]
好，辛苦

**Comment by heiye9** [comment]
![image](https://user-images.githubusercontent.com/24930493/61699972-76a45600-ad6e-11e9-94ef-d7dd517067f2.png)
我好像遇到了相似的问题，写在标签里的wxs，之前1.0版本没有问题，升级了2.0之后报的错。
但如果把wxs写到单文件，再像这样引入就不会报错。
```html
<wxs src="./parse.wxs" module="parse"/>
```
![image](https://user-images.githubusercontent.com/24930493/61699742-0bf31a80-ad6e-11e9-8967-3fea0769cc30.png)

**Comment by sky-admin** [comment]
升级到2.1.15可解，感谢各位反馈。

**Comment by sky-admin** [comment]
没问题的话就先close了，还存在或者相关的问题需要进一步反馈请reopen此issue
