### ISSUE TITLE
组件中 properties  值改变了，但template无变更

### ISSUE THREAD

**Issue by zhupaizhang** [didi/mpx#187]
通过`this.data.cut_left=left` 修改组件值。在最后打印出`this.data`，发现值已经改变了。但在template中数据无变更。请问下，这方面该如何操作？

**Comment by zhupaizhang** [comment]
直接通过`this.cut_left=left`赋值，`this.data`中的值是没有变化。`this`打印出来，`cut_left`的值已经改变了。但是template 中的绑定`{{cut_letf}}px`,依旧没变化。

**Comment by sky-admin** [comment]
可以发个demo吗？

**Comment by zhupaizhang** [comment]
> 可以发个demo吗？
我本来是用images-cropper 改成适应mpx，不行，我就抛弃掉imags-cropper了。

**Comment by sky-admin** [comment]
没事，你可以发个demo我们有空看下，应该都是支持的

**Comment by zhupaizhang** [comment]
> 没事，你可以发个demo我们有空看下，应该都是支持的

等我这边闲下来。我复现下。如果是我姿势不对，我就不发了。还存在的话。我发给您们。谢谢！
