### ISSUE TITLE
使用 import 与export default  打包后小程序报错  

### ISSUE THREAD

**Issue by wahsggx** [didi/mpx#190]
在index.js中使用export default 输出接口
![image](https://user-images.githubusercontent.com/26195239/61763564-650f8c80-ae08-11e9-954f-937765e19a47.png)

然后在app.mpx中引入index.js文件
```
import api from "api/index";
```
打包过程中没有报错，但是用微信小程序工具打开报错
![image](https://user-images.githubusercontent.com/26195239/61763720-faab1c00-ae08-11e9-8028-98f9f9be913e.png)

project.config.json中设置
```
 "es6": true,
```
请问下，这是什么原因
谢谢

**Comment by Lin-Ya** [comment]
> 在index.js中使用export default 输出接口
> ![image](https://user-images.githubusercontent.com/26195239/61763564-650f8c80-ae08-11e9-954f-937765e19a47.png)
> 
> 然后在app.mpx中引入index.js文件
> 
> ```
> import api from "api/index";
> ```
> 
> 打包过程中没有报错，但是用微信小程序工具打开报错
> ![image](https://user-images.githubusercontent.com/26195239/61763720-faab1c00-ae08-11e9-8028-98f9f9be913e.png)
> 
> project.config.json中设置
> 
> ```
>  "es6": true,
> ```
> 
> 请问下，这是什么原因
> 谢谢

我是在.babelrc里面添加了transform-es2015-modules-commonjs这个插件然后就解决了，你可以尝试一下。
![image](https://user-images.githubusercontent.com/33563178/61764066-6b9f0380-ae0a-11e9-9718-12b305f9199e.png)

**Comment by wahsggx** [comment]
好的，谢谢

**Comment by Lin-Ya** [comment]
实际上我是在 mpx 引入towxml的时候也遇到了这个问题，但是这里  #114 没有怎么解释一下。

**Comment by sky-admin** [comment]
没有遇到过，有复现demo吗？方便给一个demo吗？

**Comment by Lin-Ya** [comment]
> 没有遇到过，有复现demo吗？方便给一个demo吗？

[地址](https://github.com/Lin-Ya/mpx-scrolltop)，已在README做简单说明。

**Comment by hiyuki** [comment]
这是由于引入的外部的cmd库额外跑了一次babel，babel-plugin-transform-runtime在其中注入了import代码导致的问题，解决方法就是确保引入的外部cmd库不跑babel，比如上例中将引入的towxml放到babel-loader的exclude或者babelrc的ignore中即可规避

**Comment by sky-admin** [comment]
@Lin-Ya 我隐藏了一个你的回复，因为其中信息可能产生误导，不应该添加transform-es2015-modules-commonjs这个babel插件哈，应该在babel-loader中exclude掉已经是构建后的lib库代码。

**Comment by Lin-Ya** [comment]
> @Lin-Ya 我隐藏了一个你的回复，因为其中信息可能产生误导，不应该添加transform-es2015-modules-commonjs这个babel插件哈，应该在babel-loader中exclude掉已经是构建后的lib库代码。

@sky-admin OK
