### ISSUE TITLE
希望提供对云开发的支持

### ISSUE THREAD

**Issue by annting** [didi/mpx#191]
mpx 好像没有对小程序的云开发提供支持,  cloudfunctionRoot 指定的目录, 无法正确的编译到dist 目录下, 需要每次手动复制, 希望提供对云开发的支持

**Comment by sky-admin** [comment]
https://github.com/sky-admin/mpx-cloud-demo
可以参考下这个示例，正式的解决方案在路上了，会尽快放出来

**Comment by sky-admin** [comment]
done, 提供了云开发使用模板，也可以参考示例中的cloud项目。#227
