### ISSUE TITLE
多端编译问题

### ISSUE THREAD

**Issue by heiye9** [didi/mpx#192]
第一个问题
![image](https://user-images.githubusercontent.com/24930493/61876923-86fc3280-af20-11e9-9f1f-f157c7275c40.png)
![image](https://user-images.githubusercontent.com/24930493/61877183-0f7ad300-af21-11e9-82fe-96233ecfba15.png)

-----------------------------------------
第二个问题
我只选择了编译wx和qq平台 `npm run watch --wx --qq`，但是编译时给我报了ali不支持某方法的warning。
![image](https://user-images.githubusercontent.com/24930493/61877506-bfe8d700-af21-11e9-8454-8e7a306ca64a.png)

**Comment by sky-admin** [comment]
第一个问题已在处理中了。
第二个问题今天看下。
感谢反馈～

**Comment by sky-admin** [comment]
第二个问题，请问是什么版本？之前手误写错了，确实可能发生这个情况，已经改好了我记得

**Comment by heiye9** [comment]
> 第二个问题，请问是什么版本？之前手误写错了，确实可能发生这个情况，已经改好了我记得

![image](https://user-images.githubusercontent.com/24930493/61920454-420de580-af8c-11e9-9b2a-6c3a594d261f.png)

**Comment by lsycxyj** [comment]
@sky-admin 只改好这个bug会令另外一个bug暴露出来的…rules之前还没做if处理，导致后面删除节点后不存在的节点也报不支持标签/属性…

**Comment by sky-admin** [comment]
@lsycxyj 你说的这个问题已经在处理了，就是这里的第一个问题嘛

**Comment by heiye9** [comment]
请问什么时候发布新版本呢？

**Comment by hiyuki** [comment]
2.2.3版本已处理
