### ISSUE TITLE
wx:style和wx:class内不能换行书写（2.0版本）

### ISSUE THREAD

**Issue by heiye9** [didi/mpx#193]
在2.0版本中，貌似因为编译template都没有\转义符，导致在wx:style和wx:class里写换行的时候运行报错。
![image](https://user-images.githubusercontent.com/24930493/61931230-a0e65580-afb2-11e9-8a84-780dd3abaa4a.png)
![image](https://user-images.githubusercontent.com/24930493/61931680-dfc8db00-afb3-11e9-8cc6-e2f2268c83b1.png)
![image](https://user-images.githubusercontent.com/24930493/61931261-b0659e80-afb2-11e9-8d8f-9c64ab1fe2e3.png)
![image](https://user-images.githubusercontent.com/24930493/61932487-1e5f9500-afb6-11e9-953a-510fa8c6dde0.png)
以上是2.0版本的表现。
第二张图的dist文件为了方便截图看，我格式化了，但不影响。
因为在格式化之前 { } 里面的内容本身就是换行的。

--------

以下是1.0版本正常运行的编译结果

![image](https://user-images.githubusercontent.com/24930493/61932046-f9b6ed80-afb4-11e9-96ff-85ef08f41377.png)

通篇很多\n   \"  
2.0这边就没有，几乎是从原文直接copy。

**Comment by sky-admin** [comment]
在解决中了

**Comment by hiyuki** [comment]
2.2.0 fixed
