### ISSUE TITLE
mpx.getSystemInfoSync() 打包后头条报错

### ISSUE THREAD

**Issue by wahsggx** [didi/mpx#194]
执行 `mpx.getSystemInfoSync() `，打包后头条报错，微信百度正常
![image](https://user-images.githubusercontent.com/26195239/62100001-84a02c80-b2c2-11e9-8bd5-7ce80e5b36a5.png)

请问下，这是什么原因

**Comment by wahsggx** [comment]
查看了bundle.js 
```
r.wx = "undefined" != typeof wx && "function" == typeof t.getSystemInfo, r.ali = "undefined" != typeof my && "function" == typeof my.getSystemInfo, r.swan = "undefined" != typeof swan && "function" == typeof swan.getSystemInfo
```
里面并没有tt.getSystemInfo

**Comment by sky-admin** [comment]
api-proxy是什么版本？

**Comment by wahsggx** [comment]
@mpxjs/api-proxy": "^2.1.13",
    "@mpxjs/core": "^2.1.15",
    "@mpxjs/fetch": "^2.0.12",

**Comment by sky-admin** [comment]
没有复现啊，能发我一个demo吗？

**Comment by sky-admin** [comment]
经查，应该是安装了某个有bug的版本，为了使原有的wx.xxxApi这种写法能正常跨平台，会把wx.转换成mpx.，这个带bug的版本转换得过多，把core本身里的一个环境判断方法里的wx.转成了mpx.，那里没有mpx，就是个undefined，就会报该错误。
解法是升级到最新版。据了解题主是因为使用cnpm装出的问题，有相同问题的朋友可以试试用npm装 `npm i @mpxjs/core@latest @mpxjs/webpack-plugin@latest`
