### ISSUE TITLE
@mpxjs/url-loader 不支持 webpack 的 alias

### ISSUE THREAD

**Issue by kid1412621** [didi/mpx#195]
请问是有配置还是? 而且该插件的文档页面也访问不了

**Comment by sky-admin** [comment]
url-loader？你是指图片资源等没有没应用alias是吗？图片资源前面加个~

**Comment by kid1412621** [comment]
> url-loader？你是指图片资源等没有没应用 alias 是吗？图片资源前面加个～

咦, 这个和 vue cli 3 不一样呢, vue 里面 ~ 是解析 node_modules 的资源嘛, 那现在譬如我 `alias src = @` , 那我引用时需要 `~@/path` 这样呀?
