### ISSUE TITLE
动态样式绑定在QQ小程序开发者工具上没有效果

### ISSUE THREAD

**Issue by namezww** [didi/mpx#201]
![image](https://user-images.githubusercontent.com/33592059/62275627-ec967480-b474-11e9-99a0-fd80cbea8b90.png)

版本是"@mpxjs/webpack-plugin": "^2.1.15", QQ小程序开发者工具是0.1.27,
麻烦看一下，谢谢

**Comment by thuman** [comment]
QQ小程序开发者工具降级到0.1.26吧，这个是QQ是bug
