### ISSUE TITLE
TS2307 cannot find module  '@mpxjs/core'

### ISSUE THREAD

**Issue by heiye9** [didi/mpx#204]
![image](https://user-images.githubusercontent.com/24930493/62409802-4763d380-b60f-11e9-8845-2c62921f9a2b.png)

**Comment by sky-admin** [comment]
哦，不好意思，package.json里发布的文件夹只有src和types，现在改成@types文件夹了，就没发上去，我马上修一下

**Comment by sky-admin** [comment]
2.2.1 fixed
