### ISSUE TITLE
echarts 接入编译失败

### ISSUE THREAD

**Issue by mrgeneralgoo** [didi/mpx#205]
mpxjs/core/-/core-2.1.15
mpxjs/webpack-plugin/-/webpack-plugin-2.1.15
ecomfe/echarts-for-weixin [v1.0.3](https://github.com/ecomfe/echarts-for-weixin/releases/tag/v1.0.3) src 方式手动引入

这段代码没有解析成功，导致依赖的js文件没被编译
```js
import WxCanvas from './wx-canvas';
import * as echarts from './echarts';
```

![ecKNdK.png](https://s2.ax1x.com/2019/08/04/ecKNdK.png)

**Comment by sky-admin** [comment]
https://github.com/echaoo/mpx-echarts
试下这个？

**Comment by sky-admin** [comment]
好像上面那个包也有问题，容我查查

**Comment by hiyuki** [comment]
上面这个warning是由于对echarts的dist进行了一次不必要的babel处理导致的，解决方法可以在webpack配置中将echarts文件夹exclude出babel的处理范围：
```js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/@mpxjs')],
        exclude: [resolve('src/ec-canvas')]
      }
```
另外Mpx本身的runtime处理会对echarts中的环境判断造成影响导致echarts运行时报错，这里已经在最新的@mpxjs/webpack-plugin@2.2.2版本中得到修复
