### ISSUE TITLE
@keyframes 微信平台兼容支持下

### ISSUE THREAD

**Issue by distance295** [didi/mpx#206]
在style中定义@keyframes 之后编译到微信平台的时候会出现@-moz-keyframes的编译结果，此时微信小程序开发工具解析报错。

**Comment by hiyuki** [comment]
这个是stylus的一个默认行为，无法通过编译配置关闭，只能在对应的文件中修改vendors变量来规避该行为，详情查看http://stylus-lang.com/docs/keyframes.html
