### ISSUE TITLE
example里的todomvc打包百度小程序 跑不起来

### ISSUE THREAD

**Issue by logonod** [didi/mpx#208]
customComponentStatistics error: TypeError: Cannot read property 'componentProto' of undefined
value @ index.js:1
customComponentStatistics @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
t.default @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
Promise resolved (async)
(anonymous) @ index.js:1
Promise resolved (async)
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
exports.dispatchEvent @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/utils/message.js:1
e.event.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/master/index.js:1
ipcRenderer.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/src/services/event/renderer/event-map.js:1
emitTwo @ events.js:126
emit @ events.js:214
index.js:1 【Custom Component Error】can't find pages/index, please check your config:
            1. Please check if the reference path is correct;
            2. If it is a page under this path, the "component: true" in the current page JSON should be removed.
value @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
getCustomComponentsData @ index.js:1
sendInitData @ index.js:1
success @ index.js:1
t.communicator.onMessage.listenPreviousEvent @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
Promise resolved (async)
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
exports.dispatchEvent @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/utils/message.js:1
e.event.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/master/index.js:1
ipcRenderer.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/src/services/event/renderer/event-map.js:1
emitTwo @ events.js:126
emit @ events.js:214
index.js:1 【Custom Component Error】can't find pages/index, please check your config:
            1. Please check if the reference path is correct;
            2. If it is a page under this path, the "component: true" in the current page JSON should be removed.
value @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
getCustomComponentsData @ index.js:1
sendInitData @ index.js:1
success @ index.js:1
t.communicator.onMessage.listenPreviousEvent @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
exports.dispatchEvent @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/utils/message.js:1
e.event.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/master/index.js:1
ipcRenderer.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/src/services/event/renderer/event-map.js:1
emitTwo @ events.js:126
emit @ events.js:214
index.js:1 Uncaught TypeError: Cannot read property 'usingComponents' of undefined
    at index.js:1
    at Array.reduce (<anonymous>)
    at t (index.js:1)
    at Object.getCustomComponentsData (index.js:1)
    at Object.sendInitData (index.js:1)
    at success (index.js:1)
    at t.communicator.onMessage.listenPreviousEvent (index.js:1)
    at r.value (index.js:1)
    at index.js:1
    at Array.forEach (<anonymous>)
(anonymous) @ index.js:1
t @ index.js:1
getCustomComponentsData @ index.js:1
sendInitData @ index.js:1
success @ index.js:1
t.communicator.onMessage.listenPreviousEvent @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
exports.dispatchEvent @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/utils/message.js:1
e.event.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/master/index.js:1
ipcRenderer.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/src/services/event/renderer/event-map.js:1
emitTwo @ events.js:126
emit @ events.js:214
index.js:1 Uncaught (in promise) TypeError: Cannot read property 'usingComponents' of undefined
    at index.js:1
    at Array.reduce (<anonymous>)
    at t (index.js:1)
    at Object.getCustomComponentsData (index.js:1)
    at Object.sendInitData (index.js:1)
    at success (index.js:1)
    at t.communicator.onMessage.listenPreviousEvent (index.js:1)
    at r.value (index.js:1)
    at r.value (index.js:1)
    at index.js:1
(anonymous) @ index.js:1
t @ index.js:1
getCustomComponentsData @ index.js:1
sendInitData @ index.js:1
success @ index.js:1
t.communicator.onMessage.listenPreviousEvent @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
Promise rejected (async)
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
Promise resolved (async)
value @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
exports.dispatchEvent @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/utils/message.js:1
e.event.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/master/index.js:1
ipcRenderer.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/src/services/event/renderer/event-map.js:1
emitTwo @ events.js:126
emit @ events.js:214
index.js:1 Uncaught (in promise) {status: "1", message: "invalid event"}
(anonymous) @ index.js:1
I @ index.js:1
onError @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
Promise resolved (async)
e.onMessage.listenPreviousEvent @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
_sendAppLifeCycleMessage @ index.js:1
_onAppError @ index.js:1
(anonymous) @ index.js:1
exports.dispatchEvent @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/utils/message.js:1
e.event.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/master/index.js:1
ipcRenderer.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/src/services/event/renderer/event-map.js:1
emitTwo @ events.js:126
emit @ events.js:214
index.js:1 Uncaught (in promise) {status: "1", message: "invalid event"}
b @ index.js:1
onError @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
Promise resolved (async)
e.onMessage.listenPreviousEvent @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
_sendAppLifeCycleMessage @ index.js:1
_onAppError @ index.js:1
(anonymous) @ index.js:1
exports.dispatchEvent @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/utils/message.js:1
e.event.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/extensions/simulator-swan-api/src/webview/master/index.js:1
ipcRenderer.on @ /Applications/百度开发者工具.app/Contents/Resources/app.asar/dist/src/services/event/renderer/event-map.js:1
emitTwo @ events.js:126
emit @ events.js:214

**Comment by sky-admin** [comment]
todomvc目前只做了微信支付宝两个平台，匹配别的平台还需要一些调整，应该不是加个--swan就行的，会尽快提供所有平台的，请稍等。

**Comment by sky-admin** [comment]
已更新todomvc示例的百度版本，按readme即可运行。
