### ISSUE TITLE
npm run watch报错

### ISSUE THREAD

**Issue by s3hengwu** [didi/mpx#21]
![cc](https://user-images.githubusercontent.com/8500025/49925525-35a0b500-fef4-11e8-96d7-96ae517d9db6.png)

**Comment by sky-admin** [comment]
sorry, 模板改结构的时候没注意，需要改下src/miniprogram/app.mpx 里json中的pages域下，去掉一层index

**Comment by sky-admin** [comment]
重新init项目或者参考[这个](https://github.com/mpx-ecology/mpx-template/commit/11ff21b399ad8d516ae803699a2e2f4fdc55c8c8)改一下吧。
PS：一般项目不需要设为插件项目进行开发哦。
