### ISSUE TITLE
store 组件化

### ISSUE THREAD

**Issue by transtone** [didi/mpx#214]
有没有计划将封装的 mobx 变成一个原生的插件，和 https://github.com/dao42/wechat-weapp-mobx 一样？

这里有一些案例：
https://github.com/zfxmnb/westore/issues/1

**Comment by hiyuki** [comment]
目前暂时没有，mpx本身作为框架而言已经十分轻量，如果进行进一步的抽离势必会对使用体验和性能造成影响，建议直接使用mpx框架

**Comment by transtone** [comment]
这几天在测试mpx，有几个问题：
1. 在使用 vant-weapp 的时候，修改组件样式不生效。这个是关键性阻断。
2. 微信开发者工具自动修改 app.json 不成功，报错。
3. sitemap.json 无法自动复制到 dist，微信开发者工具会自动生成，但更新代码又被删掉了。

**Comment by sky-admin** [comment]
第一点，微信的组件机制的样式就是隔离的，在原生里也不生效的
第二点，开发者工具为什么会修改app.json？是说的project.conf.json吗？解法有两个，一个是手工改外层的，另一个是去掉对它的copy-plugin，通过miniprogram-root来指定小程序文件夹，用开发者工具打开项目目录，事实上我们在1.x阶段就是这样做的，2.0为了更好的跨多小程序平台，改成了现在这样。
第三点，同理，加上copy-plugin从外部复制sitemap.json文件进去即可。这个是新增的东西，后续我们会在脚手架的模板中预置这个逻辑。

**Comment by transtone** [comment]
初始化的时候，appid 没填，所以开发者工具会报错，然后弹出修改 app.json。

copy-plugin 是什么，我去文档中翻翻看。

**Comment by sky-admin** [comment]
webpack的copy-plugin，用它来拷贝的，你说的应该是project.config.json在项目根目录。拷贝逻辑在build.js里

**Comment by transtone** [comment]
找到 copy-plugin 了。这个配置是不是可以写在文档里？
