### ISSUE TITLE
在webpack中添加对eslint的支持

### ISSUE THREAD

**Issue by duop** [didi/mpx#216]
目前通过cli生成的项目中，eslint是在npm script中，如果要使用lint的话，需要单独运行一个`npm run lint`的命令，期望能够在编写代码保存时就提供eslint检测，在webpack编辑前添加eslint检测似乎是一个不错的选择，在vue或react的脚手架项目中也是默认以这种方式使用eslint。

**Comment by sky-admin** [comment]
已经这样做了，模板刚改，init一个新项目看看是否符合你预期？

**Comment by duop** [comment]
在使用新模板创建的项目中，eslint能检测到单文件script标签中的代码，但是无法检测sctipt标签通过src属性引入的标签。

我创建项目时使用了ts，也希望能够在eslint中加入ts的支持，目前npm script和eslintrc.js中需要手动修改。

**Comment by sky-admin** [comment]
好的，src引入的无法lint的问题在修复中了。

**Comment by hiyuki** [comment]
@mpxjs/webpack-plugin@2.2.5 已经修复
