### ISSUE TITLE
vant-weapp 样式不生效

### ISSUE THREAD

**Issue by transtone** [didi/mpx#218]
https://github.com/transtone/mpx-test

![image](https://user-images.githubusercontent.com/46688/62755030-e4f25380-baa4-11e9-87d4-454b2ee4a14c.png)

![image](https://user-images.githubusercontent.com/46688/62755046-fe939b00-baa4-11e9-89ed-f322a57696e5.png)

这个例子里 components/list.mpx 中设置了  .van-checkbox 的样式，在微信开发者工具里根本看不到。

**Comment by sky-admin** [comment]
原生也看不到
![image](https://user-images.githubusercontent.com/6292668/62755088-2c78df80-baa5-11e9-820a-a36760a53602.png)

**Comment by sky-admin** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html

**Comment by transtone** [comment]
![image](https://user-images.githubusercontent.com/46688/62755568-1a983c00-baa7-11e9-917f-a325faed04e6.png)

不要乱甩锅，这是原生的效果。

**Comment by sky-admin** [comment]
OK，首先，关于上面提到的原生样式隔离是客观存在的。而vant组件库是按文档下面提到的addGlobalClass设为true来让页面样式可以影响组件样式的，接下来我会验证下你提到的这个问题。

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/62756798-aca24380-baab-11e9-940f-f63ec2c64c2d.png)

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/62756836-c479c780-baab-11e9-80b9-fdb119d0f4b7.png)

**Comment by sky-admin** [comment]
mpx里的样式一样没有问题，你那之所以有问题，应该是因为你在组件list里使用的vant的checkbox吧。和原生一样放到页面一级，一样可以生效。

**Comment by transtone** [comment]
已核实，是微信组件样式隔离的问题。

感谢兄弟的回复，解决了这个问题，可以继续用 mpx 做开发了。
