### ISSUE TITLE
关于package下分路由功能

### ISSUE THREAD

**Issue by idenet** [didi/mpx#222]
在app.mpx下编写
```
    "packages": [
      "./router/login"
    ],
```
在router文件夹下的login.mpx编写
```
<script type="application/json" lang="json">
  {
    "pages": [
      "/pages/login/reset"
    ]
  }
</script>
```
之前可以用，现在无法使用了。建议重新兼容这个功能。好处是在首页app.mpx下的pages里，只要首页tabbar的主页面路由。
通过主页面navigateto跳转的路由都可以写到，router下的相对应文件下，使路由结构更加清晰

**Comment by hiyuki** [comment]
其实是可以用的，写这种/开头的绝对路径如果需要将resolveMode设置为native并且传递projectRoot路径才能和微信小程序保持一致，另外qq群里反馈的使用../开头的相对路径报错的问题已经在新版本中处理掉了，写相对路径也可以了@2.2.8
