### ISSUE TITLE
vant css desgin 750后样式没转换成rpx

### ISSUE THREAD

**Issue by ChangeZhang** [didi/mpx#223]
![image](https://user-images.githubusercontent.com/6948367/62921318-fa37ec80-bdda-11e9-9d29-d33c353fc2ec.png)
![image](https://user-images.githubusercontent.com/6948367/62921338-04f28180-bddb-11e9-8243-bbd178017688.png)
配置好后，第二张图生成的css内 px 单位没变！！

**Comment by sky-admin** [comment]
抱歉，文档写错了，对象里面应该写mode而不是transRpx。
```js
            {
              transRpx: 'only', // 这里应该为 mode: 'xxxx'
              comment: 'use rpx',
              include: resolve('src')
            }
```
