### ISSUE TITLE
todoMVC 的示例代码 app.mpx attached console.log 输出999个

### ISSUE THREAD

**Issue by ChangeZhang** [didi/mpx#224]
![image](https://user-images.githubusercontent.com/6948367/62925672-6fa8ba80-bde5-11e9-86f6-e601a3904803.png)
![image](https://user-images.githubusercontent.com/6948367/62925688-7800f580-bde5-11e9-8a71-57c36939fe9c.png)
![image](https://user-images.githubusercontent.com/6948367/62925882-e5ad2180-bde5-11e9-92e7-887016016b1e.png)

官方的todoMVC的例子中 app.mpx attached 中的那段console会执行N次，

**Comment by sky-admin** [comment]
console.log没有执行多次，打印的filteredTodos是个被mobx处理过的数组，之所以长度为999是因为mobx用这个对象来模拟数组，使用上没有差别，具体可见mobx的文档：https://cn.mobx.js.org/refguide/array.html#mobx-4-%E5%8F%8A%E4%BB%A5%E4%B8%8B%E7%89%88%E6%9C%AC%E4%B8%AD%E6%95%B0%E7%BB%84%E7%9A%84%E5%B1%80%E9%99%90%E6%80%A7

**Comment by ChangeZhang** [comment]
> console.log没有执行多次，打印的filteredTodos是个被mobx处理过的数组，之所以长度为999是因为mobx用这个对象来模拟数组，使用上没有差别，具体可见mobx的文档：https://cn.mobx.js.org/refguide/array.html#mobx-4-%E5%8F%8A%E4%BB%A5%E4%B8%8B%E7%89%88%E6%9C%AC%E4%B8%AD%E6%95%B0%E7%BB%84%E7%9A%84%E5%B1%80%E9%99%90%E6%80%A7

明白了，是没有执行多次 我描述错误！！！对比试用了一下午感觉 mpx是目前最好的~~

**Comment by sky-admin** [comment]
嗯你的感觉没有错😆

**Comment by ChangeZhang** [comment]
![image](https://user-images.githubusercontent.com/6948367/62931471-0038c800-bdf1-11e9-8ddf-9aee5a67c620.png)
用最新的脚手架2.1.0初始化的项目 @mpxjs/core 和 @mpxjs/webpack-plugin  都不是最新的。是要自己手动更新吗？大神

**Comment by sky-admin** [comment]
不需要，写的是^2.0.0，会自动装最新的（没有package-lock的情况下）
