### ISSUE TITLE
使用ts时，数据管理dispatch action时参数推断context缺失

### ISSUE THREAD

**Issue by clevergod** [didi/mpx#226]
使用ts时，数据管理dispatch action时参数推断context缺失

**Comment by clevergod** [comment]
`actions: {
    async getRegion ({ commit, state }: any) {
      try {
        const data = await CommonApi.region()
        console.log(data)
        commit('setRegion', data)
      } catch (e) {
        console.error(e)
      }
    }
  }`

**Comment by clevergod** [comment]
`js
actions: {
    async getRegion ({ commit, state }: any) {
      try {
        const data = await CommonApi.region()
        console.log(data)
        commit('setRegion', data)
      } catch (e) {
        console.error(e)
      }
    }
  }
`

**Comment by clevergod** [comment]
```js

actions: {
    async getRegion ({ commit, state }: any) {
      try {
        const data = await CommonApi.region()
        console.log(data)
        commit('setRegion', data)
      } catch (e) {
        console.error(e)
      }
    }
  }
```

**Comment by hiyuki** [comment]
createStore中由于ts的能力无法直接推断出context，createStoreWithThis利用了ThisType的能力能够进行推断，使用方法修改为基于this访问，例如this.commit和this.state，详情查看https://didi.github.io/mpx/ts.html文档示例

**Comment by clevergod** [comment]
> createStore中由于ts的能力限制无法指定context参数类型，我们提供了createStoreWithThis变种api，该api利用了ThisType的能力基于类型推导指定this的类型，使用方法修改为基于this访问，例如this.commit和this.state，详情查看[https://didi.github.io/mpx/ts.html文档示例](https://didi.github.io/mpx/ts.html%E6%96%87%E6%A1%A3%E7%A4%BA%E4%BE%8B)

谢谢，this.commit也可以使用
