### ISSUE TITLE
加载 腾讯LBS JSSDK报错

### ISSUE THREAD

**Issue by SamXiao** [didi/mpx#230]
在MPX项目中使用 
`var QQMapWX = require('../../libs/qqmap-wx-jssdk.js');`
方式引入sdk，编译后运行报错
`checkin.js:1317 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`

**Comment by sky-admin** [comment]
babel-loader里exclude掉这个文件，或者不要放在src里试试？

**Comment by SamXiao** [comment]
"babel-loader里exclude掉这个文件" 这个可行  多谢
