### ISSUE TITLE
mpx.fetch 不能设置 header content-type

### ISSUE THREAD

**Issue by hejinzhi** [didi/mpx#234]
如图，设置后 request header 还是  x-www-*

![image](https://user-images.githubusercontent.com/18588816/63485537-533c0a80-c4d6-11e9-929f-d9204c0d544c.png)

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/63565221-a1b2dd00-c59a-11e9-8844-ad9cd8042505.png)
好像没有问题啊？

**Comment by sky-admin** [comment]
提供一个demo吧

**Comment by hejinzhi** [comment]
找到原因了，去掉 emulateJSON 就可以，谢谢
