### ISSUE TITLE
mpx同时编译支付宝，微信多模块时，支付宝无法正确编译问题

### ISSUE THREAD

**Issue by yuzejia** [didi/mpx#237]
npm i @mpxjs/webpack-plugin@latest @mpxjs/core@latest
mpx 升级2.2.19；
执行 npm run watch --wx --ali ；后 微信可以正常编译；支付宝编译出来的文件 ali>component >下的某些文件格式不是 axml  而是 wxml；导致项目无法正确运行！

单独执行 npm run watch --ali  可以正确进行编译！

![C59K`BW~Z0C3Y4V$N2SAQTE](https://user-images.githubusercontent.com/25543828/63681632-b60c0980-c828-11e9-8c28-c4a28077f933.png)
![M_TZL`JW9JS9NC1MCT`ZX~M](https://user-images.githubusercontent.com/25543828/63681637-b99f9080-c828-11e9-9ea2-ce73998ac0ba.png)

**Comment by hiyuki** [comment]
感谢反馈，已修复，@mpxjs/webpack-plugin@2.2.20
