### ISSUE TITLE
实践发现mpx 不能兼容 wux weapp

### ISSUE THREAD

**Issue by saoraozhe3hao** [didi/mpx#238]
mpx 用的是 babel-core
wux weapp 用的是@babel/core

**Comment by sky-admin** [comment]
问题是？babel是个开发时依赖，仅在build时使用，不一致应该没关系，mpx里直接引入wux-weapp build好的dist应该没问题吧？

**Comment by sky-admin** [comment]
没有进一步的证据或者demo反馈问题的话，这个issue暂时先关闭了，应该是可以正常work的，仍有问题请reopen
