### ISSUE TITLE
打包后小程序报错Uncaught TypeError: Cannot redefine property: toString

### ISSUE THREAD

**Issue by erguotou520** [didi/mpx#239]
简单的demo项目没有问题，但我们是直接将原有的项目复制进来进行改造的，但是webpack打包后在小程序端打开报错`Uncaught TypeError: Cannot redefine property: toString`，报错位置是在`app.js`里的`core_js_modules_es7_object_get_own_property_descriptors__WEBPACK_IMPORTED_MODULE_0__`位置处

**Comment by sky-admin** [comment]
验证中……方便提供一个复现demo吗？

**Comment by sky-admin** [comment]
信息太少，还是给个demo吧

**Comment by erguotou520** [comment]
emmmmm，因为是直接复制的整个项目，内容非常多，正在尝试能不能弄出一个简单的demo

**Comment by erguotou520** [comment]
是我babel的配置有问题，直接用的`@vue/preset`

**Comment by erguotou520** [comment]
我只要`@babel/preset-env`开启 `useBuiltIns="usage"`就会报这个错误，有没有什么思路？

**Comment by erguotou520** [comment]
测试了下，改为`false`然后手动`import core-js`的代码也会报着个错误，原因应该是`core-js`中会redefine `Function.prototype.toString`，但是小程序中不允许修改

**Comment by yzy463300** [comment]
是用的babel7吗？babel7好像会覆盖jscore的toString方法，但是小程序不允许修改

**Comment by wangxianfa** [comment]
所以这个大家是怎么解决的

**Comment by sky-admin** [comment]
最新的模板里已经完善了babel7的配置，新生产一个项目把src粘过去吧。

**Comment by wangxianfa** [comment]
> 最新的模板里已经完善了babel7的配置，新生产一个项目把src粘过去吧。

我是自己通过webpack把小程序项目打包，引入polyfill的过程中遇到的这个问题，看着是小程序中的Function.prototype.toString configable为false造成的，不引入polyfill的话低版本includes等不支持，没办法的话就只能像miniprogram-ci里面的方法搞了

**Comment by qianjunsteve** [comment]
遇到同样问题，楼主解决了吗
