### ISSUE TITLE
mpx image标签编译错误

### ISSUE THREAD

**Issue by luotingv1** [didi/mpx#243]
<image src='cloud://lt-1a8882.6c74-lt-1a8882/3.jpeg' class="bg-swiper"></image>
会导致编译错误路径
![image](https://user-images.githubusercontent.com/24503005/63903845-8ab03700-ca41-11e9-88d1-f683301eb1e8.png)

**Comment by hiyuki** [comment]
已修复 https://github.com/didi/mpx/releases/tag/v2.2.21
