### ISSUE TITLE
初始化项目后 <script type="application/json"> 删掉后报错

### ISSUE THREAD

**Issue by ChangeZhang** [didi/mpx#245]
![image](https://user-images.githubusercontent.com/6948367/64009379-570d0400-cb4a-11e9-8aa8-d21a5432a5c0.png)
初始化项目后，pages/index.mpx是这样的
![image](https://user-images.githubusercontent.com/6948367/64009418-63915c80-cb4a-11e9-91b1-faf1aefc5db4.png)
然后，我删除了pages/index.mpx 的<script type="application/json">里面的一些内容后
![image](https://user-images.githubusercontent.com/6948367/64009467-7e63d100-cb4a-11e9-806f-bf0101c50a78.png)
就会报这个错，运行不起来了就
![image](https://user-images.githubusercontent.com/6948367/64009575-ad7a4280-cb4a-11e9-8543-6036b3f0acad.png)

**Comment by hiyuki** [comment]
测试了一下这个应该属于wx开发者工具的问题，原因微信开发者工具在刷新后执行了没有任何地方引用的组件js逻辑，导致查找不到模块报错，遇到这个问题可以考虑关闭watch重新执行一遍mpx的构建，整个文件夹都会清空重新生成即可解决
