### ISSUE TITLE
使用第三方组件vant-weapp的action-sheet组件报错

### ISSUE THREAD

**Issue by weekitmo** [didi/mpx#247]
编译目标是百度小程序
`<button>'s property 'open-type' does not support '[{{ item.openType }}]' value in baidu environment!`

**Comment by weekitmo** [comment]
@mpxjs/webpack-plugin 升到2.2.21额外报错：
`Cannot read property '1' of null`， 具体是编译的时候wx:for的swan 会出现一个building...item in 12，但我的项目中没有这个写法

**Comment by weekitmo** [comment]
@mpxjs/webpack-plugin 找到原因了，是因为vant的组件的loading用了这个写法
```
attrsMap:
   { 'wx:if': '{{ type === \'spinner\' }}',
     'wx:for': 'item in 12',
     'wx:key': 'index',
     class: 'van-loading__dot' } }
```

**Comment by sky-admin** [comment]
第一个问题是，button的open-type，微信和百度的可能并不对等，然后又用了动态的{{ item.openType }}，转换结果可能不符合预期，报的一个警告，如果你确认用起来没问题，可以忽略。
第二个我们解决一下。

**Comment by weekitmo** [comment]
@sky-admin  
第一个其实我也理解，只是觉得报红有点...，这种类型的错误，因为也不属于直接不能运行，用一个警告(报黄)代替会不会好点

**Comment by sky-admin** [comment]
我们有警告和错误两种，是根据我们自己认为的重要程度来分的，不怎么影响使用的就会是黄色。button的opentype承载的东西还蛮重要的一般，比如用户信息获取之类的，如果不一致是可能导致程序逻辑走不下去的对吧。这里用一个动态的值，我们也无法确知它到底会有什么，万一出问题了呢。
这里主要是因为是第三方组件库里的东西，你也不好改，正常场景下建议是通过一个条件编译fix掉这种问题

**Comment by Aimee1608** [comment]
字节跳动小程序里面，直接报这个错，
/Applications/bytedanceide.app/Contents/Resources/app.asar.unpacked/simulator-sdk/temFiles/dist/preload/bgPreload.7dd0f846fc98718974aa.js:240 Error:

in file ./pages/expList

Error:

in file ./components/vant-weapp224d26dd/action-sheet/index

SyntaxError: Bad attr class
  1 | <wxs src="../wxs/utils.wxs" module="utils"/> <van-popup show="{{ show }}" position="bottom" z-index="{{ zIndex }}" overlay="{{ overlay }}" custom-class="van-action-sheet" safe-area-inset-bottom="{{ safeAreaInsetBottom }}" close-on-click-overlay="{{ closeOnClickOverlay }}" bind:close="onClose"><view class="van-hairline--bottom van-action-sheet__header" tt:if="{{ title }}">
  2 |     {{ title }}
> 3 |     <van-icon name="close" custom-class="van-action-sheet__close" bind:click="onClose"/></view> <view tt:if="{{ actions && actions.length }}"><button open-type="{{ item.openType }}" class="{{ utils.bem('action-sheet__item', { disabled: item.disabled || item.loading }) }} van-hairline--top {{ item.className || '' }}" hover-class="van-action-sheet__item--hover" data-index="{{ index }}" bind:tap="onSelect" tt:for="{{ actions }}" tt:key="index"><block tt:if="{{ !item.loading }}">
    |                                                                                                                                                                                                          ^
  4 |         {{ item.name }}
  5 |         <text class="van-action-sheet__subname" tt:if="{{ item.subname }}">{{ item.subname }}</text></block> <van-loading size="20px" tt:else/></button></view> <slot/> <view class="van-action-sheet__cancel" hover-class="van-action-sheet__cancel--hover" hover-stay-time="70" bind:tap="onCancel" tt:if="{{ cancelText }}">
  6 |     {{ cancelText }}

**Comment by sky-admin** [comment]
#275
