### ISSUE TITLE
project.config.json里配置miniprogramRoot: 'dist/'后 开发工具上点预览报错

### ISSUE THREAD

**Issue by ChangeZhang** [didi/mpx#251]
![image](https://user-images.githubusercontent.com/6948367/64317172-72b05880-cfe9-11e9-84aa-4d667c4be579.png)
![image](https://user-images.githubusercontent.com/6948367/64317184-7a6ffd00-cfe9-11e9-89ca-281f301aa358.png)

**Comment by ChangeZhang** [comment]
编译运行是没问题的

**Comment by sky-admin** [comment]
能提供一个可复现的demo吗？

**Comment by ChangeZhang** [comment]
sorry,不知道怎么DEMO，就是工具导入项目选到根目录，没选到xxx/dist/ 然后在根目录的project.config.json配置miniprogramRoot: 'dist/'后项目运行没问题，点预览和上传都会报这个错
![image](https://user-images.githubusercontent.com/6948367/64323900-f4a77e00-cff7-11e9-8644-2adbc281a052.png)
![image](https://user-images.githubusercontent.com/6948367/64324050-36d0bf80-cff8-11e9-9d52-d461f08b1cc5.png)

**Comment by sky-admin** [comment]
行，稍等，我试试复现

**Comment by ChangeZhang** [comment]
辛苦，麻烦了~

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/64327596-9205b080-cffe-11e9-95ac-3e4e227b7a21.png)
并没有复现？操作路径是新生成一个项目，build完成后修改project.config.json添加那个字段，然后打开项目目录而不是dist目录，然后点击预览，没报错。

**Comment by sky-admin** [comment]
开发者工具1907300

**Comment by ChangeZhang** [comment]
好的，我一会用你的开发者版本工具看看。谢谢了
