### ISSUE TITLE
computed 变量 观察的 store里的 属性，如果computed变量 没在template中用到，则观察失效

### ISSUE THREAD

**Issue by saoraozhe3hao** [didi/mpx#252]
`        computed: {
            location() {
                return store.state.location;
            }
        }`
如果 template中 没用到 location， 改变 store.state.location 时，location() 不被触发

**Comment by sky-admin** [comment]
会改变，但不会被setData到渲染层。这是一个性能优化，如果你模板上并不使用，你并不应该将其setData，线程通信比较费性能。
你通过watch或者别的手段打印this.location会看到已经发生变化了。
你之所以认为不被触发是使用开发者工具的data页观察的是吗？

**Comment by hiyuki** [comment]
你这里有建立watch来观测location吗，computed出于对性能的考虑是采用lazy update的方式来更新的，当没有任何watch（模板上使用也是一种watch）访问loaction时，更新了store.state.location，location的计算函数也不会重新执行，这是正常的表现
