### ISSUE TITLE
构建生产环境时，use px不生效。sass、mode:all、构建命令带参数-p

### ISSUE THREAD

**Issue by guyuejinshang** [didi/mpx#255]
在这些条件下会把/* use px */注释删掉，导致px全部被转为rpx
1、node ./build/build.js -p（不带-p参数没问题。但是代码就没有压缩了）
2、css是用的sass，less没问题
3、webpack.conf.js中transRpx内的mode=all

**Comment by hiyuki** [comment]
给sass-loader添加参数{sassOptions:outputStyle:'nested'}，给mpx中的sass传入的配置的方法可以参考#62
