### ISSUE TITLE
`@mpxjs/webpack-plugin` 模块升级后获取的$refs下的对象结构不一致的问题

### ISSUE THREAD

**Issue by songyazhao** [didi/mpx#256]
Hi, 我有这样的一个组件 `filter.mpx`, 组件里引用了另外两个组件 `dm-mask`、`dm-select`，在代码里我在 `created` 周期函数里打印了 filter 组件的 $refs，在将 `@mpxjs/webpack-plugin` 升级到`2.2.22`版本后出现下述问题：通过 $refs 获取的 `dmSelect` 组件变成了一个被数组包裹的对象，请教一下，这种差异化是新版特意设计的还是新版本的Bug呢？

> 升级后`"@mpxjs/webpack-plugin": "2.2.22"` 下：

![image](https://user-images.githubusercontent.com/23444330/64681828-fe772880-d4b2-11e9-80c2-65f402b17161.png)

> 原版本`"@mpxjs/webpack-plugin": "2.2.13"` 下：

![image](https://user-images.githubusercontent.com/23444330/64679320-18623c80-d4ae-11e9-9a28-8c9a27785fef.png)

> 出现问题的最小结构部分代码：
```vue
<template>
  <dm-mask wx:ref="dmMask"></dm-mask>

  <block wx:for="{{options}}" wx:key="index">
    <dm-select
      wx:if="{{index === 0}}"
      wx:ref="dmSelect"
    ></dm-select>
  </block>
</template>

<script>
import { createComponent } from '@mpxjs/core'

createComponent({
  data: {
    options: [
      { a: '随便写点啥' },
      { a: '随便写点啥' },
      { a: '随便写点啥' }
    ]
  },

  created () {
    console.log(this.$refs)
  }
})
</script>

<script type="application/json">
  {
    "component": true,
    "usingComponents": {
      "dm-mask": "../../components/dmx/dm-mask",
      "dm-select": "../../components/dmx/dm-select"
    }
  }
</script>
```

**目前发现这种问题只发生在自定义组件下，如果用原生 `view` 则一切正常**

**Comment by hiyuki** [comment]
这个是预期内的行为，之前的其实是有bug的，在for当中正常确实应该返回一个数组，对于组件来说在for当中会调用selectAllComponents获取组件实例数组，而对于原生view来说也是同样的，在for当中会调用SelectorQuery.selectAll来获取NodesRef，虽然返回的都是单个的nodesRef，但是执行boundingClientRect等查询函数时返回的结果就是数组

**Comment by songyazhao** [comment]
@hiyuki 
好的 ，感谢在百忙中回复，对于你刚刚说的，有句话不太理解
`"对于组件来说在for当中会调用selectAllComponents获取组件实例数组，而对于原生view来说也是同样的"`
里面 `对于原生view来说也是同样的` 这句话和我在代码里实际实验的结果不一致呢：如下图，`dmSelect` 和 `view` 的结构并不一致, dmSelect 是一个数组，而view是直接获取到的一个对象

![image](https://user-images.githubusercontent.com/23444330/64685859-3e8dd980-d4ba-11e9-8152-bd936dfb7db4.png)

```vue
<template>
  <dm-mask wx:ref="dmMask"></dm-mask>

  <block wx:for="{{options}}" wx:key="index">
    <dm-select
      wx:if="{{index === 0}}"
      wx:ref="dmSelect"
    ></dm-select>
    <view
      wx:if="{{index === 1}}"
      wx:ref="view"
    ></view>
  </block>
</template>
```

**Comment by hiyuki** [comment]
你可以试一下this.$refs.view.boundingClientRect((res)=>{
console.log(res) // 此处的res是一个数组，而如果这个view是在for之外，此处的res会成为一个对象
}).exec()
