### ISSUE TITLE
不支持跳过cover-image的src路径编译

### ISSUE THREAD

**Issue by erguotou520** [didi/mpx#260]
某些情况下我给cover-image设置的src是需要小程序的原生语法进行变量替换的，例如静态的图片资源在循环列表中的时候
```html
<cover-image src="/tabbar/{{item}}{{item.name===selectedName ? '_selected' : ''}}.png" />
```
我看loader中好像没有跳过编译的方法，现在这么写会一直提示路径找不到。

**Comment by sky-admin** [comment]
在 #263 统一处理吧，这个和是不是cover-imega没关系，image的src不能是插值动态变量，原因和解决方法见那个issue

**Comment by sky-admin** [comment]
好吧误解你的意思了，可以的，这个我们能支持

**Comment by erguotou520** [comment]
加一个什么类似 `{{~/static/xx.png}}`的支持

**Comment by hiyuki** [comment]
2.2.30已修复
https://github.com/didi/mpx/releases/tag/v2.2.30
