### ISSUE TITLE
微信小程序 image src 动态本地路径问题

### ISSUE THREAD

**Issue by ZoeHuang13** [didi/mpx#263]
`<image class="kv" src="../image/detail-kv.png"></image>`
是可以加载成功的，下面就不行
`<image class="kv" src="{{'../image/detail-kv.png'}}"></image>`
Failed to load local image resource /image/detail-kv.png 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
应该是因为图片目录也被编译了，请问有什么解决办法吗？动态加载本地图片路径。

**Comment by sky-admin** [comment]
https://didi.github.io/mpx/understanding/resource.html#%E5%8A%A8%E6%80%81%E5%BC%95%E7%94%A8%E6%9C%AC%E5%9C%B0%E8%B5%84%E6%BA%90

**Comment by sky-admin** [comment]
这个问题和 #260 类似
是的，webpack构建是基于依赖收集的，如果那是个插值语法写的变量，将无法收集到那个资源。

**Comment by ZoeHuang13** [comment]
> https://didi.github.io/mpx/understanding/resource.html#%E5%8A%A8%E6%80%81%E5%BC%95%E7%94%A8%E6%9C%AC%E5%9C%B0%E8%B5%84%E6%BA%90

看来我文档找的还是不够仔细，感谢

**Comment by sky-admin** [comment]
解决方案见链接里，对于有限张图片和较多张图片有两种方式来解决。

如果实在想在模板上插值来做，可以试试建一个static文件夹配一个webpack-copy-plugin，把图片拷贝过去，不走webpack的依赖收集，路径也完全自己控制。此方案非常不建议使用，出问题需自行解决……

**Comment by erguotou520** [comment]
我是通过copy目录的方法实现的，但是image的src写成插值的方式还是会报错，想跳过webpack的收集怎么处理？
