### ISSUE TITLE
mpx.getStorageSync('wx') 取值为空

### ISSUE THREAD

**Issue by wahsggx** [didi/mpx#266]
mpx.setStorageSync('wx', data) 
mpx.getStorageSync('wx') 取值为undefined

版本号：
"@mpxjs/api-proxy": "^2.2.0",
"@mpxjs/core": "^2.2.23",
"@mpxjs/webpack-plugin": "^2.2.22",

**Comment by httpsxiao** [comment]
可以把 @mpxjs/webpack-plugin 和 @mpxjs/api-proxy 都升级到最新版 2.2.26 试一下
