### ISSUE TITLE
cancelToken.exec()方法导致的catch语句在下一个请求发出后才执行,期望是在下一个请求发出前执行

### ISSUE THREAD

**Issue by zhaoyunyes** [didi/mpx#271]
**场景:**
按下搜索按钮进行商品搜索,并显示搜索出来的商品列表
为了避免上次搜索请求还没返回结果,故在进行搜索前先取消上次搜索
**关键代码和步骤:**
_储存商品搜索结果对象的定义:_
![image](https://user-images.githubusercontent.com/16451550/65572680-67729c00-df9b-11e9-80ea-e81fd305283d.png)
_关键步骤:_
![image](https://user-images.githubusercontent.com/16451550/65572765-ac96ce00-df9b-11e9-9a60-f53a8069f4bc.png)
![image](https://user-images.githubusercontent.com/16451550/65572783-bb7d8080-df9b-11e9-8531-4b289b24473c.png)
![image](https://user-images.githubusercontent.com/16451550/65572892-0dbea180-df9c-11e9-9140-c110784722ea.png)

**问题描述:**
在下一个请求发出之后,上一个被取消的请求才进入catch,如上图所示的第6步,此时就把this.goodsRes.isFetching置为false了,而实际上下一个请求还在请求中,所以此时this.goodsRes.isFetching应该为true才对

**期望结果:**
~~上一个被取消的请求的catch语句应该在下一个请求发出之前执行,以避免可能的数据错乱~~
cancelToken.exec()返回一个Promise,从而能够知道上一个请求有没有(何时)取消成功

**Comment by tangminFE** [comment]
xfetch里的cancelToken.exec()会在下一个版本返回Promise

**Comment by hiyuki** [comment]
2.2.30已修复
https://github.com/didi/mpx/releases/tag/v2.2.30
