### ISSUE TITLE
支付宝小程序分包，预览里面分包里面mpxkey只有18个 不能使用阿里api

### ISSUE THREAD

**Issue by Aimee1608** [didi/mpx#277]
在分包里面使用getStorageSync，预览的时候会报getStorageSync undefined,
通过打印mpx实例，发现只有18个key, 而正常应该有300多个

**Comment by hiyuki** [comment]
这个问题我们已知，是支付宝的本身分包机制与微信不同导致的，马上会发新版本处理

**Comment by hiyuki** [comment]
2.2.30已修复
https://github.com/didi/mpx/releases/tag/v2.2.30
