### ISSUE TITLE
mpx  微信小程序 转义字符 报错

### ISSUE THREAD

**Issue by annting** [didi/mpx#280]
页面中需要显示 "<"  这种特殊字符,   按照微信的写法是 `  <text decode="true"> A &lt; B</text>`, 但 mpx编译后的代码为:
`<view><list mpxPageStatus="{{mpxPageStatus}}"></list> <text decode="true"> A < B</text></view> `

先将特殊字符转了, 导致微信开发工具中报错了

**Comment by hiyuki** [comment]
ok 我们处理一下

**Comment by hiyuki** [comment]
2.2.30已修复
https://github.com/didi/mpx/releases/tag/v2.2.30
