### ISSUE TITLE
open-type 不支持动态绑定

### ISSUE THREAD

**Issue by saoraozhe3hao** [didi/mpx#282]
<button>'s property 'open-type' does not support '[{{ openType }}]' value in byt edance environment!

**Comment by sky-admin** [comment]
支持的，但是有风险，因为平台差异对不齐，所以会报错，如果你认为你动态的值全会在对应平台上支持，你就可以忽略这个错误。

**Comment by sky-admin** [comment]
我们将error换成了warning
