### ISSUE TITLE
百度小程序for循环：更新渲染数据无法视图更新

### ISSUE THREAD

**Issue by wahsggx** [didi/mpx#285]
如题，微信和头条正常，
"@mpxjs/api-proxy": "^2.2.27",
"@mpxjs/core": "^2.2.27",
"@mpxjs/webpack-plugin": "^2.2.29",

**Comment by hiyuki** [comment]
能否提供个复现代码 我们check一下

**Comment by sky-admin** [comment]
问题已QQ沟通确认，处理中

**Comment by hiyuki** [comment]
2.2.30已修复
https://github.com/didi/mpx/releases/tag/v2.2.30
