### ISSUE TITLE
picker组件mode="multiSelector"，动态更新渲染数据无法触发视图更新

### ISSUE THREAD

**Issue by wahsggx** [didi/mpx#286]
picker设置mode="multiSelector"，比如省市区联动组件，改变第一列省份的时候同时改变第二列第三列（市、区）的渲染数据，但是不会视图更新

"@mpxjs/api-proxy": "^2.2.27",
"@mpxjs/core": "^2.2.27",
"@mpxjs/webpack-plugin": "^2.2.29",

微信头条均出现上述问题

**Comment by hiyuki** [comment]
我们check一下

**Comment by hiyuki** [comment]
@wahsggx 无法复现，麻烦提供下复现代码片段或者完整复现demo

**Comment by hiyuki** [comment]
已通过线下沟通定位问题并修复，https://github.com/didi/mpx/releases/tag/v2.2.31
