### ISSUE TITLE
mpx 不支持 weui-miniprogram组件库 跨平台编译

### ISSUE THREAD

**Issue by saoraozhe3hao** [didi/mpx#287]
实践：微信小程序代码跨平台编译为字节跳动小程序，源项目中用到了微信官方的 weui-miniprogram组件库，编译成字节跳动小程序，编译时没有报错，在字节跳动开发者工具中打开，报
Error:
in file ./components/mpx26b204e2/src/components/weui/cells/cells
parent.append is not a function

weui-miniprogram，文档在这：
https://developers.weixin.qq.com/miniprogram/dev/extended/weui/quickstart.html
weui-miniprogram，github在这：
https://github.com/wechat-miniprogram/weui-miniprogram

**Comment by sky-admin** [comment]
https://github.com/wechat-miniprogram/weui-miniprogram/blob/master/src/cells/cells.wxml#L7
试了下好像是这个template影响的，而且这里用的居然是v-if和v-else

**Comment by sky-admin** [comment]
经测试，template应为block，以及v-改为wx:后表现正常，应该是对方代码的问题，辛苦反馈给weui的同学吧。
