### ISSUE TITLE
可否提供以百度小程序为母版构建其他小程序的方法？

### ISSUE THREAD

**Issue by vivine** [didi/mpx#291]
因为我司主要是百度小程序战场，现在需要拓展疆域，所以需要一个像MPX这样的跨平台解决方案，但目前只提供了微信为母版构建其他小程序。特别需要支持百度为母版转其他。

研究过你们的@mpxjs/webpack-plugin插件，但并没有太深入，如果自己修改的话，请指教需要修改哪些地方，才能满足以上我们的需求。或者官方能否提供一个呢？

最后，谢谢！！

**Comment by sky-admin** [comment]
好的，我们尽快就转换部分提供一份文档，主要是lib/platform部分，可以参考wx的先看看。

**Comment by vivine** [comment]
@sky-admin 另外，@mpxjs/cli 最新版本里边用的 @mpxjs/core 并不是最新的，还有其他两个依赖也不是最新的，都升级了这么多版本了，建议cli也升级一个版本，毕竟使用脚手架创建项目的偏多。。。

**Comment by sky-admin** [comment]
模板和cli是分开的。2.0是模板声明的，那个版本号前带^，没有lock直接装的话会装到最新版的。

**Comment by hiyuki** [comment]
我们近期提供一个母版，把基础的转换部分打上，之后你们就可以自行往里面添加规则来完善转换了

**Comment by vivine** [comment]
> 模板和cli是分开的。2.0是模板声明的，那个版本号前带^，没有lock直接装的话会装到最新版的。

我今天就是直接npm装的，装完看版本还是低的版本，也不知道是什么原因，最后手动升版本了。有可能跟我的npm源有关系吧。

**Comment by vivine** [comment]
> 我们近期提供一个母版，把基础的转换部分打上，之后你们就可以自行往里面添加规则来完善转换了

太好了，大概什么时候出呀？
