### ISSUE TITLE
vant-weapp 在百度小程序下的问题

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#293]
百度小程序下引入vant-weapp 组件库的问题

- [x] 引入notice-bar methods->init方法 报错： Cannot read property 'getRect' of undefined
```javascript
        init() {
            Promise.all([
                this.getRect('.van-notice-bar__content'),
                this.getRect('.van-notice-bar__wrap')
            ]).then((rects) => {
                const [contentRect, wrapRect] = rects;
                if (contentRect == null ||
                    wrapRect == null ||
                    !contentRect.width ||
                    !wrapRect.width) {
                    return;
                }
                const { speed, scrollable, delay } = this.data;
                if (scrollable && wrapRect.width < contentRect.width) {
                    const duration = (contentRect.width / speed) * 1000;
                    this.wrapWidth = wrapRect.width;
                    this.contentWidth = contentRect.width;
                    this.duration = duration;
                    this.animation = wx.createAnimation({
                        duration,
                        timingFunction: 'linear',
                        delay
                    });
                    this.scroll();
                }
            });
        },
```

**Comment by okxiaoliang4** [comment]
@httpsxiao 发现vant-weapp的gird组件调用updateChildren方法this.children也为空，推测vant-weapp库在百度小程序下methods下面方法的this指向都有问题

**Comment by hiyuki** [comment]
正常调用this指向没有问题，直接传入setdata作为回调时this的指向和微信不一致，我们可以从框架层面代理setdata来抹平，目前已经进行了处理，下一版发布就能解决

**Comment by okxiaoliang4** [comment]
**问题描述**
引入van-grid组件后设置每行个数微信下正常，百度下不正常

**复现步骤**
```
yarn
yarn watch:cross
```

**期望的表现**
百度与微信表现一样，可以设置每行个数

**截图**

![1570870114(1)](https://user-images.githubusercontent.com/22525904/66698458-dcbacc80-ed10-11e9-8088-08abcdb70344.jpg)
![1570870136(1)](https://user-images.githubusercontent.com/22525904/66698459-dd536300-ed10-11e9-8910-c6c6feb075e1.jpg)

**系统及环境**
与系统及环境无关

**附件**
[mpx-demo.zip](https://github.com/didi/mpx/files/3720408/mpx-demo.zip)

**Comment by httpsxiao** [comment]
> **问题描述**
> 微信小程序和百度小程序生命周期触发不一致，是否可以抹平差异
> 
> **复现步骤**
> 页面1->2->1
> 百度下onLoad，onShow出现的情况
> 1: onLoad -> 2: onLoad -> 1: onShow
> 1: onLoad,1: onShow -> 2: onLoad,2: onShow -> 1: onShow
> 
> **期望的表现**
> 希望可以抹平差异
> 
> **截图**
> 无
> 
> **系统及环境**
> 无
> 
> **附件**
> 无

没有复现，可以提供一个复现的 demo 吗？

**Comment by okxiaoliang4** [comment]
> > **问题描述**
> > 微信小程序和百度小程序生命周期触发不一致，是否可以抹平差异
> > **复现步骤**
> > 页面1->2->1
> > 百度下onLoad，onShow出现的情况
> > 1: onLoad -> 2: onLoad -> 1: onShow
> > 1: onLoad,1: onShow -> 2: onLoad,2: onShow -> 1: onShow
> > **期望的表现**
> > 希望可以抹平差异
> > **截图**
> > 无
> > **系统及环境**
> > 无
> > **附件**
> > 无
> 
> 没有复现，可以提供一个复现的 demo 吗？

@httpsxiao 可以用mixin解决百度与微信的差异，支付宝没看，现在已经对这个没需求了，不过还是希望可以各个平台的生命周期触发一致，明天附上demo
