### ISSUE TITLE
版本升级2.2.30 后 首页 icon 图标无法正常 显示

### ISSUE THREAD

**Issue by yuzejia** [didi/mpx#296]
![image](https://user-images.githubusercontent.com/25543828/66385903-dfa57c80-e9f3-11e9-96af-ca478560db27.png)

手机上无法正常显示图标：
![F@MYZVDVV3NK8{05KE{4_BF](https://user-images.githubusercontent.com/25543828/66385846-c00e5400-e9f3-11e9-9092-55aaa7c885c0.png)

**Comment by hiyuki** [comment]
提供一下复现demo吧，demo源码打个包拖拽上传到issue回复当中

**Comment by sky-admin** [comment]
据IM沟通，此问题在demo中无法复现。暂时关闭，若找到复现方式，请重新打开。
