### ISSUE TITLE
如何引入插件版阿拉丁

### ISSUE THREAD

**Issue by erguotou520** [didi/mpx#300]
阿拉丁插件版要求替换原生的App和Page，不知道在mpx如何去实现呢？

**Comment by sky-admin** [comment]
现在createComponent/createPage内部真正调用的构造器是编译时注入的。
我们可以考虑在createComponent里允许用户传入自定义的构造器，但是这样做以后，跨小程序平台上可能会收到一定影响，阿拉丁的微信、支付宝、百度、QQ应该分开提供的构造器吧？
那你可能需要这样写：
`
const option = {
  
}

**Comment by erguotou520** [comment]
这样做可行，但是这样的特性还没有添加吧？

**Comment by sky-admin** [comment]
嗯，马上添加

**Comment by sky-admin** [comment]
使用方式是通过第二个参数的customCtor传对应的构造器哈，发布后文档也会更新，预计今天发布。

**Comment by sky-admin** [comment]
已发布，2.2.33版本。

**Comment by erguotou520** [comment]
可以全局么？

**Comment by sky-admin** [comment]
不能，难道原生的可以？应该也得每个都引吧？

**Comment by erguotou520** [comment]
全局是为了方便全局配置，如果每个页面都写代码侵入量有点大

**Comment by erguotou520** [comment]
全局是为了方便全局配置，如果每个页面都写代码侵入量有点大

**Comment by erguotou520** [comment]
确认可以生效么？我加入后页面空白了，写法如下
```js
import { createPage } from '@mpxjs/core'
createPage({
  data: {}
}, { customCtor: Page })
```
此Page为小程序的Page，还不是阿拉丁的，这个时候页面就是空白，生命周期什么的也没调用
