### ISSUE TITLE
构建成百度小程序后报错，页面不显示[Bug report]

### ISSUE THREAD

**Issue by vivine** [didi/mpx#303]
**问题描述**
使用单文件.mpx构建页面后，百度小程序报错，且页面不能呈现。

**复现步骤**
请打开附件demo，`npm i` 之后执行构建
另外，附件我增加了.eslintignore文件，如果把此文件最后一行注释掉，构建时候就会eslint报错，但是报错的那个文件 price.filter.js确实没有它所说的错误

**期望的表现**
希望能够显示正常，或者能够反馈一下到底是啥原因造成的。

**截图**
![image](https://user-images.githubusercontent.com/1614610/66632114-5633bb80-ec3a-11e9-9dbf-fbb199a8151a.png)

**系统及环境**
百度小程序开发工具2.9.1
构建环境：
node: v8.11.1 

**附件**
[tp.brand.zip](https://github.com/didi/mpx/files/3716104/tp.brand.zip)

**Comment by sky-admin** [comment]
src/request/md5.js 不应该再走一遍babel，在webpack.conf.js里babel-loader部分exclude一下它或者把它从src里挪出去，到项目下的lib之类的文件夹里。

**Comment by vivine** [comment]
@sky-admin 已经解决，可以关闭了.
