### ISSUE TITLE
局部导出使用MPX开发的页面/组件，整合到已有原生百度小程序中后运行报错[Bug report]

### ISSUE THREAD

**Issue by vivine** [didi/mpx#305]
**问题描述**
局部导出使用MPX开发的页面/组件，整合到已有原生百度小程序中后运行报错

**复现步骤**
1. 官方mpx demo 使用局部导出模式，导出为百度小程序 pages/index 以及 components/list
2. 拷贝 bundle.js 到附件demo里边的更目录，拷贝生成的页面/组件到相关目录
3. 小程序开发工具打开，构建时出错
4. demo见附件

**截图**
![image](https://user-images.githubusercontent.com/1614610/66693402-15d84a00-ecdb-11e9-90b4-280f8334b1f7.png)

**附件**
[swan-demo.zip](https://github.com/didi/mpx/files/3720103/swan-demo.zip)

**Comment by sky-admin** [comment]
2.2.33版本已解决，升级下试试吧，感谢反馈。
