### ISSUE TITLE
[Bug report] 微信与百度样式处理差异

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#306]
**问题描述**
百度小程序下第三方库使用postcss-px-to-viewport与微信下输出不一致

微信下给vant-weapp配置了transRpx编译后产出的文件为rpx
百度下产出的文件为vw，但转vw时postcss.config.js中的配置没有生效，例如保留3位小数

**复现步骤**
```
yarn
yarn watch:cross
```

**期望的表现**
百度与微信一样产出的文件使用rpx

**截图**
![1570850855](https://user-images.githubusercontent.com/22525904/66694203-8edb9f80-ece3-11e9-8f37-e042418dc6f9.jpg)
![1570850878(1)](https://user-images.githubusercontent.com/22525904/66694204-8f743600-ece3-11e9-8f4c-d1bf08a6d6f1.jpg)
![1570850927(1)](https://user-images.githubusercontent.com/22525904/66694205-8f743600-ece3-11e9-9486-2b78a8288413.jpg)
![1570850962(1)](https://user-images.githubusercontent.com/22525904/66694206-8f743600-ece3-11e9-843e-3630ceac9764.jpg)

**系统及环境**
与系统及环境无关

**附件**
[mpx-demo.zip](https://github.com/didi/mpx/files/3720169/mpx-demo.zip)

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/66694447-f72b8080-ece5-11e9-91aa-cb69d8c04ec2.png)

**Comment by sky-admin** [comment]
看起来输出没问题啊？

**Comment by okxiaoliang4** [comment]
emmmm……看来是开发工具显示的时候显示成了vw。不好意思没看输出后的文件
