### ISSUE TITLE
clearInterval没有效果

### ISSUE THREAD

**Issue by namezww** [didi/mpx#309]
![image](https://user-images.githubusercontent.com/33592059/66735712-b8d6c280-ee99-11e9-8eb1-2172fdc0eb8b.png)
![image](https://user-images.githubusercontent.com/33592059/66735746-d60b9100-ee99-11e9-8f2f-24eea831e94f.png)

**Comment by sky-admin** [comment]
clearInterval是接受一个intervalid以停止那个循环，没说会把intervalid给清空啊。

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/66736969-410a9700-ee9d-11e9-9a23-6eee5221394a.png)

**Comment by namezww** [comment]
> clearInterval是接受一个intervalid以停止那个循环，没说会把intervalid给清空啊。

我用定时器写了一个文字跑马灯，每次调用前先清除定时器，但多调用几次，速度越来越快，应该是定时器没有清除掉

**Comment by sky-admin** [comment]
代码发完整一些，你截图这个部分看不出你说的功能

**Comment by namezww** [comment]
> 代码发完整一些，你截图这个部分看不出你说的功能

![image](https://user-images.githubusercontent.com/33592059/66737600-fe49be80-ee9e-11e9-9052-798a82ce3532.png)
每次调用scrollTxt方法前，清除了定时器，但速度还是越来越快

**Comment by sky-admin** [comment]
setInterval的第一个参数是个回调函数，所以this.interval = setInterval(……)会先发生，所以你clear的是新的interval哦，是这个问题吗？
