### ISSUE TITLE
[Bug report] ts类型推导

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#310]
**问题描述**
mapState使用对象传递导致类型推导报错

**复现步骤**
将使用deps的mapState('xx',['xx'])修改为=>mapState({xx: (state)=>state.xx.xx})

**期望的表现**
正常的类型推导

**截图**

![1571120687(1)](https://user-images.githubusercontent.com/22525904/66805423-91462f80-ef57-11e9-9781-87118dbd631b.jpg)
![1571120687](https://user-images.githubusercontent.com/22525904/66805424-92775c80-ef57-11e9-97cd-b2c674dc7414.jpg)

**系统及环境**
无关

**附件**
无

**Comment by httpsxiao** [comment]
提供一个复现的 demo 吧？

**Comment by okxiaoliang4** [comment]
应该是编译器的问题，我把整个代码剪切再粘贴还是存在，后来我加多行包含this的代码再删掉就可以了……谢谢

**Comment by okxiaoliang4** [comment]
![1571281067](https://user-images.githubusercontent.com/22525904/66974231-0f781280-f0cd-11e9-89f0-68f8d1590957.jpg)

![1571281067(1)](https://user-images.githubusercontent.com/22525904/66974228-0e46e580-f0cd-11e9-99de-2686ef5d9c6e.jpg)

运行后正常输出 cityId: -1 但ts类型报错

附件demo：
[mpx-demo.zip](https://github.com/didi/mpx/files/3737228/mpx-demo.zip)

**Comment by httpsxiao** [comment]
@okxiaoliang4
这个问题已经在master里面修复了，发版了之后同步到 issue 里面

**Comment by okxiaoliang4** [comment]
@httpsxiao 好的

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.2.34 已支持
