### ISSUE TITLE
条件编译下引入第三方库打包出错

### ISSUE THREAD

**Issue by wahsggx** [didi/mpx#313]
**问题描述**
在mpx文件中，使用条件编译引入支付宝的第三方组件库，编译后缺少引入组件的axml文件和acss文件

**复现步骤**
如下图
**期望的表现**
使用条件编译引入对应平台的第三方组件，编译正常

**截图**
![image](https://user-images.githubusercontent.com/26195239/66902501-57e2f200-f033-11e9-8f21-e33fe2f09378.png)
![image](https://user-images.githubusercontent.com/26195239/66902509-5adde280-f033-11e9-9b3a-eac1d1482617.png)
![image](https://user-images.githubusercontent.com/26195239/66902478-4d285d00-f033-11e9-888b-313eca6cb9e5.png)

**系统及环境**
"@mpxjs/api-proxy": "^2.2.30",
    "@mpxjs/core": "^2.2.30",
    "@mpxjs/fetch": "^2.2.30",
    "mini-antui": "^0.4.34",

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by sky-admin** [comment]
这个问题产生的原因是由于虽然条件编译可以在不同平台下给引入不同组件，但是引入的组件依然会走跨平台转换，如果已经是某个平台的代码，则需要通过中缀或者mode=的query来标识。
在这种使用第三方组件库的场景下，以上两种模式并不能让用户很好使用，所以我们会允许用户提前标识某个路径下的所有组件均为某个mode的。处理中。

**Comment by hiyuki** [comment]
2.2.34已支持 https://github.com/didi/mpx/releases/tag/v2.2.34
