### ISSUE TITLE
如何跳过app.mpx中iconPath的路径解析编译？

### ISSUE THREAD

**Issue by erguotou520** [didi/mpx#315]
**问题描述**
我想让`app.mpx`中`tabBar.list[index].iconPath|selectedIconPath`跳过图片编译，原因是现在这些tabbar的图片会编译到分包的包里面，所以我希望可以直接使用静态地址（通过CopyPlugin实现的），或者修复编译到分包中的问题。

**复现步骤**
`app.mpx`中主要字段配置示例
```json
"tabBar": {
    "list": [
      {
        "text": "首页",
        "pagePath": "pages/index/index",
        "iconPath": "./res/tabbar/home.png",
        "selectedIconPath": "./res/tabbar/home_selected.png"
      },
      {
        "text": "我的",
        "pagePath": "pages/my/my",
        "iconPath": "./res/tabbar/my.png",
        "selectedIconPath": "./res/tabbar/my_selected.png"
      }
    ]
  },
"pages": [
   "./pages/index/index",
   "./pages/my/my"
 ],
"packages": [
    "./packages/sub1?root=sub1",
    "./packages/sub2?root=sub2",
    "./packages/sub3?root=sub3"
  ]
```
另外代码里还有修改iconPath的代码
```js
import dataIcon from './res/tabbar/data.png'
import dataSelectedIcon from './res/tabbar/data_selected.png'
wx.setTabBarItem({
  index: 2,
  text: '资料',
  iconPath: dataIcon,
  selectedIconPath: dataSelectedIcon
})
```
**期望的表现**
图片统一编译到根目录到`img`目录，现在比较随机，每个分包都有可能会打包出img目录

**截图**
编译后的位置
![image](https://user-images.githubusercontent.com/7945757/67175814-1a4ae400-f3fa-11e9-9fc9-32f598176b9c.png)

**系统及环境**
MacOs

**Comment by hiyuki** [comment]
能否上传一个资源随机出现在分包中的复现demo，跳过的编译的特性下个版本可以支持

**Comment by chaping** [comment]
我也遇到跟 @erguotou520 一样的问题，就是 app.mpx中tabBar配置的iconPath图片资源会打包到分包中，正常的应该打包到主包中才对吧

**Comment by hiyuki** [comment]
2.2.34 已修复

**Comment by erguotou520** [comment]
跳过编译有了么

**Comment by apphost** [comment]
> 跳过编译有了么
请问问题解决了吗?

**Comment by ee07b570** [comment]
> > 跳过编译有了么
> > 请问问题解决了吗?
webpack.cong.js 改成这样就好了
{
        test: /\.(png|jpe?g|gif|svg)$/,
        loader: MpxWebpackPlugin.urlLoader({
          name: 'assets/[name].[ext]'
        })
      }
