### ISSUE TITLE
[Bug report] api-proxy 缺失

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#318]
**问题描述**
百度下 api-proxy 缺少对compressImage的支持，官方是有这个api的

**复现步骤**
引入api-proxy，使用mpx.compressImage

**期望的表现**
正常调用compressImage

**截图**
![image](https://user-images.githubusercontent.com/22525904/67264876-ee555e80-f4de-11e9-8284-02c65659faa7.png)

**系统及环境**
win10

**附件**
无

**Comment by hiyuki** [comment]
新增自定义方法补全、或者采用条件编译处理
