### ISSUE TITLE
小程序原生wxss引用公用的wxss在打包时路径错误

### ISSUE THREAD

**Issue by erguotou520** [didi/mpx#320]
**问题描述**
有2个组件（原生写法）同时引用一个wxss文件，打包时这2个组件的引用文件不存在，在根目录下（如果是分包，则在分包根目录下）。已知2.2.33版本是没有问题的。

**复现步骤**
直接`yarn build`
[share_wxss.zip](https://github.com/didi/mpx/files/3766130/share_wxss.zip)

**期望的表现**
正常打包，路径正确

**截图**
![image](https://user-images.githubusercontent.com/7945757/67461676-77e86600-f670-11e9-8aaf-743f305ee60f.png)
![image](https://user-images.githubusercontent.com/7945757/67461735-a23a2380-f670-11e9-8ec1-f51c04b73fa9.png)

**系统及环境**
MacOS

**Comment by lsycxyj** [comment]
@erguotou520 v2.2.37 还有重现不？

**Comment by erguotou520** [comment]
明天试下

**Comment by erguotou520** [comment]
已修复
