### ISSUE TITLE
通过this.list = data 设置数组数据 然后 Console.log(this.list)输出来的数据不对，why?

### ISSUE THREAD

**Issue by huixu123** [didi/mpx#324]
![image](https://user-images.githubusercontent.com/13418365/67735136-31af5000-fa3e-11e9-97ff-4d56e223a4f2.png)

![image](https://user-images.githubusercontent.com/13418365/67735161-41c72f80-fa3e-11e9-89ce-ed90e2a5b4c0.png)

**Comment by hiyuki** [comment]
mpx运行时的主要能力就是支持数据响应，往this.xxx上赋值的数据都会被转换为响应式数据，这里你赋值了一个数组转换为ObservableArray是符合预期的，你可以按照正常数组一样去调用他的所以活着length或者数组实例的所有api，对你的使用没有影响
