### ISSUE TITLE
[Bug report]&nbsp; 没有输出为空格

### ISSUE THREAD

**Issue by zaxlct** [didi/mpx#327]
**问题描述**
`&nbsp;` 没有输出为空格，还是输出 `&nbsp; `

**复现步骤**
请给出如何复现这个问题的方法，像下面一样分步骤描述清楚
尽可能给出简洁的步骤，如果比较麻烦，或者小demo上较难复现，请准备一个demo作为附件，光标选中最下方的附件拖拽上传一个demo

**期望的表现**
请描述你期望正常情况下应该发生什么？

**截图**
如果可能且方便的话，请附上关于问题的截图

**系统及环境**
如果你猜想或验证过这个问题和设备或环境有关系，请描述你的环境

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by hiyuki** [comment]
这是小程序本身正常的表现，期望输出为空格可以使用text标签包裹并且对text传递decode="true"
https://developers.weixin.qq.com/miniprogram/dev/component/text.html
