### ISSUE TITLE
@mpxjs/mock 怎么用

### ISSUE THREAD

**Issue by lzd358194530** [didi/mpx#328]
@mpxjs/mock  怎么用 需要一个demo  是集成到项目里面 还是 需要开node  服务

**Comment by tangminFE** [comment]
在小程序中引入
import mock from '@mpxjs/mock'
mock([{
  url: 'http://api.example.com',
  rule: {
        'list|1-10': [{
            'id|+1': 1
        }]
    }
}])
rule字段规则同mockjs，支持字符串或正则表达式

**Comment by lzd358194530** [comment]
@tangminFE  直接在app.mpx中引入吗  好像不起作用  启动好了可以直接用浏览器访问接口吗

**Comment by lzd358194530** [comment]
可以了   原来浏览器不能访问 代码里可以 感谢回答

**Comment by tangminFE** [comment]
是在app.mpx中引入，不可以直接用浏览器访问，可以用小程序开发者工具
