### ISSUE TITLE
自定义custom-tab-bar不可用

### ISSUE THREAD

**Issue by clevergod** [didi/mpx#329]
**问题描述**
使用custom-tab-bar

**复现步骤**
app.mpx中json设置自定义tabbar
"tabBar": {
    "custom": true
}
创建目录
src/custom-tab-bar
复制官方文档的demo
发现dist目录里只有一个js文件 src/custom-tab-bar/index.js

改造为src/custom-tab-bar/index.mpx 出现相同的结果

**截图**

![image](https://user-images.githubusercontent.com/21006901/68021943-c683a900-fcdd-11e9-9e46-da2333df435e.png)

**系统及环境**
mpx版本 "version": "2.2.40"

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.2.41 已修复，感谢反馈问题

**Comment by clevergod** [comment]
> https://github.com/didi/mpx/releases/tag/v2.2.41 已修复，感谢反馈问题

请问npm 什么时候可以更新？

**Comment by sky-admin** [comment]
https://www.npmjs.com/package/@mpxjs/webpack-plugin  已经发布2.2.41包了啊

**Comment by clevergod** [comment]
> https://github.com/didi/mpx/releases/tag/v2.2.41 已修复，感谢反馈问题

最新的2.5.1版本 又复现了这个问题

**Comment by hiyuki** [comment]
我这边测试没有复现，请上传复现demo

**Comment by clevergod** [comment]
> 我这边测试没有复现，请上传复现demo

对不起打扰了😿，我自己代码的问题
