### ISSUE TITLE
几率性事件，第一次构建时首页路径会变更

### ISSUE THREAD

**Issue by yangcore** [didi/mpx#33]
发现个问题，有几率  刚启动watch  项目 ，小程序的   首页路径可能会变成别的页面的路径，需要重新 app.mpx 修改保存才好；概率性事件
![image](https://user-images.githubusercontent.com/20217483/50077847-7c5a1c00-0220-11e9-8c99-a2f32c65fcb6.png) 
编译前

![image](https://user-images.githubusercontent.com/20217483/50077859-8419c080-0220-11e9-87f9-249030de8deb.png)

编译后

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v1.0.11
Fixed
