### ISSUE TITLE
在iphone8 plus 机型下 引入wxa-plugin-canvas Poster.js 分包页面 ... 语法报错

### ISSUE THREAD

**Issue by zjjaxx** [didi/mpx#330]
引入wxa-plugin-canvas Poster.js 分包页面 ... 语法报错
demo
https://github.com/zjjaxx/poster-debug.git

**Comment by sky-admin** [comment]
https://github.com/jasondu/wxa-plugin-canvas/blob/master/miniprogram_dist/poster/poster.js#L7
它的dist代码并没有对展开表达式用babel处理，可能是依赖微信开发者本身的es6转es5能力，你勾选开发者工具上的es6转es5试试，或者在babel-loader里include它。

**Comment by sky-admin** [comment]
如果要打开开发者工具里的es6转es5，因为配置文件project.config.json是在根目录每次被copy进去的，需要修改根目录下的配置文件，否则下次run依然不会启用es6转es5

**Comment by zjjaxx** [comment]
打开开发者工具里的es6转es5 还是...报错，请问下怎么在babel-loader里include它。

**Comment by sky-admin** [comment]
webpack.conf.js 第38行起
```js
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/@mpxjs'), resolve('node_modules/wxa-plugin-canvas')],
        exclude: [resolve('node_modules/@mpxjs/webpack-plugin')]
      },
```
如何验证是否OK，可以搜dist/wx下的文件，不再可以搜索出代码里有...

**Comment by zjjaxx** [comment]
可以了，十分感谢
