### ISSUE TITLE
[Bug report]Pug 模板里不能用 <  > && 等符号

### ISSUE THREAD

**Issue by zaxlct** [didi/mpx#331]
**问题描述**
Pug 模板里一旦使用大于或者小于符号就报错
```
<template lang="pug">
  view(wx:if="{{2 > 1}}")
</template>
```

[sm]:215 Uncaught Error: Module build failed (from ./node_modules/@mpxjs/webpack-plugin/lib/template-compiler/index.js):
SyntaxError: Unexpected token ;
**复现步骤**

**期望的表现**
请描述你期望正常情况下应该发生什么？

**截图**
如果可能且方便的话，请附上关于问题的截图

**系统及环境**
```
   Mac OS
    "@mpxjs/core": "^2.2.40",
    "pug": "^2.0.4",
    "pug-plain-loader": "^1.0.0",
```

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by zaxlct** [comment]
刚刚又发现 && 符号也报错。。。
```
view(wx:if="{{2 && 1}}")
```

很常见的需求啊，难道没人用 pug 开发吗

**Comment by zaxlct** [comment]
这么明显的 BUG 没人处理吗？？？弃坑...

**Comment by hiyuki** [comment]
不好意思，最近业务比较繁忙没看到这个issue，今天会发版修复该问题

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.2.43 已修复
