### ISSUE TITLE
[mpx 插件]移植 vue 插件遇到的执行问题求助

### ISSUE THREAD

**Issue by zaxlct** [didi/mpx#332]
**问题描述**
该插件的导出方式在 vue  或者 Mpvue 里正常，但是移植到 mpx 后，`this._route`是 undefined。不知道什么原因
```
export default function install(Vue) {
  const _router = {/**/}

  Vue.mixin({
    onLoad() {
      function parseRoute() {/**/}
      this._route = parseRoute(this)
    },
    onShow() {
      _router.app = this
      _router.currentRoute = this._route
    }
  }, 'page')

  Object.defineProperty(Vue.prototype, '$router', {
    get() { return _router }
  })

  Object.defineProperty(Vue.prototype, '$route', {
    // this._route is undefined
    get() { return this._route }
  })
}
```

**复现步骤**
无

**期望的表现**
请描述你期望正常情况下应该发生什么？

**截图**
如果可能且方便的话，请附上关于问题的截图

**系统及环境**
如果你猜想或验证过这个问题和设备或环境有关系，请描述你的环境

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by sky-admin** [comment]
O__O "…
this._route 是mixin到onLoad里执行获取的吧？这时install方法里的this. _route就是undefined看起来没什么问题？

**Comment by zaxlct** [comment]
@sky-admin 
没错，看起来是没问题。但是...在 mpvue 里是没问题的，这个是 mpvue 的一个插件，我想移植过来，结果....
