### ISSUE TITLE
[Bug report]api-proxy把非function类型属性变成了function

### ISSUE THREAD

**Issue by lsycxyj** [didi/mpx#337]
**问题描述**
api-proxy把非function类型属性变成了function

**复现步骤**
请给出如何复现这个问题的方法，像下面一样分步骤描述清楚
1. 访问mpx.env属性，却获取到了一个function类型的属性

**期望的表现**
获取到mpx下的原来的非function属性

**Comment by hiyuki** [comment]
已修复 https://github.com/didi/mpx/releases/tag/v2.2.44
