### ISSUE TITLE
使用自定义tabbar，使用this.getTabBar方法时，ts报错

### ISSUE THREAD

**Issue by clevergod** [didi/mpx#339]
**问题描述**
使用自定义tabbar，使用this.getTabBar方法时，ts报错：
Property 'getTabBar' does not exist on type 'ComponentIns

**复现步骤**
使用ts，createPage() onShow中调用 this.getTabBar
引用微信官方文档：
如需实现 tab 选中态，要在当前页面下，通过 getTabBar 接口获取组件实例，并调用 setData 更新选中态。
报错提示：
Property 'getTabBar' does not exist on type 'ComponentIns<{ showGradeModal: boolean; }, {}, { courseList(): CardBlock; locationSetted(): boolean; }, { asyncData(): Promise<[void, void]>; switchGradeModal(): void; getSift: () => Promise<void>; getCourses: () => Promise<...>; getADS: () => Promise<...>; }, []>'

目前我添加了// @ts-ignore  忽略了该报错

**Comment by httpsxiao** [comment]
已修复 https://github.com/didi/mpx/releases/tag/v2.2.46
