### ISSUE TITLE
[Bug report]最新版编译出的代码含有解构语法

### ISSUE THREAD

**Issue by yuu2lee4** [didi/mpx#340]
**问题描述**
最新版@mpxjs/core 编译出的代码含有解构语法 { ...obj }，ios11是不支持解构语法的，降级到2.0.x就正常了

**Comment by yuu2lee4** [comment]
哦 原来是在template里有解构语法

**Comment by hiyuki** [comment]
模版中的解构语法目前确实存在问题，可以先不在模版中使用解构规避该问题，后面我们想办法支持上

**Comment by lsycxyj** [comment]
这个是core对`...obj`的解析有问题？

**Comment by hiyuki** [comment]
不是，这个是由于编译时模板渲染函数没走babel的问题，但是由于这部分注入的逻辑的比较特殊，不是太好跑babel
