### ISSUE TITLE
Cannot read property 'createTextNode' of undefined[Bug report]

### ISSUE THREAD

**Issue by a1252822413** [didi/mpx#343]
**问题描述**
在适配pc版本的时候出现的错误：Cannot read property 'createTextNode' of undefined

**复现步骤**
小程序自动编译pc版本，预览的时候直接白屏，然后console报这个错误

**Comment by a1252822413** [comment]
cannot read property  "jsoninfo" of undefine还有这个错误。
出现这两个错误，具体的反应就是小程序只有底部的tab，其他的程序未执行，点击按钮什么的全都没反应

**Comment by a1252822413** [comment]
整理一下，复现步骤；
1.用cli工具随便新建一个项目
2.npm install 
3.打开微信开发者工具，运行项目（不打开微信的es6转es5），此时可以调试运行，也可以手机上运行，pc小程序预览就会出上以上报错。
4.打开微信的es6转es5，再次pc端小程序 调试，此时就正常了，不报错了。

**Comment by sky-admin** [comment]
表现确实和你说的一样，但是PC版小程序的调试能力几乎为零，不知道为什么，暂时解法只能是打开开发者工具的es6转es5，可以在根目录或 static/wx 的project.config.json里配置。模板也会更新为打开微信的es6转es5能力的状态，感谢反馈。
