### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by github1586** [didi/mpx#346]
**问题描述**
![image](https://user-images.githubusercontent.com/24525964/69957372-85312400-153d-11ea-8411-da378e9a0262.png)

![image](https://user-images.githubusercontent.com/24525964/69957393-8eba8c00-153d-11ea-8fda-fcd5ed008924.png)

大佬，用动态组件报错了

**Comment by sky-admin** [comment]
打个zip包直接拖拽到github回复窗里就可以上传了。（打zip前记得删node_modules）

**Comment by github1586** [comment]
[wx-test.zip](https://github.com/didi/mpx/files/3914394/wx-test.zip)

**Comment by github1586** [comment]
@sky-admin

**Comment by sky-admin** [comment]
有编译报错注意一下，json格式的要求很严格，你的src/components/test.mpx的json，多了一个逗号

**Comment by github1586** [comment]
@sky-admin  感谢！！！

**Comment by github1586** [comment]
![image](https://user-images.githubusercontent.com/24525964/70134989-1c27e880-16c4-11ea-890b-9e7d2f800369.png)

**Comment by github1586** [comment]
@sky-admin

**Comment by github1586** [comment]
麻烦大佬 帮忙看一下

**Comment by github1586** [comment]
修改完动态组件的指向组件之后 需要关闭终端 重新编译一次 就不会报错了
