### ISSUE TITLE
修改完动态组件的指向组件之后 需要关闭终端 重新编译一次 

### ISSUE THREAD

**Issue by github1586** [didi/mpx#347]
![image](https://user-images.githubusercontent.com/24525964/70197719-b8df9a00-1747-11ea-81d7-2748ea0af714.png)

- 

修改完动态组件的指向组件之后 需要关闭终端 重新编译一次 就不会报错了

**Comment by hiyuki** [comment]
这是由于小程序开发者工具本身的执行机制带来的限制，在删除组件时确实需要重启一次编译，这个问题框架层面不太好处理
