### ISSUE TITLE
[Bug report] ts error

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#349]
**问题描述**
ts computed类型推导有误

**复现步骤**
```javascript
{
    computed: {
        testData() {
            return [1, 2, 3, 4, 5, 6, 7, 8, 9, 0];
        },
        testData2() {
            // this.testData会认为是个method而不是number[]
            return this.testData.map((num) => num + 1);
        },
    }
}
```

**期望的表现**
this.testData的类型推导应为number[]而不是()=>number[]

**截图**
![image](https://user-images.githubusercontent.com/22525904/70491164-76e59800-1b3b-11ea-86c4-0215d3a62c64.png)

**系统及环境**
@mpxjs/core 2.3.0

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by hiyuki** [comment]
这个是已知问题，此处如果直接推导为computed的返回类型TS会报出类型自引用的报错，mpx中提供了一个辅助方法getComputed绕过这个问题，可以看一下文档示例中有相关描述，https://didi.github.io/mpx/ts.html

**Comment by okxiaoliang4** [comment]
好的谢谢
