### ISSUE TITLE
组件事件绑定  不能写成  bind:click-overlay  中间加  -  的样式，编译报错

### ISSUE THREAD

**Issue by yangcore** [didi/mpx#35]
使用   van-popup 添加事件编译失败
![image](https://user-images.githubusercontent.com/20217483/50141426-6e6ccf80-02e2-11e9-9493-051b851cd24f.png)
![image](https://user-images.githubusercontent.com/20217483/50141451-788ece00-02e2-11e9-863a-062d0d0c16f1.png)

**Comment by hiyuki** [comment]
fixed 2a25dc5f2d6b6b8792a961c84023be942521c3ae
