### ISSUE TITLE
wxss里引用 cdn 的图片资源，能否统一添加 cdn 路径？

### ISSUE THREAD

**Issue by chaucerling** [didi/mpx#359]
``` js
{
  test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
  loader: 'url-loader',
  options: {
    publicPath: 'https://cdn.com/weapp-images/'
  }
}
```
我原来原生的微信小程序项目，wxss里的图片都是使用cdn的资源，然后通过 webpack url-loader 统一配置cdn路径，现在要迁移到mpx，有方法像之前那样统一配置吗

**Comment by sky-admin** [comment]
一样的，build/webpack.conf.js 里 MpxWebpackPlugin.urlLoader里，name下一行写这个就行。

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/71389554-ccd83680-2637-11ea-959c-e6c62de3e679.png)

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/71389571-e0839d00-2637-11ea-841c-458c05c77009.png)
