### ISSUE TITLE
请问怎么支持h5呢? 

### ISSUE THREAD

**Issue by wangzhengbo** [didi/mpx#362]
看到更新日志里面说到可以支持h5了，但是examples里面的build方法都没有增加对h5的支持

**Comment by sky-admin** [comment]
example还未更新产出H5的示例，实际使用的话，脚手架生成项目里选微信、跨平台、需要转H5，就可以使用了。npm run build --web即可

**Comment by hiyuki** [comment]
文档中有，可以查看一下，https://didi.github.io/mpx/platform.html#%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BC%96%E8%AF%91
Example我们之后会补上
