### ISSUE TITLE
wsx 无法使用

### ISSUE THREAD

**Issue by andys0n** [didi/mpx#363]
**问题描述**
使用 wxs 出现问题，不知道是什么原因，能否告诉我一下是为什么吗？

**复现步骤**
1. 简单的拷贝微信官方文档 wxs 代码到自己项目 index.mpx 下；
![Screen Shot 2020-01-03 at 4 27 04 PM](https://user-images.githubusercontent.com/41569161/71713933-c1121e80-2e46-11ea-981f-db0c15f84d7e.png)

2. 自己 index.mpx 下的代码；
<img width="343" alt="Screen Shot 2020-01-03 at 4 28 16 PM" src="https://user-images.githubusercontent.com/41569161/71714038-2fef7780-2e47-11ea-88a3-d92127378000.png">
<img width="214" alt="Screen Shot 2020-01-03 at 4 28 30 PM" src="https://user-images.githubusercontent.com/41569161/71714039-30880e00-2e47-11ea-89dd-6fa12fecdc21.png">

3. 发现微信开发者工具抛出异常；
![Screen Shot 2020-01-03 at 4 29 30 PM](https://user-images.githubusercontent.com/41569161/71714085-5f05e900-2e47-11ea-9c41-a1ce498fe013.png)

感觉是 webpack 打包时候，并没有把 wxs 的代码进行打包处理；
![Screen Shot 2020-01-03 at 4 41 56 PM](https://user-images.githubusercontent.com/41569161/71714232-fd924a00-2e47-11ea-93e6-bb3b53f6ed67.png)
![Screen Shot 2020-01-03 at 4 42 42 PM](https://user-images.githubusercontent.com/41569161/71714266-1ac71880-2e48-11ea-9596-a3e8f6c20379.png)

**Comment by sky-admin** [comment]
写进template里面

**Comment by sky-admin** [comment]
```html
<template>
<wxs>……</wxs>
<view>{{m1.xxx}}</view>
</template>
```
注意wxml文件整个对应template块，mpx文件中没有wxs块
