### ISSUE TITLE
第三方组件库 QQ小程序编译问题

### ISSUE THREAD

**Issue by molimobai** [didi/mpx#364]
**问题描述**
通过编译官方mpx示例项目“useuilib” 项目编译完成
微信小程序项目正常，发现QQ小程序编译完成后打开项目报错现象
检索QQ小程序编译后的组件文件发现，在vant的组件下文件里qml文件出现<wxs src="../wxs/utils.wxs" module="utils"/>引用问题，导致报错

**复现步骤**
编译官方mpx示例项目“useuilib” 使用QQ小程序打开

**发现问题**
示例中使用"vant-weapp": "^0.5.14"组件版本发现存在上面提出问题
更改使用vant UI版本 "@vant/weapp": "^1.0.2"组件版本时可以正常打开编译文件（但是组件样式存在问题，微信小程序中显示正常）然后之后删除文件重新编译又无法打开编译文件，提示qs引用报错，之后就复现不出来可以正常打开编译的那份文件了。=-=
1.是否组件版本问题导致的报错？
2.qs使用是否存在问题？

**Comment by molimobai** [comment]
问题描述中  出现wxs引用报错=》  wxs src="../wxs/utils.wxs" module="utils"

**Comment by sky-admin** [comment]
测试发现无论引哪里的qs都会失败，话说产出的不应该是wxs吧？我这里产出的是.qs文件，路径也是对的，最后发现在qq小程序的开发者工具里关掉新的qml编译核心就可以了

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/71903351-d799dc00-319e-11ea-93f5-010b24cdb16c.png)

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/71903383-e6808e80-319e-11ea-9b75-7a8fe3da3e38.png)
不关掉的话报这个错

**Comment by molimobai** [comment]
好的  试了下qs文件的情况下关闭新的QML编译内核就可以正常输出了。
关于.qs文件 测试了下换了新的项目直接引用组件，编译出来就没出现wxs的引用了，可能之前的模板编译出现了迷之bug吧。
