### ISSUE TITLE
是否可以官方出个路由插件？

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#365]
是否可以官方出个类似vue-router的插件？

**Comment by hiyuki** [comment]
具体场景是什么？小程序的路由系统本身约等于web中的mpa，如果是期望实现spa形式的路由的话由于小程序中并未暴露history相关api技术上也无法实现

**Comment by okxiaoliang4** [comment]
我自己封装了个路由插件，但是总感觉实现方式有点不理想，使用的mixin做的，现在应该可以自己解决，暂时无需了，谢谢
