### ISSUE TITLE
npm run watch失败

### ISSUE THREAD

**Issue by mayingyun** [didi/mpx#369]
**问题描述**
使用npm run watch后，Build complete.生成dist目录里面没有pages目录，src中有添加的pages以及images等文件。运行微信小程序开发工具提示：appJSON["pages"] 需至少存在一项

**截图**
![1578899357724](https://user-images.githubusercontent.com/6906903/72237803-b3af1e00-3616-11ea-91f7-6810ac2249f0.jpg)

**Comment by sky-admin** [comment]
app.mpx里json部分，pages里是否注册了？如果注册了，麻烦打个zip包扔上来吧。

**Comment by mayingyun** [comment]
我检查了app.mpx，是有注册的，我记得之前打开vscode是编译成功过的，login页面运行显示过，之后就关掉了，今天打开再run watch就没有了。
[training_test.zip](https://github.com/didi/mpx/files/4052451/training_test.zip)

**Comment by sky-admin** [comment]
稍等

**Comment by sky-admin** [comment]
奇怪，你改过什么构建脚本吗？要不就是命中了曾经一个错误的模板。应该是删掉build/webpack.conf.js，26行起的mpx-loader部分就好，这个loader现在改为在build.js里设置了，等于你这里设了两个mpx-loader

**Comment by mayingyun** [comment]
是的，删除mpx-loader部分后，编译就成功了，之前是参考mpx文档中关于transRpx部分，针对微信小程序使用use rpx设置，文档中此部分设置还在webpack.config.js文件中。刚查了build.js，里面有关于rpx的设置了。谢谢。

**Comment by sky-admin** [comment]
好的，明白了，我去改下文档
