### ISSUE TITLE
首次执行错误问题：Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by mpxxcx** [didi/mpx#371]
我把dist删除 重新 npm run wacht 后  进入小程序  会出现这个问题说  试图对不可迭代实例进行结构破坏的尝试无效   当我多点几个页面后 这个错误又没了
[src.zip](https://github.com/didi/mpx/files/4069827/src.zip)

![image](https://user-images.githubusercontent.com/59951425/72502732-f66e3180-3874-11ea-9c71-bb3882108b51.png)

**Comment by sky-admin** [comment]
多点几个页面是什么意思？出这个错的时候还能渲染出东西吗？

**Comment by sky-admin** [comment]
我这里无法复现，建议试试不要删掉dist文件夹，如果你开发者工具打开的是dist，删dist/* ，如果开发者工具打开的是dist/wx，删dist/wx/* 。这样是不是就不会出这种问题呢？

**Comment by mpxxcx** [comment]
> 多点几个页面是什么意思？出这个错的时候还能渲染出东西吗？

页面东西都是能正常渲染出来的  就是跳转时就出现这个错误  没有任何影响   当刷新后这个错误就没有了   重新删除dist   npm run watch 后  首次进入小程序 这个就会复现

**Comment by sky-admin** [comment]
平台是Windows还是Mac呢？
