### ISSUE TITLE
[Bug report]版本升级问题

### ISSUE THREAD

**Issue by mayingyun** [didi/mpx#377]
**问题描述**
我使用npm安装脚手架命令安装，显示mpx版本2.1，github发布的版本都到2.4了，我用的npm镜像是淘宝的，不清楚哪里出问题了？是我哪里理解的不对？

**截图**
![image](https://user-images.githubusercontent.com/6906903/74329799-71baf880-4dcb-11ea-9e27-9b79fdb0be25.png)

**Comment by sky-admin** [comment]
mpx版本一般是指@mpxjs/core 和 @mpxjs/webpack-plugin 的版本，你说的2.1应该是脚手架版本，脚手架只是个cli工具用于生成项目的，2.1已经是脚手架的最新版本了。
看mpx的版本应该是看项目里package.json 或 package-lock.json里的版本（因为package.json里我们指定的是带^的版本号，不一定能准确反映实际安装的版本）。

**Comment by sky-admin** [comment]
再补充解释一下……三个包：
cli工具 @mpxjs/cli 最新版就是2.1了
运行时核心 @mpxjs/core 最新版现在应该是2.4.6
编译核心 @mpxjs/webpack-plugin 最新现在应该是2.4.7
其中cli工具只是个脚手架，生成项目用的，不重要哈。运行时核心和编译核心才是最重要的。

**Comment by mayingyun** [comment]
受教了，谢谢。
