### ISSUE TITLE
改进：在写小程序分包时，编译后页面使用到的组件引用路径优化

### ISSUE THREAD

**Issue by Venus-WXP** [didi/mpx#379]
**问题描述**
我司现有原生语法写的微信小程序，近期需要升级新增页面，由于大小限制，我便使用了分包机制，我正在使用mpx写小程序的几个新加页面，并且将其编译文件生成的目录由原来的dist改到了另外一个小程序的分包路径下了，按照mpx的单文件形式进行了编译处理，生成的页面所引用的组件路径都是以 / 开头的（例如：/components/chat5bda63f4/lib/iview/input/index），但实际呢该组件存在的路径是 /我的分包名/components/chat5bda63f4/lib/iview/input/index 这样，我就要手动将分包下生成的components目录复制到 根路径下 或者 将生成的页面的包引用路径 手动更改为合适的位置；这样问题就来了，现有的小程序空间已经无法装下那些生成组件了，必须放到子包路径下，所以，第一种方法不可行，那么第二种方法，我就要不断的修改生成页面的组件引用路径，源码每次修改自动编译后都会重置，这显然是不现实的，希望大佬们可以增加配置项，将生成页面的组件引用路径可以改为相对路径的形式，这样，我在子包里使用框架生成的页面就毫无问题了。

**Comment by sky-admin** [comment]
为什么关闭了？是找到解决方案了吗？直接产出分包应该可解吧？

**Comment by Venus-WXP** [comment]
> 为什么关闭了？是找到解决方案了吗？直接产出分包应该可解吧？

直接产分包吧，但是产的分包会把 wxs 文件 和 一个 bundle文件产到主小程序包中，也就是最外层，虽然不完美，但不追究了，主要我这里赶时间，没时间折腾了

**Comment by hiyuki** [comment]
先open吧，留档记录，之后框架会进行相对路径输出支持
