### ISSUE TITLE
[Bug report] eharts无法编译

### ISSUE THREAD

**Issue by HARDCOREAJ** [didi/mpx#380]
**问题描述**
在项目里引入了eharts, npm run watch执行编译命令非常慢,而且无法解析正确的路径

**复现步骤**
1. 根据echarts-for-wexin的要求将组件引入项目
2.在自己的component里引入
3.编译非常慢,最终提示无法解析目标路径

**期望的表现**
应该和正常的小程序项目一样不会出现编译很慢和路径问题

**截图**
![image](https://user-images.githubusercontent.com/40049420/74703679-e5845780-5248-11ea-8460-041d70fb883d.png)

**系统及环境**
node - 12.13.0
npm - 6.12.0

**附件**
光标选中这里并拖拽demo到此上传到github
[mini_program.zip](https://github.com/didi/mpx/files/4217309/mini_program.zip)

**Comment by sky-admin** [comment]
这个找不到模块应该是你截图这个的js域里引入echarts时候报出来的，你引的时候没写.min.js，resolve会尝试找.js的文件，但是那个文件是.min.js，以及这个文件是构建好了的，所以要么不要放在src里，要么在webpack.conf.js里exclude掉。

**Comment by sky-admin** [comment]
友情提示~最好是重新准备个demo，不然这不是开源了嘛。当心别人剽窃你的劳动成果。
以及我不知道为什么，我这里装完跑起来会有很多lint错误及vant-weapp缺失组件，不知道你的lock文件是否正确？还是你本地确实也有这些问题？

**Comment by HARDCOREAJ** [comment]
> 友情提示~最好是重新准备个demo，不然这不是开源了嘛。当心别人剽窃你的劳动成果。
> 以及我不知道为什么，我这里装完跑起来会有很多lint错误及vant-weapp缺失组件，不知道你的lock文件是否正确？还是你本地确实也有这些问题？

lock文件是正确的,可能我用了yarn按照依赖，但是它建议是npm安装
谢谢大哥提醒, 项目里的lint错误我直接忽略了，vant-weapp缺失组件是因为我直接把node_modules里面的vant-weapp文件夹替换成最新版了(麻烦帮我看下)。
[vant-weapp.zip](https://github.com/didi/mpx/files/4217405/vant-weapp.zip)

**Comment by HARDCOREAJ** [comment]
> 这个找不到模块应该是你截图这个的js域里引入echarts时候报出来的，你引的时候没写.min.js，resolve会尝试找.js的文件，但是那个文件是.min.js，以及这个文件是构建好了的，所以要么不要放在src里，要么在webpack.conf.js里exclude掉。

老哥,我为了减少体积下了官方的定制包，所以我一开始就加上min.js了。
![image](https://user-images.githubusercontent.com/40049420/74705756-f5ec0080-524f-11ea-95d2-cf61c2b0390d.png)

如果我不放在src里面,那么它就会解析不到路径的。

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/74705945-80346480-5250-11ea-89a3-2e06259b7729.png)

**Comment by HARDCOREAJ** [comment]
谢谢提醒，看到了. 很惭愧.... 

请问编译慢问题如何解决呢,10分钟了还没编译出来?(如果我不把这个ec-canvas文件放到src里面)，编译时就无法解析到路径了)
![image](https://user-images.githubusercontent.com/40049420/74706690-993e1500-5252-11ea-9a38-6bef39c970f3.png)

**Comment by sky-admin** [comment]
[mini_program.zip](https://github.com/didi/mpx/files/4217485/mini_program.zip)

**Comment by sky-admin** [comment]
主要修改了，webpack.conf.js里，babel-loader的exclude规则，注释掉了eslint，加了alias来让vant-weapp映射成@vant/weapp

**Comment by HARDCOREAJ** [comment]
> 主要修改了，webpack.conf.js里，babel-loader的exclude规则，注释掉了eslint，加了alias来让vant-weapp映射成@vant/weapp

老哥,非常感谢！建议官网文档可以把这个信息加上去,可能很多像我一样的菜鸟不熟悉webpack导致遇到问题不知道如何解决。
