### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by Czj-W** [didi/mpx#382]
**问题描述**
做了一个时间选择器（picker-view组件）
因为ObservableArray的影响导致是无法定位到当前时间，而是显示1990年1月1日

**期望的表现**
可以定位到当前时间如2020年2月19日

**Comment by hiyuki** [comment]
请提供一个复现demo

**Comment by Czj-W** [comment]
bug描述：
无法定位到当前时间 如图

理想状态：
如图

本人通过测试发现，关键在于years months days这三个赋值过程出问题
麻烦大佬检查检查原因

**Comment by hiyuki** [comment]
图我也看不到，能否按照bug-report提示的编写个复现的demo项目，将项目中的node_modules删除后打包拖拽到该issuer中来，便于我们复现排查问题

**Comment by Czj-W** [comment]
不好意思，已重新上传到issuer，请留意，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dong Hongping"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 下午5:10
收件人:&nbsp;"didi/mpx"<mpx@noreply.github.com&gt;;
抄送:&nbsp;"陈梓健"<277171229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/mpx] [Bug report] (#382)




图我也看不到，能否按照bug-report提示的编写个复现的demo项目，将项目中的node_modules删除后打包拖拽到该issuer中来，便于我们复现排查问题

**Comment by sky-admin** [comment]
#383 重新更详细描述了此问题，此issue关闭
