### ISSUE TITLE
picker-view组件没有按照指定条件来显示

### ISSUE THREAD

**Issue by Czj-W** [didi/mpx#383]
**问题描述**
我用过picker-view创建一个时间选择器，
打开时间选择器应显示 2020年 2月 20日
目前显示却是 1990年 1月 1 日
通过value（一个数组，如[0,0,0]）来控制年(years)月(months)日(days)的显示，但在开发过程中发现value不能控制年月日，通过自检发现问题出在赋值的过程，如this.years=xxx this.months=xxx this.days=xxx

**复现步骤**
npm i
启动小程序
npm run watch
打开demo页面即可
[mpx-demo.zip](https://github.com/didi/mpx/files/4229845/mpx-demo.zip)

**期望的表现**
打开picker-view组件即可显示当前时间，如 2020年 2月 20日

**截图**
如果可能且方便的话，请附上关于问题的截图

![bug-img](https://user-images.githubusercontent.com/46423633/74920508-3cd02680-5407-11ea-97f2-25faf647f6d0.png)

**系统及环境**
系统：windows

**Comment by sky-admin** [comment]
首先数据的赋值应该是没问题的，你可以新加个view把数据展示出来看看。

然后你的问题，参考下官方的例子，years/month/day/values应该提前准备好，就可以生效。
