### ISSUE TITLE
[Bug report] 转web时，swiper组件纵向滚动有问题

### ISSUE THREAD

**Issue by llccing** [didi/mpx#384]
**问题描述**
转web时，swiper组件纵向滚动有问题

**复现步骤**
[demo](https://github.com/llccing-demo/mpx-demo)

**期望的表现**
纵向滚动能够正常

**截图**
如果可能且方便的话，请附上关于问题的截图

**系统及环境**
无关

**附件**
无

**Comment by hiyuki** [comment]
已知问题，原因是由于输出web中的swiper实现依赖于兄弟团队的better-scroll开源滚动库的slider插件，该插件在垂直滚动初始化时存在一定问题，目前已经与该插件作者沟通待对方修复发版后即可正常使用，届时我再关闭这个issue

**Comment by hiyuki** [comment]
已更新依赖修复，将@mpxjs/webpack-plugin升级至2.4.10即可正常使用
https://github.com/didi/mpx/releases/tag/v2.4.10
