### ISSUE TITLE
[Bug report] qq 小程序 editor 组件使用失败

### ISSUE THREAD

**Issue by programmerwy** [didi/mpx#386]
**问题描述**
代码是基于 wx 小程序的，其中使用了 < editor > 组件，编译成 qq 小程序的时候，提示编译错误：[template compiler][.../src/pagesub/edit/index.mpx]: <editor> is not supported in qq environment
注：实际上 qq 上已经可以使用 editor 组件了

**复现步骤**

1. 页面中引用 < editor > 组件
2. npm run watch --qq
3. 看到错误

**系统及环境**
macOS 10.14.6
shell 环境编译

**Comment by sky-admin** [comment]
好的，我确认下，OK的话我尽快修改一下规则修复这个问题。多谢反馈。

**Comment by sky-admin** [comment]
QQ小程序的文档里没有editor，不过我试了下是可以使用的，但是两者是否能完全等价呢？比如editorContext是否存在且可用？我尝试失败了，如果确实可以对应使用，辛苦提供一个demo我看下？或者不能完全对应的情况下仍希望使用，可以考虑看下条件编译一节：https://didi.github.io/mpx/platform.html#%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BC%96%E8%AF%91

**Comment by programmerwy** [comment]
`editorContext ` 这个是可用的，代码放到最后面了，你说的仍然希望使用的方法，我看过编译的那章，好像没有提到可以自己加配置，有没有可以强行通过，或者开发插件的方式提供出来，我自己搞下也行

我现在写的小程序测试可用，功能都有，类似下面的方式就可以
```javascript
this.createSelectorQuery().select('#editor').context((res) => {
    this.editorCtx = res.context;
    this.triggerEvent('onEditorCreate', this.editorCtx);
    this.onToolbarHeightChange(this.editorCtx);
}).exec();
```
我看下你提供的

**Comment by programmerwy** [comment]
有没有编译白名单啥的

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/75678451-a0d8d180-5cc8-11ea-9aec-9642bf530bd8.png)
如图，在模板上写mode=xx平台，这部分代码在跨平台编译时就默认使用，不走转换。

**Comment by sky-admin** [comment]
编译白名单也有 https://didi.github.io/mpx/compilationEnhance/#mpxjswebpack-plugin 参考这个部分的 modeRules

**Comment by sky-admin** [comment]
但是很奇怪，这个editor在我这里工作得时好时坏，我check下我的开发者工具版本看看

**Comment by sky-admin** [comment]
升级到最新的稳定版仍不行，1是刷新后editor点击无反应，2是context里能看到insertText方法，但是是在 context.action.method里，但是真的调用时会报action是undefined。

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/75679884-6c1a4980-5ccb-11ea-8338-5aa884d04bcd.png)

**Comment by sky-admin** [comment]
修改文件后编译，第一次还能点选激活editor并输入内容，这时再刷新一次就会报这个warning：
![image](https://user-images.githubusercontent.com/6292668/75680070-b56a9900-5ccb-11ea-87ad-c223db4763f9.png)

**Comment by sky-admin** [comment]
先看看条件编译或编译白名单能否解决你的问题吧？

**Comment by programmerwy** [comment]
> 升级到最新的稳定版仍不行，1是刷新后editor点击无反应，2是context里能看到insertText方法，但是是在 context.action.method里，但是真的调用时会报action是undefined。

不行留个联系方式吧，我之前调试 editor 的时候也有遇到类似问题，应该是跟调用时序啥的有关系，比如 editor 还没有 ready 之类的，解决后就比较稳定

**Comment by programmerwy** [comment]
> 先看看条件编译或编译白名单能否解决你的问题吧？

我先看下你说的编译这里能不能绕过去看看，辛苦了

**Comment by programmerwy** [comment]
> 修改文件后编译，第一次还能点选激活editor并输入内容，这时再刷新一次就会报这个warning：
> ![image](https://user-images.githubusercontent.com/6292668/75680070-b56a9900-5ccb-11ea-87ad-c223db4763f9.png)

你贴的图我都看不到😂

**Comment by sky-admin** [comment]
> > 升级到最新的稳定版仍不行，1是刷新后editor点击无反应，2是context里能看到insertText方法，但是是在 context.action.method里，但是真的调用时会报action是undefined。
> 
> 不行留个联系方式吧，我之前调试 editor 的时候也有遇到类似问题，应该是跟调用时序啥的有关系，比如 editor 还没有 ready 之类的，解决后就比较稳定

联系的话进QQ群就行

**Comment by sky-admin** [comment]
条件编译是否可以解决？
这个问题是否还有后续？
没问题的话此issue先关闭了，有问题的话请再打开继续。

**Comment by programmerwy** [comment]
我用 mode = qq 的还是不行，编译还是会提示有问题
![image](https://user-images.githubusercontent.com/24842116/76165684-dfbcca80-6193-11ea-8d47-61a3119ee135.png)
![image](https://user-images.githubusercontent.com/24842116/76165688-f19e6d80-6193-11ea-8310-9870e4821728.png)

**Comment by sky-admin** [comment]
[mpxqqdemo.zip](https://github.com/didi/mpx/files/4307060/mpxqqdemo.zip)

**Comment by sky-admin** [comment]
试试这个demo？npm i && npm run build --qq 不会报错

**Comment by programmerwy** [comment]
demo 没问题，我的也恢复了，不过和组件有关系，你看下有没有必要处理一下，我在 components 里面写好后，在 page 里面引用，类似这样：`<template><editor /></template>`，这里的 editor 其实是个自定义组件名，但是被识别成了原生组件，所以编译报错，如果我改成类似`<template><editor-comp /></template>` 就可以了，然后真正使用原生组件的地方用 mode="qq"
```javascript
"usingComponents": {
      "editor": "./components/editor/editor",
      "submit": "./components/submit"
}
```

**Comment by programmerwy** [comment]
非常感谢，问题已经解决

**Comment by programmerwy** [comment]
但是用 mode=qq 会导致不编译 wx 好像。。我其实希望 wx 和 qq 都可以用

**Comment by sky-admin** [comment]
不支持也不鼓励自定义组件注册得和原生组件名一致，建议加个前缀。wx/qq都能用也很简单，就是再写一份mode=wx的，npm run build --wx --qq就可以两者都OK都正常。对你可以把它封装成一个基础组件，但不建议名字伪装得和原生组件一样

**Comment by programmerwy** [comment]
好




| |
王岩
|
|
邮箱：programmerwy@163.com
|

签名由 网易邮箱大师 定制

在2020年03月10日 10:54，Huanyu Li 写道：

不支持也不鼓励自定义组件注册得和原生组件名一致，建议加个前缀。wx/qq都能用也很简单，就是再写一份mode=wx的，npm run build --wx --qq就可以两者都OK都正常。对你可以把它封装成一个基础组件，但不建议名字伪装得和原生组件一样
