### ISSUE TITLE
[实际难点] 项目里引进了canvas, 如何优化体积并合理分包？

### ISSUE THREAD

**Issue by HARDCOREAJ** [didi/mpx#388]
**问题描述**
老哥,请问下。因为项目要用到echarts图表,  然后打包出来的ec-canvas达到了729kb。由于我的项目目前有两个模块依赖于它(首页，个人信息), 我是不是要把这两个模块当作主包，其余的模块当作分包？

**复现步骤**
请给出如何复现这个问题的方法，像下面一样分步骤描述清楚
尽可能给出简洁的步骤，如果比较麻烦，或者小demo上较难复现，请准备一个demo作为附件，光标选中最下方的附件拖拽上传一个demo

**期望的表现**
请描述你期望正常情况下应该发生什么？

**截图**
如果可能且方便的话，请附上关于问题的截图

**系统及环境**
如果你猜想或验证过这个问题和设备或环境有关系，请描述你的环境

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by HARDCOREAJ** [comment]
如果单纯的使用小程序的分包,项目会不会有bug？

**Comment by hiyuki** [comment]
单纯使用分包不会遇到bug，可以放心使用，资源的话Mpx本身会按照一个最优的方式进行输出，一般来讲也不用关心
