### ISSUE TITLE
不支持useExtendedLib

### ISSUE THREAD

**Issue by YXL76** [didi/mpx#389]
**问题描述**
在useExtendedLib启用weui后，页面引入相关组件因为找不到路径报错。

**复现步骤**
```json
"usingComponents": {
  "mp-form-page": "weui-miniprogram/form-page/form-page",
  "mp-form": "weui-miniprogram/form/form"
}
```

**期望的表现**
希望能够正确处理开启`useExtendedLib`的情况。

**Comment by hiyuki** [comment]
ok，近期会处理支持

**Comment by hiyuki** [comment]
已支持相关配置，https://github.com/didi/mpx/releases/tag/v2.5.4
