### ISSUE TITLE
[Bug report] wxml 使用 import ，无法解析

### ISSUE THREAD

**Issue by NineSwordsMonster** [didi/mpx#391]
**问题描述**
vant 1.0.7 的wxml 使用了import 引入，mpx的webpack插件无法解析

**复现步骤**
1. 升级vant 到 1.0.7
2. mpx 编译报错

**期望的表现**
正常编译

**截图**
![image](https://user-images.githubusercontent.com/10054584/76139814-f75e5b00-608e-11ea-92e1-06b96ac3eec0.png)

**系统及环境**
无关

**附件**
![7F5A22DBA35B921A6C6FFCF503C1D705](https://user-images.githubusercontent.com/10054584/76139819-06dda400-608f-11ea-8f77-1c63f6b784e4.jpg)
![CC81042C97DCD5F23FFF1C1B0A87CEC9](https://user-images.githubusercontent.com/10054584/76139820-093ffe00-608f-11ea-8159-c0002c1d0a8d.jpg)

**Comment by hiyuki** [comment]
在webpack config的resolve.extensions中添加上'.wxml'即可正常解析
