### ISSUE TITLE
[Bug report]mpx模板里边使用wx:class和wx:style时，编译成百度swan时，百度小程序开发工具打开页面无法渲染

### ISSUE THREAD

**Issue by vivine** [didi/mpx#396]
**问题描述**
当在.mpx文件的template里边使用wx:class或者wx:style，编译成小程序后，swan（百度）会生成一个filter/stringify[hash].filter.js，导致百度小程序无法渲染

初步排查了一下，是因为 mpxjs/webpack-plugin 构建的时候，生成的stringify[hash].filter.js是基于commonjs模块的写法，而在百度小程序里边，filter必须是ES6模块的写法，也就是filter里边必须是export default {} 这样的写法才行，大概几个版前，mpx生成的filter叫做injectHelper[hash].filter.js，那个时候还是正确的，没有这个错误，现在改成stringify[hash].filter.js之后才出现了这个错误。

**复现步骤**
1. 新建一个页面，模板里边使用wx:style或者wx:class
2. npm run watch --swan
3. 打开百度小程序开发者工具，导入dist/swan
4. 打开后是空白页面，bug重现

**期望的表现**
期望能正确渲染

**截图**
![image](http://up.fd.zol-img.com.cn/g2/M00/0D/0D/ChMlWV5t8N2IGNLQAAPx5PhlsyYAANsoQAIGnMAA_H8202.jpg)

**系统及环境**

百度开发者工具

"@mpxjs/webpack-plugin": "^2.4.1"

**Comment by hiyuki** [comment]
2.4.16已修复
https://github.com/didi/mpx/releases/tag/v2.4.16

**Comment by vivine** [comment]
@hiyuki 请问npm更新了吗
