### ISSUE TITLE
希望增加alias支持

### ISSUE THREAD

**Issue by idenet** [didi/mpx#40]
```
  {
    "usingComponents": {
      "list": "../components/list",
      "xx-button": "../../node_modules/xx-weapp/button/index"
    }
  }
```
如此引入非常不方便

**Comment by cougarwww** [comment]
node modules下的直接引入就行了
        "usingComponents": {
            "van-tab": "vant-weapp/dist/tab",
            "van-tabs": "vant-weapp/dist/tabs"
}

**Comment by hiyuki** [comment]
直接写模块路径就可以了，另外alias也是支持的哦，直接在webpack中配置alias就可以在usingComponents中写了
