### ISSUE TITLE
微信原生写的小程序转成mpx框架报错及多平台输出为空的错误

### ISSUE THREAD

**Issue by shanegaoxp** [didi/mpx#403]
**问题描述**
微信原生写的小程序转成mpx框架报错及多平台输出错误，
**复现步骤**
1. 先用MPX脚手架，把以前用微信原生写的小程序代码，放到src相应位置，合并了入口app.mpx文件。
2. 由于原生微信小程序用了分包加载方案，所以手动将mpx.plugin.conf.js文件配置修改：resolveMode: 'native',  projectRoot: path.resolve(__dirname, '../src'),

app.json 部分配置：
![image](https://user-images.githubusercontent.com/54571703/76816646-b22eeb80-683b-11ea-8456-08cc8c1b9b27.png)

mpx.plugin.conf.js文件部分配置
![image](https://user-images.githubusercontent.com/54571703/76816670-c672e880-683b-11ea-9318-8d49c342543a.png)

3.原生方案自己封装了promisify方法，因为MPX 提供了 @mpxjs/api-proxy，就在原来写的每个引用promise方法的js文件头部引入@mpxjs/api-proxy，并替换（注释）了自己写的promise，但没有做其他修改（比如没有按照mpx的方式合并成单文件）
step1）文件头部引用如下：
 import mpx from '@mpxjs/core'
  import apiProxy from '@mpxjs/api-proxy'
  mpx.use(apiProxy, { usePromise: true })
  const request = mpx.request
![image](https://user-images.githubusercontent.com/54571703/76816715-e9050180-683b-11ea-990d-7a2071553382.png)

step2）使用request方法
request({
                url: url,
                method: 'GET',
                header:{
                    'content-type': 'json'
                }
![image](https://user-images.githubusercontent.com/54571703/76816753-0b971a80-683c-11ea-8cff-cb3939a4bab4.png)

4.没有使用 import { createPage } from '@mpxjs/core'  和 import { createComponent } from '@mpxjs/core'的方案，入口app.mpx文件 js代码写在 App({})中，各页面js文件的 代码写在Page({})中，原生代码基本没有变化，除了上面提到的promise方法的变化，而且代码中除了应用mpx.方法（比如mpx.request（赋值给request）），还用了wx.的方法（比如wx.getSystemInfo(） ，不知道有没有冲突。
![image](https://user-images.githubusercontent.com/54571703/76816845-426d3080-683c-11ea-808b-2767d9d40b9e.png)

5.原生js文件引用模块，写的是require方式，在应用mpx后很多报错，就改成了import 的方式，报错消失，下面是修改后的例子：

import { openFindFriend as _openFindFriend, openFeedPublish, openFeedDetail } from '../../../common/helpers/routeHelper.js'
import { isEmpty as _isEmpty } from '../../../common/helpers/stringHelper.js'
import { getFeedListAdId } from '../../../common/helpers/adHelper.js'
import { feedListFilter } from '../../../common/helpers/responseDataHelper.js'
![image](https://user-images.githubusercontent.com/54571703/76816922-76e0ec80-683c-11ea-8173-7317bad1a055.png)

**核心问题1**6.脚手架配置时选择了多平台方式，运行 npm run watch ，用微信编辑器预览，但微信编辑器报错如下（bundle.js:14062 Uncaught TypeError: (0 , _js.getEnvObj) is not a function），其中bundle.js 中的 getEnvObj 方法并非我们写的，应该是mpx框架提供的，不知道如何查错，报错如下：
_bundle.js:14062 Uncaught TypeError: (0 , _js.getEnvObj) is not a function_
    at Object.<anonymous> (bundle.js:14062)
    at __webpack_require__ (bundle.js:85)
    at Object.<anonymous> (bundle.js:13692)
    at __webpack_require__ (bundle.js:85)
    at Object.<anonymous> (bundle.js:13591)
    at __webpack_require__ (bundle.js:85)
    at Object._ (app.js? [sm]:63)
    at __webpack_require__ (bundle.js:85)
    at Module.<anonymous> (app.js? [sm]:16)
    at Module._ (app.js? [sm]:31)
![image](https://user-images.githubusercontent.com/54571703/76813839-2796be00-6834-11ea-98cf-b3c1a5a8e9f3.png)

**核心问题2**7.用build:cross 或者prod:cross 运行时，并没有生成多平台的dist文件，dist下只有 WX空文件夹，build:cross报错如下（prod:cross 相似）：
 Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qzone_demo_mpx@1.0.0 build: `node ./build/build.js -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qzone_demo_mpx@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2020-03-17T02_25_00_000Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qzone_demo_mpx@1.0.0 build:cross: `npm run build --wx --ali --swan --web`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qzone_demo_mpx@1.0.0 build:cross script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2020-03-17T02_25_00_027Z-debug.log
PS D:\practice\qzone_mpx_demo>
![image](https://user-images.githubusercontent.com/54571703/76816024-1cdf2780-683a-11ea-8902-ced7c917776b.png)

**系统及环境**
win 10 64位，vscode 和微信原生编辑器

**Comment by sky-admin** [comment]
已通过IM进一步沟通问题及辅助调试。
背景是现有原生项目接入Mpx，因原有代码不是很符合Mpx工程化规范，用户有自行努力解决但遇到了一些问题。
主要问题包括babel配了一个多余的plugin，ESmodule的导入导出使用存在问题。

此issue先关闭了，还有问题再沟通。

PS：此外这种问题还可以通过整个关闭mpx的babel来解决，Mpx方案是完全支持原生小程序的commonjs导入导出规范的，但是不利于后续开发，建议还是像该提问者一样修改以匹配Mpx更优。
