### ISSUE TITLE
qq编译问题 open-type不能为空

### ISSUE THREAD

**Issue by yc0524** [didi/mpx#404]
`<button
     open-type="{{ cardLogin ? 'getUserInfo' : '' }}"
     bindgetuserinfo="onGetUserInfo"
     bindtap="onNextStep"
  >
       按钮
  </button>`
**qq版本无法编译open-type为空，微信版本可以**

**Comment by yc0524** [comment]
![image](https://user-images.githubusercontent.com/33405012/77143533-79527900-6abe-11ea-8323-4377e05b636d.png)

**Comment by yc0524** [comment]
![image](https://user-images.githubusercontent.com/33405012/77143553-85d6d180-6abe-11ea-8de4-6492925fe574.png)

**Comment by sky-admin** [comment]
好的，我们处理下，感谢反馈

**Comment by sky-admin** [comment]
这个部分不是为空的问题，而是之前担心动态的open-type不支持，核对发现微信QQ已完全一样。
所以已干掉对QQ的报错，下个版本生效。
