### ISSUE TITLE
QQ小程序数据绑定问题

### ISSUE THREAD

**Issue by yc0524** [didi/mpx#405]
```<template>
  <list></list>
</template>

<script>
  import { createPage } from '@mpxjs/core'

  createPage({
    data: {
      isGood: false,
      isStr: ''
    },
    onLoad () {
      console.log('onload')
      this.isGood = true
      this.isStr = 'SSS'
    }
  })
</script>

<script type="application/json">
  {
    "usingComponents": {
      "list": "../components/list"
    }
  }
</script>
```
**编译qq data的值无变化，数据绑定没成功   切换到0.1.26版本和最新版本开发工具都无效 麻烦帮看看**

**Comment by yc0524** [comment]
![image](https://user-images.githubusercontent.com/33405012/77162261-85eac780-6ae6-11ea-8d6e-ecdea2589d9d.png)

**Comment by sky-admin** [comment]
是通过开发者工具观察data里的值是否改变这样吗？
Mpx这边会收集模板上用到的数据，模板上没有使用的话，是不会真实setData发送数据过去的。
你这个例子里，好像模板上未用到。你在js里获取变化是没问题的。可以watch试试，只是不会发送到模板层

**Comment by yc0524** [comment]
![image](https://user-images.githubusercontent.com/33405012/77162406-d8c47f00-6ae6-11ea-9c72-bb27544422f0.png)

**Comment by yc0524** [comment]
好的 我再看看  确实是可以的

**Comment by sky-admin** [comment]
嗯嗯，这是一个Mpx的优化，你未在模板中使用的数据，发送到模板层是一个性能浪费。

**Comment by yc0524** [comment]
```<template>
  <view>
    <view wx:if="{{show}}">abc</view>
  </view>
</template>

<script>
  import { createPage } from '@mpxjs/core'

  createPage({
    data: {
      show: false
    },
    onLoad () {
      this.show = true
    }
  })
</script>

<script type="application/json">
  {
    "usingComponents": {
      "list": "../components/list"
    }
  }
</script>
```
这种写法也不行  show只是用来控制显示隐藏  也算是在模板中使用了吧  但是不生效(AppData 监测到值改变了 页面没渲染)

**Comment by sky-admin** [comment]
是的，这种算在模板中使用了，你在AppData中都能看到改变，确定没渲染？？我这里试是可以的啊

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/77223007-8e4d0c00-6b93-11ea-93f0-1ad0d10f27b9.png)

**Comment by yc0524** [comment]
![image](https://user-images.githubusercontent.com/33405012/77223129-d587cc80-6b94-11ea-9236-e51ffd6631c7.png)
额..开发工具问题吗?  我的确实没显示...我的最新window版本的

**Comment by sky-admin** [comment]
项目删掉node_modules打个压缩包贴上来我试试？

**Comment by yc0524** [comment]
[qq-demo.zip](https://github.com/didi/mpx/files/4362623/qq-demo.zip)

**Comment by sky-admin** [comment]
确实有你说的情况，然鹅我对了半天代码基本一样，跑起来也符合预期，就是不渲染，，然后我打开了这个。。
![image](https://user-images.githubusercontent.com/6292668/77224062-0409a580-6b9d-11ea-870b-ec2de09e1878.png)

**Comment by sky-admin** [comment]
应该是QQ开发者工具的bug，勾选这个关闭新的编译内核。

**Comment by yc0524** [comment]
...确实是  感谢帮忙排查  我建议你们也可以写进文档 .. 不然这种问题开发者也难排查出来
