### ISSUE TITLE
编译成 QQ 小程序，提醒 open-type 不支持 openGroupProfile

### ISSUE THREAD

**Issue by csnan** [didi/mpx#409]
![image](https://user-images.githubusercontent.com/47582074/77396124-1161a280-6dde-11ea-9f86-4ca2d676f15c.png)

**Comment by sky-admin** [comment]
安装最新的@mpxjs/webpack-plugin试试。PS：@mpxjs/core也需要同步升级哈

**Comment by csnan** [comment]
> 安装最新的@mpxjs/webpack-plugin试试。PS：@mpxjs/core也需要同步升级哈

已解决，感谢！
