### ISSUE TITLE
用cli生成的项目中，list组件未生成.json文件

### ISSUE THREAD

**Issue by yansm** [didi/mpx#41]
用cli生成的项目在运行时报错
_VM650:2 未找到 plugin.json 中的定义的 publicComponents "components/list491edbce/list" 对应的 JSON 文件_
稍微追了一下，webpack-plugin/lib/json-compiler 文件25行
 const rootName = this._compilation._preparedEntrypoints[0].name
来判断是否为app文件并不准确，导致在113行上判断
  if (resourcePath === rootName) 
时rootName与resourcePath相等了，同为组件名，从而未生成组件的json文件。
具体是哪次做了shift操作？还是组件进入队列的优先级变高了没往下追
是只有我才有的问题吗？ 
![image](https://user-images.githubusercontent.com/7484195/50297386-a37e4b00-04b7-11e9-8477-ce1bb44b1b40.png)

**Comment by yansm** [comment]
好像是我选择了plugin project模式才会这样

**Comment by hiyuki** [comment]
v1.0.13已修复，感谢反馈~
