### ISSUE TITLE
mpx 写样式的部分里面写@font-face报错

### ISSUE THREAD

**Issue by 13615817501** [didi/mpx#411]
[demo.zip](https://github.com/didi/mpx/files/4381436/demo.zip)
mpx 在app.mpx里面写@font-face报错 
![image](https://user-images.githubusercontent.com/23720587/77546536-f890e400-6ee6-11ea-9968-775a37c164d5.png)
![image](https://user-images.githubusercontent.com/23720587/77546675-2b3adc80-6ee7-11ea-840a-7328e08a8f5c.png)
由于base64太长了 截不全
但是把这个@font-face的内容写在原生小程序的app.wxss里面就不报错可以生效 ，demo是HTML页面效果也可以实现，就是mpx里面实现不了报错

**Comment by sky-admin** [comment]
因为你这个下面还有个ttf格式的引用，但是那个ttf文件并不存在吧。
构建时候有报错不？
删了那个ttf就行。
