### ISSUE TITLE
跨平台编译后，钉钉应用无法运行

### ISSUE THREAD

**Issue by xhtea** [didi/mpx#412]
**问题描述**
使用跨平台编译输出后，在微信端和支付宝小程序端，可以正常运行，不过当代码切换到钉钉应用时，报错不能运行

**复现步骤**
1、直接下载官方框架，不作任何修改后，直接运行

**期望的表现**
能够钉钉E应用也正常运行

**截图**
![钉钉报错截图](https://user-images.githubusercontent.com/25979037/77638957-ef5d5100-6f92-11ea-87d5-fd56d246f737.png)

**Comment by sky-admin** [comment]
这个是由于钉钉小程序中无法像支付宝小程序里一样获取全局对象导致的，正在调研如何在钉钉小程序中获取全局对象

**Comment by sky-admin** [comment]
抱歉，解决那个全局对象的问题后发现钉钉小程序不支持component2编译，所以暂时无法支持，等钉钉小程序更新了component2编译后mpx再行支持。
ps: 关于component2 https://opendocs.alipay.com/mini/framework/custom-component-overview
