### ISSUE TITLE
.wxml文件中无法通过require方式加载本地图片

### ISSUE THREAD

**Issue by hetchzhao** [didi/mpx#414]
**问题描述**
.wxml文件中无法通过require方式加载本地图片

**复现步骤**
通过原生接入的方式开始，并引入了vantWeapp组件库。
1. 加载本地图片
webpack.conf.js
```
.......
resolve: {
    alias: {
      "@": path.resolve(__dirname, "../", "src"),
      "@image": path.resolve(__dirname, "../", "src/assets/img")
    },
    extensions: [".js", ".mpx", ".wxml"],
    modules: ["node_modules"]
  }
......
```

xxx.wxml
```
<van-image width="10rem" height="10rem" fit="contain" src="{{requir('@image/image.jpg')}}" />
```

**期望的表现**
希望xxx.wxml中也能解析到本地图片的地址

**截图**
<img width="403" alt="WX20200330-214030@2x" src="https://user-images.githubusercontent.com/6813909/77919002-3b7bfe80-72cf-11ea-9a54-df48d9b6639e.png">

**系统及环境**
微信开发者工具：1.02.2
macOS Catalina：10.15.1

**Comment by hiyuki** [comment]
已支持相关配置，https://github.com/didi/mpx/releases/tag/v2.5.4
