### ISSUE TITLE
[建议]静态资源可以配置cdn, 尤其是CSS里边的背景图片建议支持CDN

### ISSUE THREAD

**Issue by vivine** [didi/mpx#417]
**现存问题**
小程序使用很多图片资源，尤其是背景图，导致构建后包大于2M（小程序包限制），所以建议支持使用cdn图片地址的方式。

**期望的表现**
1、支持图片使用CDN图片，在webpack里边构建的时候可以配置
2、CSS背景图片支持大小限制，大于k数的走CDN，否则走base64
3、支持用户自己决定是否使用CDN图片，比如说在图片地址后面加上?cdn，则解析为cdn，否则解析为本地图片或者base64
4、npm script 里边watch的时候建议不走CDN，production的时候可以走上面的CDN流程

**附加问题**
在mpx-cli模板里边，webpack.config.js 配置的 resolve，顺序是有问题的
```javascript
resolve: {
    extensions: ['.mpx', '.vue', '.js', '.ts', '.wxml'], // 之前是 ['.js', '.mpx', '.wxml', '.vue']
    modules: ['node_modules']
}
```
如果，.js 在前面，那么当我不使用单文件，而是一个页面是一个目录，里边有 index.mpx，index.js或者index.ts，index.scss 的时候，就会优先使用.js作为入口文件，那么.js里边并没有引用.mpx，导致构建的时候不能生成.wxml文件，所以这里的顺序还得变一下

**Comment by hiyuki** [comment]
已支持，https://github.com/didi/mpx/releases/tag/v2.5.4
