### ISSUE TITLE
input text类型和密码类型之间相互的切换，键盘直接关闭，机型小米9

### ISSUE THREAD

**Issue by DreamMMan** [didi/mpx#419]
text类型和number、idcard、digit 相互切换键盘直接切换到对应类型的模式，而input text类型和密码类型之间相互的切换，键盘直接关闭，机型小米9

**Comment by sky-admin** [comment]
这应该是小米对密码安全键盘做了什么处理，微信小程序本身和小米的密码安全键盘直接存在一些冲突，你用原生试试应该也这样。
