### ISSUE TITLE
多端转换使用customCtor: Page构造页面，对应json文件含component字段

### ISSUE THREAD

**Issue by wusiquan** [didi/mpx#420]
**问题描述**
转百度小程序时，由于使用Component构造页面，百度小程序会先调用onShow后调用onLoad（这是百度小程序的问题，官方已经收到反馈，头条小程序是onLoad, onShow的顺序）

于是就想使用mpx的选项`{ customCtor: Page }`来构造页面使其生命周期统一，但是转换的后的页面对应json文件，含有` { "component": true }`字段，会报错

**复现步骤**
@mpxjs/core 2.5.3
@mpxjs/webpack-plugin 2.5.4-0
代码已放入附件，build后到对应的小程序开发者工具查看

首页5秒后自动跳到testPage页，此页将会报错

**期望的表现**
期望去除{ customCtor: Page }构造页面时，对应的页面json中，不含有{ "component": true } 字段

这是百度小程序的引发的问题，是否考虑要针对swan环境时，默认用Page来构造页面，是不是和ali一样了?

**附件**
[issue-420.zip](https://github.com/didi/mpx/files/4443581/issue-420.zip)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.5，支持一个新的配置项forceUsePageCtor，可以不用传递customCtor了
