### ISSUE TITLE
关于向子组件携带事件

### ISSUE THREAD

**Issue by CQCcq** [didi/mpx#424]
**问题描述**
请用干净简洁的文字描述你的问题

**复现步骤**
请给出如何复现这个问题的方法，像下面一样分步骤描述清楚
1. vue是props向子组件传递参数的时候也是支持传递方法的所以一些组件封装时既有v-bind也有@去封装事件在用到vant-weapp时，我的一个事件无法得到子组件的响应
2. 
    <view > 
       <van-tree-select
          items="{{ items }}"
          main-active-index="{{ mainActiveIndex }}"
          active-id="{{ activeId }}"
          max="{{ max }}"
          wx:click-nav="onClickNav"
          wx:click-item="onClickItem"
        />
    </view>
3.我的github项目地址
https://github.com/CQCcq/personalMpx
尽可能给出简洁的步骤，如果比较麻烦，或者小demo上较难复现，请准备一个demo作为附件，光标选中最下方的附件拖拽上传一个demo

**期望的表现**
请描述你期望正常情况下应该发生什么？

**截图**
如果可能且方便的话，请附上关于问题的截图

**系统及环境**
如果你猜想或验证过这个问题和设备或环境有关系，请描述你的环境

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by hiyuki** [comment]
Mpx在自定义组件上完全基于小程序自身的实现，不支持props传递函数，请改用事件方式进行通信
