### ISSUE TITLE
[Bug report]不支持无埋点工具 growingio 

### ISSUE THREAD

**Issue by zaxlct** [didi/mpx#425]
**问题描述**
按照原生小程序的方式引入无埋点 growingio sdk，但是 growingio 后台无任何统计数据。
联系了 gio 的客服，对方回复：
> 抓包看了当前小程序发送的数据，只有 click事件，即元素点击，没有 vst和page事件，
因为我们平台是根据vst和page来计算数据的，
这样虽然您看到请求成功了，但是因为没有vst和page，所以在gio平台上是没有数据的

然后我再次尝试把打包后的小程序，再次引入 growingio ，还是没有数据。。。

请问 mpx 是对事件做了统一封装了吗

**期望的表现**
无

请描述你期望正常情况下应该发生什么？

**截图**
无

**系统及环境**
2.5.7

**附件**
无

**Comment by sky-admin** [comment]
vst是什么？page事件我猜可能和mpx会用component来构造页面有关系，可以通过customCtor传Page来改回用page构造页面试试。

**Comment by zaxlct** [comment]
@sky-admin 谢谢你，谢谢mpx！

**Comment by xugongyang** [comment]
> vst是什么？page事件我猜可能和mpx会用component来构造页面有关系，可以通过customCtor传Page来改回用page构造页面试试。

customCtor 传 Page 怎么用啊，官方文档没看明白，能否给个简单示例
