### ISSUE TITLE
引入支付宝小程序组件报错在list文件夹下的index.mpx内

### ISSUE THREAD

**Issue by CQCcq** [didi/mpx#427]
**问题描述**
github地址:https://github.com/CQCcq/personalMpx

**复现步骤**
请给出如何复现这个问题的方法，像下面一样分步骤描述清楚
1. npm 安装组件后
2. 按需引入组件编译时报错且组件不显示
尽可能给出简洁的步骤，如果比较麻烦，或者小demo上较难复现，请准备一个demo作为附件，光标选中最下方的附件拖拽上传一个demo

**期望的表现**
请描述你期望正常情况下应该发生什么？
能向微信小程序ui组件库一样正常显示，避免自己写组件ui最好是都能使用iview毕竟该组件即有支持微信小程序的版本也有支持支付宝小程序的版本

**截图**
如果可能且方便的话，请附上关于问题的截图

![image](https://user-images.githubusercontent.com/44135143/79084048-5dac5c80-7d64-11ea-80a2-90e236a6cc01.png)
![image](https://user-images.githubusercontent.com/44135143/79084113-a49a5200-7d64-11ea-8533-14dccb05bfa9.png)

**系统及环境**
如果你猜想或验证过这个问题和设备或环境有关系，请描述你的环境

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by hiyuki** [comment]
modeRules写的完全是错的，按照下面来写即可  
```js
modeRules: {
    ali: {
      include: [/mini-ali-ui/]
    }
  }
```
modeRules配置我们文档的说明得也不够清晰，后续会完善

另外提issue的时候希望能够构建能复现问题的最简demo，不要把项目直接贴上来，里面有太多额外干扰信息不便于我们定位问题。

**Comment by CQCcq** [comment]
好的！谢谢
