### ISSUE TITLE
[Bug report] sjs使用export var xxx = xxx导出变量报错

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#429]
**问题描述**
sjs使用export var xxx = xxx导出变量报错

**复现步骤**
sjs使用export var xxx = xxx导出变量

**期望的表现**
正常编译

**截图**
![image](https://user-images.githubusercontent.com/22525904/79108811-b18d6480-7da9-11ea-96c6-f4d1d5be5775.png)

![image](https://user-images.githubusercontent.com/22525904/79108934-f31e0f80-7da9-11ea-9229-2a5be84f14b2.png)

**系统及环境**

**附件**

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.9 已支持
