### ISSUE TITLE
[Bug report] 编译到支付宝后运行时报错

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#430]
**问题描述**
编译到支付宝后运行时报错

**复现步骤**
以微信为base编译到支付宝

**期望的表现**
不报错

**截图**

![image](https://user-images.githubusercontent.com/22525904/79110154-6163d180-7dac-11ea-9ec5-f544a73ea699.png)

**系统及环境**

"@mpxjs/core": "^2.5.7"
"@mpxjs/webpack-plugin": "^2.5.7",

**附件**

**Comment by hiyuki** [comment]
信息过少，无法进行排查，请在补充复现demo后reopen
