### ISSUE TITLE
不得不再次提问了

### ISSUE THREAD

**Issue by CQCcq** [didi/mpx#431]
**问题描述**
npm引入是不会报错的，但是用下载的方式components引入组件就会报错，问题路劲
list/index.mpx
build.js内有transRpx:[写的有组件路径]

webpack.conf.js内有ali:[/ivewali/]
**复现步骤**
请给出如何复现这个问题的方法，像下面一样分步骤描述清楚

![image](https://user-images.githubusercontent.com/44135143/79110272-a7b93080-7dac-11ea-9405-60880d327ca6.png)

尽可能给出简洁的步骤，如果比较麻烦，或者小demo上较难复现，请准备一个demo作为附件，光标选中最下方的附件拖拽上传一个demo

**期望的表现**
请描述你期望正常情况下应该发生什么？

**截图**
如果可能且方便的话，请附上关于问题的截图

**系统及环境**
如果你猜想或验证过这个问题和设备或环境有关系，请描述你的环境

**附件**
光标选中这里并拖拽demo到此上传到github

**Comment by CQCcq** [comment]
github地址：https://github.com/CQCcq/personalMpx

**Comment by sky-admin** [comment]
modeRules不正确用法导致
