### ISSUE TITLE
关于connectSoket百度和wx差异处理

### ISSUE THREAD

**Issue by tliwyl** [didi/mpx#432]
```
let socketChannel = connectSocket({ url })//这里connectSocket就是wx.connectSocket()
```
这段代码返回值再微信中返回值如下图
<img width="394" alt="屏幕快照 2020-04-13 下午5 50 02" src="https://user-images.githubusercontent.com/22835834/79111911-0338ed80-7db0-11ea-8bd5-47e0e621b1aa.png">
在百度中返回值如下：
<img width="376" alt="屏幕快照 2020-04-13 下午6 00 05" src="https://user-images.githubusercontent.com/22835834/79112286-cc170c00-7db0-11ea-9714-b5b329a88456.png">

百度中返回一个带__returned 的Promise对象，其onOpen，onClose方法都在__returned属性的原型上，导致必须区别对待两个环境。目前添加如下代码兼容两套环境：
```
	socketChannel = connectSocket({ url })
		
	if (__mpx_mode__ === "swan") {
		socketChannel = socketChannel.__returned
	}
        socketChannel.onOpen(() => {
	        console.info("socketChannel onOpen");
		//......
       });
```
有没有更优雅点的方法去解决这种问题

**Comment by hiyuki** [comment]
在安装了api-proxy的情况下直接使用mpx.connectSocket的方式去调用api就能保持自然对齐
