### ISSUE TITLE
[Bug report] 支付宝小程序环境中Number.isFinite方法不存在

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#433]
**问题描述**
支付宝小程序环境中Number.isFinite方法不存在

**复现步骤**
```
Number.isFinite(111)
```

**期望的表现**
正常输出boolean值

**截图**

![image](https://user-images.githubusercontent.com/22525904/79216335-94c36080-7e7f-11ea-9668-c9a44603105f.png)

![image](https://user-images.githubusercontent.com/22525904/79216328-92610680-7e7f-11ea-8f58-7d56b6c50edd.png)

**系统及环境**

mpx版本2.5.7

typescript版本3.7.2

typescript环境配置
```json
{
    "compilerOptions": {
        "target": "es6",
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "noImplicitThis": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "allowSyntheticDefaultImports": true,
        "moduleResolution": "node",
        "lib": ["dom", "es6", "dom.iterable", "es2017"],
        "importHelpers": true,
        "baseUrl": ".",
        "paths": {
            "@/*": ["src/*"]
        }
    },
    "include": ["src/**/*.ts", "src/**/*.js"],
    "exclude": ["node_modules"]
}
```

**附件**

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.9 已修复
