### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by tliwyl** [didi/mpx#439]
```
 <navigator open-type="reLaunch" url="/pages/index?stid={{source.bbcShopId}}"  class="stroll">XXXX<text class="icon"></text></navigator>
```
 这段代码转ali小程序时报错提示：
```
<navigator>'s property 'open-type' does not support '[reLaunch]' value in ali environment!
```

阿里navigator 的open-type 值如下：
<img width="674" alt="屏幕快照 2020-04-20 下午6 43 58" src="https://user-images.githubusercontent.com/22835834/79744000-32afa300-8338-11ea-9e3f-c528bc73beae.png">

属性名 | 描述
-- | --
navigate | 对应 my.navigateTo 的功能。
redirect | 对应 my.redirectTo 的功能。
switchTab | 对应 my.switchTab 的功能。
navigateBack | 对应 my.navigateBack 的功能。
reLaunch | 对应 my.reLaunch 的功能。

有reLuanch这个值为什么还会报错

**Comment by sky-admin** [comment]
这个应该是支付宝后支持的，之前编写转换规则的时候还没有，我们现在加上，下个版本生效

**Comment by sky-admin** [comment]
急用可以先自行修改node_modules 里 @mpxjs/webpack-plugin/lib/platform/template/wx/component-config/navigator.js 28行加上relaunch即可。感谢反馈。

**Comment by tliwyl** [comment]
@sky-admin  video 标签也是同样问题：
```
<video> is not supported in ali environment!
```
能否一起支持一下
