### ISSUE TITLE
编译头条小程序不支持button的动态open-type

### ISSUE THREAD

**Issue by yc0524** [didi/mpx#440]
```
<button
            class="weui-dialog__btn"
            open-type="{{ buttonType }}"
            bindtap="hide"
          >
            {{ confirmText }}
          </button>```

**Comment by yc0524** [comment]
报错: <button>'s property 'open-type' does not support '[{{ buttonType }}]' value in bytedance environment!

**Comment by sky-admin** [comment]
因为微信的opentype和头条的无法完全对齐，用动态值可能出问题所以进行一个提示，其实不影响转换结果。
如果自己确认过动态值没问题，只是单纯想解决这个报错，可以看下文档中条件编译一节
