### ISSUE TITLE
使用less 和style-resource-loader，配置不生效

### ISSUE THREAD

**Issue by leowang1028** [didi/mpx#441]
**问题描述**
加了style-resource-loader，想全局引入一些变量和mixin，但是配置不生效

```
rules: [
      {
        test: /\.mpx$/,
        use: MpxWebpackPlugin.loader({
          transRpx: [
            {
              mode: 'all',
              designWidth: 375,
              include: resolve('node_modules/@vant/weapp')
            }
          ],
          loaders: {
            less: [
              {
                loader: 'style-resources-loader',
                options: {
                  resources: [
                    resolve('../src/static/style/var.less')
                  ]
                }
              }
            ]
          }
        })
      }
    ]
```
错误：ebpack-plugin/lib/selector.js?type=styles&index=0!./src/app.mpx)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

  font-size: 28rpx;
  color: @primary;
       ^
Variable @primary is undefined

**Comment by sky-admin** [comment]
给后来者指路： 参考 #62 
我看你已经看了这个issue，不过是配在 webpack.conf.js 的loader里，不是在modeRules里，你这个配置，是不是缺了什么

**Comment by sky-admin** [comment]
是不是也应该写上这一串：['style-loader', 'css-loader', 'less-loader', {
                loader: 'style-resources-loader',
                options: {
                    patterns: path.resolve(__dirname, 'path/to/less/variables/*.less'),
                    injector: 'append'
                }
            }]

**Comment by leowang1028** [comment]
> 是不是也应该写上这一串：['style-loader', 'css-loader', 'less-loader', {
> loader: 'style-resources-loader',
> options: {
> patterns: path.resolve(__dirname, 'path/to/less/variables/*.less'),
> injector: 'append'
> }
> }]

我在webpack.conf.js中的module.rules中加了配置
```
  {
        test: /\.mpx$/,
        use: MpxWebpackPlugin.loader({
          less: ['style-loader', 'css-loader', 'less-loader', {
              loader: 'style-resources-loader',
              options: {
                patterns: [
                  resolve('../src/static/style/var.less')
                ],
                injector: 'append'
              }
            }
          ]
        })
      }
```
虽然不报错了，但是好像覆盖了mpx的一些配置，导致无法小程序代码
```
Built at: 2020-04-23 9:04:47
              Asset       Size  Chunks                    Chunk Names
             app.js    323 KiB       1  [emitted]  [big]  app
           app.json   17 bytes          [emitted]
          bundle.js   6.98 KiB       0  [emitted]         bundle
project.config.json  334 bytes          [emitted]

  Build complete.
```

**Comment by sky-admin** [comment]
已微信沟通解决。
注意loader修改配置应该找已有loader，不要自行新添加。由于新老项目差异，loader配置可能在build.js 或 webpack.conf.js 里，千万记得是修改已有，不要新加mpx的loader

**Comment by OliverCN** [comment]
> 已微信沟通解决。
> 注意loader修改配置应该找已有loader，不要自行新添加。由于新老项目差异，loader配置可能在build.js 或 webpack.conf.js 里，千万记得是修改已有，不要新加mpx的loader

具体是怎么解决的呢？我使用的是2.6版本，配置方式是不是不一样了啊？

我发现config/index.js这个文件里有个mpxLoaderConfig的空对象，看了下引用关系，貌似是留给我们自己配置loader的地方，但我在这里配置了之后报错，能帮我看看为什么吗？是不是不应该在这里配置啊
```
const mpxLoaderConfig = {
  loaders: {
    less: [
      "style-loader",
      "css-loader",
      "less-loader",
      {
        loader: "style-resources-loader",
        options: {
          injector: "append",
          patterns: [path.resolve(__dirname, "../src/style/variable.less")]
        }
      }
    ]
  }
};
```

![Snipaste_2020-10-22_16-48-40](https://user-images.githubusercontent.com/6055762/96848040-7c637c80-1486-11eb-81fa-1259aa8ef37f.png)

**Comment by boboidream** [comment]
> > 已微信沟通解决。
> > 注意loader修改配置应该找已有loader，不要自行新添加。由于新老项目差异，loader配置可能在build.js 或 webpack.conf.js 里，千万记得是修改已有，不要新加mpx的loader
> 
> 具体是怎么解决的呢？我使用的是2.6版本，配置方式是不是不一样了啊？
> 
> 我发现config/index.js这个文件里有个mpxLoaderConfig的空对象，看了下引用关系，貌似是留给我们自己配置loader的地方，但我在这里配置了之后报错，能帮我看看为什么吗？是不是不应该在这里配置啊
> 
> ```
> const mpxLoaderConfig = {
>   loaders: {
>     less: [
>       "style-loader",
>       "css-loader",
>       "less-loader",
>       {
>         loader: "style-resources-loader",
>         options: {
>           injector: "append",
>           patterns: [path.resolve(__dirname, "../src/style/variable.less")]
>         }
>       }
>     ]
>   }
> };
> ```
> 
> ![Snipaste_2020-10-22_16-48-40](https://user-images.githubusercontent.com/6055762/96848040-7c637c80-1486-11eb-81fa-1259aa8ef37f.png)

把 `"style-loader"` 这个去掉试试
