### ISSUE TITLE
style不能响应改变[Bug report]

### ISSUE THREAD

**Issue by yuu2lee4** [didi/mpx#442]
**问题描述**
请用干净简洁的文字描述你的问题
最新版mpx绑定的style改变之后，没有响应最新的改变，之前的版本可以

![image](https://user-images.githubusercontent.com/8046366/80114021-9c88b080-85b5-11ea-824f-bcf565cbf4fc.png)

**复现步骤**
![image](https://user-images.githubusercontent.com/8046366/80114248-f0939500-85b5-11ea-9d54-55269fb7b87d.png)
点击demo里的`大大大`按钮，改变了style的fontSize，但是字体大小并没有改变

**系统及环境**
mac10.15,node12.16.2

**附件**
[mpxtest.zip](https://github.com/didi/mpx/files/4523277/mpxtest.zip)

**Comment by zqjimlove** [comment]
我试了一下，发现以数据路径形式修改节点的属性并不会更新。这个问题和数组路径新增数据后的长度问题。

https://developers.weixin.qq.com/community/develop/article/doc/0000ec6fe2c960e426a9fcf4151c13

```javascript
// 无效
this.setData({
  'menuStyle.background': 'yellow',
})

// 有效
this.setData({
  menuStyle: {
    background: 'yellow',
  },
})
```

**Comment by zqjimlove** [comment]
```html
<view 
  data-style-obj="{{menuStyle}}" 
  data-style='{{__stringify__.stringifyStyle("", (menuStyle))}}'
  bindtap="log"
>
</view>
```

数据路径更新打印日志：

```json
{
  "style": "background:red;",
  "styleObj": {
    "background": "green"
  }
}
```

对象更新日志：

```json
{
  "style": "background:green;",
  "styleObj": {
    "background": "green"
  }
}
```

wxs的打印日志是正确的。

**Comment by hiyuki** [comment]
嗯，这个问题我们之前也有遇到，属于wx本身数据路径赋值的bug，目前有两种解决方案，一种是遇到这类问题时使用setData规避，另一种是在app.mpx配置mpx.config.useStrictDiff=false。

也感谢@zqjimlove 协助排查~
