### ISSUE TITLE
[Bug report]TS模版创建项目，输出Web，不能运行，mpx-keep-alive、router-view未注册

### ISSUE THREAD

**Issue by arbing** [didi/mpx#443]
**问题描述**

TS模版创建项目，输出Web，不能运行，mpx-keep-alive、router-view未注册

![image](https://user-images.githubusercontent.com/687757/80399141-4edcb280-88eb-11ea-8890-31519fdef11b.png)

**复现步骤**

![image](https://user-images.githubusercontent.com/687757/80399031-22c13180-88eb-11ea-8c7b-432a206e2c12.png)

![image](https://user-images.githubusercontent.com/687757/80399451-c7dc0a00-88eb-11ea-9e44-4fe5f72c2ee6.png)

**Comment by hiyuki** [comment]
确认问题，正在处理

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.15 已处理
