### ISSUE TITLE
在store模块化的时候，无法修改子模块中的 mutation

### ISSUE THREAD

**Issue by huqijie** [didi/mpx#444]
**问题描述**
无法调用子模块 mutation 中的方法修改 state

**期望的表现**
修改子模块中 state 属性值

**系统及环境**
Mac

[store.zip](https://github.com/didi/mpx/files/4584620/store.zip)

**Comment by huqijie** [comment]
computed: {
      ...store.mapState('home', ['active']),
      ...store.mapState('contract', ['a', 'b', 'c'])
    },
    methods: {
      ...store.mapMutations(['home']),
      onChange(event) {
        let index = event.detail;
        store.commit('home.SET_TABBAR_INDEX', index)
        console.log(this.active, this.a, this.b, this.c);
      }
    }

**Comment by hiyuki** [comment]
请按照issue指引上传可运行的复现demo

**Comment by huqijie** [comment]
demo.zip

**Comment by hiyuki** [comment]
你把deps和modules搞混了，请仔细阅读文档，demo中将store/index.js中创建主store的地方改为下面的形式：
```js
const store = createStore({
  state,
  mutations,
  getters,
  actions,
  deps: modules
})
```
