### ISSUE TITLE
现在不支持自定义tabbar 转web吗？

### ISSUE THREAD

**Issue by JanssenZhang** [didi/mpx#447]

**Comment by hiyuki** [comment]
是的，目前还没有支持，我们后续会进行支持

**Comment by JanssenZhang** [comment]
@hiyuki 我看到转web后navigateTo的回调也不支持呢，你们后面对转web的全面优化支持会在什么时候发布呢？

**Comment by hiyuki** [comment]
navigateTo回调确定是支持的，确保你引入并使用了api-proxy插件，输出web的能力一直在完善当中，可以关注我们的release信息

**Comment by JanssenZhang** [comment]
转web时，redirectTo和navigateTo的回调在vue router的方法里参数位置写错了
