### ISSUE TITLE
wx:model双向数据绑定有问题

### ISSUE THREAD

**Issue by 13615817501** [didi/mpx#456]
![111111111](https://user-images.githubusercontent.com/23720587/81632738-9a3fa680-943d-11ea-8b3d-fdd200e3c242.png)
![Uploading 22222222222.png…]()
![33333333](https://user-images.githubusercontent.com/23720587/81632747-9e6bc400-943d-11ea-8f43-c70af200f375.png)
![Uploading 444444444444444444.png…]()

**Comment by sky-admin** [comment]
第一次的表现应该是符合预期的吧？然后后面就不会变了对吗？
这个问题产生的原因是，你试图在input方法里对aaa赋一个相同的值。
首先双向绑定本身就是个语法糖，其实就是帮用户做了props传值和监听事件改值。最终真实的代码其实是在你的input handler前有一个mpx注入的__model handler，在那里会取e.detail.value的值赋值给aaa,结果赋完你又赋了一次aaa=1，那么第一次就会生效让input变成1，但是第二次你还对aaa赋值1，这时候aaa在记录中本来就是1，两次值相同，mpx不会真实调用setData来发送（因为前后都是1，mpx认为你的值没有变化，没必要发送）

**Comment by sky-admin** [comment]
简而言之就是你这个操作让mpx以为这个值没变，不用发送数据，为了方便你明白，可以看下这样写：
```html
<template>
  <input type="text" wx:model="{{aaa}}" bindinput="handleInput"/>
</template>

<script>
  import { createPage } from '@mpxjs/core'

  let a = 1
  createPage({
    data: {
      aaa: 123
    },
    methods: {
      handleInput (e) {
        this.aaa = a++
      }
    }
  })
</script>
```
效果是你按多少次键盘，input就变成对应数字

**Comment by sky-admin** [comment]
就是说你不能在input的handler里为aaa赋一个相同的值，否则第二次及以后就会失效。
对于你微信群里说的你的应用场景，我觉得你应该考虑去watch这个值的变化然后做相应的逻辑，而不是直接在input的handler里这样操作

**Comment by sky-admin** [comment]
解决方案：
你的input handler （就是你那个changeaaa方法）return你要设的值
或者直接this.setData
建议用第一种
