### ISSUE TITLE
[Bug report] 百度环境下mixin无效

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#457]
**问题描述**
百度环境下mixin无效

**复现步骤**

```javascript
// auth.ts
import mpx from '@mpxjs/core';
import Dialog from '@vant/weapp/dist/dialog/dialog';

export default {
    methods: {
        async __handleGlobalAuthDialogGetUserInfo(e: any) {
        },
    },
};

// app.ts
import authMixin from './mixin/auth'
mpx.mixin(authMixin);

createApp()
```

**期望的表现**
createPage与createComponent的实例上都应该有__handleGlobalAuthDialogGetUserInfo方法

**截图**
![image](https://user-images.githubusercontent.com/22525904/82021934-5c9d8080-96be-11ea-9a0b-95561b9ec626.png)

**系统及环境**
"@mpxjs/core": "^2.5.16"
"@mpxjs/webpack-plugin": "^2.5.16"

**附件**

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.18 已修复
