### ISSUE TITLE
web模式下,引用vant组件无法正常工作

### ISSUE THREAD

**Issue by MrBaoquan** [didi/mpx#458]
好像是丢了样式
[web_vant组件测试_复现demo.zip](https://github.com/didi/mpx/files/4633167/vant_test.zip)

**Comment by sky-admin** [comment]
在 app.ts 里引入css
并在build.js里加入对css的loader

**Comment by sky-admin** [comment]
build.js里改动：
![image](https://user-images.githubusercontent.com/6292668/82054111-00a01f80-96f1-11ea-9327-6acc848c8031.png)

**Comment by sky-admin** [comment]
app.ts 里引入全部样式：
![image](https://user-images.githubusercontent.com/6292668/82054169-17467680-96f1-11ea-8e98-76f06216dafd.png)
当然你也可以按需引用对应组件的样式，比如button你就引`import 'vant/lib/button/style';`，见vant文档哈

**Comment by sky-admin** [comment]
最终的效果：
![image](https://user-images.githubusercontent.com/6292668/82054301-4b219c00-96f1-11ea-8cf9-2954c3c68e43.png)

**Comment by MrBaoquan** [comment]
感谢感谢,好使
