### ISSUE TITLE
数据管理 store中，是否可以增加插件注入的功能，如vuex一样。

### ISSUE THREAD

**Issue by Virczz** [didi/mpx#459]
之前的mpvue项目，用到了 vuex-persistedstate，用于保存用户的登录态。
现在我的实现是在 mutations和actions时 setStorage,在getters中getStorage。
可能项目中不需要持久存储所有的数据，那就希望可以通过在 state 中配置是否需要持久化，来实现

**Comment by hiyuki** [comment]
可以考虑，我调研一下

**Comment by jackrouse** [comment]
如何全局监听store的更改，方便小程序调试，我想每次store有更改就能把store的状态打印出来，一直打console感觉好麻烦。

**Comment by ToPeas** [comment]
> 如何全局监听store的更改，方便小程序调试，我想每次store有更改就能把store的状态打印出来，一直打console感觉好麻烦。

目前已经支持插件机制

**Comment by js5323** [comment]
> > 如何全局监听store的更改，方便小程序调试，我想每次store有更改就能把store的状态打印出来，一直打console感觉好麻烦。
> 
> 目前已经支持插件机制

Hello， 请问插件机制是怎么使用，有文档说明吗？

**Comment by hiyuki** [comment]
https://www.mpxjs.cn/guide/advance/pinia.html#%E4%BD%BF%E7%94%A8%E6%8F%92%E4%BB%B6
