### ISSUE TITLE
scroll-view中数据为动态数据时调用scrollTop不生效

### ISSUE THREAD

**Issue by zhdwwf** [didi/mpx#46]
如题，在mpx中使用scroll-view时，设置scrollTop=0无法使滚动条回到顶部，但在原生小程序下可以，mpx代码如下图，请问此问题是mpx bug还是用法不对？谢谢
可运行的测试Demo地址：[https://github.com/zhdwwf/mpx-scrolltop-test](https://github.com/zhdwwf/mpx-scrolltop-test)  其中microdemo为原生小程序项目，scrolltopdemo为mpx项目
![image](https://user-images.githubusercontent.com/564279/50419322-4a256b80-086b-11e9-95ab-10a3e23ce934.png)

**Comment by sky-admin** [comment]
因为scrollTop一直是0，this.scrollTop=0会认为没有必要进行，遇到这种case可以通过：        this.$forceUpdate()
来强行要求setState
相关文档：https://didi.github.io/mpx/api.html#page--component-%E6%96%B0%E5%A2%9E%E7%9A%84%E5%AE%9E%E4%BE%8B%E6%96%B9%E6%B3%95

**Comment by zhdwwf** [comment]
原来如此，看文档还是不仔细啊，谢谢回复!

**Comment by Lin-Ya** [comment]
> 原来如此，看文档还是不仔细啊，谢谢回复!

你好，请问这个问题能成功解决吗？
```
back: function () {
        this.$forceUpdate({ top: 0 })
      }
```
我在back函数中使用了this.$forceUpdate依旧不能回到顶部。

**Comment by Lin-Ya** [comment]
> 因为scrollTop一直是0，this.scrollTop=0会认为没有必要进行，遇到这种case可以通过： this.$forceUpdate({scrollTop: 0})
> 来强行要求setState
> 相关文档：https://didi.github.io/mpx/api.html#page--component-%E6%96%B0%E5%A2%9E%E7%9A%84%E5%AE%9E%E4%BE%8B%E6%96%B9%E6%B3%95

```
back: function () {
        this.$forceUpdate({ top: 0 })
      }
```
我在点击按钮绑定的back函数中使用了this.$forceUpdate依旧不能回到顶部，两次设置的值不一样也不能生效

**Comment by sky-admin** [comment]
方便发下相关代码我们看看吗？

**Comment by Lin-Ya** [comment]
> 方便发下相关代码我们看看吗？

刚刚回到家重新做一个demo以后发现，scroll-view的高度应该设为屏幕高度即可，可能被雨淋了才醒过来。。。
[demo 地址附上](https://github.com/Lin-Ya/mpx-scrolltop)，方便其他人能第一时间解决。

**Comment by sky-admin** [comment]
解决就好，哈哈
