### ISSUE TITLE
[Bug report] 支付宝 for a:key="index" 的问题

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#461]
**问题描述**
在支付宝下使用for循环时如果该数组的item是undefined则小程序异常

**复现步骤**
for循环一个item是undefined的数组

或者直接使用vant-weapp的skeleton这里rowArray创建了row长度的undefined数组，支付宝下a:key="index"会读取undefined的index就会导致异常

```javascript
props: {
        row: {
            type: Number,
            value: 0,
            observer(value) {
                this.setData({ rowArray: Array.from({ length: value }) });
            },
        },
}
```

**期望的表现**
循环应该使用index正常执行循环

**截图**
![image](https://user-images.githubusercontent.com/22525904/82307951-ad311880-99f3-11ea-9565-194ef92ab7b8.png)

**系统及环境**

**附件**

**Comment by hiyuki** [comment]
该表现符合wx:key或者a:key的描述，这里写index本身是错误的行为，微信当中使用同样存在问题，可以具体看一下a:key的使用描述https://opendocs.alipay.com/mini/framework/list-render
