### ISSUE TITLE
字节跳动小程序 wxs 支持

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#465]
请问目前在跟进字节跳动小程序wxs吗？进度如何了？现在准备要搞字节小程序了

**Comment by hiyuki** [comment]
预计本周内支持

**Comment by okxiaoliang4** [comment]
https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/developer-instrument/developer-instrument-update-and-download
字节跳动 1.9.8版本已更新
![image](https://user-images.githubusercontent.com/22525904/89869884-9b70a300-dbe7-11ea-8fde-978ae31e10d5.png)

**Comment by okxiaoliang4** [comment]
#544 已支持
