### ISSUE TITLE
[Bug report] 项目中的postcss.config.js影响到框架内部处理

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#466]
**问题描述**
mpx编译时使用了项目中postcss.config.js的配置

**复现步骤**
项目根目录添加postcss.config.js

**期望的表现**
mpx编译时的配置与项目中postcss.config.js的配置分离

**截图**

**系统及环境**

**附件**

**Comment by hiyuki** [comment]
2.5.20已支持，可将postcssInlineConfig中的ignoreConfigFile设置为true来实现，详情查看：https://github.com/didi/mpx/releases/tag/v2.5.20
