### ISSUE TITLE
[Bug report]properties内配置Number类型参数，微信开发者工具报错

### ISSUE THREAD

**Issue by SimoralX** [didi/mpx#470]
**问题描述**
properties新建类型Number的，打包无报错，但是开发者工具报错了。

**复现步骤**
请给出如何复现这个问题的方法，像下面一样分步骤描述清楚
1. 新创建一个项目
2. 然后在 `src/components/list.mpx` 内新增一个组件的对外属性，并配置类型为Number。
3. 开启 `npm run watch`
4. 开发者工具直接报错了

**期望的表现**
请描述你期望正常情况下应该发生什么？

**截图**
![20200526123931](https://user-images.githubusercontent.com/30761931/82861513-7a38d880-9f4f-11ea-98da-d0514d2eae3d.png)

![20200526123949](https://user-images.githubusercontent.com/30761931/82861517-815fe680-9f4f-11ea-98dc-6d9bec828ed6.png)

**系统及环境**
感觉和系统和环境应该没关系吧，我是直接使用 `npm i` 安装的。

**附件**
[我新创建的项目已经上传到码云](https://gitee.com/simorel/mpx-bug-report/blob/master/src/components/list.mpx#L13)

以下是其中 `list.mpx` 组件代码：
```js
<template>
  <view class="list">
    <view wx:for="{{listData}}" wx:key="index">{{item}}</view>
  </view>
</template>

<script>
  import { createComponent } from '@mpxjs/core'

  createComponent({
    properties: {
      prop: {
        type: Number,
        value: 10
      }
    },
    data: {
      listData: ['手机', '电视', '电脑']
    }
  })
</script>

<style lang="stylus">
  .list
    background-color red
</style>

<script type="application/json">
  {
    "component": true
  }
</script>
```

**Comment by sky-admin** [comment]
我把你码云上的项目拉到本地跑了下没有报错啊？

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/82973555-571f2f00-a00a-11ea-96e7-f78492eb490c.png)

**Comment by SimoralX** [comment]
感谢，问题已解决，开发者工具需要 【详情】-【本地设置】-关闭【ES6转ES5】、【增强编译】两项。
