### ISSUE TITLE
vscode 编辑器支持太差 

### ISSUE THREAD

**Issue by lupingW** [didi/mpx#471]
**问题描述**
作为vscode的重度使用者, 发写mpx没有专用插件, 并且官网教的通过各种方法来优化编写效率的方法也不是很明确.希望作者能早日推出插件或者出一份详细的文档

**复现步骤**

**期望的表现**
类似于vue插件的效果

**截图**

**系统及环境**

**附件**

**Comment by hiyuki** [comment]
#127

**Comment by hiyuki** [comment]
目前由于时间人力原因目前暂时无法提供专用的vsc插件，主要基于vue的ide插件生态进行支持，相关讨论可以参考 #127 
及文档描述：https://didi.github.io/mpx/single/what-is-single-file.html#%E7%BC%96%E8%BE%91%E5%99%A8ide%E9%AB%98%E4%BA%AE%E3%80%81%E6%8F%90%E7%A4%BA
