### ISSUE TITLE
template内的图片资源低于limit配置的，没有base64处理。

### ISSUE THREAD

**Issue by SimoralX** [didi/mpx#475]
https://github.com/didi/mpx/blob/c9f95822336458ada97f7f1fcdc67380eb8b7624/packages/webpack-plugin/lib/url-loader.js#L23

我在本地试了一下，如果修改为 
```js
if (query.type === 'styles' || query.type === 'template') {
   return true
}
```
就可以正常将 template 中引用的图片低于limit的正常base64处理。

**Comment by hiyuki** [comment]
这个的设计意图就是这样的，因为小程序模板和js中有部分场景只支持图像路径，不支持base64，为了避免这些地方报错所以全量关闭了非样式中引用图像的base64处理，limit也只会对样式中引用的图像资源生效
