### ISSUE TITLE
使用scss写样式，怎样把变量文件配置成全局的呢？

### ISSUE THREAD

**Issue by OliverCN** [didi/mpx#478]
之前用mpvue开发时，可以通过修改loader引入全局变量，改用mpx后尝试用同样的方式引入，但一直不正确，请问要怎么引入才正确呢

**Comment by sky-admin** [comment]
修改loader？是指为sass添加sass-resources-loader以帮你自动引入一些全局样式吗？可以看下这个：https://github.com/didi/mpx/issues/62

**Comment by OliverCN** [comment]
> 修改loader？是指为sass添加sass-resources-loader以帮你自动引入一些全局样式吗？可以看下这个：#62

是的，已根据提示解决，谢谢
