### ISSUE TITLE
[Bug report]TypeError: Function(...) is not a function

### ISSUE THREAD

**Issue by HelloUndefined** [didi/mpx#479]
**问题描述**  
跨平台构建小程序, 使用async/await, 微信编译功能正常, 支付宝报错
2. 期望的表现
支付宝正常使用async/await
3. 实际的表现
TypeError: Function(...) is not a function
![QQ图片20200610202329](https://user-images.githubusercontent.com/21164162/84267313-6f3d9500-ab58-11ea-9efc-196ced5895ba.png)
![QQ图片20200610202339](https://user-images.githubusercontent.com/21164162/84267371-8aa8a000-ab58-11ea-83da-9f240e5d6ae4.png)
![微信图片_20200610201308](https://user-images.githubusercontent.com/21164162/84266455-115c7d80-ab57-11ea-94ee-96eaaa6784c6.png)
![QQ图片20200610202347](https://user-images.githubusercontent.com/21164162/84267398-94ca9e80-ab58-11ea-9dd3-2926b8ffbc23.png)

Windows环境
    "@mpxjs/api-proxy": "^2.5.10",
    "@mpxjs/core": "^2.5.11",
    "@mpxjs/fetch": "^2.3.9",
    "@mpxjs/webpack-plugin": "^2.5.11",
支付宝开发者工具版本1.12.15
微信开发者工具版本1.03.2005140

**最简复现demo**  
[demo.zip](https://github.com/didi/mpx/files/4758374/demo.zip)

**Comment by sky-admin** [comment]
https://github.com/facebook/regenerator/issues/381
应该是由于babel7的runtime依赖的regenerator-runtime导致的。
建议生产环境先使用Babel6。

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.31
目前Mpx已经正式支持babel7，上面的问题已经修复，可以使用脚手架新创建项目使用

**Comment by zyaxuan** [comment]
更新到babel7， "@mpxjs/api-proxy": "^2.7.44", 也更新到 2.7.44  当前问题还是存在
```json
{
    "@babel/core": "^7.10.4",
    "@babel/eslint-parser": "^7.16.0",
    "@babel/plugin-transform-runtime": "^7.10.4",
    "@babel/plugin-transform-typescript": "^7.16.1",
    "@babel/preset-env": "^7.10.4",
    "@babel/runtime-corejs3": "^7.10.4",
}
```

**Comment by Blackgan3** [comment]
> 更新到babel7， "@mpxjs/api-proxy": "^2.7.44", 也更新到 2.7.44 当前问题还是存在
> 
> ```json
> {
>     "@babel/core": "^7.10.4",
>     "@babel/eslint-parser": "^7.16.0",
>     "@babel/plugin-transform-runtime": "^7.10.4",
>     "@babel/plugin-transform-typescript": "^7.16.1",
>     "@babel/preset-env": "^7.10.4",
>     "@babel/runtime-corejs3": "^7.10.4",
> }
> ```

需更新只 @mpxjs/webpack-plugin@2.7.45 版本
