### ISSUE TITLE
[Bug report] wxs 编译问题

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#481]
**问题描述**  
@vant/weapp 组件库有蛮多地方的wxs直接export一个function，在编译到百度、支付宝的时候都无法使用，是否可以在编译层面处理一下

**环境信息描述**  
系统：mac
mpx依赖版本：
"@mpxjs/core": "^2.5.20",
"@mpxjs/webpack-plugin": "^2.5.23",

**最简复现demo**  

1. 安装@vant/weapp 组件库
2. 使用picker组件编译到百度、支付宝

![image](https://user-images.githubusercontent.com/22525904/84371062-af118480-ac0b-11ea-8982-11d22d78bbab.png)

**Comment by hiyuki** [comment]
这个你自己写个wxs代理一层再输出对象形式就可以了吧

**Comment by okxiaoliang4** [comment]
用alias处理了，只是如果别人也用到别人也得处理一次，并且vant如果更新了不能直接更新依赖包，后面我看看能不能贡献一下代码

**Comment by hiyuki** [comment]
嗯嗯，欢迎pr~
