### ISSUE TITLE
[Bug report] webpack-plugin@2.5.24的问题

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#483]
**问题描述**  
1. 更新了@mpx/webpack-plugin 2.5.24之后编译到百度有很多报错，实测微信与支付宝没有，稍微排查了一下好像跟wx:class有关

![image](https://user-images.githubusercontent.com/22525904/84375740-99538d80-ac12-11ea-9c0a-c664e71b7b04.png)

2. wxs没有处理
```html
<filter src="~@vant/weapp/dist/wxs/utils.wxs" module="utils" />
```
![image](https://user-images.githubusercontent.com/22525904/84458280-3bb55480-ac97-11ea-9b5b-7877c22fa936.png)

3. 百度环境下click事件传入参数报错
```html
<!-- 报错代码 -->
<van-button
    bind:click="handleStandsButtonTap(item)"
    custom-class="custom-stands-button"
    plain
    size="large"
    type="primary"
></van-button>
<!-- 未报错 -->
<van-button
    bind:click="handleStandsButtonTap"
    data-item="{{item}}"
    custom-class="custom-stands-button"
    plain
    size="large"
    type="primary"
></van-button>
<!-- 未报错 -->
<van-button
    bind:tap="handleStandsButtonTap(item)"
    custom-class="custom-stands-button"
    plain
    size="large"
    type="primary"
></van-button>
```
![image](https://user-images.githubusercontent.com/22525904/84458825-7370cc00-ac98-11ea-80de-6761d879395c.png)

![image](https://user-images.githubusercontent.com/22525904/84458753-54723a00-ac98-11ea-9960-7c6789b01867.png)

**环境信息描述**  
至少包含以下部分：
mac
@mpx/core 2.5.20
@mpx/webpack-plugin 2.5.24

**最简复现demo**  
[归档.zip](https://github.com/didi/mpx/files/4768387/default.zip)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.5.25 fixed

**Comment by sky-admin** [comment]
第三点是因为vant设计的时候，click事件是它自己上报的，上报的时候没带参数，百度下拿不到这个dataset。用bindtap等于走的原生的tap事件，能拿到。

**Comment by okxiaoliang4** [comment]
支付宝用bind:tap不触发事件……那这里用__mpx_mode__去判断一下分2个button吗

**Comment by okxiaoliang4** [comment]
还是说自己alias出来一个js去手动抛出多一个tap事件呢

**Comment by sky-admin** [comment]
手动多抛一个tap事件吧

**Comment by okxiaoliang4** [comment]
行，我试试这么处理先，谢谢

**Comment by hiyuki** [comment]
fixed https://github.com/didi/mpx/releases/tag/v2.5.27
