### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by fatindeed** [didi/mpx#484]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
页面代码
`<button wx:if="{{__mpx_mode__ === 'ali'}}" class="loginBtn" open-type="getAuthorize" scope="phoneNumber" onGetAuthorize="alipayPhonenumberLogin" onError="onGetPhoneNumberError">手机号授权登录</button>`
运行
`npm run build --ali`
2. 期望的表现
根据[支付宝小程序的文档](https://opendocs.alipay.com/mini/component/button)，getAuthorize是支持的
3. 实际的表现
> Module Error (from ./node_modules/@mpxjs/webpack-plugin/lib/template-compiler/index.js):
>[template compiler][D:\Repositories\mpx-mingxiang\src\pages\user\login.mpx]: <button>'s property 'open-type' does not support '[getAuthorize]' value in ali environment!
> @ ./src/pages/user/login.mpx 12:0-417
>
>  Build failed with errors.

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
Windows 10
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
@mpxjs/core 2.5.20
@mpxjs/webpack-plugin 2.5.21
@mpxjs/api-proxy 2.5.20
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**Comment by sky-admin** [comment]
转换部分的设计之前是从微信出发转换到支付宝，微信本身没有getAuthorize这种open-type，而是直接getUserInfo/getPhoneNumber，因此之前没考虑过用户直接写getAuthorize这种场景。更新了转换规则，安装最新版即可。

**Comment by hiyuki** [comment]
修正一下上面的@sky-admin回答，这里的问题不是“没有考虑到”，而是目前使用if进行的内联条件编译标记为ali节点依然走了wx2ali的转换规则，理想情况下这些节点应该不走这个转换，目前我们对于转换规则的应用是精确到区块维度的，比如这里这个button写在一个mode='ali'的区块中则不会报这个错，后续我们会考虑将其精确到节点精度，就能完全避免类似问题
