### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by chinavane** [didi/mpx#486]
**问题描述**  
因为之前的项目状态管理用的是namespace，但我们不支持，而module如果拆成多个，但是每个module中的state变量内容是相同的，比如说都有一个list:[]的状态值，那么，不管是多module模式还是多store模式，在页面切换的时候都会产生冲突。

比如：新闻中有list，产品中有list，而分成了两个vuex模块，或者是两个store，那么新闻切到产品以及产品切到新闻时，list在我们这里是同一个。会产生叠加的情况。

**Comment by hiyuki** [comment]
你是希望在两个模块中有两个模块管理但是复用list这个数据吗？你可以建立一个公共的store来存list状态，然后用多实例模式使用这个公共的store作为deps分别创建两个模块各自的store，这样两个模块的store都能访问并且操作公共store中的list数据

**Comment by chinavane** [comment]
不是复用，而是单独，比如说news新闻，我们对于数据的操作是list，产品也是list，订单也是list，所以news里的state键名是list，产品、订单都一样，但是不管是module还是多个store，在请求完news以后再操作product，那么product里的store数据还是会有news的。所以vuex里的namespace命名空间的作用就起来了，而我们现在是多store，但似乎state名称一致的时候，数据就会冲突。我们想要的是不一样，而不是一样去复用。

**Comment by chinavane** [comment]
<img width="450" alt="QQ20200619-104120@2x" src="https://user-images.githubusercontent.com/8588836/85091241-9c094080-b219-11ea-8eeb-d71b2f5dc623.png">

**Comment by chinavane** [comment]
每个模块的state状态值都应该是独立的，不然切换模块的时候就会产生问题。

**Comment by hiyuki** [comment]
不想要复用的话每个store当中都定义list就好了，为何会冲突？理论上多store能够实现namespace中的所有功能，能否提供一个namespace能实现但是多store实现不了的示例代码？

**Comment by hiyuki** [comment]
即使是在modules模式下每个模块的state也确实是有独立空间存储的，而getters/mutations/actions是复用的全局命名空间，这一点和vuex完全一致；多实例模式下合并多个store则是state/getters/mutations/actions都存在自己独立的命名空间，这也和namespace的效果一致

**Comment by chinavane** [comment]
[mpx-test.zip](https://github.com/didi/mpx/files/4802736/mpx-test.zip)

产品与新闻的数据格式是下面的内容
```
{"docs":[{"_id":"5ed4ba582133034a8c7d6786","title":"新闻1","id":"5ed4ba582133034a8c7d6786"},{"_id":"5ee7602d1a9373081a7d4eb8","title":"新闻2","id":"5ee7602d1a9373081a7d4eb8"},{"_id":"5ee760331a9373081a7d4eb9","title":"新闻3","id":"5ee760331a9373081a7d4eb9"},{"_id":"5ee760391a9373081a7d4eba","title":"新闻4","id":"5ee760391a9373081a7d4eba"},{"_id":"5ee7603f1a9373081a7d4ebb","title":"新闻5","id":"5ee7603f1a9373081a7d4ebb"},{"_id":"5ee760461a9373081a7d4ebc","title":"新闻6","id":"5ee760461a9373081a7d4ebc"},{"_id":"5ee7604d1a9373081a7d4ebd","title":"新闻7","id":"5ee7604d1a9373081a7d4ebd"},{"_id":"5ee760551a9373081a7d4ebe","title":"新闻8","id":"5ee760551a9373081a7d4ebe"},{"_id":"5ee7605e1a9373081a7d4ebf","title":"新闻9","id":"5ee7605e1a9373081a7d4ebf"},{"_id":"5ee760651a9373081a7d4ec0","title":"新闻10","id":"5ee760651a9373081a7d4ec0"}],"totalDocs":21,"limit":10,"totalPages":3,"page":1,"pagingCounter":1,"hasPrevPage":false,"hasNextPage":true,"prevPage":null,"nextPage":2}
```

**Comment by chinavane** [comment]
![Uploading question.gif…]()

**Comment by hiyuki** [comment]
这个单纯是因为你创建两个store的state都指向了同一个对象导致的，你可以通过函数返回对象字面量的方式让每个store创建时拿到一个全新的对象（类似vue当中用data函数返回全新的对象避免数据共享），这样就不会造成数据共享，以及多store模式下你不需要声明modules，直接以返回的storeObj创建store即可
