### ISSUE TITLE
[Bug report] wxs编译到支付宝下无效

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#488]
**问题描述**  
使用vant-weapp 的picker组件时发现按照示例指定columns为 ['杭州', '宁波', '温州', '嘉兴', '湖州'] 时，微信下显示正常，支付宝下却循环了5次picker-column，初步排查发现 isSimple(columns)的返回值为undefined，导致显示异常

**环境信息描述**  
至少包含以下部分：
1. Mac
2. 包版本
@mpxjs/core": "^2.5.11
@mpxjs/webpack-plugin": "^2.5.11
3. 支付宝小程序IDE版本 1.12.15

**最简复现demo**  
[demo.zip](https://github.com/didi/mpx/files/4817078/default.zip)

**Comment by sky-admin** [comment]
支付宝里……还和顺序有关，不能在最后引入，要去头顶引

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/85389055-81b4c700-b579-11ea-8a60-14a23f0a4d3d.png)

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/85389098-92653d00-b579-11ea-80e7-8462ec1b01b9.png)

**Comment by okxiaoliang4** [comment]
实测移到最上方可以了，不过看群里 @hiyuki 说要再仔细确定一下规则，看看是否webpack plugin处理，麻烦了，谢谢，我先自己移上去

**Comment by hiyuki** [comment]
fixed https://github.com/didi/mpx/releases/tag/v2.5.29
