### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Artmagic** [didi/mpx#489]
node 版本10.15.3
npm 版本 6.4.1
mpx/core 2.0.0

编译出现错误

![image](https://user-images.githubusercontent.com/20658775/85378982-c9cdec80-b56d-11ea-9c0d-57bdbc707987.png)
![image](https://user-images.githubusercontent.com/20658775/85379011-d5b9ae80-b56d-11ea-98d4-9fb0b8a6a94a.png)

demo下载
[ai.zip](https://github.com/didi/mpx/files/4818087/ai.zip)

**Comment by sky-admin** [comment]
这个项目不是用cli工具生成的吧？或者是发生过拷贝？.babel文件丢了，这种.开头的文件在mac下默认是隐藏文件，估计拷贝丢了。

**Comment by sky-admin** [comment]
用cli工具重新init一个项目，把src拷进新项目里即可。
