### ISSUE TITLE
[Bug report] 字节跳动小程序ad webpack 校验出错

### ISSUE THREAD

**Issue by wgqzlj** [didi/mpx#493]
**问题描述**  
npm run build:cross 的时候，提示：
```
<ad> is not supported in bytedance environment!
```

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows) mac
2. Mpx依赖版本:
>    "@mpxjs/api-proxy": "^2.5.20",
>    "@mpxjs/core": "^2.5.28",
>    "@mpxjs/fetch": "^2.3.9"

ad标签组件已经支持： https://microapp.bytedance.com/dev/cn/mini-app/develop/component/open-capacity/ad

**Comment by hiyuki** [comment]
ok 我们处理一下

**Comment by wgqzlj** [comment]
Thanks very much.
