### ISSUE TITLE
[Bug report] 支付宝下 externalClasses 无效

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#497]
**问题描述**  

使用 van-field 传入 input-class无效

**环境信息描述**  
mpx依赖版本：
"@mpxjs/core": "^2.5.28"
"@mpxjs/webpack-plugin": "^2.5.29"
支付宝IDE版本：1.12.15

**最简复现demo**  
[复现demo.zip](https://github.com/didi/mpx/files/4843710/default.zip)

**Comment by hiyuki** [comment]
MpxWebpackPlugin配置中传入externalClasses:['input-class']即可使用，需要用到其他的externalClasses的话同理传入到配置数组中即可

**Comment by okxiaoliang4** [comment]
哦哦，我的锅，放完假回来忘记了有这个配置……
