### ISSUE TITLE
添加小程序腾讯地图选点插件报错

### ISSUE THREAD

**Issue by flyjin** [didi/mpx#500]
在APP.mpx中添加
` "plugins": {
    "chooseLocation": {
      "version": "1.0.4",
      "provider": "wx76a9a06e5b4e693e"
    }
  },`
其他插件未测试 
run watch可以通过 无报错 但是在微信开发者工具中会报错
![微信截图_20200630093706](https://user-images.githubusercontent.com/16444854/86073108-b2cf5300-bab5-11ea-9abc-160e3a8e0ae5.png)

新建的mpx项目 都不行 
但是用原生的小程序新建一个项目测试  没有此问题

**Comment by zuonidelaowang** [comment]
我也是这个问题, 关注一下

**Comment by starql** [comment]
你们解决了这个问题了吗? 我使用高德一样在报错

**Comment by hiyuki** [comment]
这是之前脚手架的babel7配置通过preset-env使用了polyfill导致，使用最新的脚手架再创建一个babel7项目即可。
https://github.com/didi/mpx/releases/tag/v2.5.31

**Comment by starql** [comment]
感谢!
