### ISSUE TITLE
文档上内联样式 background-image 使用本地图片的疑问

### ISSUE THREAD

**Issue by xin2014** [didi/mpx#505]
通过实践得知内联样式使用本地图片作为背景图片在开发者工具上可以显示, 但是真机不显示, 例如下面的代码
![image](https://user-images.githubusercontent.com/7124907/87380658-87745a00-c5c5-11ea-9506-159b5c68cf48.png)

网上大多说是背景不支持本地图片, 少部分说内联样式的背景可以使用本地图片, 并且 mpx 的文档上也有这样写法
![image](https://user-images.githubusercontent.com/7124907/87379327-8b52ad00-c5c2-11ea-8e3d-1f210cc8f77b.png)

现在的问题是文档上的写法真的有效吗, 如果有效, 那么我的写法问题出在哪里, 如果无效, 为什么文档上会有这样的写法

**Comment by hiyuki** [comment]
开发者工具有效真机无效应该是小程序本身的限制，内联style中使用图像的限制应该和wxss相同，只支持cdn地址或者base64，目前对于js中引入的图片资源，编译时无法判断具体是在什么位置使用，所以会整体处理为本地路径(因为小程序也有很多地方是只支持本地路径不支持base64的)，后续会考虑支持一个?isStyle的query让用户主动声明js中引入的资源是否用于style，这样用于style的图像就能和wxss中得到同样的处理进而避免这个问题

**Comment by hiyuki** [comment]
关于文档中的写法应该单纯是我们在编写case时遗漏了真机测试，后续我们会修正

**Comment by hiyuki** [comment]
目前已支持?isStyle声明js中引入的资源是要在style中使用，上述示例问题可以用
