### ISSUE TITLE
[Bug report]构建为swan的时候，全局配置属性丢失

### ISSUE THREAD

**Issue by vivine** [didi/mpx#506]
**问题描述**  
mpx构建为百度小程序时，丢失全局配置属性：networkTimeout、permission、requiredBackgroundModes

原因如下：
https://github.com/didi/mpx/blob/c8b6f09491abf3553db90c2442099f9f94022962/packages/webpack-plugin/lib/platform/json/wx/index.js#L210-L220

在这个文件里做了删除。

**建议**
各家小程序都在持续更新迭代，所以希望mpx官方也定期检查配置，^@^

**Comment by vivine** [comment]
**补充**
使用 **条件编译的方式，写两块json配置** 这种方式还是不行，我猜想是因为条件编译执行在前，上面这个js执行在后的原因，所以官方修复的时候建议考虑一下这种需要临时救急的方案

**Comment by sky-admin** [comment]
条件编译写两块这个方式不可能不行啊

**Comment by sky-admin** [comment]
![image](https://user-images.githubusercontent.com/6292668/87410358-ca035a00-c5f8-11ea-9011-8024a42430a2.png)

**Comment by vivine** [comment]
> 条件编译写两块这个方式不可能不行啊

按照你的方法是可以了，但是我使用下面这种方法就不行，额~~~
```html
<script name="json">
    const config = {
        pages: {},
        window: {}
    }
    if (__mpx_mode__ === 'swan') {
        config.networkTimeout = {}
    }
    module.exports = config
</script>
```
