### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by liushooter** [didi/mpx#515]
node version v12.16.2
mpx version 2.5.30

初始化项目后，运行 `npm run watch` ， 提示错误 `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined`

一直在building.....

**Comment by hiyuki** [comment]
请把报错的项目删除node_modules后打包上传

**Comment by sky-admin** [comment]
#520
