### ISSUE TITLE
微信小程序分享到朋友圈，打开空白报错shareImageMessage:fail

### ISSUE THREAD

**Issue by yc0524** [didi/mpx#517]
https://developers.weixin.qq.com/community/develop/article/doc/0008c4d40f86c8faddaa240c156413

**Comment by yc0524** [comment]
![image](https://user-images.githubusercontent.com/33405012/88127961-84055200-cc07-11ea-9f84-ed4dc116e74d.png)

**Comment by hiyuki** [comment]
fixed https://github.com/didi/mpx/releases/tag/v2.5.33
