### ISSUE TITLE
初始化项目之后npm run watch之后报错，一直在building...

### ISSUE THREAD

**Issue by xcp3719** [didi/mpx#520]
### 环境信息
- 系统：macos 10.14.6
- node版本：v12.16.2
- @mpxjs/core: 2.5.11
### 操作步骤
1. 查看文档Introduction章节的【安装使用】
2. npm i -g @mpxjs/cli
3. mpx init mpx-project（选项为wx+no+yes+yes+yes+yes+no+no+mpx-project+A mpx project+'xcp'+touristappid）
4. cd mpx-project
5. npm I
6. npm run watch

### 情况说明
原来一直用微信小程序原生开发，今天想试试mpx。按照操作步骤之后，报错"(node:8554) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined"，然后命令行界面一直停留在⠸ building...。尝试过control+c停止，然后直接执行npm run build，依然报错"ERROR in Entry module not found: Error: Can't resolve '/Users/xiecp/project/mpx-project/src/miniprogram/app.mpx' in '/Users/xiecp/project/mpx-project'"。项目目录下也未生成dist文件夹，无法使用小程序开发工具进行查看。
### 希望结果
在macos 10.14.6执行npm run watch后能够正常运行初始项目，以便进行后续了解框架，进行开发体验
### 相关截图
- 执行npm run watch后
<img width="650" alt="image" src="https://user-images.githubusercontent.com/67538938/88750988-42d1ec80-d189-11ea-9f45-bcaa00eccc2f.png">

- 强制停止npm run watch，执行npm run build后
<img width="650" alt="image" src="https://user-images.githubusercontent.com/67538938/88752711-3059b200-d18d-11ea-99e6-a583250a9e4c.png">

- 定位到的相关代码（路径：/node_modules/@mpxjs/webpack-plugin/lib/index.js）
<img width="915" alt="image" src="https://user-images.githubusercontent.com/67538938/88753077-f2a95900-d18d-11ea-9fa1-1b11d5cb3380.png">

**Comment by sky-admin** [comment]
抱歉，模板这个配置下工作确实有点问题，这边会尽快修复

**Comment by xcp3719** [comment]
> 抱歉，模板这个配置下工作确实有点问题，这边会尽快修复
👌🏻

**Comment by sky-admin** [comment]
https://github.com/mpx-ecology/mpx-template/pull/58

**Comment by xcp3719** [comment]
谢谢你~
"是否需要使用小程序云开发能力"的选项选no可以正常初始化项目。模板项目那边还没merge，merge之后我再试试。

**Comment by sky-admin** [comment]
嗯嗯，云开发的模板我们还需要再调整调整，先不要用云开发能力吧

**Comment by xcp3719** [comment]
好的

**Comment by sky-admin** [comment]
先临时修复了下，应该是可用的了，关于云开发，可以参考这个：https://github.com/didi/mpx/tree/master/examples/mpx-cloud

**Comment by sky-admin** [comment]
OK，大的调整已经完成了。
