### ISSUE TITLE
[Bug report] 支付宝不支持自定义组件onTap

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#523]
**问题描述**  
以微信为base编译到支付宝上自定义组件bind:tap失效，是否有除了手动抛出tap事件外的优良方式

**环境信息描述**  
mac
"@mpxjs/core": "^2.5.28"

**最简复现demo**  

```html
<van-button bind:tap="xxx"></van-button>
```

**Comment by hiyuki** [comment]
我后续考虑一下
