### ISSUE TITLE
引入本地化的 iconfont 样式文件，会报错

### ISSUE THREAD

**Issue by ialmost** [didi/mpx#53]
![3](https://user-images.githubusercontent.com/6847189/50508015-f7da8980-0aba-11e9-9d7c-34a9daba2ed5.png)

**Comment by sky-admin** [comment]
建议用网络资源，或者在webpack.base.conf.js中@mpxjs/url-loader处test里添加相应的文件后缀比如：
test: /\.(png|jpe?g|gif|svg|ttf)$/
