### ISSUE TITLE
[Bug report]将.babelrc 替换为 babel.config.js 后发现 babel.config.js 没有生效。

### ISSUE THREAD

**Issue by li-kang** [didi/mpx#530]
**问题描述**  
将.babelrc 替换为 babel.config.js 后发现 babel.config.js 没有生效。

**环境信息描述**  
至少包含以下部分：
1. 系统类型Mac
2. Mpx依赖版本 2.5.33

**Comment by sky-admin** [comment]
生成项目时候是选的用babel7吗？babel7默认应该就是babel.config.js，babel6才是babelrc

**Comment by li-kang** [comment]
谢谢 确实是这样
