### ISSUE TITLE
[Bug report] 支付宝下 vant field 组件clearable无法清除输入框中内容

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#532]
**问题描述**  
支付宝下vant field 组件clearable无法清除输入框中内容
使用wx:model双向绑定后绑定值情况了但是输入框中的内容还存在
![image](https://user-images.githubusercontent.com/22525904/89404884-4814d580-d74d-11ea-8d8f-c669011cb60a.png)

**环境信息描述**  
至少包含以下部分：
1. Mac
2. mpx版本 
"@mpxjs/core": "^2.5.33"
"@mpxjs/webpack-plugin": "^2.5.33"
3. 支付宝IDE 1.13.4

**最简复现demo**  
[归档.zip](https://github.com/didi/mpx/files/5027842/default.zip)

**Comment by hiyuki** [comment]
我check一下

**Comment by okxiaoliang4** [comment]
排查发现微信小程序上 onClear 这一步 `this.setData({ innerValue: "" });` 即便这里innerValue本来就是空也可以将值置空
但支付宝环境却不行，怀疑支付宝更新逻辑省略掉相同值的更新

**Comment by okxiaoliang4** [comment]
> https://opendocs.alipay.com/mini/component/input
input 如何用 js 代码清空数据？
需要添加属性 controlled="{{true}}" ，也可以在 onInput 事件里把输入的值通过 setData 再赋值给 value，再去 setData 设置 value。

本想通过这个属性控制输入框内的值，但发现设置为false后值又变回出来了。怀疑只是切换了input值的一个变量引用，当`controlled`属性为true时切换用户的引用,false时用内部引用，所以该方案无效
```javascript
this.setData({ controlled: true }, () => {
    this.setData({ innerValue: "" });
    this.setData({ controlled: false });
});
```
后来使用以下方案进行替代
```javascript
if (__mpx_mode__ === "ali") {
    this.setData({ innerValue: " " }, () => {
        this.setData({ innerValue: "" });
    });
} else {
    this.setData({ innerValue: "" });
}
```
