### ISSUE TITLE
[Bug report] theme.json 无法被正确处理

### ISSUE THREAD

**Issue by jissin** [didi/mpx#535]
**问题描述**  
根据微信官方文档，theme.json 用来适配 dark mode，我在开发过程中发现的问题如下：
1. src/theme.json 不会被正确输出到 dist/theme.json
2. theme.json 中的键值对： "iconPath1": "static/icon1.png" 不会被正确替换成 "iconPath1": "img/icon1[hash].png"

**环境信息描述**  
1. macOS 10.15.6
2.  "@mpxjs/core": "^2.5.11", "@mpxjs/webpack-plugin": "2.5.33", "@mpxjs/api-proxy": "^2.5.10"

**最简复现demo**  
如需 demo 请回复

**Comment by okxiaoliang4** [comment]
把图片和 theme.json 放到static下应该可以

**Comment by jissin** [comment]
> 把图片和 theme.json 放到static下应该可以

src/static 吗？我试了没有效果

**Comment by okxiaoliang4** [comment]
项目根目录下 static/wx

**Comment by okxiaoliang4** [comment]
你脚手架模板根目录没有static目录吗，那你用的可能是旧的模板创建的项目，可以看看新版的build.js
https://github.com/mpx-ecology/mpx-template/blob/master/template/build/build.js
把 modeArr.forEach 里面的内容修改一下
```javascript
const plugins = [
    new MpxWebpackPlugin(Object.assign({
      mode: item,
      srcMode: userSelectedMode
    }, mpxWebpackPluginConfig))
  ]
  const copyList = [{
    context: resolve(`static/${item}`),
    from: '**/*',
    to: mainSubDir ? '..' : ''
  }]
plugins.push(new CopyWebpackPlugin(copyList))
```

再把merge options 的 plugins 替换成这个变量，试试

**Comment by sky-admin** [comment]
目前应该是确实有点问题的，我们尽快出个临时方案。

**Comment by jissin** [comment]
> 你脚手架模板根目录没有static目录吗，那你用的可能是旧的模板创建的项目，可以看看新版的build.js
> https://github.com/mpx-ecology/mpx-template/blob/master/template/build/build.js
> 把 modeArr.forEach 里面的内容修改一下
> 
> ```js
> const plugins = [
>     new MpxWebpackPlugin(Object.assign({
>       mode: item,
>       srcMode: userSelectedMode
>     }, mpxWebpackPluginConfig))
>   ]
>   const copyList = [{
>     context: resolve(`static/${item}`),
>     from: '**/*',
>     to: mainSubDir ? '..' : ''
>   }]
> plugins.push(new CopyWebpackPlugin(copyList))
> ```
> 
> 再把merge options 的 plugins 替换成这个变量，试试

请问怎么使用新的模版，我现在用最新版本的 cli 创建的项目也是没有 static 目录的

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.26 已经支持，按照微信小程序的规范正常编写即可
