### ISSUE TITLE
[Bug report] watch数组源为引用时oldValue表现与预期不符

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#539]
**问题描述**  
使用this.$watch或watch属性创建监听时，若数据源为对象watch callback的oldValue会与预期不符，总是会与newValue一致
![image](https://user-images.githubusercontent.com/22525904/89773337-4a54a680-db36-11ea-899e-df120b43d334.png)

**环境信息描述**  
Mac
mpx版本
"@mpxjs/core": "^2.5.33"
"@mpxjs/webpack-plugin": "^2.5.33"
支付宝IDE 1.13.4

**最简复现demo**  
[归档.zip](https://github.com/didi/mpx/files/5050243/default.zip)

**Comment by anotherso1a** [comment]
造成这种问题的原因是`watch`所监听的function的返回中的`this.test1`值为一个数组，所以当新值产生时也对原有值进行了更替。

**那既然两次结果一致为何又会触发watch的回调？**

由于watch监听的function返回值是一个新数组，内存地址一定与上次返回的数组不同，所以无论如何都会触发watch回调，可参考以下测试案例：

```js
createPage({
  data() {
    return {
      a:1,
      b:0
    };
  },
  onLoad() {
    this.$watch(
      () => {
        return [this.a + this.b];
      },
      function (newValue, oldValue) {
        console.log(JSON.stringify([newValue,oldValue]));
      }
    );
  },
  methods: {
    change() {
      this.a++
      this.b--
    }
  }
});
```

可以看到每次change方法执行，都会触发watch回调。

这个算是在实现上作出的取舍。如果是想同时监听多个值，可以使用expression字符串进行监听。

以上案例中的watch方法可改为：

```js
    this.$watch(
      "a,b",
      function (newValue, oldValue) {
        console.log(JSON.stringify([newValue,oldValue]));
      }
    );
```

**Comment by hiyuki** [comment]
这个返回符合预期，watch追踪函数中返回的数组是引用类型，新旧值里的引用都指向这个数组本身，想要解决也很简单，切断引用关系即可，比如返回的时候深拷贝或者stringify；
