### ISSUE TITLE
微信小程序PC端报错

### ISSUE THREAD

**Issue by MrBaoquan** [didi/mpx#548]
**微信小程序PC端报错**  
mpx init 初始工程都报错，在开发者工具及手机端没问题  PC端报错
是否现在不兼容PC端小程序?

**Comment by hiyuki** [comment]
之前确实没有专门做过pc小程序的兼容性测试，我们check一下

**Comment by Blackgan3** [comment]
@MrBaoquan  我们这边check了下，init 后项目在pc端可正常打开，麻烦补充下你的环境描述信息和**最小复现demo**吧

**Comment by hiyuki** [comment]
@MrBaoquan hello，上述所提问题我们在本地验证没有复现，如问题仍然存在，请按照issue指引提供详细复现环境描述及最简复现demo后再次打开。
