### ISSUE TITLE
[Bug report] swan 键值冲突

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#550]
**问题描述**  
js中没有包含id，但却提示冲突
![image](https://user-images.githubusercontent.com/22525904/90100120-9c800c80-dd6e-11ea-8aad-40b090fdc19d.png)
![image](https://user-images.githubusercontent.com/22525904/90100139-a30e8400-dd6e-11ea-9407-5fc93ddfb816.png)

**环境信息描述**  
至少包含以下部分：
mac
"@mpxjs/core": "^2.5.28"

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.3 已修复
