### ISSUE TITLE
[Bug report] swan 事件参数绑定动态值为null

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#553]
**问题描述**  

```html
<!-- 为静态值时可以正常传参 -->
<van-cell
    bind:click="onClick('aaa')"
    is-link
    value="aaa"
/>

<!-- 为动态属性值时参数为null -->
<van-cell
    bind:click="onClick(test.b)"
    is-link
    value="bbb"
/>
```
```javascript
{
    methods: {
        onClick(e) {
            console.log(e)
        }
    }
}
```

**环境信息描述**  
至少包含以下部分：
mac
@mpx/core@2.5.28
@mpx/webpack-plugin@2.6.3

**最简复现demo**  
[归档.zip](https://github.com/didi/mpx/files/5073345/default.zip)

**Comment by hiyuki** [comment]
这个看上去像是百度小程序框架的限制，只有初始数据可以通过dataset传入，比如你示例中将data函数改为对象即可正常工作，这个限制从mpx框架层面应该无法突破，只能修改业务写法规避...

**Comment by okxiaoliang4** [comment]
![image](https://user-images.githubusercontent.com/22525904/90240466-dc70ed80-de5b-11ea-8b3d-a3dda7666a64.png)
![image](https://user-images.githubusercontent.com/22525904/90240479-e266ce80-de5b-11ea-9f86-29e558a8cc3d.png)

那这个呢，在for循环上是可以正常的获取到的喔
