### ISSUE TITLE
[Bug report] 获取properties有误

### ISSUE THREAD

**Issue by DroganC** [didi/mpx#554]
跨平台输出web模式；
小程序端获取组件properties  ：
` properties: {
      span: {
        type: [String, Number],
        value: 24
      },
      offset: {
        type: Number,
        value: 0
      },
      gutter: {
        type: Number,
        value: 0
      }`
console.log(this.span)会直接打印出properties对象本身包括data里的数据； web打印正常；

![image](https://user-images.githubusercontent.com/32896700/90228782-6cf20280-de49-11ea-8380-d0be9ee34c9d.png)

**Comment by DroganC** [comment]
`"dependencies": {
    "@miniprogram-component-plus/col": "^1.0.0",
    "@miniprogram-component-plus/row": "^1.0.0",
    "@mpxjs/api-proxy": "^2.5.33",
    "@mpxjs/core": "^2.6.0",
    "eventemitter3": "^4.0.4",
    "figlet": "^1.5.0",
    "inquirer": "^7.3.3",
    "lodash": "^4.17.19",
    "vue": "^2.6.11",
    "vue-i18n": "^8.21.0",
    "wux-weapp": "^3.8.6"
  },
  "devDependencies": {
    "copy-webpack-plugin": "^5.0.3",
    "@mpxjs/webpack-plugin": "^2.5.31",
    "http-server": "^0.12.0",
    "npm-run-all": "^4.1.5",
    "extract-text-webpack-plugin": "^3.0.2",
    "html-webpack-plugin": "^3.2.0",
    "vue-loader": "^14.2.4",
    "vue-router": "^3.1.3",
    "vue-template-compiler": "^2.6.10",
    "style-loader": "^1.0.1",
    "ts-loader": "^6.0.0",
    "typescript": "^3.5.0",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "@babel/core": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.10.4",
    "@babel/preset-env": "^7.10.4",
    "@babel/runtime-corejs3": "^7.10.4",
    "babel-loader": "^8.1.0",
    "chalk": "^2.3.2",
    "css-loader": "^0.28.11",
    "file-loader": "^1.1.11",
    "html-loader": "^0.5.5",
    "ora": "^2.0.0",
    "path": "^0.12.7",
    "rimraf": "^2.6.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "url-loader": "^1.0.1",
    "webpack": "^4.16.1",
    "webpack-cli": "^3.1.0",
    "webpack-merge": "^4.1.2",
    "webpack-bundle-analyzer": "^3.3.2",
    "commander": "^6.0.0",
    "less": "^3.11.3",
    "less-loader": "^6.1.0",
    "terser-webpack-plugin": "^4.1.0"
  }`

**Comment by okxiaoliang4** [comment]
#552 已解决，等下版本发布即可，如果比较急可以按照这个pr自己手改先

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.4 已修复
