### ISSUE TITLE
[Bug report] 条件渲染失效

### ISSUE THREAD

**Issue by neeblue** [didi/mpx#560]
**问题描述**  
1. 条件渲染失效：wx:if 为 true 时，wx:else 仍然会渲染

**环境信息描述**  
1. @mpxjs/webpack-plugin 版本为 2.6.8

**Comment by hiyuki** [comment]
感谢反馈，上一版本会导致wx:else在编译后被意外移除，目前新版已修复https://github.com/didi/mpx/releases/tag/v2.6.9
