### ISSUE TITLE
[Bug report] 支付宝端selectComponent失效

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#561]
**问题描述**  
使用selectComponent支付宝端失效，排查发现2.6.x版本都有问题，降为2.5.x就ok了，2.6.x 版本`__children__[]. identifiers`都为空数组

**环境信息描述**  
macos 10.15.3
@mpxjs/core@2.6.x
小程序IDE 1.13.7

**最简复现demo**

**Comment by hiyuki** [comment]
感谢反馈，已修复 https://github.com/didi/mpx/releases/tag/v2.6.10

**Comment by okxiaoliang4** [comment]
v2.6.10 id选择器还是有丢失的情况
![image](https://user-images.githubusercontent.com/22525904/91698132-ccb80f80-eba4-11ea-9b62-e70aa5bf5862.png)
![image](https://user-images.githubusercontent.com/22525904/91698140-cfb30000-eba4-11ea-9043-108a12de08c2.png)

退回到2.5.x是OK的
![C61DA8183490D956F8EC28C017A06379](https://user-images.githubusercontent.com/22525904/91698194-e5c0c080-eba4-11ea-819c-3ec1e49849fc.jpg)
