### ISSUE TITLE
请问“是否需要配置Dll”是什么意思？有什么作用？

### ISSUE THREAD

**Issue by cheese-git** [didi/mpx#571]
初始化项目时有这个选项，官方文档中没有找到相应的内容。

**Comment by Blackgan3** [comment]
配置dll 是为了将较大的bundle文件拆解打包，提升构建速度，使用了webpack的DllPlugin 和  DllReferencePlugin 插件来提供给小程序开发的能力

选择配置 dll 后，可以在 build 文件夹下的 dll.config.js 文件中进行 dll 文件配置，具体的配置文档我们整理下稍后发你

**Comment by cheese-git** [comment]
感谢 :pray:

**Comment by qiwang97** [comment]
@Blackgan3 能发一份 dll 文件配置或者在文档增加这部分说明么
