### ISSUE TITLE
无法引入 vant-dialog 组件

### ISSUE THREAD

**Issue by Sanzro-Lee** [didi/mpx#573]
**问题描述**  
1. 问题触发的条件
```
<script type="application/json">
{
  "usingComponents": {
      // 引入 vant-dialog
      "van-dialog": "vant-weapp/dist/dialog/index"
  }
}
</script>
```

2. 期望的表现
正常引入 van-dialog 组件。

3. 实际的表现
微信小程序开发工具报错：Component is not found in path "components/vant-weapp3df1e56b/dialog/index"。

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
macOS

2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
"@mpxjs/core": "^2.6.12",
"@mpxjs/webpack-plugin": "2.6.11",
"@mpxjs/api-proxy": "^2.5.33",

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
小程序平台：微信
开发者工具版本：1.03.2008270
基础库版本：2.12.2

**最简复现demo**  
已上传。
[van-dialog-demo.zip](https://github.com/didi/mpx/files/5179587/van-dialog-demo.zip)

**Comment by sky-admin** [comment]
vant dialog 组件的位置是 vant-weapp/dist/dialog/index ，按你上面写的内容搞应该是没问题的，你的demo可以复现问题，但是里面写的组件地址是 vant-weapp/dist/dialog/dialog ，这是不对的。

**Comment by Sanzro-Lee** [comment]
在<script></script>中引入，应该为：
```
<script>
import Dialog from 'vant-weapp/dist/dialog/dialog.js'
</script>
```

在<script type="application/json></script>中，则按照vant-weapp官网正常引入：
<script type="application/json">
{
  "usingComponents": {
    "van-dialog": "vant-weapp/dist/dialog/index"
  }
}
</script>

另外我是在<van-icon bindtap="clickDialog"></van-icon>绑定方法，去触发Dialog.alert({})，但是会有样式的问题。
