### ISSUE TITLE
使用mpx开发的小程序，在微信电脑版中打不开，都是空白页面

### ISSUE THREAD

**Issue by jackrouse** [didi/mpx#578]
**问题描述**  
使用mpx开发的小程序，在微信电脑版中打不开，都是空白页面

**环境信息描述**  
1. Window 微信客户端=》小程序面板=》最近使用小程序=》点击打开小程序。

**最简复现demo**  
 Window 微信客户端 打开滴滴出行小程序也是空白

**Comment by Blackgan3** [comment]
已经定位到问题，下个版本会发布修复

**Comment by Blackgan3** [comment]
@jackrouse  如果这会儿需要在 pc 端预览的话，可以开启开发者工具的增强编译选项，就可以打开了

**Comment by xugongyang** [comment]
> https://github.com/didi/mpx/releases/tag/v2.6.15 已修复

没有修复吧，mpx 版本 2.6.22, 发布生产的小程序，在PC  微信打开仍然是白屏
