### ISSUE TITLE
使用vant组件编译时 Build failed with errors.

### ISSUE THREAD

**Issue by DaQI-X** [didi/mpx#580]
**问题描述**  
mpx开发小程序中引入vant组件，npm run build:cross 不成功。
![image](https://user-images.githubusercontent.com/32231997/92566439-cfa2b680-f2ae-11ea-85aa-155dbb60bd28.png)

**环境信息描述**  
Windows
Mpx脚手架构建

**最简复现demo**  

[createMpx.zip](https://github.com/didi/mpx/files/5193255/createMpx.zip)

**Comment by sky-admin** [comment]
这个问题首先是之前改造模板时候遗漏了个点，导致多平台构建时候错误信息没有被打印出来，在build.js 199行，把原来的日志打印替换成这个：
```js
if (Array.isArray(stats.stats)) {
    stats.stats.forEach(item => {
      console.log(item.compilation.name + '打包结果：')
      process.stdout.write(item.toString({
        colors: true,
        modules: false,
        children: false,
        chunks: false,
        chunkModules: false,
        entrypoints: false
      }) + '\n\n')
    })
  } else {
    process.stdout.write(stats.toString({
      colors: true,
      modules: false,
      children: false,
      chunks: false,
      chunkModules: false,
      entrypoints: false
    }) + '\n\n')
  }
```
然后就可以看到错误具体是什么了

**Comment by sky-admin** [comment]
然后是vant组件本身是微信小程序的组件库，Mpx框架虽然可以进行跨平台编译来让它变得可以用于支付宝/百度等小程序平台，但是这个过程是一个能转就转，转不了的报错提示，然后需要用户自行通过条件编译来抹平这样一个行为。
上面那个日志输出的部分修改完毕后，再执行 npm run build:cross 就可以看到，微信里构建是没有任何问题的，支付宝报了一些warning，但是没有error，说明可能可以工作但有可能存在一些问题/风险，百度下就报了一些error了，说明vant存在一些无法转换到百度小程序的点。
接下来就是三个方案了，一个是通过alias能力自行修复vant在百度里的兼容问题，二个是找找有没有百度下的组件库通过条件编译在百度环境下用支持百度的组件库，三是可以期待下我们后续的跨端UI组件库。

**Comment by DaQI-X** [comment]
好的，非常感谢！
