### ISSUE TITLE
[Bug report] 高德地图微信小程序SDK集成set property ’AMAPWX‘ of undefined

### ISSUE THREAD

**Issue by TrevorYS** [didi/mpx#586]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
 高德地图微信小程序SDK集成set property ’AMAPWX‘ of undefined
2. 期望的表现
3. 实际的表现
![image](https://user-images.githubusercontent.com/19200800/92705224-1dd6b900-f386-11ea-863b-8a726c0fe2c4.png)
![image](https://user-images.githubusercontent.com/19200800/92705242-23340380-f386-11ea-8c1e-d684f7152a3f.png)

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

demo：
[mpx-amap.zip](https://github.com/didi/mpx/files/5200330/mpx-amap.zip)

**Comment by Blackgan3** [comment]
在使用 commonJs， 并且直接引入构建好的 es5 代码时，不能再次经过 babel 编译
修改方法：
在 babel-loader 处添加对 utils/amap-wx.js 的过滤

```
// webpack.conf.js   中  rules
{
    test: /\.js$/,
    loader: 'babel-loader',
    include: [resolve('src'), resolve('test'), resolve('node_modules/@mpxjs')],
    exclude: [resolve('src/utils/amap-wx.js')]
  },
```
