### ISSUE TITLE
页面事件处理函数onTabItemTap无法使用

### ISSUE THREAD

**Issue by idenet** [didi/mpx#59]

**Comment by sky-admin** [comment]
因为MPX使用Component创建的页面，所以这个地方工作和预期不符。
之所以要使用Component创建页面是为了解决父子组件传递props时机问题。
微信文档上说了可以使用Component来创建页面：https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html
所以目前这个问题在尝试推动微信方面解决。

**Comment by pkingwa** [comment]
已推微信修复中

**Comment by sky-admin** [comment]
据悉微信已修复
