### ISSUE TITLE
[Bug report] wechat-miniprogram 版本问题

### ISSUE THREAD

**Issue by SuperHuangXu** [didi/mpx#596]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. @mpxjs/core 中 wechat-miniprogram 的版本是 `^2.8.3`， 所以安装了 [2.12.0 版本](https://github.com/wechat-miniprogram/api-typings/blob/2.12.0/types/wx/lib.wx.api.d.ts)，但这个版本里没有`createRewardedVideoAd`定义， `2.8.3`和`3.0.2` 都有这个定义，需要将`@mpxjs/core`里的版本更新下。

**环境信息描述**  
@mpxjs/core 2.6.17

**Comment by hiyuki** [comment]
好的，感谢反馈~ pr已合入，下个版本release
