### ISSUE TITLE
[Bug report] corejs 3 document undefined

### ISSUE THREAD

**Issue by bingtsingw** [didi/mpx#605]
**问题描述**  
PC版微信打开小程序报错. 调研发现是core-js的[bug](https://github.com/zloirock/core-js/issues/865), 我向上游仓库提交了[pr](https://github.com/zloirock/core-js/pull/866), 但是不知道啥时候才能release, 希望能先在webpack plugin里面hack一下, 谢谢

**环境信息描述**  
1. 系统类型: Windows版微信最新
2. Mpx依赖版本: 全部最新, corejs 3

**Comment by Blackgan3** [comment]
好的，我们跟进下，补充下你用的mpx版本信息吧，其他信息也尽量补充全哈

**Comment by Blackgan3** [comment]
上传个最小复现 demo 吧

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.24 已经处理
