### ISSUE TITLE
[Bug report] mac端自动真机调试启动报错

### ISSUE THREAD

**Issue by yangcore** [didi/mpx#608]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
微信小程序开发工具，mac端自动真机调试启动报错
![image](https://user-images.githubusercontent.com/20217483/94360802-b7220100-00e2-11eb-837d-cb5006754e92.png)
2. 期望的表现
无报错，正常使用
3. 实际的表现
有报错如上图

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
@mpxjs/webpack-plugin: 2.6.20
@mpxjs/core:2.6.19
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
微信小程序 开发工具版本：1.03.2008270 基础库：2.9.3

**Comment by Blackgan3** [comment]
我这边试了一下，并没有复现这个问题，还请提供一个可以复现的demo

**Comment by yangcore** [comment]
> 我这边试了一下，并没有复现这个问题，还请提供一个可以复现的demo

![image](https://user-images.githubusercontent.com/20217483/94545604-55e36480-027f-11eb-9a1f-f125acaa0377.png)
![image](https://user-images.githubusercontent.com/20217483/94545669-6dbae880-027f-11eb-8b40-31a947e5ac39.png)

自带demo即可复现

**Comment by Blackgan3** [comment]
好的，我这块是最新的开发者工具测试的，找不到你这个对应的开发者工具版本了，你升级下开发者工具试下呢

**Comment by Blackgan3** [comment]
升级下基础库吧，用2.12版本，新版本基础库是没问题的
