### ISSUE TITLE
[Bug report] 用新模板搭建项目使用alias异常

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#612]
**问题描述**  
webpack使用alias打包axml时提示无对应loader

```
ERROR in ./src/components/@vant/skeleton/index.axml?context=/Users/jelf/project/fontend/mpx-template-1/src&mode=ali&packageName=main 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <import-sjs from="~@vant/weapp/dist/wxs/utils.wxs" name="utils" />
| <view a:if="{{ loading }}" class="custom-class {{ utils.bem('skeleton', [{animate}]) }}">
|     <view a:if="{{ avatar }}" class="avatar-class {{ utils.bem('skeleton__avatar', [avatarShape])}}" style="{{ 'width:' + avatarSize + ';height:' + avatarSize }}" />

  Build failed with errors.
```

**环境信息描述**  
至少包含以下部分：
Mac
"@mpxjs/core": "^2.6.22"
"@mpxjs/webpack-plugin": "^2.6.22"

**最简复现demo**  
[归档.zip](https://github.com/didi/mpx/files/5302870/default.zip)

**Comment by hiyuki** [comment]
这个问题是各种resolve配置综合作用产生的特殊case，流程大概是这样的，对于app.mpx的usingComponents中skeleton/index这个request，在ali mode下，mpx回去优先查找skeleton/index.ali，然后由于extension中配置了.wxml，resolver会尝试查找skeleton/index.ali.wxml，然后由于alias中又这个配置，所以resolve到了这个alias的目标skeleton/index.axml，然后将其当做一个入口js进行处理，引发parse错误。。。

mpx文件条件编译这块当时考虑了很久，为了最好地兼容alias，这个处理逻辑不好进行变动，对于本case来说，在原始request中显式声明拓展名skeleton/index.js即可规避。。
