### ISSUE TITLE
[Bug report] 百度externalClasses与wx:class冲突

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#619]
**问题描述**  
百度环境使用了externalClasses的element上使用wx:class会导致externalClasses失效

```html
<template minapp="mpx" xlang="wxml">
    <view>
        <view class="custom-class t2 {{testClass}}"> text </view>
        <view class="custom-class t2" wx:class="{{ [testClass] }}"> text </view>
    </view>
</template>
```
可以看到element2个样式不一样

**环境信息描述**  
至少包含以下部分：
Mac
"@mpxjs/core": "^2.6.23"
"@mpxjs/webpack-plugin": "^2.6.25"
百度开发工具v3.17.1
基础库版本3.210.115

**最简复现demo**  
[归档.zip](https://github.com/didi/mpx/files/5390689/default.zip)

**Comment by okxiaoliang4** [comment]
第二个问题：

app.json pages配置一个不存在的页面文件，然后配置webpack.resolve.alias到一个实际存在的页面，没报错，但无法正常输出页面

```
// app.json
{
  "pages": ["./pages/test2","./pages/test3"]
}

// webpack.resolve
{
  extensions: [".mpx", ".js", ".wxml"],
  modules: ["node_modules"],
  alias: {
    [resolveSrc() + "/pages/test3"]: resolveSrc() + "/pages/test2",
  }
}
```

test3页面没有正常输出
![image](https://user-images.githubusercontent.com/22525904/96244669-f4d6c300-0fd8-11eb-8251-7a59656e4e97.png)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.29
