### ISSUE TITLE
sass-resources-loader没有效果

### ISSUE THREAD

**Issue by sousuo28** [didi/mpx#62]
配置如下：
```javascript
{
        test: /\.scss$/,
        use: [
          {loader: 'css-loader', options: {sourceMap: true}},
          {loader: 'sass-loader', options: {sourceMap: true}},
          {
            loader: 'sass-resources-loader',
            options: {
              sourceMap: true,
              resources: [
                resolve('src/styles/mixins.scss')
              ]
            }
          }
        ]
      }
```
在.mpx文件中和.scss文件中均无法找到mixins.scss文件中定义的function
求问这个是哪里配置错误了么？

**Comment by hiyuki** [comment]
对于.scss文件应该是完全走你在rules中的配置，框架不会做处理，如果纯.scss文件有问题应该是配置的问题，对于.mpx中特殊配置需要通过往mpx-loader中传递形如loaders:{scss:[...]}的配置来处理lang="scss"的style

**Comment by sousuo28** [comment]
> 对于.scss文件应该是完全走你在rules中的配置，框架不会做处理，如果纯.scss文件有问题应该是配置的问题，对于.mpx中特殊配置需要通过往mpx-loader中传递形如loaders:{scss:[...]}的配置来处理lang="scss"的style

感谢大佬。这么久没close不好意思。根据提示研究出来了：

**Comment by leowang1028** [comment]
你好，你这个是配置在mpx.plugin.conf的modeRules中的吗？

**Comment by leehomyfch** [comment]
> 对于.scss文件应该是完全走你在rules中的配置，框架不会做处理，如果纯.scss文件有问题应该是配置的问题，对于.mpx中特殊配置需要通过往mpx-loader中传递形如loaders:{scss:[...]}的配置来处理lang="scss"的style

请问为什么我最新mpx脚手架中,写的scss文件他会自动帮我编译成wxss
