### ISSUE TITLE
[Bug report] app.json resolve页面与预期不符

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#620]
**问题描述**  
补上个月的issue

app.json pages配置一个不存在的页面文件，然后配置webpack.resolve.alias到一个实际存在的页面，没报错，但无法正常输出页面

```
// app.json
{
  "pages": ["./pages/test2","./pages/test3"]
}

// webpack.resolve
{
  extensions: [".mpx", ".js", ".wxml"],
  modules: ["node_modules"],
  alias: {
    [resolveSrc() + "/pages/test3"]: resolveSrc() + "/pages/test2",
  }
}
```

test3页面没有正常输出
![image](https://user-images.githubusercontent.com/22525904/96244669-f4d6c300-0fd8-11eb-8251-7a59656e4e97.png)

**环境信息描述**  
至少包含以下部分：
Mac
"@mpxjs/core": "^2.6.23"
"@mpxjs/webpack-plugin": "^2.6.25"
百度开发工具v3.17.1
基础库版本3.210.115

**最简复现demo**  
[归档.zip](https://github.com/didi/mpx/files/5390689/default.zip)

**Comment by hiyuki** [comment]
这个是符合预期的，因为你demo用alias把test3指向了test2，而原本page中就存在test2，经过去重后最终输出test2是符合预期的，如果你把test3指向test，最终能够按照预期输出test2和test两个页面
