### ISSUE TITLE
[Bug report] dark mode 适配问题

### ISSUE THREAD

**Issue by jissin** [didi/mpx#622]
**问题描述**  
2.6.26 版本支持了 dark mode 的适配，我使用后发现了问题：

mpx 编译之后，theme.json 会被编译到 /JSON/theme[hash].json
对应的 app.json 里会有："themeLocation": "/JSON/theme[hash].json"

此时开发是没问题的，但是在微信开发者工具中点击预览会报错，提示 800059，导致无法预览

"themeLocation": "./theme.json" 会报同样的错
"themeLocation": "theme.json" 表现正常
"themeLocation": "theme123.json" 表现正常

所以，可能 mpx 需要把 theme.json 编译输出到根目录才能解决

不过这其实不是 mpx 的问题，应该是微信开发者工具的 bug，我已经问了官方以后会不会支持 thme.json 自定义路径，但是还没有收到回复

可以用这个 demo 测试一下，在 app.json 里更改 themeLocation 的值，然后点击预览就能看到效果

[minicode-1.zip](https://github.com/didi/mpx/files/5406181/minicode-1.zip)

**Comment by hiyuki** [comment]
我这边测试发现json输出位置可以任意，但是在app.json中写的themeLocation路径不能以/或者./开头，不过微信官方文档示例中介绍themeLocation时的示例就是用的/开头。。。也是挺乌龙的。。。

目前最新版本@mpxjs/webpack-plugin@2.6.27中已经处理
