### ISSUE TITLE
Component 配置项里目前没有支持 styleIsolation 选项

### ISSUE THREAD

**Issue by Inchill** [didi/mpx#624]
<img width="300" alt="截屏2020-10-22 下午5 38 50" src="https://user-images.githubusercontent.com/44435802/96854171-cd2aa380-148d-11eb-961f-b85e9c6e3870.png">
<img width="279" alt="截屏2020-10-22 下午5 28 27" src="https://user-images.githubusercontent.com/44435802/96854204-d4ea4800-148d-11eb-9b62-fb478e715280.png">

**Comment by hiyuki** [comment]
ok，我们更新一下定义文件

**Comment by hiyuki** [comment]
已修复，https://github.com/didi/mpx/releases/tag/v2.6.30
