### ISSUE TITLE
component  动态组件失效

### ISSUE THREAD

**Issue by huangjincq** [didi/mpx#627]
微信版本 7.0.19 使用动态组件失效了，无法切换组件。希望调查一下原因

**Comment by huangjincq** [comment]
"@mpxjs/api-proxy": "^2.5.10",
"@mpxjs/core": "^2.5.11",
 "@mpxjs/fetch": "^2.3.9",

**Comment by hiyuki** [comment]
请按照bug report issue指引，提供一个简单的复现demo
