### ISSUE TITLE
[Bug report] 使用分包wx:class异常

### ISSUE THREAD

**Issue by naifen00** [didi/mpx#630]
**问题描述**  
使用分包后，分包模板内使用了wx:class的元素 class标签都会消失

**Comment by yuu2lee4** [comment]
同样的问题

**Comment by hiyuki** [comment]
请按照指引提供环境描述及简单复现demo

**Comment by naifen00** [comment]
框架升级到最新好了

**Comment by yuu2lee4** [comment]
最新框架yarn watch没问题，yarn watch:prod或者yarn build还是有问题
