### ISSUE TITLE
QQ小程序和微信小程序的订阅消息接口差异

### ISSUE THREAD

**Issue by moonou** [didi/mpx#632]
# 描述

在 QQ小程序 中订阅消息的接口为 `qq.subscribeAppMsg` [文档](https://q.qq.com/wiki/develop/miniprogram/API/open_port/port_subscription.html)

在微信小程序中订阅消息调用为 `wx.requestSubscribeMessage` [文档](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/subscribe-message/wx.requestSubscribeMessage.html)

在使用 mpx 推荐的兼容写法 `mpx.requestSubscribeMessage` 无法实现自动代理到 QQ小程序 对应的API中。对于这种情况下 mpx 目前的方案可以通过配置实现吗？

# 备注
可以在 QQ小程序 通过 `mpx.subscribeAppMsg` 调用到接，但是这样就需要做平台判断。另外，由于项目使用了 TypeScript ，这样使用会在类型推导上产生错误。

**Comment by Blackgan3** [comment]
我们下个版本支持下
  mpx.requestSubscribeMessage 在QQ小程序中转换为 qq.subscribeAppMsg

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.32 已支持
