### ISSUE TITLE
[Bug report] component中slot失效

### ISSUE THREAD

**Issue by pagnkelly** [didi/mpx#633]
在`<component>`里的slot如果写了wx:if的判断   则只会在usingComponents引入的第一个组件生效，其他组件只渲染初始wx:if的判断

![image](https://user-images.githubusercontent.com/16016300/97665340-3164ed00-1ab6-11eb-9dd0-633a8b8705b5.png)
![image](https://user-images.githubusercontent.com/16016300/97665419-55283300-1ab6-11eb-89aa-378927e8bf36.png)

期望a ， b 组件表现一致， 一秒后wx:if判断切换都展示1234

demo地址：   https://github.com/pagnkelly/mpx-issue

**Comment by hiyuki** [comment]
已修复 https://github.com/didi/mpx/releases/tag/v2.6.31
