### ISSUE TITLE
通过this.xxx形式赋值无效，console.log打印数据正确，但appdata中没有，页面没变化

### ISSUE THREAD

**Issue by OliverCN** [didi/mpx#634]
直接上代码

```
<template>
  <view class="container">
    <button bindtap="onClick">点击</button>
  </view>
</template>

<script>
import { createPage } from "@mpxjs/core";
createPage({
  data: {
    list: []
  },
  methods: {
    onClick() {
      const arr = [
        {
          name: "J",
          age: 1
        },
        {
          name: "K",
          age: 2
        }
      ];
      this.list = arr;
      console.log(this.list);
    }
  }
});
</script>
```
点击之后不能正确赋值，但打印this.list却是正常的

![Snipaste_2020-11-02_17-10-15](https://user-images.githubusercontent.com/6055762/97850044-73986380-1d2e-11eb-8419-8275038e374a.png)
![Snipaste_2020-11-02_17-11-05](https://user-images.githubusercontent.com/6055762/97850056-772bea80-1d2e-11eb-8611-4b2abb9e5785.png)

版本：
"@mpxjs/core": "^2.6.22",
"@mpxjs/webpack-plugin": "^2.6.22",

**Comment by hiyuki** [comment]
这个表现是符合预期的，这个是Mpx做的优化项之一，模板上未使用的数据不会发送到视图层，但是不会影响你在逻辑层使用，比如你上述示例中在模板中写个列表渲染，appData中就会展示

**Comment by OliverCN** [comment]
> 这个表现是符合预期的，这个是Mpx做的优化项之一，模板上未使用的数据不会发送到视图层，但是不会影响你在逻辑层使用，比如你上述示例中在模板中写个列表渲染，appData中就会展示

嗯，我试了下确实可以，不过也遇到个现象无法解释，先看我的代码

```
<template>
  <view class="container">
    <button bindtap="onClick">赋值</button>
    <button bindtap="onDisplay">显示</button>
    <view wx:if="{{show}}">{{
      user.name + "-" + user.age + "-" + user.addr
    }}</view>
  </view>
</template>

<script>
import { createPage } from "@mpxjs/core";
createPage({
  data: {
    user: {
      name: "",
      age: "",
      addr: ""
    },
    show: false
  },
  methods: {
    onClick() {
      this.user = {
        name: "JJ",
        age: 23,
        addr: "北京市"
      };
    },
    onDisplay() {
      this.show = true;
    }
  }
});
</script>
```
实际场景是请求完接口后才把数据以弹窗的形式展示，这里就模拟了下

当我在template里只显示name和age两个属性的时候，一切正常，但当我加上addr这个属性时，就全显示不出来了，有点奇怪，不知道是什么原因

**Comment by hiyuki** [comment]
我这边直接粘贴你的代码测试时没有问题的，提供一下完整的复现demo及环境描述把，比如系统，开发者工具版本，基础版本等
