### ISSUE TITLE
@mpxjs/core 2.6.22版本，app实例上挂载方法失败

### ISSUE THREAD

**Issue by Memorn** [didi/mpx#638]
报错信息：

host-report-errors.js:6 Unhandled promise rejection TypeError: K.setShopListTimer is not a function

代码示例：
app.mpx
------------------------------------
createApp({
  methods: {
    setShopListTimer () {
      let { shopListTimer } = this.globalData
      let { shopList } = store.state
      if (shopListTimer || (shopList && shopList.length === 0)) {
        return
      }
      this.globalData.shopListTimer = setInterval(() => {
        this.shopListFormat()
      }, 1000)
    },
    clearShopListTimer () {
      if (this.globalData.shopListTimer) {
        clearInterval(this.globalData.shopListTimer)
      }
    }
  }
})
-----------------------------------------
home/index.mpx

const app = getApp()

// 上拉加载事件监听
onReachBottom () {
    // TODO 上拉加载结合scroll完善loading效果
    if (this.noMoreShops) { return }
    this.getFeedIndex()
},
// 获取首页商户数据
    getFeedIndex:  function () {
       ....
        app.setShopListTimer() // 启动商户状态标签更新定时器
     ....
    },
onUnload () {
    app.clearShopListTimer() // 销毁全局处理商户营业时间定时器
    this.clearPolling(this.tid) // 关闭页面时清除进行中订单轮询
}
-------------------------------------------

**Comment by zhaoyiming0803** [comment]
> 报错信息：
> 
> host-report-errors.js:6 Unhandled promise rejection TypeError: K.setShopListTimer is not a function
> 
> ## 代码示例：
> app.mpx
> ## createApp({
> methods: {
> setShopListTimer () {
> let { shopListTimer } = this.globalData
> let { shopList } = store.state
> if (shopListTimer || (shopList && shopList.length === 0)) {
> return
> }
> this.globalData.shopListTimer = setInterval(() => {
> this.shopListFormat()
> }, 1000)
> },
> clearShopListTimer () {
> if (this.globalData.shopListTimer) {
> clearInterval(this.globalData.shopListTimer)
> }
> }
> }
> })
> home/index.mpx
> 
> const app = getApp()
> 
> ## // 上拉加载事件监听
> onReachBottom () {
> // TODO 上拉加载结合scroll完善loading效果
> if (this.noMoreShops) { return }
> this.getFeedIndex()
> },
> // 获取首页商户数据
> getFeedIndex: function () {
> ....
> app.setShopListTimer() // 启动商户状态标签更新定时器
> ....
> },
> onUnload () {
> app.clearShopListTimer() // 销毁全局处理商户营业时间定时器
> this.clearPolling(this.tid) // 关闭页面时清除进行中订单轮询
> }

为了和小程序 api 对齐，现在 createApp 中 通过 methods 定义的方法默认不会被 dissolve 到 app 实例上，可以通过 mixin 的方式解决，如下：

``` script
createApp({
    mixins: [{
      setShopListTimer () {
        console.log('mixin print')
      }
    }]
})
```

``` script
const app = getApp()
  createPage({
    onReachBottom () {
       app.setShopListTimer()
    }
})
```
