### ISSUE TITLE
wx:for 时，改变item中的属性不会生效

### ISSUE THREAD

**Issue by ialmost** [didi/mpx#64]
wx:for 时，改变item中的属性不会生效

**Comment by hiyuki** [comment]
贴一下完整代码

**Comment by ialmost** [comment]
> 这个问题确实存在，原因在于内联事件处理中的参数是从小程序的渲染层传递过来的，已经不是原本的响应式数据，目前暂时不太好解决，建议还是使用index来直接访问数据进行修改，我们在文档中也标注一下

好的

**Comment by ialmost** [comment]
> 这个问题确实存在，原因在于内联事件处理中的参数是从小程序的渲染层传递过来的，已经不是原本的响应式数据，目前暂时不太好解决，建议还是使用index来直接访问数据进行修改，我们在文档中也标注一下

好的
