### ISSUE TITLE
[Bug report]希望支持new的class对象的响应式，目前无法observe

### ISSUE THREAD

**Issue by loca-spirit** [didi/mpx#644]
**问题描述**  
项目都是ts的项目，数据模型都是class对象的，数据初始化都是new class对象。所以希望new出来的对象可以进行observe，我们不希望把它转为普通的object。

**Comment by hiyuki** [comment]
最新版本已经支持，不过在data中声明实例数据需要采用function的形式来返回(同vue一致)，否则实例对象中的原型属性会在初始化时被丢弃
