### ISSUE TITLE
跨平台输出为Web的时候 关于wx.getStorageSync()的报错

### ISSUE THREAD

**Issue by LCSluchaoshun** [didi/mpx#646]
转web 的时候遇到报错：
![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
app.mpx 里已use(apiProxy)

**Comment by zhaoyiming0803** [comment]
> 转web 的时候遇到报错：
> ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> app.mpx 里已use(apiProxy)

贴下你app.mpx中怎么use的apiProxy

**Comment by LCSluchaoshun** [comment]
![image](https://user-images.githubusercontent.com/42520935/99027098-62a9e680-25a7-11eb-9961-fce2b01f4792.png)

**Comment by LCSluchaoshun** [comment]
> > 转web 的时候遇到报错：
> > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > app.mpx 里已use(apiProxy)
> 
> 贴下你app.mpx中怎么use的apiProxy

![image](https://user-images.githubusercontent.com/42520935/99027158-879e5980-25a7-11eb-9575-ad8160149fbc.png)

**Comment by LCSluchaoshun** [comment]
> > 转web 的时候遇到报错：
> > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > app.mpx 里已use(apiProxy)
> 
> 贴下你app.mpx中怎么use的apiProxy

![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)

**Comment by zhaoyiming0803** [comment]
> > > 转web 的时候遇到报错：
> > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > app.mpx 里已use(apiProxy)
> > 
> > 
> > 贴下你app.mpx中怎么use的apiProxy
> 
> ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)

看起来use没问题，给个最小复现demo我看下

**Comment by LCSluchaoshun** [comment]
> > > > 转web 的时候遇到报错：
> > > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > > app.mpx 里已use(apiProxy)
> > > 
> > > 
> > > 贴下你app.mpx中怎么use的apiProxy
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)
> 
> 看起来use没问题，给个最小复现demo我看下

您好，已经上传了 [demo](https://gitee.com/lcs0520/demo.git)

**Comment by LCSluchaoshun** [comment]
> > > > 转web 的时候遇到报错：
> > > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > > app.mpx 里已use(apiProxy)
> > > 
> > > 
> > > 贴下你app.mpx中怎么use的apiProxy
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)
> 
> 看起来use没问题，给个最小复现demo我看下

您好，请问出现这个问题是哪个地方的原因呀？

**Comment by zhaoyiming0803** [comment]
> > > > > 转web 的时候遇到报错：
> > > > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > > > app.mpx 里已use(apiProxy)
> > > > 
> > > > 
> > > > 贴下你app.mpx中怎么use的apiProxy
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)
> > 
> > 
> > 看起来use没问题，给个最小复现demo我看下
> 
> 您好，请问出现这个问题是哪个地方的原因呀？

刚看了下，你在app.mpx中，先引入 requestPlugin ，后执行的 mpx.use(apiProxy)，但是你 requestPlugin 中又导入了 store，store 中执行了 wx.getStorageSync，这时 api 还没有被代理到 mpx 对象上，所以报错。

可以通过调换 mpx.use(apiProxy) 和 import requestPlugin 的位置解决

**Comment by LCSluchaoshun** [comment]
> ```js
> request
> ```
这样的话 getStorageSync不会报错了，但是 require 引入的request文件内的方法（httpGet,httpPost）没办法挂载到mpx 对象了

**Comment by LCSluchaoshun** [comment]
> > > > > > 转web 的时候遇到报错：
> > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > > > > app.mpx 里已use(apiProxy)
> > > > > 
> > > > > 
> > > > > 贴下你app.mpx中怎么use的apiProxy
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)
> > > 
> > > 
> > > 看起来use没问题，给个最小复现demo我看下
> > 
> > 
> > 您好，请问出现这个问题是哪个地方的原因呀？
> 
> 刚看了下，你在app.mpx中，先引入 requestPlugin ，后执行的 mpx.use(apiProxy)，但是你 requestPlugin 中又导入了 store，store 中执行了 wx.getStorageSync，这时 api 还没有被代理到 mpx 对象上，所以报错。
> 
> 可以使用 require 引入：
> 
> ```js
> mpx.use(apiProxy, { usePromise: true })     
> const requestPlugin = require('common/request')
> ```

您好，getStorageSync的报错解决了但是通过require引入的request 文件内的方法（httpGet,httpPost）好像没有被挂载到mpx对象上

**Comment by zhaoyiming0803** [comment]
> > > > > > > 转web 的时候遇到报错：
> > > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > > > > > app.mpx 里已use(apiProxy)
> > > > > > 
> > > > > > 
> > > > > > 贴下你app.mpx中怎么use的apiProxy
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)
> > > > 
> > > > 
> > > > 看起来use没问题，给个最小复现demo我看下
> > > 
> > > 
> > > 您好，请问出现这个问题是哪个地方的原因呀？
> > 
> > 
> > 刚看了下，你在app.mpx中，先引入 requestPlugin ，后执行的 mpx.use(apiProxy)，但是你 requestPlugin 中又导入了 store，store 中执行了 wx.getStorageSync，这时 api 还没有被代理到 mpx 对象上，所以报错。
> > 可以使用 require 引入：
> > ```js
> > mpx.use(apiProxy, { usePromise: true })     
> > const requestPlugin = require('common/request')
> > ```
> 
> 您好，getStorageSync的报错解决了但是通过require引入的request 文件内的方法（httpGet,httpPost）好像没有被挂载到mpx对象上

``` javascript
const requestPlugin = require('common/request').default

// requestPlugin
function install (proxyMpx) {
  proxyMpx.httpGet = function () {}
}
```

**Comment by LCSluchaoshun** [comment]
> ```js
> require('common/request').default
> ```

十分感谢大佬指点迷津！

**Comment by LCSluchaoshun** [comment]
> > > > > > > > 转web 的时候遇到报错：
> > > > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > > > > > > app.mpx 里已use(apiProxy)
> > > > > > > 
> > > > > > > 
> > > > > > > 贴下你app.mpx中怎么use的apiProxy
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)
> > > > > 
> > > > > 
> > > > > 看起来use没问题，给个最小复现demo我看下
> > > > 
> > > > 
> > > > 您好，请问出现这个问题是哪个地方的原因呀？
> > > 
> > > 
> > > 刚看了下，你在app.mpx中，先引入 requestPlugin ，后执行的 mpx.use(apiProxy)，但是你 requestPlugin 中又导入了 store，store 中执行了 wx.getStorageSync，这时 api 还没有被代理到 mpx 对象上，所以报错。
> > > 可以使用 require 引入：
> > > ```js
> > > mpx.use(apiProxy, { usePromise: true })     
> > > const requestPlugin = require('common/request')
> > > ```
> > 
> > 
> > 您好，getStorageSync的报错解决了但是通过require引入的request 文件内的方法（httpGet,httpPost）好像没有被挂载到mpx对象上
> 
> ```js
> const requestPlugin = require('common/request').default
> 
> // requestPlugin
> function install (proxyMpx) {
>   proxyMpx.httpGet = function () {}
> }
> ```

十分感谢大佬指点迷津!

**Comment by LCSluchaoshun** [comment]
> > > > > > > > > 转web 的时候遇到报错：
> > > > > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023985-b36a1100-25a0-11eb-9210-1f96b798e0c5.png)
> > > > > > > > > ![image](https://user-images.githubusercontent.com/42520935/99023934-98979c80-25a0-11eb-8d6b-fedd8d1f02e1.png)
> > > > > > > > > app.mpx 里已use(apiProxy)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 贴下你app.mpx中怎么use的apiProxy
> > > > > > > 
> > > > > > > 
> > > > > > > ![image](https://user-images.githubusercontent.com/42520935/99027230-b1f01700-25a7-11eb-9bd9-a82744de96d5.png)
> > > > > > 
> > > > > > 
> > > > > > 看起来use没问题，给个最小复现demo我看下
> > > > > 
> > > > > 
> > > > > 您好，请问出现这个问题是哪个地方的原因呀？
> > > > 
> > > > 
> > > > 刚看了下，你在app.mpx中，先引入 requestPlugin ，后执行的 mpx.use(apiProxy)，但是你 requestPlugin 中又导入了 store，store 中执行了 wx.getStorageSync，这时 api 还没有被代理到 mpx 对象上，所以报错。
> > > > 可以使用 require 引入：
> > > > ```js
> > > > mpx.use(apiProxy, { usePromise: true })     
> > > > const requestPlugin = require('common/request')
> > > > ```
> > > 
> > > 
> > > 您好，getStorageSync的报错解决了但是通过require引入的request 文件内的方法（httpGet,httpPost）好像没有被挂载到mpx对象上
> > 
> > 
> > ```js
> > const requestPlugin = require('common/request').default
> > 
> > // requestPlugin
> > function install (proxyMpx) {
> >   proxyMpx.httpGet = function () {}
> > }
> > ```
> 
> 十分感谢大佬指点迷津!

谢谢前辈~！

**Comment by shiyu123** [comment]
我看文档里说，引入apiProxy后要用mpx去调用api，比如mpx.showToast，但我看你写的都是wx开头的，是不是用wx开头的就可以跨平台了，不用非得换成mpx。
