### ISSUE TITLE
[Bug report] 模板里的表达式出现小于号时解析出错

### ISSUE THREAD

**Issue by shiyu123** [didi/mpx#650]
**问题描述**  
源码片段：
```
<view class="mark-num">
  {{item.GetCount<item.LimitCount?item.GetCount:item.LimitCount}}
</view>
```
编译结果：
```
<view class="mark-num">{{item.GetCount</view>
```

**环境信息描述**  
Windows
"@mpxjs/core": "^2.6.31"
"@mpxjs/webpack-plugin": "^2.6.31",
"@mpxjs/api-proxy": "^2.5.10",
微信小程序
1.03.2010240
2.12.2

**Comment by hiyuki** [comment]
这是由于html解析时将<后紧跟字符作为标签开始解析了，<表达式后添加个空格即可规避
