### ISSUE TITLE
[Bug report] 原生迁移输出 web 异常

### ISSUE THREAD

**Issue by shiyu123** [didi/mpx#651]
**问题描述**  
1. 问题触发的条件
原生迁移输出 web 。
2. 期望的表现
网页正常显示。
3. 实际的表现
提示渲染异常。

**环境信息描述**  
1. 系统类型(Mac或者Windows)
Windows
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
"@mpxjs/core": "^2.6.31"
"@mpxjs/webpack-plugin": "^2.6.31",
"@mpxjs/api-proxy": "^2.5.10",
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
微信小程序
1.03.2010240
2.12.2

**Comment by shiyu123** [comment]
mpx单文件的形式可以正常输出。

**Comment by Blackgan3** [comment]
可以将原生代码先渐进迁移成 Mpx 单文件模式

**Comment by shiyu123** [comment]
要转的太多了，我是旧项目迁移到mpx的，要是框架支持的话我就可以渐进迁移，不然的话就要一口气转很多页面。

**Comment by shiyu123** [comment]
> 可以将原生代码先渐进迁移成 Mpx 单文件模式

要转的太多了，我是旧项目迁移到mpx的，要是框架支持的话我就可以渐进迁移，不然的话就要一口气转很多页面。

**Comment by Blackgan3** [comment]
框架目前还不支持直接将原声的文件给转成 web

**Comment by shiyu123** [comment]
> 框架目前还不支持直接将原生的文件给转成 web

短期内有考虑支持吗，有的话我就再等等，没有的话我就开始进行迁移了。

**Comment by Blackgan3** [comment]
我们会考虑支持下，不过可能需要些时日，项目紧急的话可以先进行迁移转 web

**Comment by shiyu123** [comment]
> 我们会考虑支持下，不过可能需要些时日，项目紧急的话可以先进行迁移转
