### ISSUE TITLE
[Bug report] 跨端输出 web 时，图片找不到

### ISSUE THREAD

**Issue by shiyu123** [didi/mpx#652]
**问题描述**  
1. 问题触发的条件
用脚手架创建的初始 demo，跨端输出 web 的时候，图片找不到。
```
<image src="./xxx.png" />
```
2. 期望的表现
图片正常显示。
3. 实际的表现
图片找不到。

**环境信息描述**  
1. 系统类型(Mac或者Windows)
Windows
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看
"@mpxjs/core": "^2.6.31"
"@mpxjs/webpack-plugin": "^2.6.31",
"@mpxjs/api-proxy": "^2.5.10",

**Comment by zhaoyiming0803** [comment]
> **问题描述**
> 
> 1. 问题触发的条件
>    用脚手架创建的初始 demo，跨端输出 web 的时候，图片找不到。
> 
> ```
> <image src="./xxx.png" />
> ```
> 
> 1. 期望的表现
>    图片正常显示。
> 2. 实际的表现
>    图片找不到。
> 
> **环境信息描述**
> 
> 1. 系统类型(Mac或者Windows)
>    Windows
> 2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看
>    "@mpxjs/core": "^2.6.31"
>    "@mpxjs/webpack-plugin": "^2.6.31",
>    "@mpxjs/api-proxy": "^2.5.10",

这边看了下，可以的。
```html
<image src="./cart-active.png"></image>
```

**Comment by zhaoyiming0803** [comment]
> **问题描述**
> 
> 1. 问题触发的条件
>    用脚手架创建的初始 demo，跨端输出 web 的时候，图片找不到。
> 
> ```
> <image src="./xxx.png" />
> ```
> 
> 1. 期望的表现
>    图片正常显示。
> 2. 实际的表现
>    图片找不到。
> 
> **环境信息描述**
> 
> 1. 系统类型(Mac或者Windows)
>    Windows
> 2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看
>    "@mpxjs/core": "^2.6.31"
>    "@mpxjs/webpack-plugin": "^2.6.31",
>    "@mpxjs/api-proxy": "^2.5.10",

刚在windows上看了下，"@mpxjs/core": "^2.6.31" "@mpxjs/webpack-plugin": "^2.6.31", "@mpxjs/api-proxy": "^2.5.10", 可以正常加载图片的。
```javascript
<image src="timg.jpg"></image>
```

**Comment by shiyu123** [comment]
我还是找不到图片，编译输出的 dist/web 目录里没找到相应图片，image src 的方式图片依赖采集不到，require 的方式才可以。
```
<template>
  <view class="list">
    <image class="test" src="../images/yubo.png"></image>
    <image class="test" src="{{img}}"></image>
  </view>
</template>

<script>
import { createComponent } from '@mpxjs/core'

createComponent({
  data: {
    img: require('../images/yubo.png')
  }
})
</script>
```

**Comment by zhaoyiming0803** [comment]
> 我还是找不到图片，编译输出的 dist/web 目录里没找到相应图片，image src 的方式图片依赖采集不到，require 的方式才可以。
> 
> ```
> <template>
>   <view class="list">
>     <image class="test" src="../images/yubo.png"></image>
>     <image class="test" src="{{img}}"></image>
>   </view>
> </template>
> 
> <script>
> import { createComponent } from '@mpxjs/core'
> 
> createComponent({
>   data: {
>     img: require('../images/yubo.png')
>   }
> })
> </script>
> ```

给个最小复现demo吧。

**Comment by shiyu123** [comment]
[demo](https://gitee.com/sy-net/mpx)

**Comment by zhaoyiming0803** [comment]
> [demo](https://gitee.com/sy-net/mpx)

把你项目中 vue-loader 的版本退回 14.2.4就可以了。

看你项目是对原先mpx-cli生成的初始项目的build部分有很大改动吧，而且demo里边的mpx/core等版本号也不是上述issue的版本。

**Comment by shiyu123** [comment]
build部分没有改动，我是用mpx-cli创建了个新的项目测试的，只是后来我试着将mpx/core这些库更新到最新看看能否解决，忘记改回来了，我现在将vue-loader的版本退回到14.2.4执行npm run watch --web会提示VueLoaderPlugin is not a constructor。

**Comment by zhaoyiming0803** [comment]
> VueLoaderPlugin

14.2.4没有 VueLoaderPlugin，把你 getPlugins.js 文件中对 VueLoaderPlugin 引用和调用都干掉

**Comment by zhaoyiming0803** [comment]
> VueLoaderPlugin

14.2.4没有 VueLoaderPlugin，把你 getPlugins.js 文件中对 VueLoaderPlugin 引用和调用干掉

**Comment by shiyu123** [comment]
好的，图片出来了，谢谢~
