### ISSUE TITLE
加入类似vue-cli 环境变量和模式的功能

### ISSUE THREAD

**Issue by yuu2lee4** [didi/mpx#654]
参照：https://cli.vuejs.org/zh/guide/mode-and-env.html
这样可以根据不同的环境打包

**Comment by hiyuki** [comment]
这个诉求可以通过自行修改build脚本实现，其实就是读取一下npm_config然后将对应参数通过definePlugin或者是mpx的defs添加到环境变量即可，类似vue中这种某些特定变量自动注入的模式我们后续也可以参考一下加到脚手架当中。。。
