### ISSUE TITLE
[Feature Request] 采用像 vue assets static 的静态资源处理方式

### ISSUE THREAD

**Issue by shiyu123** [didi/mpx#655]
能否支持像 vue 那样对相对路径引入的静态资源才使用 webpack 进行解析处理，绝对路径则保持不变跳过 webpack 处理，然后将 static 目录的资源直接输出到各个模式（wx/ali...）的根目录里。

**Comment by hiyuki** [comment]
绝对路径在resolveMode为native时配合projectRoot使用是有意义，兼容小程序的路径解析方式，没法直接删除，后面这个static目录中非mode下的文件直接输出到所有项目目录下可以支持，我们修改一下脚手架

**Comment by Blackgan3** [comment]
脚手架已支持static目录中非mode下的文件直接输出到所有项目目录下
