### ISSUE TITLE
MPX  小程序的统计分析用哪个sdk

### ISSUE THREAD

**Issue by xugongyang** [didi/mpx#656]
之前用wepy 写的小程序， 阿拉丁和友盟统计 sdk 都能集成，收集到小程序统计信息。

现在用mpx 开发的小程序，阿拉丁和友盟 sdk 都集成失败，而且window PC 微信打开小程序白屏

**Comment by hiyuki** [comment]
统计sdk集成失败是由于统计sdk中没有适配使用component构造器创建页面的缘故，你可以改一下创建页面的方式来处理；
```js
// 通过这种方式创建页面
createPage(options, { customCtor: Page })
```

window PC白屏之前确实存在，最新版本已修复，确认版本已经更新到最新，如果还存在问题请上传复现demo便于我们排查

**Comment by xugongyang** [comment]
> 统计sdk集成失败是由于统计sdk中没有适配使用component构造器创建页面的缘故，你可以改一下创建页面的方式来处理；
> 
> ```js
> // 通过这种方式创建页面
> createPage(options, { customCtor: Page })
> ```
> 
> window PC白屏之前确实存在，最新版本已修复，确认版本已经更新到最新，如果还存在问题请上传复现demo便于我们排查

createPage(options, { customCtor: Page }) 怎么用，不知道怎么写，大佬帮指导下，谢谢

**Comment by xugongyang** [comment]
> 统计sdk集成失败是由于统计sdk中没有适配使用component构造器创建页面的缘故，你可以改一下创建页面的方式来处理；
> 
> ```js
> // 通过这种方式创建页面
> createPage(options, { customCtor: Page })
> ```
> 
> window PC白屏之前确实存在，最新版本已修复，确认版本已经更新到最新，如果还存在问题请上传复现demo便于我们排查



> > 统计sdk集成失败是由于统计sdk中没有适配使用component构造器创建页面的缘故，你可以改一下创建页面的方式来处理；
> > ```js
> > // 通过这种方式创建页面
> > createPage(options, { customCtor: Page })
> > ```
> > 
> > 
> > window PC白屏之前确实存在，最新版本已修复，确认版本已经更新到最新，如果还存在问题请上传复现demo便于我们排查
> 
> createPage(options, { customCtor: Page }) 怎么用，不知道怎么写，大佬帮指导下，谢谢
 { customCtor: Page } Page 哪里定义的，怎么引入，求指点

**Comment by hiyuki** [comment]
就是按照实例代码那么写啊，options就是你原本创建page传的选项，不用动，添加第二个参数`{ customCtor: Page }`，`Page`是小程序全局暴露的页面构造函数，不需要你定义，直接这么写就可以了

**Comment by GuanJdoJ** [comment]
我在app.mpx是这么配置的
createApp(options, {customCtor: App})
测试了友盟可以集成成功
