### ISSUE TITLE
新版本中配置sass-resources-loader无效

### ISSUE THREAD

**Issue by TrevorYS** [didi/mpx#659]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
2. 期望的表现
3. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows) Mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)2.6.15

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
![image](https://user-images.githubusercontent.com/19200800/100058232-e5faf000-2e63-11eb-8cfe-4c80cf5bb03c.png)

1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）
[mpx-scss.zip](https://github.com/didi/mpx/files/5587890/mpx-scss.zip)

**Comment by Amorcy** [comment]
> **问题描述**
> 请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
> 
> 1. 问题触发的条件
> 2. 期望的表现
> 3. 实际的表现
> 
> **环境信息描述**
> 至少包含以下部分：
> 
> 1. 系统类型(Mac或者Windows) Mac
> 2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)2.6.15
> 3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
> 
> **最简复现demo**
> 一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
> ![image](https://user-images.githubusercontent.com/19200800/100058232-e5faf000-2e63-11eb-8cfe-4c80cf5bb03c.png)
> 
> 1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
> 2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
> 3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）
>    [mpx-scss.zip](https://github.com/didi/mpx/files/5587890/mpx-scss.zip)

可以参考这个issue：
https://github.com/didi/mpx/issues/62#issuecomment-455020713

**Comment by Blackgan3** [comment]
对于scss 的处理，配置到 MpxWebpackPlugin 的 loaders中，看了下你的配置是在 webpack 的rules中配置的，对config/index.js中的mpxLoaderConfig可以修改成这样子：

```js
const mpxLoaderConfig = {
  loaders: {
    scss: [
      "css-loader",
      "sass-loader",
      {
        loader: "sass-resources-loader",
        options: {
          resources: [resolve("src/utils/global.scss")]
        }
      }
    ]
  }
}

```
