### ISSUE TITLE
[Bug report]引入 vant 组件在支付宝小程序上直接报错

### ISSUE THREAD

**Issue by wangjun521** [didi/mpx#660]
mxp: 2.6.32
vant: 1.6.1

跨平台编译 随便引入一个组件 在微信上没有问题  在支付宝小程序上直接报错如图

![image](https://user-images.githubusercontent.com/23025867/100064989-2f503d00-2e6e-11eb-8c33-f6275ca028af.png)

**Comment by Blackgan3** [comment]
参看下 issue #360

**Comment by wangjun521** [comment]
在 `babel-loader` 中添加了`exclude: [resolve('node_modules/@vant')]`  依旧是错误的 关键这里是微信没事 支付宝跪了

**Comment by Blackgan3** [comment]
提供个最小复现demo吧

**Comment by wangjun521** [comment]
**常规创建项目 设置如下**
```
// 根据创建项目时的问题生成的
// 改动需谨慎，有的选项存在互斥关系，比如跨平台开发，就不能开发插件
// 若需修改以启用新的能力，建议试试新建项目按问题生成模板后把这部分内容拷贝过来
module.exports = {
  srcMode: formatOption('wx'),
  cross: formatOption('true'),
  transWeb: formatOption('false'),
  cloudFunc: formatOption('false'),
  isPlugin: formatOption('false'),
  tsSupport: formatOption('false'),
  babel7Support: formatOption('true'),
  needEslint: formatOption('true'),
  needDll: formatOption('false'),
  needUnitTest: formatOption('false')
}
```
**在 app.mpx的的 `script` 中注册组件**
```
<script type="application/json">
  {
    "pages": [
      "./pages/index"
    ],
    "usingComponents": {
      "van-button": "@vant/weapp/dist/button/index"
    }
  }
</script>
```
**package.json中**
```
  "dependencies": {
    "@mpxjs/api-proxy": "^2.5.10",
    "@mpxjs/core": "^2.6.31",
    "@vant/weapp": "^1.6.1",
    "dayjs": "^1.9.6",
    "vue": "^2.6.10",
    "vue-i18n": "^8.15.3"
  }
```
**这时候只是注册了页面中没有引用 然后运行 `yarn watch:cross` 微信通过 支付宝有如下警告**
```
WARNING in ./node_modules/@vant/weapp/dist/button/index.wxml?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main&resourcePath=/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.js (./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=template&index=0!./node_modules/@mpxjs/webpack-plugin/lib/wxml/wxml-loader.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/template-compiler?{"usingComponents":["van-button","van-icon","van-loading","van-icon","van-loading"],"hasScoped":false,"hasComment":false,"isNative":true,"moduleId":"m1f0a3474","projectRoot":""}!./node_modules/@vant/weapp/dist/button/index.wxml?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main&resourcePath=/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.js)
Module Warning (from ./node_modules/@mpxjs/webpack-plugin/lib/template-compiler/index.js):
[template compiler][/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.wxml?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main&resourcePath=/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.js]: <button> does not support [bindcontact] event in ali environment!
 @ ./node_modules/@vant/weapp/dist/button?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main (./node_modules/@mpxjs/webpack-plugin/lib/native-loader.js!./node_modules/@vant/weapp/dist/button?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main) 9:0-583
```
这错误提示好像是 button 在 ali 环境中不支持的样子

**Comment by Blackgan3** [comment]
> **常规创建项目 设置如下**
> 
> ```
> // 根据创建项目时的问题生成的
> // 改动需谨慎，有的选项存在互斥关系，比如跨平台开发，就不能开发插件
> // 若需修改以启用新的能力，建议试试新建项目按问题生成模板后把这部分内容拷贝过来
> module.exports = {
>   srcMode: formatOption('wx'),
>   cross: formatOption('true'),
>   transWeb: formatOption('false'),
>   cloudFunc: formatOption('false'),
>   isPlugin: formatOption('false'),
>   tsSupport: formatOption('false'),
>   babel7Support: formatOption('true'),
>   needEslint: formatOption('true'),
>   needDll: formatOption('false'),
>   needUnitTest: formatOption('false')
> }
> ```
> 
> **在 app.mpx的的 `script` 中注册组件**
> 
> ```
> <script type="application/json">
>   {
>     "pages": [
>       "./pages/index"
>     ],
>     "usingComponents": {
>       "van-button": "@vant/weapp/dist/button/index"
>     }
>   }
> </script>
> ```
> 
> **package.json中**
> 
> ```
>   "dependencies": {
>     "@mpxjs/api-proxy": "^2.5.10",
>     "@mpxjs/core": "^2.6.31",
>     "@vant/weapp": "^1.6.1",
>     "dayjs": "^1.9.6",
>     "vue": "^2.6.10",
>     "vue-i18n": "^8.15.3"
>   }
> ```
> 
> **这时候只是注册了页面中没有引用 然后运行 `yarn watch:cross` 微信通过 支付宝有如下警告**
> 
> ```
> WARNING in ./node_modules/@vant/weapp/dist/button/index.wxml?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main&resourcePath=/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.js (./node_modules/@mpxjs/webpack-plugin/lib/extractor.js?type=template&index=0!./node_modules/@mpxjs/webpack-plugin/lib/wxml/wxml-loader.js?root=!./node_modules/@mpxjs/webpack-plugin/lib/template-compiler?{"usingComponents":["van-button","van-icon","van-loading","van-icon","van-loading"],"hasScoped":false,"hasComment":false,"isNative":true,"moduleId":"m1f0a3474","projectRoot":""}!./node_modules/@vant/weapp/dist/button/index.wxml?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main&resourcePath=/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.js)
> Module Warning (from ./node_modules/@mpxjs/webpack-plugin/lib/template-compiler/index.js):
> [template compiler][/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.wxml?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main&resourcePath=/Users/wang_j/Documents/mine/mpxDemo/node_modules/@vant/weapp/dist/button/index.js]: <button> does not support [bindcontact] event in ali environment!
>  @ ./node_modules/@vant/weapp/dist/button?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main (./node_modules/@mpxjs/webpack-plugin/lib/native-loader.js!./node_modules/@vant/weapp/dist/button?context=/Users/wang_j/Documents/mine/mpxDemo/src&packageName=main) 9:0-583
> ```
> 
> 这错误提示好像是 button 在 ali 环境中不支持的样子




看报错是因为在支付宝环境下引入了 wxml 这种微信小程序才支持的文件，你看下是不是需要通过 mode 判断环境引入不同的 button 文件，不同平台需要引入不同的文件

**Comment by wangjun521** [comment]
那估计歇菜了 毕竟 vant是只有微信版本的 我看到框架上说会处理 ui 库的异同 所以才打算尝试下 看来想跨平台还是乖乖写样式吧 哎

**Comment by Blackgan3** [comment]
Mpx 支持 vant 组件输出到 支付宝小程序，对于上述 模块转换问题，可在 babel.config.js 中配置 sourcetype 为 unambiguous 
使babel能够自主判断模块类型进行规避：
```js
{
  "presets": [
    [
      "@babel/env",
      {
        "modules": false,
        "shippedProposals": true
      }
    ]
  ],
  "plugins": [
    [
      "@babel/transform-runtime",
      {
        "corejs": 3,
        "helper": false,
        "version": "^7.10.4"
      }
    ]
  ],
  "sourceType": "unambiguous",
  "env": {
    "test": {
      "presets": [
        [
          "@babel/env",
          {
            "shippedProposals": true
          }
        ]
      ]
    }
  }
}

```
