### ISSUE TITLE
使用官方脚手架sass无法使用全局变量

### ISSUE THREAD

**Issue by leehomyfch** [didi/mpx#661]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
在 config/.mpxLoader.conf.js 文件里加上:
{
    test: /\.scss$/,
    use: [
      'style-loader',
      'css-loader',
      'sass-loader',
      {
        loader: 'sass-resources-loader',
        options: {
          resources: [resolve('src/utils/global.scss')]
        }
      }
    ]
  }
报错
2. 期望的表现
可以使用scss的全局变量.
3. 实际的表现
小程序上报错: .WXSS文件错误
**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
Mac以及window都有这个额问题
2. Mpx依赖版本(@mpxjs/core^2.6.31、@mpxjs/webpack-plugin^5.0.3和@mpxjs/api-proxy^2.5.10"的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
w
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by Blackgan3** [comment]
可参考 issue #659
