### ISSUE TITLE
[Bug report]data中存在bind字段的，构建时报错

### ISSUE THREAD

**Issue by naifen00** [didi/mpx#666]
**问题描述**  
1. 通过mpx init mpx_test生成项目
2. 修改pages/index.mpx如下
![image](https://user-images.githubusercontent.com/1567627/100825329-bdda4500-3492-11eb-93b3-c9a2f9db3319.png)
3. yarn build 报错如下
![image](https://user-images.githubusercontent.com/1567627/100825704-9d5eba80-3493-11eb-9a61-d2510c746eae.png)

**环境信息描述**  
1. 系统类型Mac
2. @mpxjs/core ^2.6.40
    @mpxjs/webpack-plugin ^2.6.31
3. 微信开发者工具

**最简复现demo**  
[mpx-test.zip](https://github.com/didi/mpx/files/5626831/mpx-test.zip)

**Comment by naifen00** [comment]
![image](https://user-images.githubusercontent.com/1567627/100834412-cf2d4c80-34a6-11eb-8049-a5201862d6ad.png)
红框配置内容删了就好了

**Comment by Blackgan3** [comment]
看起来是 core-js3 中新增的 instance method 检测，转成了  _concatInstanceProperty(this)--   这种代码导致解析错误，你换成 concat / filter 这种实例方法也是会有一样的问题，你可以试一下 this.bind = tjhis.bind + 1，然后看下构建生成的代码就知道怎么回事了
