### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by loca-spirit** [didi/mpx#667]
**问题描述**  
mpx版本：2.6.40
vant-ui的datepicker组件
问题描述：
datepicker组件初始化，
组件对value属性进行observe
初始化的时候发现值为null，就执行了updateValue方法更新innerValue为'100001'
**然后emit input事件，将input事件放到eventloop的最底部，我叫它队列方法1，目前还没有执行**

bug来了，
我在页面onload的时候对value进行赋值
组件对value属性进行observe
执行了updateValue方法更新innerValue为'10002'
**然后emit input事件，将input事件放到eventloop的最底部，我叫它队列方法2，目前还没有执行**

等以上都执行完，发现队列方法1才开始执行，但是取到的innerValue已经不是最开始的'100001'了，值是页面onload的时候设置的'100002'，（然后就是datepicker默认的设置值的逻辑陷入了死循环，手机发烫）

同样的代码在mpx版本：2.5.11执行没有任何问题
目前临时解决方案就是页面设置值的时候用了settimeout，这样就可以等队列方法1执行完后再执行页面赋值的逻辑了。

**Comment by Blackgan3** [comment]
麻烦提供一个最小复现demo吧

**Comment by hiyuki** [comment]
首先这个问题和Mpx无关，你使用原生开发写这么一段代码会直接触发死循环：

```js
Page({
    data: {
      minHour: 10,
      maxHour: 20,
      minDate: new Date().getTime(),
      maxDate: new Date(2024, 10, 1).getTime(),
      currentDate: new Date().getTime()
    },
    onLoad () {
      this.setData({
        currentDate: new Date(2021, 10, 1).getTime()
      })
    },
    onInput (event) {
      console.log(event.detail)
      this.setData({
        currentDate: event.detail
      })
    }
  })
```

这是vant更新同步内外值本身存在bug导致的，主要原因在于vant在执行updateValue并对外抛出事件是一个异步过程，对外抛出事件使用的值是从闭包中获取的异步执行之前的值，你在onLoad中去setData正好就处于这个异步过程中间，这就导致当前这次updateValue对外抛出的值是个过期的旧值，在外部的onInput中设置这个旧值又会触发新一轮的重复过程，导致产生了一个新旧值交替设置的死循环。

而你使用Mpx反而能够规避这个死循环，因为Mpx为了优化setData会把setData延时发送，这就避开了vant这个死循环的触发条件(在updateValue的异步过程中设置新的value)，而且在这个问题上mpx@2.5.11版本与@2.6.40版本的表现完全一致，不存在差别，你仔细检查一下是不是你升级vant版本导致的。。。。
