### ISSUE TITLE
[Bug report]wx:model-value-path=""报错

### ISSUE THREAD

**Issue by yuu2lee4** [didi/mpx#668]
![image](https://user-images.githubusercontent.com/8046366/101130650-d12a1380-363e-11eb-9153-7cfa525c3019.png)
![image](https://user-images.githubusercontent.com/8046366/101130666-d8e9b800-363e-11eb-81dc-e9e8b566352d.png)
![image](https://user-images.githubusercontent.com/8046366/101130673-dc7d3f00-363e-11eb-9621-a96892ebaa26.png)
可以发现valuepath 这里为true  调用reduce就报错了,wx:model-value-path="[]"  没问题的

另外建议文档-api里 wx:model-value-path的链一下对应指南里的部分

**Comment by hiyuki** [comment]
wx:model-value-path=""理论上应该支持，下个版本修复，api参考中的相关链接@anotherso1添加一下吧
