### ISSUE TITLE
[Bug report] 不能引入npm包的模板

### ISSUE THREAD

**Issue by YXL76** [didi/mpx#669]
**问题描述**  

对于下面的例子，解析出来好像是相对路径

```html
<template>
  <import src="npmpackage/test.wxml" />
</template>
```

**Comment by zhaoyiming0803** [comment]
> **问题描述**
> 
> 对于下面的例子，解析出来好像是相对路径
> 
> ```
> <template>
>   <import src="npmpackage/test.wxml" />
> </template>
> ```

看下文档：https://www.mpxjs.cn/guide/advance/npm.html
