### ISSUE TITLE
微信小程序 tabbar 引入 iconPath 相对路径 根据src目录的绝对路径都引入失败

### ISSUE THREAD

**Issue by yangmaoHu** [didi/mpx#67]
![273798efbd0cfb7c9e958f3a940d5b0](https://user-images.githubusercontent.com/32952596/51462586-f17abd00-1d9b-11e9-9b25-e17e56a567a5.png)
![d467a175ed7782242ba44845f39017d](https://user-images.githubusercontent.com/32952596/51462590-f3448080-1d9b-11e9-9feb-b7ec7a2e53ea.png)

**Comment by sky-admin** [comment]
#66 fixed
马上发版
