### ISSUE TITLE
使用动态绑定样式时 key值带上印号会报错

### ISSUE THREAD

**Issue by lamking** [didi/mpx#68]
` wx:class="{{ {'cur-label': curIndex === 2} }}"`

**Comment by sky-admin** [comment]
1.0.26版本，我们换用wxs来实现样式绑定，优点有可以和wx:for结合使用，以及性能更好（wxs是运行在渲染层上的，可以避免渲染层和逻辑层的通信损耗）。
这种方式你写的对象还在模板上，然后模板上对象的key不能加引号这是小程序本身的限制。
所以需要用户自行修改避免在对象的key上使用引号。
