### ISSUE TITLE
头条小程序ref在真机上异常

### ISSUE THREAD

**Issue by tliwyl** [didi/mpx#684]
父组件嵌套子组件，在子组件上声明ref属性为‘ddd’，父组件对应的ref属性为undefined（this.$refs.ddd）
代码如下
```
<template minapp='native' xlang='wxml'>
	<view class='container'>
		{{ids}}
	</view>
</template>

<script>
import { createComponent } from '@mpxjs/core';
createComponent({
	properties: {},
	data: {
	},
	properties:{
		ids:{
			type:Number,
			value:99999
		}
	},
	methods: {},
});
</script>

<style lang='css'>
.container {
}
</style>
<script  type='application/json' lang='json'>
{ 
 "component": true
}
</script>


```

list.mpx
```
<template>
	<view
		class="list"
		wx:ref="aaa"
	>
		<view
			wx:for="{{listData}}"
			wx:key="index"
		>{{item}}
		</view>
	</view>
	<view>222</view>
	<dia
		wx:ref="ddd"
		ids="{{ids}}"
	/>
</template>

<style lang="stylus">
.list {
	background-color: red;
}
</style>
<script>
import { createComponent } from '@mpxjs/core';

createComponent({
	data: {
		ids: 9999,
	},
	properties: {
		listData: {
			type: Array,
			value: ['手机', '电视', '电脑'],
		},
	},
	methods: {
		updListData() {
			this.listData = ['手机', 'mac', '平板'];
			this.ids = 88888;
			console.log(this);
			setTimeout(() => {
				console.log(this);
			}, 100);
		},
	},
});
</script>
<script type="application/json">
  {
		"component": true,
		"usingComponents": {
			 "dia":"@/components/d.mpx"
		}
  }
</script>

```
d.mpx
```
<template minapp='native' xlang='wxml'>
	<view class='container'>
		{{ids}}
	</view>
</template>

<script>
import { createComponent } from '@mpxjs/core';
createComponent({
	properties: {},
	data: {
	},
	properties:{
		ids:{
			type:Number,
			value:99999
		}
	},
	methods: {},
});
</script>

<style lang='css'>
.container {
}
</style>
<script  type='application/json' lang='json'>
{ 
 "component": true
}
</script>


```

```
updListData() {
	this.listData = ['手机', 'mac', '平板'];
	this.ids = 88888;
	console.log(this);
	setTimeout(() => {
		console.log(this);
	}, 100);
}
```
这个函数console的结果如下图:
![5891608727328_ pic](https://user-images.githubusercontent.com/22835834/102997989-39468800-4561-11eb-91e8-1309017051c7.jpg)

![5921608727469_ pic](https://user-images.githubusercontent.com/22835834/102997885-0e5c3400-4561-11eb-82e3-01da707bc9d9.jpg)

两个console 在父组件property改变后下一帧父组件的$refs.ddd属性才表现正常为d.mpx 组件实例，在模拟器中两个console表现均正常

**Comment by zhaoyiming0803** [comment]
> 父组件嵌套子组件，在子组件上声明ref属性为‘ddd’，父组件对应的ref属性为undefined（this.$refs.ddd）
> 代码如下
> 
> ```
> <template minapp='native' xlang='wxml'>
> 	<view class='container'>
> 		{{ids}}
> 	</view>
> </template>
> 
> <script>
> import { createComponent } from '@mpxjs/core';
> createComponent({
> 	properties: {},
> 	data: {
> 	},
> 	properties:{
> 		ids:{
> 			type:Number,
> 			value:99999
> 		}
> 	},
> 	methods: {},
> });
> </script>
> 
> <style lang='css'>
> .container {
> }
> </style>
> <script  type='application/json' lang='json'>
> { 
>  "component": true
> }
> </script>
> ```
> 
> list.mpx
> 
> ```
> <template>
> 	<view
> 		class="list"
> 		wx:ref="aaa"
> 	>
> 		<view
> 			wx:for="{{listData}}"
> 			wx:key="index"
> 		>{{item}}
> 		</view>
> 	</view>
> 	<view>222</view>
> 	<dia
> 		wx:ref="ddd"
> 		ids="{{ids}}"
> 	/>
> </template>
> 
> <style lang="stylus">
> .list {
> 	background-color: red;
> }
> </style>
> <script>
> import { createComponent } from '@mpxjs/core';
> 
> createComponent({
> 	data: {
> 		ids: 9999,
> 	},
> 	properties: {
> 		listData: {
> 			type: Array,
> 			value: ['手机', '电视', '电脑'],
> 		},
> 	},
> 	methods: {
> 		updListData() {
> 			this.listData = ['手机', 'mac', '平板'];
> 			this.ids = 88888;
> 			console.log(this);
> 			setTimeout(() => {
> 				console.log(this);
> 			}, 100);
> 		},
> 	},
> });
> </script>
> <script type="application/json">
>   {
> 		"component": true,
> 		"usingComponents": {
> 			 "dia":"@/components/d.mpx"
> 		}
>   }
> </script>
> ```
> 
> d.mpx
> 
> ```
> <template minapp='native' xlang='wxml'>
> 	<view class='container'>
> 		{{ids}}
> 	</view>
> </template>
> 
> <script>
> import { createComponent } from '@mpxjs/core';
> createComponent({
> 	properties: {},
> 	data: {
> 	},
> 	properties:{
> 		ids:{
> 			type:Number,
> 			value:99999
> 		}
> 	},
> 	methods: {},
> });
> </script>
> 
> <style lang='css'>
> .container {
> }
> </style>
> <script  type='application/json' lang='json'>
> { 
>  "component": true
> }
> </script>
> ```
> 
> ```
> updListData() {
> 	this.listData = ['手机', 'mac', '平板'];
> 	this.ids = 88888;
> 	console.log(this);
> 	setTimeout(() => {
> 		console.log(this);
> 	}, 100);
> }
> ```
> 
> 这个函数console的结果如下图:
> ![5891608727328_ pic](https://user-images.githubusercontent.com/22835834/102997989-39468800-4561-11eb-91e8-1309017051c7.jpg)
> 
> ![5921608727469_ pic](https://user-images.githubusercontent.com/22835834/102997885-0e5c3400-4561-11eb-82e3-01da707bc9d9.jpg)
> 
> 两个console 在父组件property改变后下一帧父组件的$refs.ddd属性才表现正常为d.mpx 组件实例，在模拟器中两个console表现均正常

@mpxjs/webpack-plugin、@mpxjs/core、@mpxjs/api-proxy 版本号多少？

**Comment by tliwyl** [comment]
上面demo
```
    "@mpxjs/api-proxy": "^2.3.0",
    "@mpxjs/core": "~2.5.20",
   "@mpxjs/webpack-plugin": "^2.4.1",
```
项目中
```
    "@mpxjs/api-proxy": "~2.6.39",
    "@mpxjs/core": "~2.6.39",
    "@mpxjs/webpack-plugin": "^2.6.39",
```

都会有上述问题（通过selectCompnent获取组件实例则正常）

**Comment by zhaoyiming0803** [comment]
> 上面demo
> 
> ```
>     "@mpxjs/api-proxy": "^2.3.0",
>     "@mpxjs/core": "~2.5.20",
>    "@mpxjs/webpack-plugin": "^2.4.1",
> ```
> 
> 项目中
> 
> ```
>     "@mpxjs/api-proxy": "~2.6.39",
>     "@mpxjs/core": "~2.6.39",
>     "@mpxjs/webpack-plugin": "^2.6.39",
> ```
> 
> 都会有上述问题（通过selectCompnent获取组件实例则正常）

我刚用最新版本的mpx-cli初始化的项目，父组件中代码如下：
``` javascript
<template>
  <view>
    <list wx:ref="listRef"></list>
    <button bindtap="onClick">按钮</button>
  </view>
</template>

<script>
  import { createPage } from '@mpxjs/core'

  createPage({
    onLoad () {},
    methods: {
      onClick () {
        console.log(this)
      }
    }
  })
</script>

<script type="application/json">
  {
    "usingComponents": {
      "list": "../components/list"
    }
  }
</script>
```
点击按钮的时候才操作，能获取到$refs的节点。看你下逻辑，是不是节点没初始化完，就去获取了。


> 父组件嵌套子组件，在子组件上声明ref属性为‘ddd’，父组件对应的ref属性为undefined（this.$refs.ddd）
> 代码如下
> 
> ```
> <template minapp='native' xlang='wxml'>
> 	<view class='container'>
> 		{{ids}}
> 	</view>
> </template>
> 
> <script>
> import { createComponent } from '@mpxjs/core';
> createComponent({
> 	properties: {},
> 	data: {
> 	},
> 	properties:{
> 		ids:{
> 			type:Number,
> 			value:99999
> 		}
> 	},
> 	methods: {},
> });
> </script>
> 
> <style lang='css'>
> .container {
> }
> </style>
> <script  type='application/json' lang='json'>
> { 
>  "component": true
> }
> </script>
> ```
> 
> list.mpx
> 
> ```
> <template>
> 	<view
> 		class="list"
> 		wx:ref="aaa"
> 	>
> 		<view
> 			wx:for="{{listData}}"
> 			wx:key="index"
> 		>{{item}}
> 		</view>
> 	</view>
> 	<view>222</view>
> 	<dia
> 		wx:ref="ddd"
> 		ids="{{ids}}"
> 	/>
> </template>
> 
> <style lang="stylus">
> .list {
> 	background-color: red;
> }
> </style>
> <script>
> import { createComponent } from '@mpxjs/core';
> 
> createComponent({
> 	data: {
> 		ids: 9999,
> 	},
> 	properties: {
> 		listData: {
> 			type: Array,
> 			value: ['手机', '电视', '电脑'],
> 		},
> 	},
> 	methods: {
> 		updListData() {
> 			this.listData = ['手机', 'mac', '平板'];
> 			this.ids = 88888;
> 			console.log(this);
> 			setTimeout(() => {
> 				console.log(this);
> 			}, 100);
> 		},
> 	},
> });
> </script>
> <script type="application/json">
>   {
> 		"component": true,
> 		"usingComponents": {
> 			 "dia":"@/components/d.mpx"
> 		}
>   }
> </script>
> ```
> 
> d.mpx
> 
> ```
> <template minapp='native' xlang='wxml'>
> 	<view class='container'>
> 		{{ids}}
> 	</view>
> </template>
> 
> <script>
> import { createComponent } from '@mpxjs/core';
> createComponent({
> 	properties: {},
> 	data: {
> 	},
> 	properties:{
> 		ids:{
> 			type:Number,
> 			value:99999
> 		}
> 	},
> 	methods: {},
> });
> </script>
> 
> <style lang='css'>
> .container {
> }
> </style>
> <script  type='application/json' lang='json'>
> { 
>  "component": true
> }
> </script>
> ```
> 
> ```
> updListData() {
> 	this.listData = ['手机', 'mac', '平板'];
> 	this.ids = 88888;
> 	console.log(this);
> 	setTimeout(() => {
> 		console.log(this);
> 	}, 100);
> }
> ```
> 
> 这个函数console的结果如下图:
> ![5891608727328_ pic](https://user-images.githubusercontent.com/22835834/102997989-39468800-4561-11eb-91e8-1309017051c7.jpg)
> 
> ![5921608727469_ pic](https://user-images.githubusercontent.com/22835834/102997885-0e5c3400-4561-11eb-82e3-01da707bc9d9.jpg)
> 
> 两个console 在父组件property改变后下一帧父组件的$refs.ddd属性才表现正常为d.mpx 组件实例，在模拟器中两个console表现均正常

**Comment by zhaoyiming0803** [comment]
> 上面demo
> 
> ```
>     "@mpxjs/api-proxy": "^2.3.0",
>     "@mpxjs/core": "~2.5.20",
>    "@mpxjs/webpack-plugin": "^2.4.1",
> ```
> 
> 项目中
> 
> ```
>     "@mpxjs/api-proxy": "~2.6.39",
>     "@mpxjs/core": "~2.6.39",
>     "@mpxjs/webpack-plugin": "^2.6.39",
> ```
> 
> 都会有上述问题（通过selectCompnent获取组件实例则正常）

用最新的mpx-cli创建了个demo，父组件代码如下，点击按钮的时候可以获取到，看下你获取ref的时候是不是节点还没渲染完。
``` javascript
<template>
  <view>
    <list wx:ref="listRef"></list>
    <button bindtap="onClick">按钮</button>
  </view>
</template>

<script>
  import { createPage } from '@mpxjs/core'

  createPage({
    onLoad () {},
    methods: {
      onClick () {
        console.log(this)
      }
    }
  })
</script>

<script type="application/json">
  {
    "usingComponents": {
      "list": "../components/list"
    }
  }
</script>
```
![WechatIMG18](https://user-images.githubusercontent.com/25874685/103126700-0f5ca500-46ca-11eb-941d-cfeaebb28fd3.png)

**Comment by tliwyl** [comment]
https://github.com/tliwyl/mpx

**Comment by zhaoyiming0803** [comment]
> https://github.com/tliwyl/mpx 这个地址
> 备注：和渲染没关系（用selectComponent获取组件实例没问题），项目中是在点击事件中获取ref属性的第一次点击总是得到undefined，第二次会正常运行。（注意是头条环境而且是真机模拟器没问题）。

好，我去看下

**Comment by zhaoyiming0803** [comment]
> https://github.com/tliwyl/mpx 这个地址
> 备注：和渲染没关系（用selectComponent获取组件实例没问题），项目中是在点击事件中获取ref属性的第一次点击总是得到undefined，第二次会正常运行。（注意是头条环境而且是真机模拟器没问题）。

试了一下，如下demo，selectComponent 和 $refs 都能获取到，ios14.0.1，头条客户端8.0.2。你用的是哪个设备，或者先升级下客户端。

父组件
``` html
<list wx:ref="listRef" id="Jcom"></list>
```

``` javascript
createPage({
    onLoad () {},
    onReady() {
      // const listRef = this.selectComponent('#Jcom')
      const listRef = this.$refs.listRef
      console.log('listRef:: ', listRef)
      listRef.updListData()
    }
  })
```

子组件：

``` html
<view wx:for="{{listData}}" wx:key="index">{{item}}</view>
```

``` javascript
createComponent({
    data: {
      listData: ['手机', '电视', '电脑'],
      ids: 9999
    },
    methods: {
      updListData() {
        this.listData = ['手机', 'mac', '平板'];
        this.ids = 88888;
        console.log('list this: ', this);
        setTimeout(() => {
          console.log('timeout list this: ', this);
        }, 100);
      },
    }
  })
```

![112233](https://user-images.githubusercontent.com/25874685/103510705-b7c7f180-4ea0-11eb-95cc-4c23cd5d183e.jpeg)

**Comment by tliwyl** [comment]
我用的是华为p30,您给的截图是page中的获取ref这个是没问题的，我说的component中获取ref会有问题。最近项目有点忙，回复有点慢。暂时用selecComponent 解决问题了

**Comment by zhaoyiming0803** [comment]
> 我用的是华为p30,您给的截图是page中的获取ref这个是没问题的，我说的component中获取ref会有问题。最近项目有点忙，回复有点慢。暂时用selecComponent 解决问题了

如下 demo 所示，在所有平台的小程序，在 attached 中都获取不到 $refs，可以把 attached 改为 ready 再获取 $refs。

另外，$refs 内部实际上就是执行 this.selectComponent 获取节点实例，不过[头条小程序的this.selectComponent 变为异步函数了](https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/guide/custom-component/component-constructor/)，所以在开发者工具上也是获取不到对应的 ref 的。
``` html
<template>
  <view class="list">
    <aCom wx:ref="listRef" id="Jcom"></aCom>
  </view>
</template>

<script>
createComponent({
    data: {
      listData: ['手机', '电视', '电脑'],
      ids: 9999
    },
    attached () {
     // 获取不到
      console.log('listRef in ready: ', this.$refs.listRef)
    },
   ready () {
      // 除头条小程外都可以获取到
      console.log('listRef in ready: ', this.$refs.listRef)

     // 只有头条小程序的 selectComponent 改成了异步函数
      const jcom = this.selectComponent('#Jcom', res => {
        console.log('selectComponent: ', res)
      })
      console.log('jcom: ', jcom)
    }
})
</script>
```

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.48
头条即将废弃selectComponent同步方法调用，我们在2.6.48版本中将头条环境下的组件ref改为promise，在头条环境下请使用`this.$refs.xxx.then((res)=>{})`的方式获取组件ref，在跨平台的情况下需通过条件编译或者判断ref是不是promise进行区分处理。
