### ISSUE TITLE
[Bug report]自定义组件上的class编译出来不对

### ISSUE THREAD

**Issue by yuu2lee4** [didi/mpx#693]
自定义组件在分包里面使用的时候class编译出来不对，主包里的没问题

![image](https://user-images.githubusercontent.com/8046366/103526259-9f190500-4ebb-11eb-945f-3ab12c638a22.png)
![image](https://user-images.githubusercontent.com/8046366/103526271-a2ac8c00-4ebb-11eb-8876-1d3ddef77d40.png)
组件内的class 前面都加了一个detail--，分包页面刚好名称也是detail.mpx

**Comment by hiyuki** [comment]
请按照引导提供完整的环境描述和最简复现demo

**Comment by yuu2lee4** [comment]
好的

**Comment by hiyuki** [comment]
问题还存在吗，如果存在的话请提供复现demo后重新开启issue

**Comment by yuu2lee4** [comment]
[mpxdemo.zip](https://github.com/didi/mpx/files/5814285/mpxdemo.zip)
现在这个demo直接class都传不进去，分包路径:resource/pages/detail

**Comment by yuu2lee4** [comment]
无法reopen
