### ISSUE TITLE
tt下监听上传文件进度UploadTask.onProgressUpdate报错

### ISSUE THREAD

**Issue by 15649968036** [didi/mpx#695]
**问题描述**  
![image](https://user-images.githubusercontent.com/56305221/104010354-53ca6380-51e7-11eb-8cfe-1dfb2dabf91c.png)

![image](https://user-images.githubusercontent.com/56305221/104010212-1fef3e00-51e7-11eb-92d4-de8fc35c2838.png)

微信和百度是可以的
头条原生也是可以走通的
![image](https://user-images.githubusercontent.com/56305221/104010579-adcb2900-51e7-11eb-9c8f-74512d504723.png)

**Comment by 15649968036** [comment]
> **问题描述**
监听上传文件进度编译后  微信百度正常 头条下报错 
![1610105641(1)](https://user-images.githubusercontent.com/56305221/104011529-326a7700-51e9-11eb-88e6-c9f4bef0d237.jpg)
![1610105589(1)](https://user-images.githubusercontent.com/56305221/104011533-36969480-51e9-11eb-99ab-452a0eb57357.jpg)

)
> 
> 头条原生也是可以走通的
![1610105691(1)](https://user-images.githubusercontent.com/56305221/104011559-444c1a00-51e9-11eb-9276-f76c94c19465.jpg)

>

**Comment by zhaoyiming0803** [comment]
> **问题描述**
> ![image](https://user-images.githubusercontent.com/56305221/104010354-53ca6380-51e7-11eb-8cfe-1dfb2dabf91c.png)
> 
> ![image](https://user-images.githubusercontent.com/56305221/104010212-1fef3e00-51e7-11eb-92d4-de8fc35c2838.png)
> 
> 微信和百度是可以的
> 头条原生也是可以走通的
> ![image](https://user-images.githubusercontent.com/56305221/104010579-adcb2900-51e7-11eb-9c8f-74512d504723.png)

可以通过以下任意一种方式解决：

第一种，关闭 usePromise

``` javascript
mpx.use(apiProxy)
```

第二种，如果使用 usePromise，使用 __returned

``` javascript
uploadTask.__returned.onProgressUpdate(res => {
    // ......
})
```

另外，如果需要跨平台输出代码的话，使用 api 的时候尽量用 mpx.xxx

**Comment by hiyuki** [comment]
https://mpxjs.cn/guide/extend/api-proxy.html#%E4%BD%BF%E7%94%A8promise%E5%BD%A2%E5%BC%8F 文档中已添加对应说明
