### ISSUE TITLE
[Bug report] webpack-pluging 更新至 2.6.44 后不能在 css 中使用 @import

### ISSUE THREAD

**Issue by YXL76** [didi/mpx#697]
这段代码可以编译通过

``` html
<style src="../app.css"></style>
```

下面这段不行

``` html
<style>
@import "../app.css";
</style>
```

**Comment by zhaoyiming0803** [comment]
> 这段代码可以编译通过
> 
> ```
> <style src="../app.css"></style>
> ```
> 
> 下面这段不行
> 
> ```
> <style>
> @import "../app.css";
> </style>
> ```

可以暂时先用以下方式解决：

``` html
<style src="../app.css"></style>
```

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.45 已修复

**Comment by theowenyoung** [comment]
Hi, @hiyuki 

这里 @import 不支持引入第三方css吗？最新版试了无法引入。用`src`的方式可以引入。

```html
<style>
/*此处编写全局样式*/
@import "mini-tailwind/dist/tailwind.css";
</style>
```

写了个最小demo, https://github.com/theowenyoung/mpx-import-npm-css/blob/main/src/app.mpx

主要是要合并第三方css和我们自己的公共css，每个组件都需要用，所以用src的方式引入的话，就得第三方和我们自己的公共css都引入，要写两个标签，不利于维护。

所以想问下这里 `@import`是有什么限制吗？
