### ISSUE TITLE
在引入.wxss文件时,打包出错

### ISSUE THREAD

**Issue by broxlighters** [didi/mpx#699]
**问题描述**  
使用colorUI时,在app.mpx引入.wxss文件出错
1. 问题触发的条件: 在app.mpx引入.wxss文件出错
2. 期望的表现: 正常打包
3. 实际的表现: 打包出错,提示.wxss文件引入出错

**环境信息描述**  
至少包含以下部分：
1. 系统类型: Windows

2. Mpx依赖版本: 
@mpxjs/core: ^2.6.31、
@mpxjs/webpack-plugin: ^2.6.31
@mpxjs/api-proxy: ^2.5.10

3. 小程序开发者工具信息: 
开发者工具版本: v1.03.2012120

**最简复现demo**  
app.mpx中的
```
<style>
  @import './main.wxss';
</style>
```
报错
demo链接:
[mpx-test.zip](https://github.com/didi/mpx/files/5792369/mpx-test.zip)

**Comment by zhaoyiming0803** [comment]
> **问题描述**
> 使用colorUI时,在app.mpx引入.wxss文件出错
> 
> 1. 问题触发的条件: 在app.mpx引入.wxss文件出错
> 2. 期望的表现: 正常打包
> 3. 实际的表现: 打包出错,提示.wxss文件引入出错
> 
> **环境信息描述**
> 至少包含以下部分：
> 
> 1. 系统类型: Windows
> 2. Mpx依赖版本:
>    @mpxjs/core: ^2.6.31、
>    @mpxjs/webpack-plugin: ^2.6.31
>    @mpxjs/api-proxy: ^2.5.10
> 3. 小程序开发者工具信息:
>    开发者工具版本: v1.03.2012120
> 
> **最简复现demo**
> app.mpx中的
> 
> ```
> <style>
>   @import './main.wxss';
> </style>
> ```
> 
> 报错
> demo链接:
> [mpx-test.zip](https://github.com/didi/mpx/files/5792369/mpx-test.zip)

可以暂时先用以下方式解决：

``` html
<style src="./main.wxss"></style>
```html

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.45 已修复
