### ISSUE TITLE
run watch 会出现问题

### ISSUE THREAD

**Issue by ialmost** [didi/mpx#70]
building...{ Error: ENOTEMPTY: directory not empty, rmdir 'D:\Office\project\wxck\dist\pages'
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'D:\\Office\\project\\wxck\\dist\\pages' }
| building...

这个问题必现，最新版本的

mpx 版本
    "@mpxjs/core": "^1.0.26",
    "@mpxjs/fetch": "^1.0.14",
    "@mpxjs/promisify": "^1.0.14",
    "@mpxjs/url-loader": "^1.0.15",
    "@mpxjs/webpack-plugin": "^1.0.26",

**Comment by sky-admin** [comment]
无法复现，应该和框架无关，尝试检查下系统的权限相关的设定。

**Comment by hiyuki** [comment]
麻烦提供一下系统版本及node版本

**Comment by hiyuki** [comment]
排查了一下这是rimraf在windows下可能出现的一个问题，rimraf的同步版本在windows下对于enotempty错误进行了100次重试，我们将rimraf的调用改为同步后基本不再复现该问题，下个版本修复

**Comment by ialmost** [comment]
> 排查了一下这是rimraf在windows下可能出现的一个问题，rimraf的同步调用在windows下对于enotempty错误会进行100次重试，异步调用时没有该处理，我们将rimraf的调用改为同步后基本不再复现该问题，改动位置为build.js的末尾，将对应代码改为
> 
> ```js
> rm.sync(path.resolve(__dirname, '../dist/*'))
> runWebpack(webpackConfig)
> ```
更改相应代码后，run watch 会出现如下错误
![image](https://user-images.githubusercontent.com/6847189/52607639-f66df080-2eb1-11e9-9f95-6e64c5eea28f.png)

**Comment by heiye9** [comment]
我在windows上也遇到同样问题，貌似是因为微信开发者工具锁了文件权限导致的。正准备给微信提反馈时发现昨天的开发版已经修复了
![image](https://user-images.githubusercontent.com/24930493/61294024-8ae4d200-a807-11e9-8224-1ccdb909c620.png)

**Comment by ialmost** [comment]
> 我在windows上也遇到同样问题，貌似是因为微信开发者工具锁了文件权限导致的。正准备给微信提反馈时发现昨天的开发版已经修复了
> ![image](https://user-images.githubusercontent.com/24930493/61294024-8ae4d200-a807-11e9-8224-1ccdb909c620.png)

看到了，等稳定版本看看如何
