### ISSUE TITLE
[Feature Request] button组件转换支持新的open-type

### ISSUE THREAD

**Issue by vivine** [didi/mpx#704]
起因：

百度进行非兼容性改造，https://smartprogram.baidu.com/forum/topic/show/125547，

将swan.login接口下线，改为需要用户触发button进行登录，新增了一个open-type类型，参考：

https://smartprogram.baidu.com/docs/develop/component/formlist_button/

因此需要mpx官方做一下兼容，查找了源程序应该是下面这个：

https://github.com/didi/mpx/blob/2ec98bdbb3d263fa179e80bebb1d0cc309a64e64/packages/webpack-plugin/lib/platform/template/wx/component-config/button.js#L62-L71

希望官方尽快兼容一下！！

**Comment by OnlyProbie** [comment]
Mpx是以微信为base实现了一套转换规则，为了保证微信正常运行，对于微信不支持的属性，都会抛出一个警告，目前看这个警告抛出是有点问题，我们check一下。
如果需要使用其他平台的特有属性可以通过条件编译的方式实现： <button open-type@swan="login"> ，具体可以参考文档：https://mpxjs.cn/guide/advance/platform.html#%E8%B7%A8%E5%B9%B3%E5%8F%B0%E7%BC%96%E8%AF%91
