### ISSUE TITLE
选择的是swan平台，用watch 例子里面的listData无法渲染出来，用build就可以渲染出来

### ISSUE THREAD

**Issue by yangcore** [didi/mpx#708]
选择的是swan平台，用watch 例子里面的listData无法渲染出来，用build就可以渲染出来
![83CE17D8ACF915579A4BA945AB740732](https://user-images.githubusercontent.com/20217483/104449353-71c60880-55d9-11eb-8f79-e30548b55bad.jpg)
![F2267DD42F5EDEDE4310D3EB2B9D30C7](https://user-images.githubusercontent.com/20217483/104449363-75598f80-55d9-11eb-8148-ee2b4777f93d.jpg)
![D8AE7AB3AA65E62239793AEC74E321EB](https://user-images.githubusercontent.com/20217483/104449368-78548000-55d9-11eb-91a4-6b5d5c3a1156.jpg)

以微信小程序为模版跨平台编译到swan，也是watch无法渲染出listData,build却可以

mpx版本v2.6.45，可以保证所有的包都是最新版本

电脑平台：mac

百度小程序开发工具版本：3.23.2

**Comment by hiyuki** [comment]
测试发现最新版本的百度开发者工具对于source-map的支持存在bug，watch模式默认开启source-map所以导致了上述问题，可以在build/getWebpackConf当中关闭source-map来应对该问题，最新版脚手架模板在百度修复之前也会对百度关闭source-map
