### ISSUE TITLE
始终没找到支持到小程序的基础版本库版本是多少

### ISSUE THREAD

**Issue by Jerry12138** [didi/mpx#71]

**Comment by sky-admin** [comment]
基础库版本主要影响的是小程序本身提供的一些API吧，mpx不怎么依赖基础库版本，只要支持自定义组件和wxs就可以比较完美地使用mpx框架了。如有发现基础库版本带来的异常表现，麻烦反馈给我们，谢谢。

**Comment by Jerry12138** [comment]
> 基础库版本主要影响的是小程序本身提供的一些API吧，MPX不怎么依赖基础库版本，只要支持自定义组件和WXS就可以比较完美地使用MPX框架了。如有发现基础库版本带来的异常表现，麻烦反馈给我们，谢谢。

@sky-admin 因为我看到组件带了pageShow和pageHide两个钩子，我担心实现原理是用了小程序组件的lifetimes，但是这个api是基础版本库2.2.3才实现的，然后又没看懂源码，所以想问一下

**Comment by hiyuki** [comment]
pageShow实现不依赖lifetimes
