### ISSUE TITLE
[Bug report]控制台报错 build.js supportedCrossMode 未定义

### ISSUE THREAD

**Issue by guozhier** [didi/mpx#714]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
    创建项目首次编译
2. 期望的表现
    项目正常编译
3. 实际的表现
    控制台报错 build.js supportedCrossMode 未定义

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
    Mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
    "@mpxjs/api-proxy": "^2.5.10",
    "@mpxjs/core": "^2.6.31",
    "@mpxjs/webpack-plugin": "^2.6.31",
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
    小程序平台：微信
    开发者工具版本：1.03.2101150
    基础库版本：2.14.4
        

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
build/build.js:
![1610960833257](https://user-images.githubusercontent.com/29756013/104894433-aeb24680-59af-11eb-9972-2fd0a87da2df.jpg)
把supportedCrossMode 改成 supportedModes 就可以正常编译了，不知道是不是我这配置有错，还是什么原因，希望能解答下谢谢！

**Comment by sky-admin** [comment]
嗯，这个是NPM7带来的问题，之前已经发现了，但是修复方案有问题，就是你说的那个地方，写错了。可以给我们提个PR：https://github.com/mpx-ecology/mpx-template/blob/master/template/build/build.js 改这个项目

**Comment by hiyuki** [comment]
确实是我们的代码有误，目前已修复，那个地方改成supportedModes即可
