### ISSUE TITLE
[Feature Request] i18n 支持网络加载语言包

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#716]
我的想法是这样，稍微验证过一下，应该是没问题的

mpx plugin options那里保持原样
默认只写上zh-CN的配置，然后增加多一个i18n辅助方法
例如：$ts，参数为：(source, locale, key, values)，然后template层面编译时类似mpxLocale一样把第一第二个参数编译成固定属性
mpx初始化时 observe(source) 
然后再修改mixin，再把source添加到data里
这样可以实现网络加载语言包，动态替换，template层面也可以实现网络语言包

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.56，可以基于这个版本提供的特性进行实现
