### ISSUE TITLE
新版本混编原生小程序失败

### ISSUE THREAD

**Issue by yulintianxia** [didi/mpx#717]
按照官方文档，混编原生小程序，报错，最新版本报错，之前的版本可以
![image](https://user-images.githubusercontent.com/44962371/105650384-9e89f200-5eee-11eb-9f93-030bbbe889d8.png)

**Comment by Blackgan3** [comment]
文档中的 mpx-progressive 项目中pages 中 Mpx 版本还是 1.X，默认走的是 小程序原生路径，新版本中的resolveMode 为 webbpack

#### 这里有两种修改方式：
* 把路径改为相对路径
```js
"pages/index/index" 改为 "./page/index/index"
```
* 改为native路径模式(这里不推荐)
```js
 new MpxWebpackPlugin({
  resolveMode: 'native'
}) 
```
可参考文档：https://mpxjs.cn/guide/advance/npm.html#%E5%85%BC%E5%AE%B9%E5%8E%9F%E7%94%9F%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%B7%AF%E5%BE%84%E8%A7%84%E8%8C%83

后续我们会对example中的版本进行升级
