### ISSUE TITLE
[配置问题]如何配置 html 映射规则， 比如 div 自动变为 view，span 自动为 text？

### ISSUE THREAD

**Issue by zaxlct** [didi/mpx#718]
目前使用的 pug 语法，每次都要手敲 `view.container  view.box  text.taobao`

如果省略 view 标签，只写 `.contanier` 则被编译为 `div` 而不是 `view`，那么怎么配置可以做到 div 标签自动编译为 view 标签

**Comment by hiyuki** [comment]
框架目前没有做这样的处理，这个需要调研一下pug能不能支持

**Comment by pecopeco** [comment]
可以自行将pug-parse插件中的默认转换标签div修改为view
