### ISSUE TITLE
[Feature Request] 支持环境变量注入,类似 MPX_KEY

### ISSUE THREAD

**Issue by theowenyoung** [didi/mpx#727]
看到之前有一个一样的问题 #654 ，但是被关闭了，希望官方能统一支持下。
 
> 我们现在支持直接访问process.env.NODE_ENV来判断是生产环境还是开发环境，通过__mpx_mode__读取当前的构建平台，以及也支持通过webpack-plugin中的defs选项添加新的自定义常量，你具体的业务场景是啥？通过上述能力是否能够完成？

业务场景就是注入一些不适合放在代码里的值，比如secret,构建时间，构建版本等信息。

试用之后发现`defs`只支持在组件内部使用，但是我希望是在正常的js里也能用`process.env.BUILD_TIME`来使用。

目前可以自己修改getPlugins来用，

```javascript
    new webpack.DefinePlugin({
      "process.env": {
        NODE_ENV: production ? '"production"' : '"development"',
        TENCENT_MAP_KEY: JSON.stringify(process.env.TENCENT_MAP_KEY),
        BUILD_TIME:JSON.string(Date.now())
      }
    })
```

希望官方可以统一支持下，期望的实现方式，允许开发者定义一个`.env`文件，

```ini
MPX_KEY=value
```

在任何地方使用的时候:

```
const x = process.env.MPX_KEY
```

**Comment by hiyuki** [comment]
defs在正常js里也内使用，或者说defs在正常js里其实就是通过definePlugin实现的，除此之外defs还可以在所有的条件编译判断中以及模板插值中使用

**Comment by zaxlct** [comment]
> Defs在正常js里也内使用，事实上defs在js中就是通过definePlugin实现的，除此之外defs还可以在所有的条件编译判断中以及模板插值中使用。
> Defs的使用限制在于key值必须为合法的identifier，不能以`process.env`这样的形式定义，像你上例中你可以定义一个
> 
> ```js
> defs: {
>   MPX_KEY: 'someValue'
> }
> ```
> 
> 就可以在上述defs可用的位置正常使用(全量js环境，模板插值，各类条件编译判断条件内)
> 
> ```
> const x = MPX_KEY
> ```
> 
> 类似于宏定义，你将其作为环境变量使用也是完全没问题的

defs 里怎么区分 dev 和 prod 呢

**Comment by theowenyoung** [comment]
好吧，@hiyuki , 试了下可以了，谢谢。

原来这里是要按照全局变量去使用的，文档里def配置好像没有提到。提交了一个文档PR https://github.com/didi/mpx/pull/728

不过这样做好像有点不太符合业界使用define变量的习惯，其他框架或者define插件本身都是使用`process.env.XXX`这样来使用的。 直接按照全局变量使用的话，有点让代码风格不太好，比如同事看了之后会有点懵...

不过，这里看官方的意见吧，也许可以在下个大版本里这里可以改一下。

**Comment by theowenyoung** [comment]
@zaxlct 可能要自己写判断,类似这样：

```js
defs: {
  MPX_KEY: process.env.NODE_ENV==='production'?'someValue':'xxxx'
}
```

**Comment by hiyuki** [comment]
@zaxlct 
现有脚手架项目中你可以通过将config/mpxPlugin.conf.js导出为函数，来实现prod模式与dev模式返回不同的mpx插件配置，示例如下：
```js
// config/mpxPlugin.conf.js
module.exports = function ({ production }) {
  if (production) {
    // 返回prod配置
    // return ...
  }
  // 返回dev配置
  // return ...
}
```
