### ISSUE TITLE
watch 偶尔会出现 wxs 未编译的情况

### ISSUE THREAD

**Issue by ialmost** [didi/mpx#73]
![image](https://user-images.githubusercontent.com/6847189/52703261-e7259a80-2fb8-11e9-854b-effbc92c4c3d.png)
![image](https://user-images.githubusercontent.com/6847189/52703276-f3a9f300-2fb8-11e9-845f-f2bbb7859718.png)

**Comment by hiyuki** [comment]
麻烦提供一下系统信息

**Comment by hiyuki** [comment]
出现该报错时可以查看一下文件系统dist中是否存在对应的wxs文件

**Comment by ialmost** [comment]
不存在

**Comment by ialmost** [comment]
> 出现该报错时可以查看一下文件系统dist中是否存在对应的wxs文件

编译说明显示已编译这些文件，但是dist中并无这些文件

**Comment by sky-admin** [comment]
无法复现，先关闭，若有相同情况再打开吧。
