### ISSUE TITLE
[Bug report]事件名中间带-的是无法触发的

### ISSUE THREAD

**Issue by zaxlct** [didi/mpx#731]
**问题描述**  
https://github.com/youzan/vant-weapp/issues/3332
mpx 也有同样的问题

**环境信息描述**  
https://github.com/youzan/vant-weapp/issues/3332
mpx 也有同样的问题

使用 mpx 时，事件名中间带-的是无法触发的

**最简复现demo**  
https://github.com/youzan/vant-weapp/issues/3332
mpx 也有同样的问题

**Comment by Blackgan3** [comment]
我用@vant/weapp 试了一下，uploader 中的 after-read 事件执行是没问题的，你这边目前还是本地稳定复现吗？或者提供一个你稳定复现的demo也行。

下方是我的使用方式
[https://dpubstatic.udache.com/static/dpubimg/uThsc1iy4t/clipboard_image_1615818381347.png](url)
