### ISSUE TITLE
[Bug report] 支付宝端externalClasses无法多层传递

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#736]
**问题描述**  
mpx.conf.js 
`externalClasses=["custom-class", "info-class"]`

页面样式
`.info-tag {xxx}`

```html
<!-- 页面 -->
<A info-class="info-tag"></A>
```

```html
<!--  组件A -->
<B custom-class="info-class"></B>
<!-- externalClasses: [‘info-class’] -->
```

```html
<!--  组件B -->
<view class="custom-class"></view>
<!-- externalClasses: [‘custom-class’] -->
```

组件B中的view无法应用页面中的`.info-tag`类

我现在处理方式是
组件B增加
`class@ali="info-class"`

微信里面不需要这样处理，不知道是否有其他解决办法?能做到类似微信里那种效果吗

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.53 已支持
