### ISSUE TITLE
Access-Control-Allow-Origin 

### ISSUE THREAD

**Issue by mayingyun** [didi/mpx#738]
在使用mpx开发输出web的时候，开发遇到的cors跨域问题，网上百度Vue项目的解决方案是在config/index.js中设置proxyTable，mpx怎么设置，在哪设置？

**Comment by Blackgan3** [comment]
开发场景下，可以使用 webpack-dev-server 的 proxy 来进行代理，具体文档链接如下：
https://webpack.docschina.org/configuration/dev-server/#devserverproxy

**Comment by Blackgan3** [comment]
不过小程序开发时，请求一般都是带host的绝对路径，通过ajax会直接打到线上服务器，走不到本地的devServer proxy，所以可以不用配置 webpack-dev-server，直接配置 charles 代理会更省事
