### ISSUE TITLE
[Bug report]微信开发者工具03190更新后框架表现一场

### ISSUE THREAD

**Issue by CXY037** [didi/mpx#743]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件： 当ctrl+c关闭yarn watch后重新yarn build 或yarn watch ，开发者工具未重启情况下，导致开发者工具无法家在自定义组件或者第三方ui组件。出现bug原因是开放者工具在本版本优化了json重载逻辑。
2. 期望的表现
3. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by Blackgan3** [comment]
我这边测试了一下，并没有复现这个异常呢

**Comment by CXY037** [comment]
我写个最小的复现代码哈

**Comment by CXY037** [comment]
我继续找一下bug原因吧，我写了最小引用复现的情况不多，但是项目中很容易复现，我找到可以100%复现的情况我再上传下代码。麻烦啦

**Comment by Blackgan3** [comment]
好的，搞到demo还辛苦再上传下

**Comment by CXY037** [comment]
嗯嗯好的不辛苦，我还在测试怎么稳定复现bug
