### ISSUE TITLE
[Bug report]scrollview的 binddragend 事件无效

### ISSUE THREAD

**Issue by KuiShang** [didi/mpx#749]
**问题描述**  

1. 在wx小程序工具  不能触发
2. 真机预览              可以触发
3. 转成web后           不能触发

**期望**

web中可以触发binddragend事件

**环境信息描述**  

1. mac
3. "@mpxjs/core": "^2.6.51",
4. "@mpxjs/webpack-plugin": "^2.6.52",
3. 小程序开发者工具信息(小程序平台 wx、开发者工具版本1.05.2102010,基础库版本 2.16.0）

**Comment by Blackgan3** [comment]
版本 [V2.6.54](https://github.com/didi/mpx/releases/tag/v2.6.54) 已经修复
