### ISSUE TITLE
执行init后进入工程目录，npm install报错，栈溢出

### ISSUE THREAD

**Issue by leowang1028** [didi/mpx#75]
![image](https://user-images.githubusercontent.com/20222764/52932674-7d780880-338b-11e9-8bf6-4e620191b012.png)

**Comment by hiyuki** [comment]
麻烦提供一下系统信息，node和npm版本信息

**Comment by leowang1028** [comment]
系统：win10
node：10.14.1
npm：6.8.0

**Comment by leowang1028** [comment]
> 麻烦提供一下系统信息，node和npm版本信息

系统：win10
node：10.14.1
npm：6.8.0

**Comment by sky-admin** [comment]
> > 麻烦提供一下系统信息，node和npm版本信息
> 
> 系统：win10
> node：10.14.1
> npm：6.8.0

使用window10试了下没问题，方便把具体的错误log信息放出来吗？我这边是node 11.5.0 npm 6.4.1。

**Comment by leowang1028** [comment]
> > > 麻烦提供一下系统信息，node和npm版本信息
> > 
> > 
> > 系统：win10
> > node：10.14.1
> > npm：6.8.0
> 
> 使用window10试了下没问题，方便把具体的错误log信息放出来吗？我这边是node 11.5.0 npm 6.4.1。

![image](https://user-images.githubusercontent.com/20222764/53309174-5bc5d680-38e1-11e9-8afa-fc972bcf6d92.png)
上周五重新install了一下，莫名的好了，这个log你们可以先看下

**Comment by sky-admin** [comment]
无法复现的偶然bug，先close了。
