### ISSUE TITLE
[Bug report]oppo r9s android6在tab事件无法获取绑定在组建上的自定义属性（如data-xxx)

### ISSUE THREAD

**Issue by KuiShang** [didi/mpx#752]
端： web
问题： 1oppo r9s android6 通过在组建上绑定 data-xxx属性，
             2 在tab事件通过event.target.dataset无法获取
期望：oppo r9s android6 可以获取

**Comment by yandadaFreedom** [comment]
版本[V2.6.57](https://github.com/didi/mpx/releases/tag/v2.6.57)已修复
