### ISSUE TITLE
[Bug report] Cannot find name 'global';  optionProcessor not export member 'getWxsMixin'

### ISSUE THREAD

**Issue by js5323** [didi/mpx#760]
**问题描述**  
执行命令 npm run watch:web 后报错
```
TS2614: Module '"../node_modules/@mpxjs/webpack-plugin/lib/runtime/optionProcessor"' has no exported member 'getWxsMixin'. 
Did you mean to use 'import getWxsMixin from "../node_modules/@mpxjs/webpack-plugin/lib/runtime/optionProcessor"' instead?
```
```
TS2304: Cannot find name 'global'.
```

**环境信息描述**  
MacOS Big Sur 11.2.3
@mpxjs/core: 2.6.59
@mpxjs/api-proxy: 2.6.59
@mpxjs/webpack-plugin: 2.6.59

**最简复现demo**  
https://github.com/js5323/mpx-project-ts.git

**Comment by Blackgan3** [comment]
getWxsMixins的报错我们会在下个版本解决

global的问题是你在tsconfig 中 显示配置了 types选项，导致默认的，所有位于 node_modules/@types 路径下的模块都会引入到编译器这一规则失效，你可以把 types配置删除，或者在 types 配置中增加 'node'

**Comment by hiyuki** [comment]
Cannot find name 'global' 如上述沟通
optionProcessor not export member 'getWxsMixin' 错误已修复：https://github.com/didi/mpx/releases/tag/v2.6.60
