### ISSUE TITLE
增强语法，只有微信的写法吗？可以跨平台吗？

### ISSUE THREAD

**Issue by jiangjiu** [didi/mpx#761]
请问一下，我们的业务只有百度小程序平台，所以在尝试mpx框架的时候，看到官网的很多写法和api只有微信版的，请问这个有没有针对百度小程序的？

市面上专注性能且编译系统强大的貌似只有mpx了，所以特别希望能用上这个框架，但是对百度小程序的支持还要靠你们了~~

**Comment by Blackgan3** [comment]
支持跨平台输出到百度小程序的
https://mpxjs.cn/guide/advance/platform.html#%E5%A4%9A%E5%B9%B3%E5%8F%B0%E6%94%AF%E6%8C%81

**Comment by jiangjiu** [comment]
非常感谢！
