### ISSUE TITLE
[Bug report]首屏渲染时，存在多余的setData，传递了mpxCid

### ISSUE THREAD

**Issue by jiangjiu** [didi/mpx#763]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：

<img width="1153" alt="WX20210428-185728@2x" src="https://user-images.githubusercontent.com/9526388/116393266-020c1e80-a854-11eb-949e-d257541d9034.png">

生成的bundlejs中，图中红框的这句代码会导致很多组件明明没有setData语句，也会产生setData=>{mpxCid:1}这样的行为，如果组件很多，setData排队阻塞就非常明显，希望能解一下

**环境信息描述**  
至少包含以下部分：
1. 系统类型 Mac
2. Mpx依赖版本  线上最新
3. 小程序开发者工具信息  百度小程序 最新

**Comment by jiangjiu** [comment]
![image](https://user-images.githubusercontent.com/9526388/116394094-1270c900-a855-11eb-9920-76faa82fb406.png)
看源码注释，这里是因为支付宝的问题才处理的？
是不是可以考虑做一下环境判断，毕竟百度小程序或者微信没问题的话，不需要承担额外的setData消耗
或者直接通过条件编译去处非当前环境的兼容代码

**Comment by hiyuki** [comment]
确定会调用setData么，mpx本身会基于模板数据依赖去调用setData，在百度场景下模板上不应该会存在mpxCid访问，这个数据也不应该会产生setData。

**Comment by hiyuki** [comment]
你可以在proxy.js文件402行`this.target.__render(processUndefined(data), callback)`打印一下data，这块才是真实的setData调用，如果确实存在问题请上传个复现demo。

**Comment by jiangjiu** [comment]
> 你可以在proxy.js文件402行`this.target.__render(processUndefined(data), callback)`打印一下data，这块才是真实的setData调用，如果确实存在问题请上传个复现demo。

仔细查了一下，是我们的同学代码写的有问题😂
模板上直接使用了item.count，但是item其实是上层向下传递的object，初始化的时候会导致render function执行失败，回退到full-set-data mode，这样就会把data中的mpxCid打印出来。
