### ISSUE TITLE
[Bug report] Component is not found in path

### ISSUE THREAD

**Issue by js5323** [didi/mpx#766]
**问题描述**  
在开发过程中，偶尔会出现控制台报错：Component is not found in path
检查了dist文件，对应component的文件都存在的。
重新执行编译后又正常了。

**环境信息描述**  
MacOS Big Sur 11.2.3
@mpxjs/core: 2.6.60
@mpxjs/api-proxy: 2.6.60
@mpxjs/webpack-plugin: 2.6.60

**Comment by Blackgan3** [comment]
辛苦提供下可复现的demo或者可复现的步骤吧

**Comment by hiyuki** [comment]
请提供复现demo后重新open
