### ISSUE TITLE
希望尽早能够支持 async/await 

### ISSUE THREAD

**Issue by nxboo** [didi/mpx#77]

**Comment by ialmost** [comment]
支持啊

**Comment by nxboo** [comment]
> 支持啊

能不能给个文档或例子？

**Comment by ialmost** [comment]
> > 支持啊
> 
> 能不能给个文档或例子？

`
async Fun () {
      let res = await this.other()
}
`

**Comment by sky-admin** [comment]
async/await的支持是babel提供的，和mpx框架无关，mpx默认脚手架配置的规则下src下的js/mpx文件中是支持的
