### ISSUE TITLE
[Bug report] 微信中使用小程序插件时出现异常

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#777]
## 触发条件：
引入任意插件，引入qs包（个人猜测可能其他包使用到的一些特性也会导致类似问题出现）

## 期望：
正常引入插件，不报错

## 环境：
mac
mpx@2.6.61
微信开发工具
![image](https://user-images.githubusercontent.com/22525904/118250339-f0c04480-b4d8-11eb-83a7-3139f00b9ed7.png)
基础库版本：2.16.1

demo:
[归档.zip](https://github.com/didi/mpx/files/6477841/default.zip)

**Comment by okxiaoliang4** [comment]
我又试了一下,这个问题应该跟mpx无关, qs 与 插件有冲突，有可能是小程序IDE的问题

**Comment by hiyuki** [comment]
那issue先关了，后续还有问题再打开吧

**Comment by okxiaoliang4** [comment]
qs替换成querystring,qs有语法微信小程序端不支持
