### ISSUE TITLE
[Bug report] mpx.reportMonitor 使用报错

### ISSUE THREAD

**Issue by veen-lee** [didi/mpx#779]
**问题描述**  
1.使用`mpx.reportMonitor('1', 1)`
2.期望正常执行
3.实际执行结果报错
![image](https://user-images.githubusercontent.com/59392242/118586106-bacadb00-b7cc-11eb-9588-9ec9b7beb683.png)

**环境信息描述**  
至少包含以下部分：
1. 系统类型 Mac
2. <img width="471" alt="截屏2021-05-18 11 34 22" src="https://user-images.githubusercontent.com/59392242/118586259-02516700-b7cd-11eb-8cbf-2c90d13e61af.png">
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
微信小程序 
开发者工具 Stable 1.05.2103200
基础库版本 2.17.0
**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by Blackgan3** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.61
版本已修复
