### ISSUE TITLE
开发小程序插件安装mpc-cli报错

### ISSUE THREAD

**Issue by ruindong** [didi/mpx#801]
ruindong-pro@Ruindong-MacBook-Pro ~ % sudo npm i mpx-cli -g
Password:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated har-validator@5.1.5: this
npm WARN nunjucks@3.2.3 requires a peer of chokidar@^3.3.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/mpx-cli/bin/mpx.js
npm ERR! dest /usr/local/bin/mpx
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/mpx-cli/bin/mpx.js' -> '/usr/local/bin/mpx'
npm ERR! File exists: /usr/local/bin/mpx
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ruindong-pro/.npm/_logs/2021-06-10T03_36_46_325Z-debug.log

**Comment by hiyuki** [comment]
报错已经写得很清楚了，删除/usr/local/bin/mpx后再安装，要是还不行可以考虑使用npx
