### ISSUE TITLE
原生小程序插件的入口index.js在Mpx框架上如何配置

### ISSUE THREAD

**Issue by ruindong** [didi/mpx#808]
![image](https://user-images.githubusercontent.com/12420600/122326665-356b4f80-cf5f-11eb-9c17-b734278f366d.png)

![image](https://user-images.githubusercontent.com/12420600/122326786-677cb180-cf5f-11eb-8d61-1777d0651e6a.png)
###  如上图原生小程序可以调用插件主入口的方法，那么在Mpx上如何使用这一操作。插件的主入口index如何编写

**Comment by hiyuki** [comment]
脚手架创建项目时选择插件项目，会生成插件项目模板，其余编写和调用插件的方式与原生小程序小程序完全一致

**Comment by ruindong** [comment]
@hiyuki 但是在使用requirePlugin的时候脚手架会报错
![image](https://user-images.githubusercontent.com/12420600/122357206-1c29c980-cf86-11eb-803a-8d028866a2be.png)

**Comment by hiyuki** [comment]
你这是个lint错误啊，ignore或者添加全局声明就行
