### ISSUE TITLE
[Bug report] template 异常

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#810]
**问题描述**  
发现有个地方格式化之后是这样：
![image](https://user-images.githubusercontent.com/22525904/122518876-5fe30880-d044-11eb-89ff-687e8c76b242.png)
然后在界面上会显示为空，但是如果改成这样：
![image](https://user-images.githubusercontent.com/22525904/122518898-670a1680-d044-11eb-8e7f-627574bc4b36.png)
 就显示正常了

**环境信息描述**  
支付宝IDE 2.0.4
Linux、Mac上编译不会有这个问题，Windows上编译必现，
@mpxjs/core 2.6.67
@mpxjs/webpack-plugin 2.6.67

**Comment by okxiaoliang4** [comment]
@mpxjs\webpack-plugin\lib\template-compiler\compiler.js
compiler parseMustache 输出结果：
![image](https://user-images.githubusercontent.com/22525904/122522104-2b714b80-d048-11eb-8303-351d16f357d9.png)

**Comment by okxiaoliang4** [comment]
判断Mustache的正则我用工具都校验过了是可以通过的，但是实际编译运行的时候返回的结果为`false`
![image](https://user-images.githubusercontent.com/22525904/122524330-9459c300-d04a-11eb-8eff-bfb9379afae6.png)
![image](https://user-images.githubusercontent.com/22525904/122524598-e7337a80-d04a-11eb-96f1-e18d43df6952.png)

![image](https://user-images.githubusercontent.com/22525904/122524362-9facee80-d04a-11eb-9b47-8789451dd312.png)

**Comment by anotherso1a** [comment]
通过现象看可能是由于是缺少正则修饰符`m`导致的:
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/RegExp
细节需要再排查一下

**Comment by anotherso1a** [comment]
方便提供一下复现demo吗？只在使用该组件库的时候才会有这种问题吗？

**Comment by Blackgan3** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.78

已修复
