### ISSUE TITLE
[Bug report] 支付宝scoped样式异常

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#812]
**问题描述**  
支付宝 scoped 样式会出现数字开头的className，例如`.23bdsb`，导致样式异常

**环境信息描述**  
@mpxjs/webpack-plugin 2.6.70

**Comment by okxiaoliang4** [comment]
https://github.com/didi/mpx/commit/87dd83a64ac49659b7e3af99c60db1715cb0acf0
@hiyuki 请问这里scopeId为什么需要修改成moduleId,定位到是该提交引发的问题

**Comment by hiyuki** [comment]
我发版修复一下

**Comment by okxiaoliang4** [comment]
好的辛苦

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.71 已修复
