### ISSUE TITLE
webpack中设定公共路径@开头，是怎么配置的呢

### ISSUE THREAD

**Issue by chybcool** [didi/mpx#822]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 文件引入以../等开头感觉比较繁琐，所有文件路径@开头方便很多，
2. 所有文件路径@开头方便很多
3. 以../或../../等比较繁琐

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by okxiaoliang4** [comment]
修改 **webpack.base.conf.js** 中 `resolve.alias`,具体配置参考webpack文档，如果使用了`typescript`，**tsconfig.json** 中`compilerOptions`需要添加`paths`配置
