### ISSUE TITLE
请教下，mpx是怎么挂载 全局方法

### ISSUE THREAD

**Issue by chybcool** [didi/mpx#829]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1.mpx是怎样把方法挂载全局的呢，如同挂vue原型上，vue.prototype.meth=xxxxx
2. 公共方法每个页面用到都 需要导一次，能通过 全局挂载实现吗
3. 全局方法挂载 

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by okxiaoliang4** [comment]
可以用用插件的形式挂载到原型上

```javascript
// plugins/store.js
import $store from "../../store";

let installed = false;

function install(target: any, options: any) {
    if (installed) return;
    installed = true;

    target.$store = $store;
    Object.defineProperty(target.prototype, "$store", {
        get() {
            return $store;
        }
    });
}

export { install };
export default install;


// app.js 页面中
import store from './plugins/store';

mpx.use(store);
```

**Comment by hiyuki** [comment]
嗯，除了楼上介绍的通过插件机制新增全局实例属性的方式，直接挂载到app上通过getApp()也是小程序中全局数据挂载的通用方式，可参考微信文档https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/app.html
