### ISSUE TITLE
上传图 回调里this没定义

### ISSUE THREAD

**Issue by chybcool** [didi/mpx#831]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1.  回调里this没定义
2. 期望的表现
3. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
//上传图片方法 参数再加 filetype 上传类型
const uploadImg = function(pathEnum, fallback) {
  wx.chooseImage({
    count: 1, // 上传数量
    sizeType: ['original', 'compressed'], // 原图还是压缩图，默认二者都有
    sourceType: ['album', 'camera'], // 来源相册还是相机默认二者
    success:(res=>{
      let filePath = res.tempFilePaths[0]
      if (regImg.test(filePath)) {
        let path = filePath.match(/\.[^.]+$/)[0]
        getUploadMaterialsSign({ fileNameSuffix: path, ossPathEnum: pathEnum }).then(r => {
          fallback(uploadFileS(r, filePath))
        })
      } else {
        let mes='格式错误,请重新选择'
        toast(mes)
      }
    })
  })
}
export { uploadImg }

xxx.mpx
import {uploadImg} from '@common/upLoadPic/oss.js'
触发chooseimage方法，回调 this.fallback 
chooseimage() {
      if (!this.isDisabled) {
        //Applet_Avatar 个人/成员头像  Applet_Device设备头像
        let pic = 'Applet_Avatar'
        this.uploadImg(pic,this.fallback)
      }
    },
    //上传头像成功
    fallback(res){
      console.log(res,'res////')
      let fileDto = {
        filePath: res.filePath,
        fileType: 'Applet_Avatar',
        fileUrl: res.fileUrl
      }
      this.form.photo = res.fileUrl  这里this.没定义
      this.form.fileDto = fileDto
    },

**Comment by hiyuki** [comment]
...你这个代码片段基本不可读，编写上传一个可复现问题的简单demo，并描述清楚预期的表现和实际的表现

**Comment by hiyuki** [comment]
请补充可运行复现demo或者完整代码截图后再打开
