### ISSUE TITLE
有没有类似vue-router 路由守卫 拦截的插件或思路的

### ISSUE THREAD

**Issue by chybcool** [didi/mpx#832]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 由于页面路由需要设定路由白名单拦截，需要有类似vue-router守卫拦截，网上看到的通过app实例生命周期实现，但好像也有一些问题，不太满足需求。
2. 有大佬推荐比较好的写法或插件嘛
3. 实际的表现

**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by hiyuki** [comment]
目前没有办法可以做到和vue-router路由守卫一样的拦截效果，可以通过页面生命周期Page.onShow和getCurrentPages配合模拟实现类似的效果，页面路由变化必然会触发当前切入页面的onShow，可以在这个时候检查当前页面是否在白名单当中，如果不在白名单中则通过redirect之类的路由api再重定向走，onShow可以通过mpx.mixin全局注入；

如果只考虑使用api进行路由跳转时那代理所有的路由跳转api也可以进行部分拦截

**Comment by chybcool** [comment]
目前用在路由跳转方法那里做了一个方法判断，暂时先可以用了；
