### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by ljh1234** [didi/mpx#835]
**问题描述**  
在使用mpx.createUserInfoButton时报错"is not a function"
1 想调用微信api`wx.createUserInfoButton`，在.mpx文件中调用`mpx.createUserInfoButton`报错

**环境信息描述**  
至少包含以下部分：
1. macbook pro(16-inch,2019) macos 11.2.3
2. mpx(@mpxjs/core: 2.6.31)
3. 微信小程序开发工具(1.03.2012120)

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
```
const userInfoButton = wx.createUserInfoButton({
     type: 'text',
     text: '获取用户信息',
 })

userInfoButton.show()
userInfoButton.onTap(() => {
mpx.authorize({
  scope: 'scope.userInfo',
  async success() {
    const userInfo = await getUserInfo()
    if (userInfo) {
      console.log('user', userInfo)
      storeUserInfo(userInfo)
    }
  }
})
})
```

**Comment by ljh1234** [comment]
更正一下代码中wx.createUserInfoButton应是mpx.createUserInfoButton

**Comment by Blackgan3** [comment]
createUserInfoButton 是微信小游戏中的api，在小程序中无法使用
