### ISSUE TITLE
[Feature Request]全局样式

### ISSUE THREAD

**Issue by StephanieFang727** [didi/mpx#836]
请问目前有支持多环境下的引入全局样式的方式吗？
尝试过
1 在app.js import css文件（提示缺少相应loader）
2 在app.mpx文件通过<style>引入再通过微信的addGlobalClass属性使组件获取到全局样式 （只能在微信环境下生效）

**Comment by hiyuki** [comment]
目前没有特别好的方式能保障所有平台全局样式都能生效，主要也得看你需要输出哪些平台，微信可以通过你上面的2实现，该方式在百度下也生效，支付宝和web默认情况下就样式就是全局的（框架提供了自动scoped功能来模拟组件局部样式），所以你上面2的方式在微信、支付宝、百度、web当中都可以work，但是在字节当中既存在组件样式隔离又不支持addGlobalClass的平台无效。

还有一种方式是通过预处理器在编译时打入全局样式，如stylus-resource-loader这种，但是这种的弊端在于构建结果中会产生大量全局样式的冗余，对包体积不利。
