### ISSUE TITLE
[Bug report]百度小程序接入原生组件库编译报错

### ISSUE THREAD

**Issue by zhangcai93** [didi/mpx#837]
**问题描述**  
*百度小程序*接入原生组件库`@smt-ui/component` 页面中使用`collapse`组件，`collapse`组件内部引用`gov-icon`组件，组件gov-icon编译报错。

**环境信息描述**  
至少包含以下部分：
1. Mac
2."@mpxjs/api-proxy": "^2.5.10",
    "@mpxjs/core": "^2.6.31",
   "@mpxjs/webpack-plugin": "^2.6.31",

**最简复现demo**  
1. mpx init一个百度小程序
2. 进入项目`npm i @smt-ui/component` 
3. page中 引用 `collapse`组件
4. `npm run watch`即可看到控制台编译报错
5. [demo压缩包zip](https://github.com/didi/mpx/files/6855115/mpx-issue.zip)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.79 已修复
