### ISSUE TITLE
[Bug report]  小程序插件中引用主包组件提示找不到

### ISSUE THREAD

**Issue by nianxiongdi** [didi/mpx#838]
**问题描述**  

1. 问题触发的条件
      微信小程序插件中引用主包的组件提示找不到文件       
2. 期望的表现
      可以在小程序插件中引用主包的文件
3. 实际的表现
     页面中有报错，如下图: app.json与打包后的路径不一致
![image](https://user-images.githubusercontent.com/41629087/126605627-c23b294b-87e1-4b06-a62a-8face7d42a7b.png)

**最简复现demo**  
github地址请[点击](https://github.com/nianxiongdi/mpx-plugin)

**Comment by Blackgan3** [comment]
https://github.com/didi/mpx/pull/841

已解决
