### ISSUE TITLE
[Bug report] 插件模式下 plugin.[env].json 异常

### ISSUE THREAD

**Issue by okxiaoliang4** [didi/mpx#839]
**问题描述**  
创建了plugin.yn.json文件
小程序插件模式下例如 `__mpx_env__ = 'yn'`时
编译异常，只有bundle.js和plugin.js输出

**环境信息描述**  
Mac

[mpx-demo.zip](https://github.com/didi/mpx/files/6860941/mpx-demo.zip)

**Comment by hiyuki** [comment]
https://github.com/mpx-ecology/mpx-template/pull/81/files
参考最新的脚手架修改进行修复
