### ISSUE TITLE
通过bindinput事件获取value然后设置inputValue不生效

### ISSUE THREAD

**Issue by ialmost** [didi/mpx#84]
![image](https://user-images.githubusercontent.com/6847189/53536637-0d634280-3b42-11e9-91f8-d31bc4e7da96.png)
`
<input type="digit" class="input" bindinput="handleInput" wx:model="{{withdrawVal}}" />
 handleInput (e) {
    let value = e.detail.value
    this.withdrawVal = value + 1
 }
`

**Comment by ialmost** [comment]
e.detail.value = value + 1
直接赋值就可以

**Comment by sky-admin** [comment]
#85

**Comment by sky-admin** [comment]
#85
