### ISSUE TITLE
[Feature Request]请求增加tsx模式

### ISSUE THREAD

**Issue by ks-stack** [didi/mpx#842]
目前mpx文件对类型的支持不友好，并且Prettier也无法启用。可以自行接入vue-class-component吗

**Comment by hiyuki** [comment]
目前无法支持jsx/tsx，Mpx本身是增强型框架，基本渲染方式还是遵从于小程序本身基于静态模板的方式，而jsx/tsx则是运行时动态模板，在目前的设计架构下无法进行支持，类似taro next/kbone那种运行时框架是可以支持的，因为那种架构下整个模板是完全动态定义的，但是会存在很大的性能开销。
