### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by FE-Sheldon** [didi/mpx#848]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
![image](https://user-images.githubusercontent.com/16032342/128515405-ba7f5f01-1b4c-486c-ba53-a2f3dcbb8522.png)

2. 期望的表现
mpx文件可以支持scss的语法
3. 实际的表现
在webpack配置sass的rules后打包后在微信开发者工具无法运行，报错信息如图
![image](https://user-images.githubusercontent.com/16032342/128515689-9bf6328f-7a93-40e4-9d97-5528e261894c.png)

**环境信息描述**  
至少包含以下部分：
1. 系统类型为windows 10 专业版
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
![image](https://user-images.githubusercontent.com/16032342/128516125-b50958f4-9fe1-4a4a-a06d-86e69ae9dc1e.png)

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）
小程序平台：微信小程序
开发者工具版本：1.05
基础库版本：2.19.1
**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
[mpx-demo.zip](https://github.com/didi/mpx/files/6945789/mpx-demo.zip)

2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

**Comment by pagnkelly** [comment]
原因是： 1.没有配置正确。2.sass-loader版本过高 需要搭配webpack5 ，现在Mpx还没有升级webpack5 （敬请期待）
你需要改动两个地方
1.更改配置地方
![image](https://user-images.githubusercontent.com/16016300/128542185-a5dd38f2-8afb-4d4e-9f28-e400f7077203.png)
2. 降低sass-loader版本以及安装sass
![image](https://user-images.githubusercontent.com/16016300/128542304-dbbde886-ec7b-408c-afc6-2c3a8b5e027e.png)
![image](https://user-images.githubusercontent.com/16016300/128542321-527da41b-dbcd-49f1-b471-271007056383.png)
[mpx-demo.zip](https://github.com/didi/mpx/files/6946822/mpx-demo.zip)
