### ISSUE TITLE
[Bug report] 需要兼容百度小程序模版里不用{{}}包裹控制属性 

### ISSUE THREAD

**Issue by zhangcai93** [didi/mpx#850]
**问题描述**  
1. 百度小程序,模版中不用{{}}包裹控制属性 , 执行有误
2. 复现demo
![image](https://user-images.githubusercontent.com/23694441/128711551-9f5c3a9e-e660-48b4-8341-afdbf5ef78c3.png)
3. 源码有todo标记
![image](https://user-images.githubusercontent.com/23694441/128710939-4d346fdd-5601-47fd-bd9f-051e9c8d7366.png)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.82 已修复
