### ISSUE TITLE
微信开发者工具的将js编译成ES5在什么情况下需要勾选

### ISSUE THREAD

**Issue by GetemJay** [didi/mpx#851]
webpack将mpx代码编译后 理论上来说就不需要开发者工具的将js编译成ES5了，但是貌似在模板里使用一些新语法不能正确的编译成es5.
所以是不是只要不在模板里使用新语法，就不需要勾选“将js编译成ES5”了

**Comment by Blackgan3** [comment]
是的，目前只要不在模板里使用新语法，就不需要勾选“将js编译成ES5”了

后续升级webpack5的计划中也会加上对模版中语法走babel的支持
