### ISSUE TITLE
px->rpx转换时的比例

### ISSUE THREAD

**Issue by yrq110** [didi/mpx#86]
建议在**px转换rpx**时在已有的基础上**将数值*2**。

以iPhone6的375px为标准尺寸的宽的话，在转换成以750为宽的自适应单位rpx时，若数值不变直接转换单位，显示出的尺寸会很小。

**Comment by sky-admin** [comment]
可以通过webpack.base.conf.js里第14行transRpx配置中传入designWidth: 375来解决。
参考文档: https://didi.github.io/mpx/compilationEnhance/#mpxwebpackpluginloader
如认为默认值就设为375px更好，欢迎提PR到模板仓库：https://github.com/mpx-ecology/mpx-template

**Comment by yrq110** [comment]
> 可以通过webpack.base.conf.js里第14行transRpx配置中传入designWidth: 375来解决。
> 参考文档: https://didi.github.io/mpx/compilationEnhance/#mpxwebpackpluginloader
> 如认为默认值就设为375px更好，欢迎提PR到模板仓库：https://github.com/mpx-ecology/mpx-template

好的谢谢，暂时目前是这样做的。
