### ISSUE TITLE
[Bug report]解析百度小程序原生组件条件语句编译错误

### ISSUE THREAD

**Issue by zzzzzb** [didi/mpx#861]
**问题描述**  
原生组件中的条件语句
<img width="1092" alt="34f4c27f9bfcc75992f56808ffb853fe" src="https://user-images.githubusercontent.com/23138439/129835052-c77fd4e1-94d1-4cee-ac3a-7075e784f6e7.png">

mpx编译过后
<img width="1059" alt="7d7059182c4681b3c93969161de1f776" src="https://user-images.githubusercontent.com/23138439/129835081-687ecb7c-83ae-4c66-a7d6-22eb99421d0e.png">

s-if语句条件全都使用了不存在的参数val

**环境信息描述**  
Mpx依赖版本：
@mpxjs/core@2.6.80
@mpxjs/webpack-plugin@2.6.82

**Comment by zzzzzb** [comment]
有可能是这个修改引入的bug？
[[Bug report] 需要兼容百度小程序模版里不用{{}}包裹控制属性 #850](https://github.com/didi/mpx/issues/850)

**Comment by hiyuki** [comment]
确实是，我发个新版修复一下
