### ISSUE TITLE
IDEA 下微信的标签无法支持高亮

### ISSUE THREAD

**Issue by waltcow** [didi/mpx#863]
根据 [IDE 高亮配置](https://mpxjs.cn/guide/basic/ide.html])提示配置后，
发现vue template下对于一些微信自定义标签无法做到高亮，
想请教下有没推荐的方案

![image](https://user-images.githubusercontent.com/3941174/130361233-1cf8685c-dece-4086-abfe-f1a7af64ca28.png)

**Comment by hiyuki** [comment]
目前我们还没有提供webstorm的插件，相关指令确实识别不出来，我们已经提供了vscode插件，是可以识别提示相关指令的，如果对这块有诉求的话可以考虑用vscode进行编码
