### ISSUE TITLE
[Bug report] createPage中有自定义属性(自定义属性不是函数), 会报运行时错误

### ISSUE THREAD

**Issue by zhangcai93** [didi/mpx#872]
问题触发的条件 createPage中有自定义属性(ps: 自定义属性不是函数), 会报运行时错误
![image](https://user-images.githubusercontent.com/23694441/132450667-7dc7b509-852a-43af-98aa-2ec8f6ba2fcb.png)
![image](https://user-images.githubusercontent.com/23694441/132450779-e6432680-c6f6-4f2b-9a99-f82184f96677.png)

debug进去, 考虑是走到了此处逻辑
![image](https://user-images.githubusercontent.com/23694441/132450927-cdecb613-8f2b-471a-bd70-14f7579d7514.png)
![image](https://user-images.githubusercontent.com/23694441/132450949-30c09b32-1678-4191-b8cb-3e6f2785ad2a.png)

复现demo:
[mpx-iss.zip](https://github.com/didi/mpx/files/7126072/mpx-iss.zip)

**Comment by Blackgan3** [comment]
demo 构建后没复现报错

**Comment by zhangcai93** [comment]
helper/log.js里面log的执行逻辑是非production模式, 不能用build构建. 还是develop模式下报运行时error, 并没有影响呢?
![image](https://user-images.githubusercontent.com/23694441/132502725-480bd263-6454-41a2-93f0-318763635b6e.png)

**Comment by Blackgan3** [comment]
OK，问题已经复现，我们修复下

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.93 已修复
