### ISSUE TITLE
[Bug report] 百度小程序onShow/onLoad生命周期执行顺序有误

### ISSUE THREAD

**Issue by zhangcai93** [didi/mpx#873]
![image](https://user-images.githubusercontent.com/23694441/132641619-41cb3b51-3b0b-40ab-8965-21b1549e38b3.png)

![image](https://user-images.githubusercontent.com/23694441/132641784-e24f2bbf-3b13-425a-a33c-2001bbb6448a.png)

预期表现: onLoad早于onShow

**Comment by zhangcai93** [comment]
百度小程序原生的Component构造器onShow和onLoad的顺序就有问题, onShow早于onLoad触发了, 但是onReady的时机确实是最后触发的.
顺序有误的应该是onReady早于onLoad了.

**Comment by Blackgan3** [comment]
是的，这里百度小程序Component 去构造Page的时候onShow onLoad执行顺序有问题

**Comment by hiyuki** [comment]
最新版本中已处理https://github.com/didi/mpx/releases/tag/v2.6.93
