### ISSUE TITLE
[Bug report] 百度小程序onShareAppMessage没有读取返回值

### ISSUE THREAD

**Issue by zhangcai93** [didi/mpx#874]
![image](https://user-images.githubusercontent.com/23694441/132642036-2f1cdf5f-c23b-4626-a692-c560b0704481.png)
onShareAppMessage函数返回的配置没有读取, 走的还是默认的配置.
预期: 和原生表现一致, 能够正确读取配置.
mpx:
![image](https://user-images.githubusercontent.com/23694441/132642190-581bdafb-af43-47c6-8e53-d4f2e90b5e81.png)
原生小程序表现:
![image](https://user-images.githubusercontent.com/23694441/132642356-f7e1a040-c79b-4bce-8dc5-c077632f0918.png)

复现demo:
[mpx-iss.zip](https://github.com/didi/mpx/files/7134434/mpx-iss.zip)

**Comment by Blackgan3** [comment]
这个测试了下应该是百度的一个bug，目前开发百度小程序建议还是先开启下 forceUsePageCtor: true 开关
