### ISSUE TITLE
[Bug report] mpx fetch 序列化异常

### ISSUE THREAD

**Issue by janyyy** [didi/mpx#875]
**问题描述**  
Get请求 我在url后拼参数，有个数组经过QS库处理后正确(sort=xxx&sort=xxy)。请求的时候只有sort=xxy  。

**环境信息描述**  
"@mpxjs/fetch": "^2.6.82"
 "qs": "^6.10.1"

**最简复现demo**  

- 处理前参数：

query: {
      page: 0,
      size: 20,
      sort: ['isTop,desc', 'publishTime,desc'],
      channelId: ''
    }

- QS 【qs.stringify(params, { indices: false }】处理后参数：

![image](https://user-images.githubusercontent.com/27274865/134612840-8dd397ef-f09d-4e83-8836-f6e4222bf6cd.png)

- MPX fetch请求时携带参数：

![image](https://user-images.githubusercontent.com/27274865/134612858-ed1bd14f-8730-4683-b7c7-a97da7ee846a.png)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.96 已修复

**Comment by janyyy** [comment]
thanks
