### ISSUE TITLE
[Bug report]@mpxjs/webpack-plugin

### ISSUE THREAD

**Issue by naiveeee** [didi/mpx#884]
微信小程序打包的时候用了MpxWebpackPlugin，项目中用了lodash.debounce 构建了production以后执行的时候提示这个（development模式下没问题），定位了一下是没有拿到Date对象

mac 微信开发者工具Stable 1.05.2110110 基础哭版本2.19.2   @mpxjs/webpack-plugin@2.6.102
[mpx-demo.zip](https://github.com/didi/mpx/files/7423671/mpx-demo.zip)

**Comment by Blackgan3** [comment]
https://github.com/didi/mpx/releases/tag/v2.6.104

版本已解决这个问题
