### ISSUE TITLE
[Feature Request] 希望Mpx支持文件路径压缩与CSS类名压缩等

### ISSUE THREAD

**Issue by kodomozz** [didi/mpx#891]
#### 希望Mpx支持文件路径压缩
在大型项目中小程序主包体积十分吃惊，希望大佬能够支持Mpx的构建产物中**usingComponents**中的路径做一个压缩`a/b/c/.0.wxml`，以减少主包的体积压力 （收益较为可观）
#### 希望Mpx支持class类名的一个压缩
在电商项目中一些营销的弹窗等需要用到较多的样式，样式类名嵌套比较深的情况下，类名的压缩可以给主要的体积带来一定的收益
#### 希望Mpx支持原子化的css
原子化的css在大型项目中可以给体积带来一些正向的收益

最后感谢Mpx给我们带来了类vue的跨端框架，开发体验如丝般顺滑，关键bug还很少

**Comment by hiyuki** [comment]
目前已经支持自定义资源输出路径，可以通过该配置对资源路径进行缩短。
https://github.com/didi/mpx/releases/tag/v2.6.107

类名压缩较难实现，实际的类名可能是由js动态控制的，很难通过静态编译手段来完成

原子类确实是一个降低样式体积占用的好的方向，我们之后会对相关的方案进行集成支持
