### ISSUE TITLE
最新版本转web 的时候，组件不显示

### ISSUE THREAD

**Issue by 1459416736** [didi/mpx#901]
最新版本小程序一切正常，就是在转web 的时候遇到这个问题，vant 组件不显示，问题如下
Unknown custom element:
 <van-progress> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

![选区_009](https://user-images.githubusercontent.com/6478087/142960149-fb89fb5a-2b95-4d1f-8c04-358c2af6fd19.png)

[demo.zip](https://github.com/didi/mpx/files/7585379/demo.zip)

**Comment by Blackgan3** [comment]
Mpx 输出 web 时暂不支持原生组件进行转换，后续会进行支持

**Comment by zhangliangxue** [comment]
> Mpx 输出 web 时暂不支持原生组件进行转换，后续会进行支持

原生组件是什么？vant weapp算吗？  我用weapp 也是这个问题
