### ISSUE TITLE
小程序原生能成功连接聊天室，mpx框架不可以，经排查是连接不了socket.io 

### ISSUE THREAD

**Issue by chenyina** [didi/mpx#906]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件:
点击直播按钮，
![image](https://user-images.githubusercontent.com/11674247/144781268-d99e82e9-0c98-4de8-8219-cc92c479b58f.png)
![image](https://user-images.githubusercontent.com/11674247/144781302-50e92590-f74f-420e-8b6a-23377119f36a.png)
出现聊天室连接失败的提示
2. 期望的表现
聊天室连接成功
3. 实际的表现
出现聊天室连接失败的提示

小程序原生能成功连接聊天室，mpx框架不可以，经排查是连接不了socket.io 
聊天室不出现，联系：微信号chenyina0526

[demo.zip](https://github.com/didi/mpx/files/7683308/demo.zip)

**Comment by chenyina** [comment]
原生可以连接socket.io的
[plv-mp-sdk-v2.2.1.zip](https://github.com/didi/mpx/files/7657746/plv-mp-sdk-v2.2.1.zip)
示例

**Comment by chenyina** [comment]
原生可以连socket.i
[new.zip](https://github.com/didi/mpx/files/7658158/new.zip)
o

**Comment by chenyina** [comment]
原生可以连接socket.i
[sdkDemo.zip](https://github.com/didi/mpx/files/7658313/sdkDemo.zip)
o

**Comment by Blackgan3** [comment]
排查后socket相关方法正常触发，辛苦联系对应的sdk提供方排查
