### ISSUE TITLE
[Bug report] xfetch 在post传参模式 参数为多维数组的时候，里层的数组会自动转换为对象

### ISSUE THREAD

**Issue by flyjin** [didi/mpx#907]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
在post传参请求时候，传递多维数组，里层的数组会自动转换为对象，换成原生的wx.request就没有此问题

**环境信息描述**  

mpx已更新最新版本，环境为微信小程序模式
"@mpxjs/fetch": "^2.6.103",
"@mpxjs/core": "^2.6.31",

**最简复现demo**  
可以自己试试这种嵌套数组请求
![QQ图片20211207083828](https://user-images.githubusercontent.com/16444854/144945064-502cae52-9c4c-4e2e-8ea2-727a1fface14.jpg)

这个relates 本来是个array ，请求时候会自动转成了对象

**Comment by Blackgan3** [comment]
![image](https://user-images.githubusercontent.com/18080281/145561703-57930441-12d5-4fa6-b15d-263bc67babff.png)

测试多层嵌套，是正常的，提供个能复现的demo吧

**Comment by Blackgan3** [comment]
![image](https://user-images.githubusercontent.com/18080281/145562320-e3509514-28e9-4d13-9898-bef972419095.png)
测试了嵌套数据和多维数组，没复现你说的这个问题，提供个可复现的demo吧

**Comment by flyjin** [comment]
`
	this.$xfetch.fetch({
        url: 'http://test.com',
        method:'post',
        data:{
          commodityList: [{ id: 123, relates: [{ id: 12313 }] }],
          payChannel: 1231,
          commId: 111,
          id: 11,
          sourceId: 2
        }})

`

**Comment by flyjin** [comment]
> ![image](https://user-images.githubusercontent.com/18080281/145562320-e3509514-28e9-4d13-9898-bef972419095.png) 测试了嵌套数据和多维数组，没复现你说的这个问题，提供个可复现的demo吧

`
this.$xfetch.fetch({
        url: 'http://test.com',
        method:'post',
        data:{
          commodityList: [{ id: 123, relates: [{ id: 12313 }] }],
          payChannel: 1231,
          commId: 111,
          id: 11,
          sourceId: 2
        }})
`

**Comment by Blackgan3** [comment]
> > ![image](https://user-images.githubusercontent.com/18080281/145562320-e3509514-28e9-4d13-9898-bef972419095.png) 测试了嵌套数据和多维数组，没复现你说的这个问题，提供个可复现的demo吧
> 
> `this.$xfetch.fetch({ url: 'http://test.com', method:'post', data:{ commodityList: [{ id: 123, relates: [{ id: 12313 }] }], payChannel: 1231, commId: 111, id: 11, sourceId: 2 }})`



![image](https://user-images.githubusercontent.com/18080281/146483703-c8f87c94-22e4-4223-9258-cd5105982473.png)
用你贴的数据也是没问题的，你这边可以整个可复现的demo
