### ISSUE TITLE
[Feature Request] 支持百度小程序以相对路径的方式引用本地图片资源

### ISSUE THREAD

**Issue by zhangcai93** [didi/mpx#920]
**百度小程序支持以相对路径方式引用本地图片资源,希望mpx编译打包可以支持**

**按照目前的打包编译机制**
- urlLoader会把css里面的不上传cdn的图片转成base64的,这种处理方式可能会有两个问题:
>  1. 大图base64转码有一定耗时
>  2.  图片打成base64之后都分散在各个css文件中, 没有一个地方可以集中各个图片的尺寸.
- fileLoader会把本地图片资源的路径都处理成绝对路径, 但backgroud-image只能支持相对路径引用.

**因此期望mpx框架能够支持以相对路径的方式引用本地图片资源**

**Comment by hiyuki** [comment]
如果只有百度平台的支持话建议还是走cdn，Mpx对此有专门的支持，能够较为便捷地实现且能够节省包体积。

**Comment by zhangcai93** [comment]
> 如果只有百度平台的支持话建议还是走cdn，Mpx对此有专门的支持，能够较为便捷地实现且能够节省包体积。

大部分图片我们会走cdn的, 但是也存在一部分资源会内置到包里, 例如首屏需要的图片或错误兜底的图片, 对于这类本身网络状态就不是很好的用户, 再从cdn拉资源不是很友好.
