### ISSUE TITLE
组件中使用iconfont 图标不能正常显示,需要使用slot在父级才能显示.

### ISSUE THREAD

**Issue by stephen7812** [didi/mpx#922]
# 组件代码: 
### 假设组件名称为: YsCard.mpx
代码见附件
[demo.md.zip](https://github.com/didi/mpx/files/7805849/demo.md.zip)

**Comment by Blackgan3** [comment]
我这边正常尝试了下是没问题的，辛苦上传一个你这边能复现问题的demo吧，就是上传一个项目上来，目前的md文档描述看起来并没有什么问题，还是需要通过你的项目来看下

**Comment by hiyuki** [comment]
请提供完整复现demo后再open
