### ISSUE TITLE
如何添加autoprefix呢

### ISSUE THREAD

**Issue by yangwenshanshan** [didi/mpx#93]
如题，现在支持autoprefix插件吗

**Comment by sky-admin** [comment]
微信开发者工具上勾选 上传代码时样式自动补全 即可，自己配的会生成moz的，在微信里会报错

**Comment by yangwenshanshan** [comment]
> 微信开发者工具上勾选上传代码时样式自动补全即可，自己配的会生成moz的，在微信里会报错

ok，感谢，我试试
