### ISSUE TITLE
[Bug report] typescript 使用空值合并?? 和 ?. 语法糖报错。

### ISSUE THREAD

**Issue by MagginZ** [didi/mpx#944]
**问题描述**  
前提条件
1. mpx-cli支持typescript，且typescript版本为 4.4.4。
2. .mpx中设置 script lang='ts'
3. 函数中使用ts的合并空值语法糖如下：
```
<script lang="ts" >
import { createPage } from '@mpxjs/core'
createPage({


  handleClick(url: string) {
    console.log(url ?? '') // 这里测试 ??
    }
})
</script>
```

实际结果：
watch 监听后报错：
![image](https://user-images.githubusercontent.com/29268220/153143004-0a5eec2f-6df4-4504-b05d-4511ca430e3f.png)

期望结果：脚本正常运行，不报错。

**环境信息描述**  
至少包含以下部分：
1. 系统类型：Mac
2. Mpx依赖版本:
"@mpxjs/api-proxy": "2.6.80",
 "@mpxjs/core": "2.6.94",
"@mpxjs/webpack-plugin": "2.6.94",

3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本: 2.18.0）

**Comment by MagginZ** [comment]
补充标题

**Comment by hiyuki** [comment]
看上去没有走ts-loader，确保的你的module.rules配置正确，如还无法定位问题请上传最简复现demo

**Comment by Blackgan3** [comment]
![image](https://user-images.githubusercontent.com/18080281/153159973-3a6aa931-8d6c-4cd2-b9f0-1ddd18ed5c2f.png)

按照描述测试没发现有问题，可以提供个demo我们看下
