### ISSUE TITLE
[Bug report] 使用第三方库vant 时，在webpack watch 时出错

### ISSUE THREAD

**Issue by waltcow** [didi/mpx#946]
最新mpx init的项目中，使用**vantUI** 作为第三方库

![image](https://user-images.githubusercontent.com/3941174/153386430-69d0fd00-d857-40ba-90b7-794b590c4a76.png)

npm run watch 时出现一下问题

![image](https://user-images.githubusercontent.com/3941174/153386550-72ff2a4a-1597-4dd7-b044-8561466c7495.png)

```
Watchpack Error (initial scan): Error: ENOTDIR: not a directory,
```

不知道那里配置出问题了？

**Comment by waltcow** [comment]
研究了一会，发现注释 `managedPaths: []` 就可以了😭

```js

snapshot: {
    // 如果希望修改node_modules下的文件时对应的缓存可以失效，可以将此处的配置改为 managedPaths: []
    managedPaths: [resolve('node_modules/')]
  },
```

**Comment by hiyuki** [comment]
fixed https://github.com/didi/mpx/releases/tag/v2.7.6
