### ISSUE TITLE
[Bug report] custom-tab-bar 无法输出

### ISSUE THREAD

**Issue by waltcow** [didi/mpx#948]
**问题描述**  

升级后最新的`"@mpxjs/webpack-plugin": "^2.7.5",`后，发现原来项目`custom-tab-bar`无法正确输出

![image](https://user-images.githubusercontent.com/3941174/153556440-f2a6f564-d2f4-4adf-aede-8ef7a1949601.png)

**Comment by waltcow** [comment]
在debug发现 `custom-tab-bar` 作为 `dynamicEntry` 处理

![image](https://user-images.githubusercontent.com/3941174/153564330-fc82172e-25fd-4440-9911-7ab653853e37.png)

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.7.6 fixed

**Comment by hiyuki** [comment]
> 

新版本目前已经在我们自己的业务中落地使用一段时间了，可能一些小的功能点还没有回归全，不过整体核心功能已经相对稳定了，可以先用着，遇到什么问题提issue我们修复很快的
