### ISSUE TITLE
最新版本项目不同页面使用wx:class wx:style后出现错误[Bug report]

### ISSUE THREAD

**Issue by CXY037** [didi/mpx#952]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件 不同页面使用wx:class wx:style
2. 期望的表现 
3. 实际的表现
ERROR in Conflict: Multiple assets emit different content to the same filename wxs/stringify4d622254.wxs

**Comment by Blackgan3** [comment]
我先按照你的这个描述试下，不过还是辛苦提供下 "不同页面使用wx:class wx:style " 具体的代码吧

**Comment by CXY037** [comment]
我实现一个最小复现

Sent with a Spark
在 2022年2月24日 +0800 15:46，BlackGan ***@***.***>，写道：

**Comment by CXY037** [comment]
yarn upgrade了下发现不报错了，估计某个webpack插件的问题，我先关闭issue，后面出现我提交最小复现代码

**Comment by guozhier** [comment]
我这复现的情况是，我的项目使用了vant-weapp ui框架，项目中如果出现多个页面重复引用相同组件的情况就会报上述错
比如A页面引入了van-button B页面也引用了，报错；
或者A页面引入了van-button，B页面引入van-dialog，但是van-dialog中引用了van-button，报错
有的时候会提示组件在某个文件注册过了，更多时候会报下面这个错误
 ERROR in Conflict: Multiple assets emit different content to the same filename  xxxxx.wxs

**Comment by hiyuki** [comment]
该问题已修复：https://github.com/didi/mpx/releases/tag/v2.7.9
@guozhier 你这个有可能是另一个问题，在另一个issue中讨论
