### ISSUE TITLE
删除node-modules后 项目无法启动

### ISSUE THREAD

**Issue by guozhier** [didi/mpx#953]
**问题描述**  
以前老的项目删过一次node-modules，重新安装依赖后，无法启动，报错如下：
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/29756013/155258470-291af93e-f767-47d1-8f49-ed0fa662b0b8.png">

求指导一下如何解决，谢谢！

**环境信息描述**  
至少包含以下部分：
1. 系统类型Mac
2. Mpx依赖版本 
    "@mpxjs/api-proxy": "^2.7.1",
    "@mpxjs/core": "^2.7.2",
    "@mpxjs/fetch": "^2.7.1"
3. 小程序开发者工具信息(小程序平台wx、开发者工具版本 1.05.2202162、基础库版本2.22.0）

**Comment by Blackgan3** [comment]
webpack 的版本是最新的吗，将webpack升级到最新版本试下

**Comment by sky-admin** [comment]
这个文件目录看起来很像是用cnpm来安装的？不要使用cnpm安装试试呢？

**Comment by EasyTZ** [comment]
看看NPM的版本，是不是更新了

**Comment by guozhier** [comment]
感谢各位，我再去改改试试

**Comment by shimangdian** [comment]
请问升级了那些依赖？我也遇到了这个问题
