### ISSUE TITLE
复现 #952 这个bug [Bug report]

### ISSUE THREAD

**Issue by guozhier** [didi/mpx#956]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
    引入vant ui 且多个页面引入重复组件时会报错
2. 期望的表现
   老版本无此报错
3. 实际的表现
   

复现过程：
我这复现的情况是，我的项目使用了vant-weapp ui框架，项目中如果出现多个页面重复引用相同组件的情况就会报上述错
比如A页面引入了van-button B页面也引用了，报错；
或者A页面引入了van-button，B页面引入van-dialog，但是van-dialog中引用了van-button，报错
有的时候会提示组件在某个文件注册过了，更多时候会报下面这个错误
ERROR in Conflict: Multiple assets emit different content to the same filename xxxxx.wxs

<img width="1974" alt="image" src="https://user-images.githubusercontent.com/29756013/155715317-65089793-f253-462e-a149-739b9d2fbd65.png">

**Comment by hiyuki** [comment]
提供一下@mpxjs/webpack-plugin的版本号，以及最好上传一个复现demo

**Comment by hiyuki** [comment]
本地按照描述测试没有复现问题，请上传复现demo
