### ISSUE TITLE
事件处理内联传参的增强机制不起作用

### ISSUE THREAD

**Issue by kentoDG** [didi/mpx#961]
**问题描述**  
1. 框架的事件处理内联传参机制不起作用，小程序框架报 does not have a method

**环境信息描述**  
1. Windows10 系统
2. Mpx依赖版本：@mpxjs/core：^7.10.4  @mpxjs/webpack-plugin：^2.7.2  @mpxjs/api-proxy：^2.7.1
3. 微信小程序：开发者工具版本：1.05.2111300  基础库版本：2.22.1
4. node版本：16.13.1

**最简复现demo**  
[ack2j-l5lc9.zip](https://github.com/didi/mpx/files/8166352/ack2j-l5lc9.zip)

**Comment by Blackgan3** [comment]
看了你上传的demo，dist文件夹下wx产物中wxml都没经过模版编译，删了dist重新构建下是没问题的

**Comment by hiyuki** [comment]
确认时windows系统下由于路径格式不一致导致的bug，https://github.com/didi/mpx/releases/tag/v2.7.12 已修复
