### ISSUE TITLE
[Bug report] build DLL 产出资源命名有问题

### ISSUE THREAD

**Issue by waltcow** [didi/mpx#979]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/3941174/159115694-04faafa8-8d2b-48b2-ac57-1c8b91b1a4f4.png">

**Comment by Blackgan3** [comment]
模版项目中build/buildDll 中的配置有些问题，我修改下，这里可以先把buildDll 中配置做下修改，将 chunkHash 改为 chunkhash
```js
const dllName = '[name].[chunkhash].dll.js'
const manifestName = '[chunkhash].manifest.json'
```

**Comment by hiyuki** [comment]
由于目前mpx@2.7版本已经完整支持了持久化缓存，使用dll提升编译速度已经不再必要，后续我们也会逐步下掉构建dll相关的能力
