### ISSUE TITLE
getMenuButtonBoundingClientRect，这个api真机调试会让微信崩溃的问题

### ISSUE THREAD

**Issue by ialmost** [didi/mpx#98]
getMenuButtonBoundingClientRect，这个api真机调试会让微信崩溃的问题

**Comment by pkingwa** [comment]
您用的啥机型，我们这边暂时没能复现，如果有问题，应该是原生小程序api的bug，可以提给微信小程序官方社区

**Comment by ialmost** [comment]
> 您用的啥机型，我们这边暂时没能复现，如果有问题，应该是原生小程序api的bug，可以提给微信小程序官方社区

在微信开发者社区发现该问题已被官方确认为BUG，感谢提醒
