### ISSUE TITLE
[Feature Request]希望mpx-fetch支持微信enableHttpDNS等属性

### ISSUE THREAD

**Issue by wiexin** [didi/mpx#980]
**问题描述**  
微信小程序 wx.request新增了enableCache、enableHttpDNS等新的属性，mpx-fetch是否考虑支持？

**Comment by Blackgan3** [comment]
微信新增的这些属性，在config中可以配置，mpx-fetch 不会对你传入的配置做特惠过滤逻辑，默认是都支持的

**Comment by wiexin** [comment]
看了一下代码是没过滤额外的配置。因为小程序HttpDNS调用统计的原因 一直以为没生效
