### ISSUE TITLE
[Bug report] Vant 依赖引入报错

### ISSUE THREAD

**Issue by TianchengTerrence** [didi/mpx#982]
**问题描述**  
请用简洁的语言描述你遇到的bug，至少包括以下部分，如提供截图请尽量完整：
1. 问题触发的条件
同时使用以下组件时报错
"usingComponents": {
        "van-tabbar-item": "@vant/weapp/tabbar-item/index",
        "van-icon": "@vant/weapp/icon/index"
      }

(vant-tabbar-item 可能也引入了van-icon)
2. 期望的表现
正常编译通过
3. 实际的表现
编译报错
ERROR in Current component [/Users/**/Documents/issue/mpx-project/node_modules/.pnpm/@vant+weapp@1.10.2/node_modules/@vant/weapp/lib/icon/index.js] is already registered with outputPath [.pnpm/@vant+weapp@1.10.2/node_modules/@vant/weapp/lib/icon/index], you can not register it with another outputPath [components/vant/weapp4c22f1fd/icon/index]!

wx-compiler (webpack 5.70.0) compiled with 1 error in 128 ms
**环境信息描述**  
至少包含以下部分：
1. 系统类型(Mac或者Windows)
Mac
2. Mpx依赖版本(@mpxjs/core、@mpxjs/webpack-plugin和@mpxjs/api-proxy的具体版本，可以通过package-lock.json或者实际去node_modules当中查看)
@mpxjs/webpack-plugin@2.7.19
@mpxjs/core@2.7.18
    "@vant/weapp": "^1.10.2",
"@mpxjs/webpack-plugin": "^2.7.2",
3. 小程序开发者工具信息(小程序平台、开发者工具版本、基础库版本）

**最简复现demo**  
一般来说通过文字和截图的描述我们很难定位到问题，为了帮助我们快速定位问题并修复，请按照以下指南编写并上传最简复现demo：
1. 根据现有项目遇到的问题，尝试精简代码，确定问题的最小复现条件
2. 使用脚手架创建新项目，基于最小复现条件编写稳定的最简复现demo
3. 删除项目中的node_modules部分，打包项目，并拖拽到issue输入框中上传（或提供远程可下载地址）

> 更新相关库版本后尝试下：
> 
> * @mpxjs/webpack-plugin@2.7.19
> * @mpxjs/core@2.7.18

问题依然出现：
[mpx-project.zip](https://github.com/didi/mpx/files/8314760/mpx-project.zip)

**Comment by Blackgan3** [comment]
更新相关库版本后尝试下：

* @mpxjs/webpack-plugin@2.7.19
* @mpxjs/core@2.7.18

**Comment by TianchengTerrence** [comment]
> 更新相关库版本后尝试下：
> 
> 
> 
> * @mpxjs/webpack-plugin@2.7.19
> 
> * @mpxjs/core@2.7.18

新Demo已提交

**Comment by hiyuki** [comment]
和pnpm的安装方式有关，我们会加一个fix来进行处理

**Comment by TianchengTerrence** [comment]
> 和pnpm的安装方式有关，我们会加一个fix来进行处理

了解，感谢！

**Comment by hiyuki** [comment]
https://github.com/didi/mpx/releases/tag/v2.7.24 已经添加了相关修复
