### ISSUE TITLE
require 引入图片不显示问题 ？

### ISSUE THREAD

**Issue by jetBn** [didi/mpx#986]
**问题描述**  
在data中使用require引入图片 不显示
1. 问题触发的条件 使用的require引入图片
2. 期望的表现 显示图片
3. 实际的表现 不显示图片

**环境信息描述**  
至少包含以下部分：
1.  mac 
2.   "@mpxjs/api-proxy": "^2.7.1",
    "@mpxjs/core": "^2.7.2",
    "@mpxjs/fetch": "^2.7.16",
    "@vant/weapp": "^1.10.2",
3. 微信开发者工具
![image](https://user-images.githubusercontent.com/26957220/159480632-e6fa1361-f78f-4bdb-b680-a983f8c1489f.png)

**最简复现demo**  
直接通过require引入图片不显示问题
<img width="525" alt="image" src="https://user-images.githubusercontent.com/26957220/159480728-d83729ae-a33c-4f42-9a75-34d4b984bbb7.png">

<img width="609" alt="image" src="https://user-images.githubusercontent.com/26957220/159480743-ffe92f06-e559-4325-ac07-acb5a1db08ca.png">
使用了ts版本

**Comment by hiyuki** [comment]
请按照指引上传复现demo

**Comment by jetBn** [comment]
> 请按照指引上传复现demo

又可以了 感觉是开发者工具问题
