### ISSUE TITLE
[Bug report] wepack alias 配置不生效

### ISSUE THREAD

**Issue by waltcow** [didi/mpx#988]
![image](https://user-images.githubusercontent.com/3941174/159652234-02a9b547-c064-40a7-aee0-adf2e410eaf2.png)

![image](https://user-images.githubusercontent.com/3941174/159652783-ca3141f7-b51f-405c-b833-8027cbac3251.png)

**Comment by ouxiong** [comment]
确实，我用@mpxjs/cli V2.7.1新建的一个项目，在webpack.base.conf.js里面配置了alias，然后也是编译不成功

**Comment by waltcow** [comment]
ts的话可以试下配置 `tsconfig.json`

> 确实，我用@mpxjs/cli V2.7.1新建的一个项目，在webpack.base.conf.js里面配置了alias，然后也是编译不成功

**Comment by hiyuki** [comment]
实际测试没有问题，请按照指引上传复现demo

**Comment by waltcow** [comment]
> 实际测试没有问题，请上传最简复现demo

今天检查发现后，原来是配置问题，不好意思😭
